// ============================================
// ADVANCED CHALLENGE — Kalkulus Batch 2
// Covers remaining topics: continuity, more derivatives,
// more integrals, applications, ODE, series
// ============================================

appendQuestions('adv_calculus', [
// [Kontinuitas] 166-170
{question:"Apakah $f(x) = \\frac{x^2-1}{x-1}$ kontinu di $x=1$?",options:["Tidak kontinu","Kontinu","Tidak terdefinisi","Kontinu dari kiri saja","Kontinu dari kanan saja"],answer:0,hint:"Cek apakah $f(1)$ terdefinisi.",explanation:"$f(1) = \\frac{0}{0}$ tidak terdefinisi.\nFungsi tidak kontinu di $x=1$.\n($\\lim_{x\\to 1} f(x) = 2$ ada, tapi $f(1)$ tidak.)"},
{question:"Tentukan nilai $k$ agar $f(x)$ kontinu di $x=2$, jika $f(x) = kx+1$ untuk $x<2$ dan $f(x) = 5$ untuk $x \\ge 2$.",options:["$k = 2$","$k = 1$","$k = 3$","$k = 5$","$k = 4$"],answer:0,hint:"Kontinu: $\\lim_{x\\to 2^-} f(x) = f(2)$.",explanation:"$\\lim_{x\\to 2^-} (kx+1) = 2k+1 = 5$.\n$2k = 4 \\Rightarrow k = 2$."},
{question:"Tentukan asimtot vertikal dari $f(x) = \\frac{1}{x-3}$.",options:["$x = 3$","$x = -3$","$x = 0$","$y = 0$","Tidak ada"],answer:0,hint:"Penyebut = 0 saat $x = 3$.",explanation:"Penyebut $x-3 = 0$ saat $x = 3$.\nAsimtot vertikal: $x = 3$."},
{question:"Tentukan asimtot horizontal dari $f(x) = \\frac{2x}{x+4}$.",options:["$y = 2$","$y = 0$","$y = 4$","$y = 1/2$","Tidak ada"],answer:0,hint:"$\\lim_{x\\to\\infty} \\frac{2x}{x+4} = \\frac{2}{1}$.",explanation:"$\\lim_{x\\to\\infty} \\frac{2x}{x+4} = \\lim \\frac{2}{1+4/x} = 2$.\nAsimtot horizontal: $y = 2$."},

// [More Derivatives] — polinomial & product/quotient
{question:"Tentukan turunan dari $f(x) = 3x$.",options:["$3$","$3x$","$x$","$0$","$1$"],answer:0,hint:"Turunan $cx = c$.",explanation:"$f'(x) = 3$."},
{question:"Tentukan turunan dari $f(x) = x^{10}$.",options:["$10x^9$","$x^9$","$10x^{10}$","$9x^{10}$","$x^{11}/11$"],answer:0,hint:"Power rule: $nx^{n-1}$.",explanation:"$f'(x) = 10x^9$."},
{question:"Tentukan turunan dari $f(x) = x^5 + 3x^4 - 2x + 1$.",options:["$5x^4 + 12x^3 - 2$","$5x^4 + 12x^3$","$5x^4 + 3x^3 - 2$","$x^4 + 3x^3 - 2$","$5x^5 + 12x^4 - 2x$"],answer:0,hint:"Turunkan suku per suku.",explanation:"$f'(x) = 5x^4 + 12x^3 - 2$."},
{question:"Tentukan turunan dari $f(x) = \\frac{3}{x^2}$.",options:["$-\\frac{6}{x^3}$","$\\frac{6}{x^3}$","$-\\frac{3}{x^3}$","$\\frac{3}{2x}$","$-\\frac{6}{x}$"],answer:0,hint:"$3/x^2 = 3x^{-2}$. Power rule: $-6x^{-3}$.",explanation:"$f(x) = 3x^{-2}$.\n$f'(x) = -6x^{-3} = -\\frac{6}{x^3}$."},
{question:"Tentukan turunan dari $f(x) = x^2 \\cos x$.",options:["$2x\\cos x - x^2\\sin x$","$2x\\cos x + x^2\\sin x$","$-2x\\sin x$","$x^2\\cos x$","$2x\\cos x$"],answer:0,hint:"Product rule: $(x^2)'\\cos x + x^2(\\cos x)'$.",explanation:"$f'(x) = 2x\\cos x + x^2(-\\sin x) = 2x\\cos x - x^2\\sin x$."},
{question:"Tentukan turunan dari $f(x) = x^3 e^x$.",options:["$e^x(x^3 + 3x^2)$","$3x^2 e^x$","$x^3 e^x$","$e^x(x^3 - 3x^2)$","$3x^2 + e^x$"],answer:0,hint:"Product rule: $(x^3)' e^x + x^3 (e^x)'$.",explanation:"$f'(x) = 3x^2 e^x + x^3 e^x = e^x(x^3 + 3x^2)$."},
{question:"Tentukan turunan dari $f(x) = \\sqrt{x} \\ln x$.",options:["$\\frac{\\ln x}{2\\sqrt{x}} + \\frac{1}{\\sqrt{x}}$","$\\frac{1}{2\\sqrt{x}}$","$\\sqrt{x} + \\ln x$","$\\frac{\\ln x}{\\sqrt{x}}$","$\\frac{1}{x\\sqrt{x}}$"],answer:0,hint:"Product rule: $(\\sqrt{x})' \\ln x + \\sqrt{x} (\\ln x)'$.",explanation:"$f'(x) = \\frac{1}{2\\sqrt{x}} \\ln x + \\sqrt{x} \\cdot \\frac{1}{x} = \\frac{\\ln x}{2\\sqrt{x}} + \\frac{1}{\\sqrt{x}}$."},
{question:"Tentukan turunan dari $f(x) = \\frac{x^2}{x-2}$.",options:["$\\frac{x^2-4x}{(x-2)^2}$","$\\frac{2x}{x-2}$","$\\frac{x}{(x-2)^2}$","$\\frac{2x(x-2)-x^2}{(x-2)^2}$","$\\frac{x^2}{(x-2)^2}$"],answer:0,hint:"Quotient rule: $\\frac{2x(x-2) - x^2(1)}{(x-2)^2}$.",explanation:"$f'(x) = \\frac{2x(x-2) - x^2}{(x-2)^2} = \\frac{2x^2-4x-x^2}{(x-2)^2} = \\frac{x^2-4x}{(x-2)^2}$."},
{question:"Tentukan turunan dari $f(x) = \\frac{\\sin x}{x}$.",options:["$\\frac{x\\cos x - \\sin x}{x^2}$","$\\frac{\\cos x}{x}$","$\\frac{\\sin x}{x^2}$","$\\cos x - \\frac{\\sin x}{x}$","$\\frac{x\\cos x + \\sin x}{x^2}$"],answer:0,hint:"Quotient rule.",explanation:"$f'(x) = \\frac{x\\cos x - \\sin x \\cdot 1}{x^2} = \\frac{x\\cos x - \\sin x}{x^2}$."},

// [More Chain Rule]
{question:"Tentukan turunan dari $f(x) = (3x - 2)^4$.",options:["$12(3x-2)^3$","$4(3x-2)^3$","$3(3x-2)^4$","$12x(3x-2)^3$","$(3x-2)^3$"],answer:0,hint:"Chain rule: $4(3x-2)^3 \\cdot 3$.",explanation:"$f'(x) = 4(3x-2)^3 \\cdot 3 = 12(3x-2)^3$."},
{question:"Tentukan turunan dari $f(x) = \\sqrt{2x+1}$.",options:["$\\frac{1}{\\sqrt{2x+1}}$","$\\frac{2}{\\sqrt{2x+1}}$","$\\frac{1}{2\\sqrt{2x+1}}$","$\\sqrt{2x+1}$","$\\frac{x}{\\sqrt{2x+1}}$"],answer:0,hint:"$f'(x) = \\frac{1}{2\\sqrt{2x+1}} \\cdot 2$.",explanation:"$f'(x) = \\frac{1}{2}(2x+1)^{-1/2} \\cdot 2 = \\frac{1}{\\sqrt{2x+1}}$."},
{question:"Tentukan turunan dari $f(x) = \\cos(x^2)$.",options:["$-2x\\sin(x^2)$","$-\\sin(x^2)$","$2x\\cos(x^2)$","$-2\\sin(x^2)$","$\\sin(x^2)$"],answer:0,hint:"Chain rule: $-\\sin(x^2) \\cdot 2x$.",explanation:"$f'(x) = -\\sin(x^2) \\cdot 2x = -2x\\sin(x^2)$."},
{question:"Tentukan turunan dari $f(x) = e^{-x^2}$.",options:["$-2xe^{-x^2}$","$-x^2 e^{-x^2}$","$e^{-x^2}$","$2xe^{-x^2}$","$-e^{-2x}$"],answer:0,hint:"Chain rule: $e^{-x^2} \\cdot (-2x)$.",explanation:"$f'(x) = e^{-x^2} \\cdot (-2x) = -2xe^{-x^2}$."},
{question:"Tentukan turunan dari $f(x) = \\sin^2(x)$.",options:["$\\sin(2x)$","$2\\sin x$","$2\\cos x$","$\\cos^2 x$","$2\\sin x \\cos x$"],answer:0,hint:"Chain rule: $2\\sin x \\cdot \\cos x = \\sin 2x$.",explanation:"$f'(x) = 2\\sin x \\cos x = \\sin(2x)$."},
{question:"Tentukan turunan dari $f(x) = 2^x$.",options:["$2^x \\ln 2$","$2^x$","$x \\cdot 2^{x-1}$","$2^x / \\ln 2$","$2x$"],answer:0,hint:"$(a^x)' = a^x \\ln a$.",explanation:"$f'(x) = 2^x \\ln 2$."},

// [Turunan Implisit tambahan]
{question:"Tentukan $\\frac{dy}{dx}$ dari $x^3 + y^3 = 8$.",options:["$-\\frac{x^2}{y^2}$","$\\frac{x^2}{y^2}$","$-\\frac{y^2}{x^2}$","$-\\frac{3x^2}{y^2}$","$\\frac{y^3}{x^3}$"],answer:0,hint:"$3x^2 + 3y^2 \\frac{dy}{dx} = 0$.",explanation:"$3x^2 + 3y^2 \\frac{dy}{dx} = 0$.\n$\\frac{dy}{dx} = -\\frac{x^2}{y^2}$."},
{question:"Gunakan diferensiasi logaritmik untuk $y = x^x$. Tentukan $\\frac{dy}{dx}$.",options:["$x^x(\\ln x + 1)$","$x \\cdot x^{x-1}$","$x^x \\ln x$","$x^{x+1}$","$e^x \\ln x$"],answer:0,hint:"$\\ln y = x \\ln x$. Diferensialkan kedua ruas.",explanation:"$\\ln y = x\\ln x$.\n$\\frac{y'}{y} = \\ln x + 1$.\n$y' = x^x(\\ln x + 1)$."},

// [Turunan Tingkat Tinggi]
{question:"Tentukan $f''(x)$ dari $f(x) = x^4 - 3x^2 + x$.",options:["$12x^2 - 6$","$4x^3 - 6x + 1$","$12x^2 - 6x$","$24x$","$4x^3 - 6x$"],answer:0,hint:"$f'(x) = 4x^3 - 6x + 1$. Turunkan lagi.",explanation:"$f'(x) = 4x^3 - 6x + 1$.\n$f''(x) = 12x^2 - 6$."},
{question:"Tentukan turunan kedua dari $f(x) = \\sin x$.",options:["$-\\sin x$","$\\cos x$","$-\\cos x$","$\\sin x$","$0$"],answer:0,hint:"$f'(x) = \\cos x$, $f''(x) = -\\sin x$.",explanation:"$f'(x) = \\cos x$.\n$f''(x) = -\\sin x$."},
{question:"Tentukan turunan kedua dari $f(x) = e^{3x}$.",options:["$9e^{3x}$","$3e^{3x}$","$6e^{3x}$","$e^{3x}$","$27e^{3x}$"],answer:0,hint:"$f'(x) = 3e^{3x}$, $f''(x) = 9e^{3x}$.",explanation:"$f'(x) = 3e^{3x}$.\n$f''(x) = 9e^{3x}$."},
{question:"Tentukan turunan kedua dari $f(x) = \\ln x$.",options:["$-\\frac{1}{x^2}$","$\\frac{1}{x^2}$","$\\frac{1}{x}$","$-\\frac{1}{x}$","$\\frac{2}{x}$"],answer:0,hint:"$f'(x) = 1/x = x^{-1}$. Turunkan lagi.",explanation:"$f'(x) = x^{-1}$.\n$f''(x) = -x^{-2} = -\\frac{1}{x^2}$."},

// [More Applications — monotonicity]
{question:"Tentukan interval di mana $f(x) = x^2 - 4x$ naik.",options:["$x > 2$","$x < 2$","$x > 0$","$x > 4$","$x < 0$"],answer:0,hint:"$f'(x) = 2x - 4 > 0 \\Rightarrow x > 2$.",explanation:"$f'(x) = 2x - 4 > 0 \\Rightarrow x > 2$.\nFungsi naik pada $(2, \\infty)$."},
{question:"Tentukan interval fungsi naik untuk $f(x) = x^3 - 3x$.",options:["$x < -1$ atau $x > 1$","$-1 < x < 1$","$x > 0$","$x > 3$","$x < -1$"],answer:0,hint:"$f'(x) = 3x^2 - 3 = 3(x-1)(x+1) > 0$.",explanation:"$f'(x) = 3(x^2-1) > 0 \\Rightarrow x < -1$ atau $x > 1$."},
{question:"Tentukan titik stasioner dari $f(x) = x^3 - 12x$.",options:["$x = 2$ dan $x = -2$","$x = 0$","$x = 12$","$x = \\pm\\sqrt{12}$","$x = 4$ dan $x = -4$"],answer:0,hint:"$f'(x) = 3x^2 - 12 = 0$.",explanation:"$3x^2 = 12 \\Rightarrow x^2 = 4 \\Rightarrow x = \\pm 2$."},
{question:"Tentukan titik belok dari $f(x) = x^3 - 3x^2 + x$.",options:["$x = 1$","$x = 0$","$x = 3$","$x = -1$","$x = 2$"],answer:0,hint:"$f''(x) = 6x - 6 = 0$.",explanation:"$f'(x) = 3x^2 - 6x + 1$.\n$f''(x) = 6x - 6 = 0 \\Rightarrow x = 1$.\nTitik belok di $(1, -1)$."},
{question:"Tentukan titik maksimum lokal dari $f(x) = -x^2 + 6x$.",options:["$(3, 9)$","$(6, 0)$","$(0, 0)$","$(3, 6)$","$(2, 8)$"],answer:0,hint:"$f'(x) = -2x + 6 = 0 \\Rightarrow x = 3$.",explanation:"$f'(x) = -2x+6 = 0 \\Rightarrow x=3$.\n$f(3) = -9+18 = 9$.\n$f''(3) = -2 < 0$ → maksimum lokal.\nTitik $(3, 9)$."},

// [More Integrals]
{question:"Tentukan $\\int 5 \\, dx$.",options:["$5x + C$","$5$","$\\frac{5x^2}{2} + C$","$C$","$0$"],answer:0,hint:"Integral konstanta: $\\int c\\,dx = cx + C$.",explanation:"$\\int 5\\,dx = 5x + C$."},
{question:"Tentukan $\\int (3x^2 - 2x + 1) \\, dx$.",options:["$x^3 - x^2 + x + C$","$6x - 2 + C$","$x^3 - x^2 + C$","$3x^3 - 2x^2 + x + C$","$x^3 - x + C$"],answer:0,hint:"Integralkan suku per suku.",explanation:"$\\int (3x^2 - 2x + 1)dx = x^3 - x^2 + x + C$."},
{question:"Tentukan $\\int \\sec^2 x \\, dx$.",options:["$\\tan x + C$","$\\sec x + C$","$\\sec x \\tan x + C$","$-\\cot x + C$","$\\sin x + C$"],answer:0,hint:"$(\\tan x)' = \\sec^2 x$.",explanation:"$\\int \\sec^2 x\\,dx = \\tan x + C$."},
{question:"Tentukan $\\int x \\cos x \\, dx$.",options:["$x\\sin x + \\cos x + C$","$x\\sin x + C$","$x\\cos x - \\sin x + C$","$\\sin x + x\\cos x + C$","$x\\sin x - \\cos x + C$"],answer:0,hint:"Integration by parts: $u = x$, $dv = \\cos x\\,dx$.",explanation:"$u=x, dv=\\cos x\\,dx$.\n$du=dx, v=\\sin x$.\n$x\\sin x - \\int \\sin x\\,dx = x\\sin x + \\cos x + C$."},
{question:"Tentukan $\\int x \\ln x \\, dx$.",options:["$\\frac{x^2}{2}\\ln x - \\frac{x^2}{4} + C$","$x\\ln x - x + C$","$\\frac{x^2}{2}\\ln x + C$","$\\frac{(\\ln x)^2}{2} + C$","$x^2 \\ln x + C$"],answer:0,hint:"By parts: $u = \\ln x$, $dv = x\\,dx$.",explanation:"$u=\\ln x, dv=x\\,dx$.\n$du=\\frac{1}{x}dx, v=\\frac{x^2}{2}$.\n$\\frac{x^2}{2}\\ln x - \\int \\frac{x}{2}dx = \\frac{x^2}{2}\\ln x - \\frac{x^2}{4} + C$."},

// [More Definite Integrals]
{question:"Hitung $\\int_1^2 x^2 \\, dx$.",options:["$\\frac{7}{3}$","$\\frac{8}{3}$","$3$","$\\frac{4}{3}$","$1$"],answer:0,hint:"$[x^3/3]_1^2 = 8/3 - 1/3$.",explanation:"$\\left[\\frac{x^3}{3}\\right]_1^2 = \\frac{8}{3} - \\frac{1}{3} = \\frac{7}{3}$."},
{question:"Hitung $\\int_{-1}^1 x^3 \\, dx$.",options:["$0$","$\\frac{1}{2}$","$1$","$-\\frac{1}{2}$","$2$"],answer:0,hint:"$x^3$ adalah fungsi ganjil pada interval simetris.",explanation:"$x^3$ fungsi ganjil. $\\int_{-a}^a f_{\\text{ganjil}}(x)dx = 0$."},
{question:"Hitung $\\int_0^{\\pi/2} \\cos x \\, dx$.",options:["$1$","$0$","$\\pi/2$","$-1$","$2$"],answer:0,hint:"$[\\sin x]_0^{\\pi/2}$.",explanation:"$[\\sin x]_0^{\\pi/2} = \\sin(\\pi/2) - \\sin 0 = 1 - 0 = 1$."},
{question:"Hitung $\\int_0^{\\pi/4} \\sec^2 x \\, dx$.",options:["$1$","$\\frac{\\pi}{4}$","$\\sqrt{2}$","$0$","$2$"],answer:0,hint:"$[\\tan x]_0^{\\pi/4}$.",explanation:"$[\\tan x]_0^{\\pi/4} = \\tan(\\pi/4) - \\tan 0 = 1 - 0 = 1$."},
{question:"Hitung $\\int_0^1 \\frac{1}{1+x^2} \\, dx$.",options:["$\\frac{\\pi}{4}$","$\\frac{\\pi}{2}$","$1$","$\\arctan 1$","$0$"],answer:0,hint:"$[\\arctan x]_0^1$.",explanation:"$[\\arctan x]_0^1 = \\arctan 1 - \\arctan 0 = \\frac{\\pi}{4} - 0 = \\frac{\\pi}{4}$."},

// [More Substitution Integrals]
{question:"Tentukan $\\int x\\sqrt{x^2+4} \\, dx$.",options:["$\\frac{1}{3}(x^2+4)^{3/2} + C$","$\\frac{2}{3}(x^2+4)^{3/2} + C$","$\\sqrt{x^2+4} + C$","$\\frac{x^2}{2}\\sqrt{x^2+4} + C$","$(x^2+4)^{3/2} + C$"],answer:0,hint:"$u = x^2+4$, $du = 2x\\,dx$.",explanation:"$u = x^2+4$.\n$\\int \\frac{1}{2}\\sqrt{u}\\,du = \\frac{1}{2} \\cdot \\frac{2}{3}u^{3/2} + C = \\frac{1}{3}(x^2+4)^{3/2} + C$."},
{question:"Tentukan $\\int \\cos(3x+1) \\, dx$.",options:["$\\frac{1}{3}\\sin(3x+1) + C$","$\\sin(3x+1) + C$","$3\\sin(3x+1) + C$","$-\\frac{1}{3}\\sin(3x+1) + C$","$\\frac{1}{3}\\cos(3x+1) + C$"],answer:0,hint:"$u = 3x+1$, $du = 3dx$.",explanation:"$\\frac{1}{3}\\int \\cos u\\,du = \\frac{1}{3}\\sin(3x+1) + C$."},
{question:"Tentukan $\\int \\frac{e^x}{e^x+1} \\, dx$.",options:["$\\ln(e^x+1) + C$","$\\frac{e^x}{e^x+1} + C$","$e^x + C$","$\\ln(e^x) + C$","$\\frac{1}{e^x+1} + C$"],answer:0,hint:"$u = e^x+1$, $du = e^x dx$.",explanation:"$u = e^x+1$.\n$\\int \\frac{du}{u} = \\ln|u| + C = \\ln(e^x+1) + C$."},
{question:"Tentukan $\\int \\tan x \\, dx$.",options:["$-\\ln|\\cos x| + C$","$\\ln|\\sin x| + C$","$\\sec^2 x + C$","$-\\cot x + C$","$\\ln|\\sec x| + C$"],answer:0,hint:"$\\int \\frac{\\sin x}{\\cos x}dx$. Sub $u = \\cos x$.",explanation:"$u = \\cos x, du = -\\sin x\\,dx$.\n$-\\int \\frac{du}{u} = -\\ln|\\cos x| + C = \\ln|\\sec x| + C$."},

// [Partial Fractions & by parts extra]
{question:"Tentukan $\\int \\frac{1}{x(x+1)} \\, dx$.",options:["$\\ln\\left|\\frac{x}{x+1}\\right| + C$","$\\ln|x(x+1)| + C$","$\\frac{1}{x+1} + C$","$\\ln|x| - \\ln|x+1| + C$","$\\arctan x + C$"],answer:0,hint:"Pecahan parsial: $\\frac{1}{x} - \\frac{1}{x+1}$.",explanation:"$\\frac{1}{x(x+1)} = \\frac{1}{x} - \\frac{1}{x+1}$.\n$\\int = \\ln|x| - \\ln|x+1| + C = \\ln|x/(x+1)| + C$."},
{question:"Tentukan $\\int x^2 e^x \\, dx$.",options:["$e^x(x^2 - 2x + 2) + C$","$x^2 e^x + C$","$e^x(x^2 + 2x + 2) + C$","$e^x(x^2 - 2x) + C$","$(x^2-1)e^x + C$"],answer:0,hint:"By parts dua kali. $u = x^2, dv = e^x dx$.",explanation:"Pertama: $x^2 e^x - 2\\int xe^x dx$.\nKedua: $xe^x - e^x$.\nTotal: $e^x(x^2 - 2x + 2) + C$."},

// [Volume]
{question:"Tentukan volume benda putar $y = x$ pada $[0,2]$ mengelilingi sumbu-$x$.",options:["$\\frac{8\\pi}{3}$","$4\\pi$","$2\\pi$","$\\frac{4\\pi}{3}$","$8\\pi$"],answer:0,hint:"$V = \\pi\\int_0^2 x^2 dx$.",explanation:"$V = \\pi\\int_0^2 x^2 dx = \\pi\\left[\\frac{x^3}{3}\\right]_0^2 = \\frac{8\\pi}{3}$."},
{question:"Tentukan volume kerucut tinggi $h$ dan jari-jari $r$ menggunakan integral.",options:["$\\frac{1}{3}\\pi r^2 h$","$\\pi r^2 h$","$\\frac{2}{3}\\pi r^2 h$","$\\frac{1}{2}\\pi r^2 h$","$\\frac{4}{3}\\pi r^3$"],answer:0,hint:"Garis $y = \\frac{r}{h}x$ diputar dari $0$ ke $h$.",explanation:"$V = \\pi\\int_0^h \\left(\\frac{r}{h}x\\right)^2 dx = \\frac{\\pi r^2}{h^2}\\left[\\frac{x^3}{3}\\right]_0^h = \\frac{1}{3}\\pi r^2 h$."},

// [More ODE]
{question:"Selesaikan $\\frac{dy}{dx} = \\sin x$.",options:["$y = -\\cos x + C$","$y = \\cos x + C$","$y = \\sin x + C$","$y = -\\sin x + C$","$y = x\\sin x + C$"],answer:0,hint:"Integralkan: $y = \\int \\sin x\\,dx$.",explanation:"$y = \\int \\sin x\\,dx = -\\cos x + C$."},
{question:"Selesaikan $\\frac{dy}{dx} = -2y$ dengan $y(0) = 100$.",options:["$y = 100e^{-2x}$","$y = -2x + 100$","$y = 100e^{2x}$","$y = e^{-2x}$","$y = 100e^{-x}$"],answer:0,hint:"Solusi umum: $y = Ce^{-2x}$. Substitusi $y(0) = 100$.",explanation:"$y = Ce^{-2x}$.\n$y(0) = C = 100$.\n$y = 100e^{-2x}$."},
{question:"Selesaikan $\\frac{dy}{dx} = \\frac{x}{y}$.",options:["$y^2 - x^2 = C$","$y = x + C$","$y^2 = x^2 + C$","$\\frac{y^2}{2} = \\frac{x^2}{2} + C$","$y = x^2 + C$"],answer:0,hint:"Pisahkan: $y\\,dy = x\\,dx$.",explanation:"$y\\,dy = x\\,dx$.\n$\\frac{y^2}{2} = \\frac{x^2}{2} + C_1$.\n$y^2 - x^2 = C$ (konstanta baru)."},
{question:"Selesaikan PD $y'' + y = 0$.",options:["$y = C_1\\cos x + C_2\\sin x$","$y = C_1 e^x + C_2 e^{-x}$","$y = Ce^x$","$y = C_1 x + C_2$","$y = C\\sin x$"],answer:0,hint:"Persamaan karakteristik: $r^2 + 1 = 0 \\Rightarrow r = \\pm i$.",explanation:"$r^2 + 1 = 0 \\Rightarrow r = \\pm i$.\nSolusi: $y = C_1\\cos x + C_2\\sin x$."},
{question:"Selesaikan PD $y'' - y = 0$.",options:["$y = C_1 e^x + C_2 e^{-x}$","$y = C_1\\cos x + C_2\\sin x$","$y = Ce^x$","$y = C_1 x + C_2$","$y = Ce^{-x}$"],answer:0,hint:"$r^2 - 1 = 0 \\Rightarrow r = \\pm 1$.",explanation:"$r^2 - 1 = 0 \\Rightarrow r = 1, -1$.\n$y = C_1 e^x + C_2 e^{-x}$."},

// [More Series]
{question:"Tentukan jumlah 10 suku pertama deret aritmetika $1 + 3 + 5 + 7 + \\cdots$",options:["$100$","$55$","$50$","$110$","$80$"],answer:0,hint:"$S_n = \\frac{n}{2}(2a + (n-1)d)$.",explanation:"$a=1, d=2, n=10$.\n$S_{10} = \\frac{10}{2}(2+18) = 5(20) = 100$."},
{question:"Tentukan jumlah tak hingga $\\frac{1}{3} + \\frac{1}{9} + \\frac{1}{27} + \\cdots$",options:["$\\frac{1}{2}$","$\\frac{1}{3}$","$1$","$\\frac{2}{3}$","$3$"],answer:0,hint:"$S = \\frac{a}{1-r} = \\frac{1/3}{1-1/3}$.",explanation:"$a = 1/3, r = 1/3$.\n$S = \\frac{1/3}{2/3} = \\frac{1}{2}$."},
{question:"Apakah deret $\\sum_{n=1}^\\infty \\frac{1}{n^2}$ konvergen?",options:["Konvergen","Divergen","Tidak dapat ditentukan","Osilasi","Tergantung $n$"],answer:0,hint:"Deret-$p$ dengan $p = 2 > 1$.",explanation:"$\\sum 1/n^p$ konvergen untuk $p > 1$.\n$p = 2 > 1$ → konvergen.\n(Nilainya $= \\pi^2/6$)."},
{question:"Tuliskan 4 suku pertama deret Maclaurin untuk $\\cos x$.",options:["$1 - \\frac{x^2}{2} + \\frac{x^4}{24} - \\frac{x^6}{720}$","$x - \\frac{x^3}{6} + \\frac{x^5}{120}$","$1 + x + \\frac{x^2}{2}$","$1 - x + x^2 - x^3$","$1 - \\frac{x^2}{2}$"],answer:0,hint:"$\\cos x = \\sum_{n=0}^\\infty \\frac{(-1)^n x^{2n}}{(2n)!}$.",explanation:"$\\cos x = 1 - \\frac{x^2}{2!} + \\frac{x^4}{4!} - \\frac{x^6}{6!} + \\cdots$\n$= 1 - \\frac{x^2}{2} + \\frac{x^4}{24} - \\frac{x^6}{720}$."},
{question:"Tuliskan 4 suku pertama deret Maclaurin untuk $\\frac{1}{1-x}$.",options:["$1 + x + x^2 + x^3$","$1 - x + x^2 - x^3$","$x + x^2 + x^3$","$1 + 2x + 3x^2$","$1 + x + 2x^2 + 6x^3$"],answer:0,hint:"Deret geometri: $\\sum_{n=0}^\\infty x^n$ untuk $|x|<1$.",explanation:"$\\frac{1}{1-x} = 1 + x + x^2 + x^3 + \\cdots$ untuk $|x| < 1$."},

// [More applications & combination]  
{question:"Tentukan luas daerah antara $y = x^2$ dan $y = \\sqrt{x}$.",options:["$\\frac{1}{3}$","$\\frac{1}{6}$","$\\frac{1}{2}$","$\\frac{2}{3}$","$1$"],answer:0,hint:"Titik potong: $x^2 = \\sqrt{x} \\Rightarrow x^4 = x \\Rightarrow x = 0, 1$.",explanation:"$\\int_0^1 (\\sqrt{x} - x^2)dx = \\left[\\frac{2}{3}x^{3/2} - \\frac{x^3}{3}\\right]_0^1 = \\frac{2}{3} - \\frac{1}{3} = \\frac{1}{3}$."},
{question:"Tentukan luas daerah di bawah $y = e^x$ pada $[0, 1]$.",options:["$e - 1$","$e$","$1$","$e + 1$","$e^2 - 1$"],answer:0,hint:"$\\int_0^1 e^x dx = [e^x]_0^1$.",explanation:"$[e^x]_0^1 = e - 1$."},
{question:"Tentukan gradien garis singgung $y = x^3 - x$ di $x = 1$.",options:["$2$","$0$","$1$","$3$","$-1$"],answer:0,hint:"$y' = 3x^2 - 1$. Sub $x = 1$.",explanation:"$y' = 3x^2 - 1$.\n$y'(1) = 3 - 1 = 2$."},
{question:"Tentukan persamaan garis singgung $y = \\sqrt{x}$ di titik $(4, 2)$.",options:["$y = \\frac{1}{4}x + 1$","$y = \\frac{1}{2}x$","$y = 4x - 14$","$y = \\frac{1}{4}x$","$y = 2x - 6$"],answer:0,hint:"$y' = \\frac{1}{2\\sqrt{x}}$. Di $x=4$: $y' = 1/4$.",explanation:"$y'(4) = \\frac{1}{2\\sqrt{4}} = \\frac{1}{4}$.\n$y - 2 = \\frac{1}{4}(x - 4)$.\n$y = \\frac{1}{4}x + 1$."},
{question:"Tentukan persamaan garis singgung $y = \\ln x$ di $x = 1$.",options:["$y = x - 1$","$y = x$","$y = \\ln x$","$y = x + 1$","$y = 1$"],answer:0,hint:"$y'(1) = 1/1 = 1$. Titik $(1, 0)$.",explanation:"$y' = 1/x$, $y'(1) = 1$.\nTitik $(1, 0)$: $y - 0 = 1(x - 1)$.\n$y = x - 1$."},
{question:"Hitung laju pertambahan volume kubus saat rusuk $5$ cm dan rusuk bertambah $2$ cm/s.",options:["$150$ cm³/s","$50$ cm³/s","$75$ cm³/s","$250$ cm³/s","$100$ cm³/s"],answer:0,hint:"$V = s^3$. $\\frac{dV}{dt} = 3s^2 \\frac{ds}{dt}$.",explanation:"$\\frac{dV}{dt} = 3(5)^2(2) = 3(25)(2) = 150$ cm³/s."},
{question:"Tentukan dua bilangan positif yang jumlahnya 20 dan hasil kalinya maksimum.",options:["$10$ dan $10$","$5$ dan $15$","$1$ dan $19$","$8$ dan $12$","$4$ dan $16$"],answer:0,hint:"Maks $xy$ dengan $x+y=20$. $P = x(20-x)$.",explanation:"$P = x(20-x) = 20x - x^2$.\n$P' = 20-2x = 0 \\Rightarrow x = 10$.\n$y = 10$. Produk maks = 100."},
{question:"Tentukan turunan dari $F(x) = \\int_0^x t^2 \\, dt$.",options:["$F'(x) = x^2$","$F'(x) = 2x$","$F'(x) = \\frac{x^3}{3}$","$F'(x) = t^2$","$F'(x) = 0$"],answer:0,hint:"FTC bagian 1: $F'(x) = f(x)$.",explanation:"$F'(x) = x^2$ (Teorema Dasar Kalkulus)."},
{question:"Tentukan turunan dari $F(x) = \\int_0^{x^2} \\sin t \\, dt$.",options:["$2x\\sin(x^2)$","$\\sin(x^2)$","$\\cos(x^2)$","$2x\\cos(x^2)$","$x\\sin(x^2)$"],answer:0,hint:"Chain rule + FTC: $F'(x) = \\sin(x^2) \\cdot 2x$.",explanation:"$F'(x) = \\sin(x^2) \\cdot \\frac{d}{dx}(x^2) = 2x\\sin(x^2)$."},
{question:"Hitung akar-akar dari $2x^2 - 5x - 3 = 0$.",options:["$x = 3$ atau $x = -\\frac{1}{2}$","$x = 3$ atau $x = \\frac{1}{2}$","$x = -3$ atau $x = \\frac{1}{2}$","$x = 5$ atau $x = 3$","$x = \\frac{5}{4}$"],answer:0,hint:"Rumus abc atau faktorkan: $(2x+1)(x-3) = 0$.",explanation:"$(2x+1)(x-3) = 0$.\n$x = -1/2$ atau $x = 3$."},
{question:"Tentukan pusat dan jari-jari lingkaran $x^2 + y^2 - 4x + 6y - 3 = 0$.",options:["Pusat $(2,-3)$, $r = 4$","Pusat $(-2,3)$, $r = 4$","Pusat $(2,-3)$, $r = 16$","Pusat $(4,-6)$, $r = 3$","Pusat $(2,-3)$, $r = \\sqrt{3}$"],answer:0,hint:"Lengkapi kuadrat sempurna.",explanation:"$(x^2-4x+4) + (y^2+6y+9) = 3+4+9 = 16$.\n$(x-2)^2 + (y+3)^2 = 16$.\nPusat $(2,-3)$, $r = 4$."},
]);
