// ============================================
// ADVANCED CHALLENGE — Pre-Kalkulus Batch 2
// Persamaan & Identitas Trigonometri, Grafik Trigonometri,
// Aturan Segitiga, Eksponen & Logaritma Lanjut
// ============================================

appendQuestions('adv_precalculus', [
// [Persamaan Trigonometri] 61-70
{question:"Selesaikan $\\sin x = \\frac{1}{2}$ untuk $0 \\le x \\le 2\\pi$.",options:["$x = \\frac{\\pi}{6}$ atau $x = \\frac{5\\pi}{6}$","$x = \\frac{\\pi}{3}$ atau $x = \\frac{2\\pi}{3}$","$x = \\frac{\\pi}{6}$","$x = \\frac{\\pi}{4}$ atau $x = \\frac{3\\pi}{4}$","$x = \\frac{5\\pi}{6}$"],answer:0,hint:"$\\sin x = 1/2$ di kuadran I dan II.",explanation:"$\\sin x = 1/2$.\nKuadran I: $x = \\pi/6$.\nKuadran II: $x = \\pi - \\pi/6 = 5\\pi/6$."},
{question:"Selesaikan $\\cos x = -\\frac{\\sqrt{2}}{2}$ untuk $0 \\le x \\le 2\\pi$.",options:["$x = \\frac{3\\pi}{4}$ atau $x = \\frac{5\\pi}{4}$","$x = \\frac{\\pi}{4}$ atau $x = \\frac{7\\pi}{4}$","$x = \\frac{3\\pi}{4}$","$x = \\frac{5\\pi}{4}$","$x = \\pi$"],answer:0,hint:"$\\cos x = -\\sqrt{2}/2$ di kuadran II dan III.",explanation:"Sudut referensi $\\pi/4$.\nKuadran II: $3\\pi/4$. Kuadran III: $5\\pi/4$."},
{question:"Selesaikan $\\tan x = 1$ untuk $0 \\le x \\le 2\\pi$.",options:["$x = \\frac{\\pi}{4}$ atau $x = \\frac{5\\pi}{4}$","$x = \\frac{\\pi}{4}$","$x = \\frac{3\\pi}{4}$ atau $x = \\frac{7\\pi}{4}$","$x = \\frac{\\pi}{2}$","$x = 0$ atau $x = \\pi$"],answer:0,hint:"$\\tan x = 1$ saat $x = \\pi/4$ dan $\\pi + \\pi/4$.",explanation:"$\\tan x = 1$ saat sudut $45°$ di kuadran I dan III.\n$x = \\pi/4, 5\\pi/4$."},
{question:"Selesaikan $2\\sin^2 x - 1 = 0$ untuk $0 \\le x \\le 2\\pi$.",options:["$x = \\frac{\\pi}{4}, \\frac{3\\pi}{4}, \\frac{5\\pi}{4}, \\frac{7\\pi}{4}$","$x = \\frac{\\pi}{6}, \\frac{5\\pi}{6}$","$x = \\frac{\\pi}{3}, \\frac{2\\pi}{3}$","$x = 0, \\pi$","$x = \\frac{\\pi}{2}, \\frac{3\\pi}{2}$"],answer:0,hint:"$\\sin^2 x = 1/2 \\Rightarrow \\sin x = \\pm 1/\\sqrt{2}$.",explanation:"$\\sin^2 x = 1/2 \\Rightarrow \\sin x = \\pm\\frac{\\sqrt{2}}{2}$.\n$x = \\pi/4, 3\\pi/4, 5\\pi/4, 7\\pi/4$."},
{question:"Selesaikan $\\cos(2x) = \\frac{1}{2}$ untuk $0 \\le x \\le \\pi$.",options:["$x = \\frac{\\pi}{6}$ atau $x = \\frac{5\\pi}{6}$","$x = \\frac{\\pi}{3}$ atau $x = \\frac{2\\pi}{3}$","$x = \\frac{\\pi}{6}$","$x = \\frac{\\pi}{4}$","$x = \\frac{\\pi}{3}$"],answer:0,hint:"$2x = \\pi/3$ atau $2x = 5\\pi/3$ (dalam $[0, 2\\pi]$).",explanation:"$\\cos(2x) = 1/2 \\Rightarrow 2x = \\pi/3, 5\\pi/3$.\n$x = \\pi/6, 5\\pi/6$."},
{question:"Selesaikan $2\\cos^2 x - \\cos x = 0$ untuk $0 \\le x \\le 2\\pi$.",options:["$x = \\frac{\\pi}{2}, \\frac{\\pi}{3}, \\frac{3\\pi}{2}, \\frac{5\\pi}{3}$","$x = 0, \\pi$","$x = \\frac{\\pi}{4}, \\frac{3\\pi}{4}$","$x = \\frac{\\pi}{6}, \\frac{5\\pi}{6}$","$x = \\frac{\\pi}{2}, \\frac{3\\pi}{2}$"],answer:0,hint:"Faktorkan: $\\cos x(2\\cos x - 1) = 0$.",explanation:"$\\cos x = 0 \\Rightarrow x = \\pi/2, 3\\pi/2$.\n$\\cos x = 1/2 \\Rightarrow x = \\pi/3, 5\\pi/3$."},
{question:"Selesaikan $\\sin(2x) = \\sin x$ untuk $0 \\le x \\le 2\\pi$.",options:["$x = 0, \\pi, 2\\pi, \\frac{\\pi}{3}, \\frac{5\\pi}{3}$","$x = 0, \\pi$","$x = \\frac{\\pi}{6}, \\frac{5\\pi}{6}$","$x = \\frac{\\pi}{4}, \\frac{3\\pi}{4}$","$x = 0, \\frac{\\pi}{2}, \\pi$"],answer:0,hint:"$2\\sin x \\cos x = \\sin x \\Rightarrow \\sin x(2\\cos x - 1) = 0$.",explanation:"$\\sin x(2\\cos x - 1) = 0$.\n$\\sin x = 0 \\Rightarrow x = 0, \\pi, 2\\pi$.\n$\\cos x = 1/2 \\Rightarrow x = \\pi/3, 5\\pi/3$."},
{question:"Selesaikan $\\tan^2 x = 3$ untuk $0 \\le x \\le 2\\pi$.",options:["$x = \\frac{\\pi}{3}, \\frac{2\\pi}{3}, \\frac{4\\pi}{3}, \\frac{5\\pi}{3}$","$x = \\frac{\\pi}{6}, \\frac{5\\pi}{6}$","$x = \\frac{\\pi}{4}, \\frac{3\\pi}{4}$","$x = \\frac{\\pi}{3}, \\frac{4\\pi}{3}$","$x = \\frac{\\pi}{3}$"],answer:0,hint:"$\\tan x = \\pm\\sqrt{3}$. Sudut referensi $= \\pi/3$.",explanation:"$\\tan x = \\pm\\sqrt{3}$.\n$x = \\pi/3, 2\\pi/3, 4\\pi/3, 5\\pi/3$."},
{question:"Selesaikan $\\sin x + \\cos x = 0$ untuk $0 \\le x \\le 2\\pi$.",options:["$x = \\frac{3\\pi}{4}$ atau $x = \\frac{7\\pi}{4}$","$x = \\frac{\\pi}{4}$ atau $x = \\frac{5\\pi}{4}$","$x = \\pi$ atau $x = 2\\pi$","$x = \\frac{\\pi}{2}$ atau $x = \\frac{3\\pi}{2}$","$x = 0$ atau $x = \\pi$"],answer:0,hint:"$\\sin x = -\\cos x \\Rightarrow \\tan x = -1$.",explanation:"$\\tan x = -1$.\nKuadran II: $x = 3\\pi/4$.\nKuadran IV: $x = 7\\pi/4$."},

// [Identitas Trigonometri] 71-80
{question:"Sederhanakan $\\sin^2 x + \\cos^2 x + \\tan^2 x$.",options:["$\\sec^2 x$","$1 + \\tan^2 x$","$2$","$1$","$\\csc^2 x$"],answer:0,hint:"$\\sin^2 x + \\cos^2 x = 1$, dan $1 + \\tan^2 x = \\sec^2 x$.",explanation:"$\\sin^2 x + \\cos^2 x + \\tan^2 x = 1 + \\tan^2 x = \\sec^2 x$."},
{question:"Sederhanakan $\\frac{\\sin x}{\\csc x} + \\frac{\\cos x}{\\sec x}$.",options:["$1$","$2$","$\\sin x + \\cos x$","$\\sin^2 x + \\cos^2 x$","$0$"],answer:0,hint:"$\\frac{\\sin x}{\\csc x} = \\sin^2 x$ dan $\\frac{\\cos x}{\\sec x} = \\cos^2 x$.",explanation:"$\\sin x \\cdot \\sin x + \\cos x \\cdot \\cos x = \\sin^2 x + \\cos^2 x = 1$."},
{question:"Sederhanakan $\\sec^2 x - \\tan^2 x$.",options:["$1$","$0$","$\\cos^2 x$","$\\sin^2 x$","$\\sec^2 x$"],answer:0,hint:"Identitas Pythagoras: $\\sec^2 x = 1 + \\tan^2 x$.",explanation:"$\\sec^2 x - \\tan^2 x = (1 + \\tan^2 x) - \\tan^2 x = 1$."},
{question:"Ekspansikan $\\cos(x + y)$ menggunakan identitas penjumlahan sudut.",options:["$\\cos x \\cos y - \\sin x \\sin y$","$\\cos x \\cos y + \\sin x \\sin y$","$\\sin x \\cos y + \\cos x \\sin y$","$\\sin x \\cos y - \\cos x \\sin y$","$\\cos x + \\cos y$"],answer:0,hint:"Rumus penjumlahan: $\\cos(A+B) = \\cos A \\cos B - \\sin A \\sin B$.",explanation:"$\\cos(x+y) = \\cos x \\cos y - \\sin x \\sin y$."},
{question:"Sederhanakan $\\frac{1 - \\cos^2 x}{\\sin x}$.",options:["$\\sin x$","$\\cos x$","$\\tan x$","$1$","$\\csc x$"],answer:0,hint:"$1 - \\cos^2 x = \\sin^2 x$.",explanation:"$\\frac{\\sin^2 x}{\\sin x} = \\sin x$."},
{question:"Sederhanakan $\\cos^2 x - \\sin^2 x$ ke bentuk sudut rangkap.",options:["$\\cos(2x)$","$\\sin(2x)$","$2\\cos x$","$1$","$\\cos x$"],answer:0,hint:"Identitas sudut rangkap: $\\cos 2x = \\cos^2 x - \\sin^2 x$.",explanation:"$\\cos^2 x - \\sin^2 x = \\cos(2x)$."},
{question:"Sederhanakan $2\\sin x \\cos x$.",options:["$\\sin(2x)$","$\\cos(2x)$","$2\\sin x$","$1$","$\\sin^2 x$"],answer:0,hint:"Identitas sudut rangkap: $\\sin 2x = 2\\sin x \\cos x$.",explanation:"$2\\sin x \\cos x = \\sin(2x)$."},
{question:"Nyatakan $\\sin^2 x$ dalam bentuk $\\cos(2x)$.",options:["$\\frac{1 - \\cos(2x)}{2}$","$\\frac{1 + \\cos(2x)}{2}$","$1 - \\cos(2x)$","$\\cos^2(2x)$","$\\frac{\\cos(2x)}{2}$"],answer:0,hint:"Dari $\\cos 2x = 1 - 2\\sin^2 x$, selesaikan untuk $\\sin^2 x$.",explanation:"$\\cos 2x = 1 - 2\\sin^2 x$.\n$\\sin^2 x = \\frac{1 - \\cos 2x}{2}$."},
{question:"Nyatakan $\\cos^2 x$ dalam bentuk $\\cos(2x)$.",options:["$\\frac{1 + \\cos(2x)}{2}$","$\\frac{1 - \\cos(2x)}{2}$","$1 + \\cos(2x)$","$\\frac{\\cos(2x)}{2}$","$\\cos^2(2x)$"],answer:0,hint:"Dari $\\cos 2x = 2\\cos^2 x - 1$, selesaikan untuk $\\cos^2 x$.",explanation:"$\\cos 2x = 2\\cos^2 x - 1$.\n$\\cos^2 x = \\frac{1 + \\cos 2x}{2}$."},

// [Grafik Trigonometri & Aturan Segitiga] 81-90
{question:"Tentukan periode dari fungsi $y = \\sin(2x)$.",options:["$\\pi$","$2\\pi$","$\\frac{\\pi}{2}$","$4\\pi$","$\\frac{2\\pi}{3}$"],answer:0,hint:"Periode $= 2\\pi / |b|$ di mana $y = \\sin(bx)$.",explanation:"$T = \\frac{2\\pi}{2} = \\pi$."},
{question:"Tentukan periode dari fungsi $y = \\cos\\left(\\frac{x}{3}\\right)$.",options:["$6\\pi$","$2\\pi$","$3\\pi$","$\\frac{2\\pi}{3}$","$\\pi$"],answer:0,hint:"$b = 1/3$. Periode $= 2\\pi / |b|$.",explanation:"$T = \\frac{2\\pi}{1/3} = 6\\pi$."},
{question:"Tentukan amplitudo dari fungsi $y = -4\\sin(x)$.",options:["$4$","$-4$","$1$","$8$","$2$"],answer:0,hint:"Amplitudo = $|A|$ dari $y = A\\sin(x)$.",explanation:"$|A| = |-4| = 4$."},
{question:"Tentukan nilai maksimum dari $y = 3\\cos(x) + 2$.",options:["$5$","$3$","$2$","$1$","$6$"],answer:0,hint:"Maks $\\cos x = 1$, jadi maks $y = 3(1) + 2$.",explanation:"$\\cos x$ maks = 1.\n$y_{\\text{maks}} = 3(1) + 2 = 5$."},
{question:"Pada segitiga ABC, jika $a=5$, $b=7$, dan $\\angle C = 60°$, hitung panjang $c$.",options:["$\\sqrt{39}$","$\\sqrt{74}$","$8$","$6$","$\\sqrt{49}$"],answer:0,hint:"Aturan cosinus: $c^2 = a^2 + b^2 - 2ab\\cos C$.",explanation:"$c^2 = 25 + 49 - 2(5)(7)\\cos 60°$\n$= 74 - 70(0.5) = 74 - 35 = 39$.\n$c = \\sqrt{39}$."},
{question:"Hitung luas segitiga dengan sisi $a=6$, $b=8$, dan sudut apit $\\angle C=30°$.",options:["$12$","$24$","$48$","$6$","$16$"],answer:0,hint:"Luas $= \\frac{1}{2}ab\\sin C$.",explanation:"$L = \\frac{1}{2}(6)(8)\\sin 30° = \\frac{1}{2}(48)(0.5) = 12$."},
{question:"Tentukan panjang sisi miring segitiga siku-siku jika kakinya 5 dan 12.",options:["$13$","$17$","$7$","$\\sqrt{119}$","$15$"],answer:0,hint:"Teorema Pythagoras: $c = \\sqrt{a^2+b^2}$.",explanation:"$c = \\sqrt{25 + 144} = \\sqrt{169} = 13$."},

// [Eksponen Lanjut] 106-115
{question:"Selesaikan $5^{2x} = 125$.",options:["$x = \\frac{3}{2}$","$x = 3$","$x = 2$","$x = \\frac{5}{2}$","$x = 1$"],answer:0,hint:"$125 = 5^3$, jadi $2x = 3$.",explanation:"$5^{2x} = 5^3 \\Rightarrow 2x = 3 \\Rightarrow x = 3/2$."},
{question:"Selesaikan $e^{3x} = 2$.",options:["$x = \\frac{\\ln 2}{3}$","$x = 3\\ln 2$","$x = \\frac{2}{3}$","$x = \\ln(2/3)$","$x = e^{2/3}$"],answer:0,hint:"$3x = \\ln 2$.",explanation:"$e^{3x} = 2 \\Rightarrow 3x = \\ln 2 \\Rightarrow x = \\frac{\\ln 2}{3}$."},
{question:"Selesaikan $4^x = 8^{x-1}$.",options:["$x = 3$","$x = 2$","$x = 4$","$x = 6$","$x = 1$"],answer:0,hint:"$4 = 2^2$, $8 = 2^3$. Samakan basis.",explanation:"$2^{2x} = 2^{3(x-1)} \\Rightarrow 2x = 3x - 3 \\Rightarrow x = 3$."},
{question:"Selesaikan dengan pemfaktoran: $e^{2x} - 5e^x + 6 = 0$.",options:["$x = \\ln 2$ atau $x = \\ln 3$","$x = 2$ atau $x = 3$","$x = \\ln 5$","$x = \\ln 6$","$x = 0$"],answer:0,hint:"Substitusi $u = e^x$: $u^2 - 5u + 6 = 0$.",explanation:"$u = e^x$. $(u-2)(u-3) = 0$.\n$e^x = 2 \\Rightarrow x = \\ln 2$.\n$e^x = 3 \\Rightarrow x = \\ln 3$."},

// [Logaritma Lanjut] 116-125
{question:"Sederhanakan $\\log_2(x) + \\log_2(y)$.",options:["$\\log_2(xy)$","$\\log_2(x+y)$","$\\log_2(x) \\cdot \\log_2(y)$","$\\log_4(xy)$","$2\\log_2(xy)$"],answer:0,hint:"Sifat log: $\\log a + \\log b = \\log(ab)$.",explanation:"$\\log_2 x + \\log_2 y = \\log_2(xy)$."},
{question:"Sederhanakan $\\log_3(x^2) - \\log_3(x)$.",options:["$\\log_3(x)$","$\\log_3(x^2/x)$","$2$","$\\log_3(2x)$","$0$"],answer:0,hint:"$\\log a^n = n\\log a$ dan $\\log a - \\log b = \\log(a/b)$.",explanation:"$\\log_3(x^2) - \\log_3(x) = \\log_3(x^2/x) = \\log_3 x$."},
{question:"Gunakan sifat perubahan basis: tulis $\\log_2 5$ dalam basis $e$.",options:["$\\frac{\\ln 5}{\\ln 2}$","$\\frac{\\ln 2}{\\ln 5}$","$\\ln(5/2)$","$\\frac{5}{2}$","$\\ln 5 - \\ln 2$"],answer:0,hint:"$\\log_a b = \\frac{\\ln b}{\\ln a}$.",explanation:"$\\log_2 5 = \\frac{\\ln 5}{\\ln 2}$."},
{question:"Selesaikan $\\log x + \\log(x+3) = 1$.",options:["$x = 2$","$x = 5$","$x = -5$","$x = 7$","$x = 10$"],answer:0,hint:"$\\log[x(x+3)] = 1 \\Rightarrow x^2+3x = 10$.",explanation:"$\\log[x(x+3)] = 1 \\Rightarrow x(x+3) = 10$.\n$x^2+3x-10 = 0 \\Rightarrow (x+5)(x-2)=0$.\n$x = 2$ (x = -5 tidak valid)."},
{question:"Selesaikan $\\log_2(x+2) - \\log_2(x-1) = 2$.",options:["$x = 2$","$x = 3$","$x = 4$","$x = 6$","$x = 5$"],answer:0,hint:"$\\log_2 \\frac{x+2}{x-1} = 2 \\Rightarrow \\frac{x+2}{x-1} = 4$.",explanation:"$\\frac{x+2}{x-1} = 4 \\Rightarrow x+2 = 4x-4 \\Rightarrow 6 = 3x \\Rightarrow x = 2$.\nCek: $x-1 = 1 > 0$ ✓."},
{question:"Selesaikan $\\ln(x) + \\ln(x-1) = \\ln(2)$.",options:["$x = 2$","$x = 1$","$x = e$","$x = 3$","$x = \\sqrt{2}$"],answer:0,hint:"$\\ln[x(x-1)] = \\ln 2 \\Rightarrow x(x-1) = 2$.",explanation:"$x(x-1) = 2 \\Rightarrow x^2 - x - 2 = 0 \\Rightarrow (x-2)(x+1) = 0$.\n$x = 2$ (x = -1 tidak valid)."},
{question:"Tentukan himpunan penyelesaian $2^x > 16$.",options:["$x > 4$","$x > 16$","$x > 2$","$x \\ge 4$","$x > 8$"],answer:0,hint:"$16 = 2^4$. Fungsi $2^x$ naik.",explanation:"$2^x > 2^4 \\Rightarrow x > 4$.\nKarena basis 2 > 1, fungsi naik."},
{question:"Tentukan himpunan penyelesaian $\\log_2(x) < 3$.",options:["$0 < x < 8$","$x < 3$","$x < 8$","$0 < x < 3$","$x > 8$"],answer:0,hint:"$\\log_2 x < 3 \\Rightarrow x < 2^3 = 8$, dan $x > 0$.",explanation:"$\\log_2 x < 3 \\Rightarrow x < 8$.\nDomain: $x > 0$.\nHP: $(0, 8)$."},

// [Persamaan Trigonometri Lanjut] — additional
{question:"Selesaikan $\\sqrt{3}\\tan x - 1 = 0$ untuk $0 \\le x \\le 2\\pi$.",options:["$x = \\frac{\\pi}{6}$ atau $x = \\frac{7\\pi}{6}$","$x = \\frac{\\pi}{3}$ atau $x = \\frac{4\\pi}{3}$","$x = \\frac{\\pi}{6}$","$x = \\frac{\\pi}{4}$ atau $x = \\frac{5\\pi}{4}$","$x = \\frac{7\\pi}{6}$"],answer:0,hint:"$\\tan x = 1/\\sqrt{3}$. Sudut referensi $= \\pi/6$.",explanation:"$\\tan x = \\frac{1}{\\sqrt{3}}$.\n$x = \\pi/6$ (kuadran I), $x = 7\\pi/6$ (kuadran III)."},
{question:"Tentukan pergeseran fasa dari $y = \\sin\\left(x - \\frac{\\pi}{4}\\right)$.",options:["Geser kanan $\\frac{\\pi}{4}$","Geser kiri $\\frac{\\pi}{4}$","Geser atas $\\frac{\\pi}{4}$","Geser bawah $\\frac{\\pi}{4}$","Tidak ada pergeseran"],answer:0,hint:"$y = \\sin(x - c)$ bergeser ke kanan sejauh $c$.",explanation:"$y = \\sin(x - \\pi/4)$ bergeser ke kanan sejauh $\\pi/4$."},
{question:"Pada segitiga ABC, jika $a=3$, $b=4$, $c=5$, hitung $\\sin A$.",options:["$\\frac{3}{5}$","$\\frac{4}{5}$","$\\frac{3}{4}$","$\\frac{5}{3}$","$\\frac{4}{3}$"],answer:0,hint:"Ini segitiga siku-siku (3-4-5). $\\sin A = a / c$.",explanation:"$3^2 + 4^2 = 5^2$ → segitiga siku-siku di C.\n$\\sin A = \\frac{\\text{depan}}{\\text{miring}} = \\frac{3}{5}$."},
{question:"Evaluasi $\\log_5 125$.",options:["$3$","$5$","$25$","$2$","$4$"],answer:0,hint:"$5^? = 125$.",explanation:"$5^3 = 125$, maka $\\log_5 125 = 3$."},
{question:"Sederhanakan $\\sqrt[3]{27x^6}$.",options:["$3x^2$","$9x^3$","$3x^3$","$27x^2$","$9x^2$"],answer:0,hint:"$\\sqrt[3]{27} = 3$ dan $\\sqrt[3]{x^6} = x^2$.",explanation:"$\\sqrt[3]{27x^6} = \\sqrt[3]{27} \\cdot \\sqrt[3]{x^6} = 3x^2$."},
{question:"Tuliskan $\\log(1000)$ sebagai bilangan bulat.",options:["$3$","$10$","$100$","$4$","$2$"],answer:0,hint:"$\\log$ basis 10: $10^? = 1000$.",explanation:"$10^3 = 1000$, maka $\\log(1000) = 3$."},
{question:"Sederhanakan $2\\ln(x) + \\ln(y)$.",options:["$\\ln(x^2 y)$","$\\ln(2xy)$","$2\\ln(xy)$","$\\ln(x^2 + y)$","$\\ln(2x + y)$"],answer:0,hint:"$2\\ln x = \\ln x^2$, lalu gunakan sifat penjumlahan.",explanation:"$2\\ln x + \\ln y = \\ln x^2 + \\ln y = \\ln(x^2 y)$."},
{question:"Selesaikan $9^x - 3^x - 6 = 0$.",options:["$x = 1$","$x = 2$","$x = \\log_3 6$","$x = 0$","$x = \\ln 3$"],answer:0,hint:"$9^x = (3^x)^2$. Substitusi $u = 3^x$: $u^2 - u - 6 = 0$.",explanation:"$u = 3^x$. $u^2 - u - 6 = 0 \\Rightarrow (u-3)(u+2) = 0$.\n$u = 3 \\Rightarrow 3^x = 3 \\Rightarrow x = 1$.\n($u = -2$ tidak valid)."},
{question:"Selesaikan $10^{x+1} = 100^{2x}$.",options:["$x = \\frac{1}{3}$","$x = 1$","$x = 2$","$x = \\frac{1}{2}$","$x = \\frac{2}{3}$"],answer:0,hint:"$100 = 10^2$, jadi $100^{2x} = 10^{4x}$.",explanation:"$10^{x+1} = 10^{4x} \\Rightarrow x+1 = 4x \\Rightarrow 1 = 3x \\Rightarrow x = 1/3$."},
{question:"Selesaikan $2^{x+2} = 3^x$.",options:["$x = \\frac{2\\ln 2}{\\ln 3 - \\ln 2}$","$x = \\frac{\\ln 4}{\\ln 3}$","$x = 2$","$x = \\frac{\\ln 3}{\\ln 2}$","$x = 4$"],answer:0,hint:"Ambil ln kedua ruas: $(x+2)\\ln 2 = x \\ln 3$.",explanation:"$(x+2)\\ln 2 = x\\ln 3$.\n$x\\ln 2 + 2\\ln 2 = x\\ln 3$.\n$2\\ln 2 = x(\\ln 3 - \\ln 2)$.\n$x = \\frac{2\\ln 2}{\\ln 3 - \\ln 2}$."},
{question:"Selesaikan $\\log_5(x^2 - 4) = 1$.",options:["$x = 3$ atau $x = -3$","$x = 3$","$x = 9$","$x = \\sqrt{9}$","$x = 1$"],answer:0,hint:"$x^2 - 4 = 5^1 = 5$.",explanation:"$x^2 - 4 = 5 \\Rightarrow x^2 = 9 \\Rightarrow x = \\pm 3$.\nCek: $9-4=5>0$ ✓."},
{question:"Tentukan penyelesaian dari $\\ln(x^2) = 4$.",options:["$x = e^2$ atau $x = -e^2$","$x = e^4$","$x = e^2$","$x = 2e$","$x = 4$"],answer:0,hint:"$\\ln x^2 = 2\\ln|x| = 4 \\Rightarrow \\ln|x| = 2$.",explanation:"$2\\ln|x| = 4 \\Rightarrow \\ln|x| = 2 \\Rightarrow |x| = e^2$.\n$x = e^2$ atau $x = -e^2$."},

// [Ekspansi Trigonometri]
{question:"Ekspansikan $\\sin(x - y)$ menggunakan identitas selisih sudut.",options:["$\\sin x \\cos y - \\cos x \\sin y$","$\\sin x \\cos y + \\cos x \\sin y$","$\\cos x \\cos y - \\sin x \\sin y$","$\\cos x \\cos y + \\sin x \\sin y$","$\\sin x - \\sin y$"],answer:0,hint:"$\\sin(A-B) = \\sin A \\cos B - \\cos A \\sin B$.",explanation:"$\\sin(x-y) = \\sin x \\cos y - \\cos x \\sin y$."},
{question:"Pada segitiga ABC, jika $\\angle A = 30°$, $\\angle B = 45°$, dan $a=10$, hitung panjang $b$.",options:["$10\\sqrt{2}$","$10$","$5\\sqrt{2}$","$20$","$5\\sqrt{3}$"],answer:0,hint:"Aturan sinus: $\\frac{a}{\\sin A} = \\frac{b}{\\sin B}$.",explanation:"$\\frac{10}{\\sin 30°} = \\frac{b}{\\sin 45°}$.\n$\\frac{10}{1/2} = \\frac{b}{\\sqrt{2}/2}$.\n$b = 20 \\cdot \\frac{\\sqrt{2}}{2} = 10\\sqrt{2}$."},
]);
