// ============================================
// ADVANCED CHALLENGE — Pre-Kalkulus Batch 5 (CLOSING)
// Final 12 questions to reach 250
// ============================================

appendQuestions('adv_precalculus', [
{question:"Tentukan hasil bagi dan sisa dari $x^4 + 2x^3 - x + 3$ dibagi $x^2 + 1$.",options:["Hasil bagi $x^2+2x-1$, sisa $-3x+4$","Hasil bagi $x^2+2x$, sisa $3$","Hasil bagi $x^2-1$, sisa $2x+3$","Hasil bagi $x^2+2x+1$, sisa $0$","Hasil bagi $x^2$, sisa $2x^3-x+3$"],answer:0,hint:"Pembagian polinomial panjang.",explanation:"$x^4+2x^3-x+3 = (x^2+1)(x^2+2x-1) + (-3x+4)$.\nHasil bagi: $x^2+2x-1$, sisa: $-3x+4$."},
{question:"Selesaikan sistem: $x^2 + y^2 = 25$ dan $x + y = 7$.",options:["$(3,4)$ dan $(4,3)$","$(5,2)$ dan $(2,5)$","$(0,7)$ dan $(7,0)$","$(5,0)$ dan $(0,5)$","Tidak ada solusi"],answer:0,hint:"Dari $y = 7-x$, substitusi ke $x^2+y^2=25$.",explanation:"$x^2+(7-x)^2=25$.\n$2x^2-14x+49=25$.\n$2x^2-14x+24=0 \\Rightarrow x^2-7x+12=0$.\n$(x-3)(x-4)=0 \\Rightarrow x=3,4$."},
{question:"Tentukan resultan dari dua vektor $\\vec{u} = 3\\hat{i} + 4\\hat{j}$ dan $\\vec{v} = -\\hat{i} + 2\\hat{j}$.",options:["$2\\hat{i} + 6\\hat{j}$","$4\\hat{i} + 6\\hat{j}$","$2\\hat{i} + 2\\hat{j}$","$3\\hat{i} + 2\\hat{j}$","$4\\hat{i} + 2\\hat{j}$"],answer:0,hint:"Jumlahkan komponen: $(3+(-1), 4+2)$.",explanation:"$\\vec{u}+\\vec{v} = (3-1)\\hat{i} + (4+2)\\hat{j} = 2\\hat{i} + 6\\hat{j}$."},
{question:"Tentukan proyeksi skalar $\\vec{a}$ pada $\\vec{b}$ jika $\\vec{a} = \\langle 3, 4 \\rangle$ dan $\\vec{b} = \\langle 1, 0 \\rangle$.",options:["$3$","$4$","$5$","$0$","$7$"],answer:0,hint:"Proyeksi skalar = $\\frac{\\vec{a} \\cdot \\vec{b}}{|\\vec{b}|}$.",explanation:"$\\frac{\\vec{a}\\cdot\\vec{b}}{|\\vec{b}|} = \\frac{3(1)+4(0)}{1} = 3$."},
{question:"Tentukan persamaan hiperbola dengan fokus di $(\\pm 5, 0)$ dan simpangan $a = 3$.",options:["$\\frac{x^2}{9} - \\frac{y^2}{16} = 1$","$\\frac{x^2}{25} - \\frac{y^2}{9} = 1$","$\\frac{x^2}{16} - \\frac{y^2}{9} = 1$","$\\frac{x^2}{9} - \\frac{y^2}{25} = 1$","$x^2 - y^2 = 9$"],answer:0,hint:"$c=5, a=3 \\Rightarrow b^2 = c^2-a^2 = 16$.",explanation:"$c=5, a=3, b^2=25-9=16$.\n$\\frac{x^2}{9} - \\frac{y^2}{16} = 1$."},
{question:"Hitung $\\binom{10}{3}$.",options:["$120$","$720$","$210$","$30$","$1000$"],answer:0,hint:"$\\binom{10}{3} = \\frac{10!}{3!7!}$.",explanation:"$\\frac{10 \\cdot 9 \\cdot 8}{3 \\cdot 2 \\cdot 1} = \\frac{720}{6} = 120$."},
{question:"Tentukan suku ke-4 dari ekspansi binomial $(x+2)^5$.",options:["$80x^2$","$40x^3$","$10x^4$","$32$","$160x$"],answer:0,hint:"Suku ke-$(k+1)$: $\\binom{5}{k}x^{5-k}2^k$. Suku ke-4: $k=3$.",explanation:"$\\binom{5}{3}x^2 \\cdot 2^3 = 10 \\cdot 8 \\cdot x^2 = 80x^2$."},
{question:"Selesaikan $\\log_2(x) + \\log_2(x+6) = 4$.",options:["$x = 2$","$x = 4$","$x = 8$","$x = -8$","$x = 10$"],answer:0,hint:"$\\log_2[x(x+6)] = 4 \\Rightarrow x^2+6x = 16$.",explanation:"$x(x+6) = 16$.\n$x^2+6x-16 = 0 \\Rightarrow (x+8)(x-2)=0$.\n$x = 2$ ($x=-8$ tidak valid karena $\\log$ argumen harus positif)."},
{question:"Konversikan $\\frac{7\\pi}{4}$ radian ke derajat.",options:["$315°$","$220°$","$270°$","$330°$","$300°$"],answer:0,hint:"$\\frac{7\\pi}{4} \\times \\frac{180}{\\pi}$.",explanation:"$\\frac{7 \\times 180}{4} = \\frac{1260}{4} = 315°$."},
{question:"Jika $\\vec{a} \\times \\vec{b} = \\langle 1, -2, 3 \\rangle$, tentukan $|\\vec{a} \\times \\vec{b}|$.",options:["$\\sqrt{14}$","$\\sqrt{6}$","$14$","$2$","$\\sqrt{10}$"],answer:0,hint:"$|\\vec{v}| = \\sqrt{1^2+(-2)^2+3^2}$.",explanation:"$|\\vec{a}\\times\\vec{b}| = \\sqrt{1+4+9} = \\sqrt{14}$."},
{question:"Tentukan domain dari $f(x) = \\log_3(x^2 - 9)$.",options:["$x < -3$ atau $x > 3$","$-3 < x < 3$","$x \\ne \\pm 3$","$x > 3$","$x > 0$"],answer:0,hint:"$x^2 - 9 > 0 \\Rightarrow (x-3)(x+3) > 0$.",explanation:"$x^2-9 > 0 \\Rightarrow x < -3$ atau $x > 3$.\nDomain: $(-\\infty,-3) \\cup (3,\\infty)$."},
{question:"Tentukan semua nilai $x$ yang memenuhi $2\\sin^2 x + 3\\sin x - 2 = 0$ untuk $0 \\le x \\le 2\\pi$.",options:["$x = \\frac{\\pi}{6}$ dan $x = \\frac{5\\pi}{6}$","$x = \\frac{\\pi}{3}$ dan $x = \\frac{2\\pi}{3}$","$x = \\frac{\\pi}{2}$","$x = \\pi$","$x = \\frac{\\pi}{4}$ dan $x = \\frac{3\\pi}{4}$"],answer:0,hint:"Substitusi $u = \\sin x$: $2u^2+3u-2 = 0 \\Rightarrow (2u-1)(u+2)=0$.",explanation:"$u = 1/2$ atau $u = -2$.\n$\\sin x = -2$ mustahil.\n$\\sin x = 1/2 \\Rightarrow x = \\pi/6, 5\\pi/6$."},
]);
