// ============================================
// ADVANCED CHALLENGE — Kalkulus Batch 5 (CLOSING)
// Final 17 questions to reach 250
// ============================================

appendQuestions('adv_calculus', [
{question:"Tentukan $\\int e^x \\sin x \\, dx$.",options:["$\\frac{e^x(\\sin x - \\cos x)}{2} + C$","$e^x \\sin x + C$","$e^x \\cos x + C$","$\\frac{e^x \\sin x}{2} + C$","$-e^x \\cos x + C$"],answer:0,hint:"Integration by parts dua kali, lalu selesaikan persamaan aljabar.",explanation:"By parts dua kali → integral muncul kembali.\n$I = e^x \\sin x - e^x \\cos x - I$.\n$2I = e^x(\\sin x - \\cos x)$.\n$I = \\frac{e^x(\\sin x - \\cos x)}{2} + C$."},
{question:"Tentukan $\\int e^x \\cos x \\, dx$.",options:["$\\frac{e^x(\\sin x + \\cos x)}{2} + C$","$e^x \\cos x + C$","$e^x \\sin x + C$","$\\frac{e^x \\cos x}{2} + C$","$-e^x \\sin x + C$"],answer:0,hint:"Mirip soal sebelumnya: by parts dua kali.",explanation:"$I = e^x \\sin x + e^x \\cos x - I$.\n$2I = e^x(\\sin x + \\cos x)$.\n$I = \\frac{e^x(\\sin x + \\cos x)}{2} + C$."},
{question:"Hitung $\\int_0^\\pi x \\sin x \\, dx$.",options:["$\\pi$","$0$","$2\\pi$","$1$","$-\\pi$"],answer:0,hint:"By parts: $u = x$, $dv = \\sin x\\,dx$.",explanation:"$[-x\\cos x]_0^\\pi + \\int_0^\\pi \\cos x\\,dx$\n$= \\pi + [\\sin x]_0^\\pi = \\pi + 0 = \\pi$."},
{question:"Tentukan volume benda putar dari $y = \\sin x$ pada $[0, \\pi]$ mengelilingi sumbu-$x$.",options:["$\\frac{\\pi^2}{2}$","$\\pi^2$","$2\\pi$","$\\pi$","$\\frac{\\pi}{2}$"],answer:0,hint:"$V = \\pi \\int_0^\\pi \\sin^2 x\\,dx$.",explanation:"$V = \\pi \\int_0^\\pi \\frac{1-\\cos 2x}{2}dx = \\frac{\\pi}{2}[x - \\frac{\\sin 2x}{2}]_0^\\pi = \\frac{\\pi^2}{2}$."},
{question:"Tentukan volume benda putar dari $y = e^x$ pada $[0, 1]$ mengelilingi sumbu-$x$.",options:["$\\frac{\\pi(e^2-1)}{2}$","$\\pi e^2$","$\\pi(e-1)$","$\\frac{\\pi e}{2}$","$\\pi e^2 - \\pi$"],answer:0,hint:"$V = \\pi\\int_0^1 e^{2x}dx$.",explanation:"$V = \\pi\\int_0^1 e^{2x}dx = \\pi\\left[\\frac{e^{2x}}{2}\\right]_0^1 = \\frac{\\pi(e^2-1)}{2}$."},
{question:"Hitung $\\frac{d}{dx}[\\tan^{-1}(3x)]$.",options:["$\\frac{3}{1+9x^2}$","$\\frac{1}{1+9x^2}$","$\\frac{3}{1+3x^2}$","$\\frac{1}{1+x^2}$","$3\\sec^2(3x)$"],answer:0,hint:"Chain rule: $\\frac{1}{1+(3x)^2} \\cdot 3$.",explanation:"$\\frac{d}{dx}\\arctan(3x) = \\frac{1}{1+9x^2} \\cdot 3 = \\frac{3}{1+9x^2}$."},
{question:"Tentukan $\\int \\frac{x^2}{x^2+1} dx$.",options:["$x - \\arctan(x) + C$","$\\arctan(x) + C$","$\\frac{x^3}{3(x^2+1)} + C$","$\\ln(x^2+1) + C$","$x + \\arctan(x) + C$"],answer:0,hint:"$\\frac{x^2}{x^2+1} = 1 - \\frac{1}{x^2+1}$.",explanation:"$\\int \\left(1 - \\frac{1}{x^2+1}\\right)dx = x - \\arctan x + C$."},
{question:"Tentukan apakah $f(x) = x^3$ memiliki titik belok di $x = 0$.",options:["Ya, karena $f''(x)$ berubah tanda di $x=0$","Tidak","Hanya titik stasioner","Titik maksimum","Titik minimum"],answer:0,hint:"$f''(x) = 6x$. Di $x=0$: $f''(0)=0$, dan $f''$ berubah tanda.",explanation:"$f''(x) = 6x$.\n$f''(0) = 0$ dan $f''$ berubah dari negatif ke positif.\nTitik belok di $(0, 0)$."},
{question:"Selesaikan PD $y' = y + 1$.",options:["$y = Ce^x - 1$","$y = Ce^x$","$y = Ce^x + 1$","$y = e^x + C$","$y = x + C$"],answer:0,hint:"Separabel: $\\frac{dy}{y+1} = dx$.",explanation:"$\\int \\frac{dy}{y+1} = \\int dx$.\n$\\ln|y+1| = x + C_1$.\n$y+1 = Ce^x \\Rightarrow y = Ce^x - 1$."},
{question:"Hitung $\\lim_{x \\to \\infty} \\left(1 + \\frac{3}{x}\\right)^x$.",options:["$e^3$","$e$","$3e$","$\\infty$","$1$"],answer:0,hint:"$\\lim \\left(1+\\frac{a}{x}\\right)^x = e^a$.",explanation:"$\\lim_{x\\to\\infty} \\left(1+\\frac{3}{x}\\right)^x = e^3$.\nGeneralisasi definisi Euler."},
{question:"Tentukan turunan dari $f(x) = \\ln(\\sec x + \\tan x)$.",options:["$\\sec x$","$\\tan x$","$\\sec x \\tan x$","$\\frac{1}{\\sec x}$","$\\sec^2 x$"],answer:0,hint:"$f'(x) = \\frac{\\sec x \\tan x + \\sec^2 x}{\\sec x + \\tan x}$.",explanation:"$f'(x) = \\frac{\\sec x(\\tan x + \\sec x)}{\\sec x + \\tan x} = \\sec x$."},
{question:"Tentukan $\\int \\sec x \\, dx$.",options:["$\\ln|\\sec x + \\tan x| + C$","$\\sec x \\tan x + C$","$\\ln|\\cos x| + C$","$\\tan x + C$","$\\sec^2 x + C$"],answer:0,hint:"Kalikan atas-bawah dengan $(\\sec x + \\tan x)$.",explanation:"$\\int \\sec x\\,dx = \\ln|\\sec x + \\tan x| + C$."},
{question:"Hitung $\\int_0^1 x e^{-x} dx$.",options:["$1 - \\frac{2}{e}$","$\\frac{1}{e}$","$1 - \\frac{1}{e}$","$e - 1$","$\\frac{2}{e}$"],answer:0,hint:"By parts: $u = x$, $dv = e^{-x}dx$.",explanation:"$[-xe^{-x}]_0^1 + \\int_0^1 e^{-x}dx$\n$= -e^{-1} + [-e^{-x}]_0^1 = -\\frac{1}{e} + (-\\frac{1}{e}+1) = 1-\\frac{2}{e}$."},
{question:"Tentukan $\\frac{\\partial^2 f}{\\partial x^2}$ dari $f(x,y) = x^3 y^2$.",options:["$6xy^2$","$2x^3$","$3x^2 y^2$","$6x^2 y$","$x^2 y^2$"],answer:0,hint:"$\\frac{\\partial f}{\\partial x} = 3x^2 y^2$. Turunkan lagi terhadap $x$.",explanation:"$f_x = 3x^2 y^2$.\n$f_{xx} = 6xy^2$."},
{question:"Hitung integral $\\int_0^2 |x - 1| dx$.",options:["$1$","$2$","$0$","$\\frac{1}{2}$","$3$"],answer:0,hint:"Pecah di $x=1$: $\\int_0^1 (1-x)dx + \\int_1^2 (x-1)dx$.",explanation:"$\\int_0^1 (1-x)dx + \\int_1^2 (x-1)dx$\n$= [x-\\frac{x^2}{2}]_0^1 + [\\frac{x^2}{2}-x]_1^2$\n$= \\frac{1}{2} + \\frac{1}{2} = 1$."},
{question:"Hitung $\\frac{d}{dx}\\left(\\frac{e^x - e^{-x}}{2}\\right)$.",options:["$\\frac{e^x + e^{-x}}{2}$","$\\frac{e^x - e^{-x}}{2}$","$e^x$","$e^{-x}$","$1$"],answer:0,hint:"$\\frac{d}{dx}(\\sinh x) = \\cosh x$.",explanation:"$\\frac{d}{dx}\\left(\\frac{e^x-e^{-x}}{2}\\right) = \\frac{e^x+e^{-x}}{2} = \\cosh x$."},
{question:"Hitung $\\lim_{x \\to 0} \\frac{\\tan x - \\sin x}{x^3}$.",options:["$\\frac{1}{2}$","$0$","$1$","$\\frac{1}{3}$","$\\infty$"],answer:0,hint:"$\\tan x - \\sin x = \\sin x(\\sec x - 1)$. Gunakan ekspansi Taylor.",explanation:"Taylor: $\\tan x \\approx x + \\frac{x^3}{3}$, $\\sin x \\approx x - \\frac{x^3}{6}$.\n$\\tan x - \\sin x \\approx \\frac{x^3}{3} + \\frac{x^3}{6} = \\frac{x^3}{2}$.\nLimit $= \\frac{1}{2}$."},
]);
