// ============================================
// ADVANCED CHALLENGE — Kalkulus Batch 4 (Final)
// Filling to 250: Multivariable intro, more applications,
// integration techniques, numerical methods, review
// ============================================

appendQuestions('adv_calculus', [
// [Kalkulus Multivariabel — Intro]
{question:"Tentukan turunan parsial $\\frac{\\partial f}{\\partial x}$ dari $f(x,y) = x^2 y + 3xy^2$.",options:["$2xy + 3y^2$","$x^2 + 6xy$","$2x + 3y$","$2xy + 6xy$","$x^2 y$"],answer:0,hint:"Turunkan terhadap $x$, perlakukan $y$ sebagai konstanta.",explanation:"$\\frac{\\partial f}{\\partial x} = 2xy + 3y^2$."},
{question:"Tentukan turunan parsial $\\frac{\\partial f}{\\partial y}$ dari $f(x,y) = x^2 y + 3xy^2$.",options:["$x^2 + 6xy$","$2xy + 3y^2$","$2x + 6y$","$x^2 + 3x$","$6xy$"],answer:0,hint:"Turunkan terhadap $y$, perlakukan $x$ sebagai konstanta.",explanation:"$\\frac{\\partial f}{\\partial y} = x^2 + 6xy$."},
{question:"Tentukan $\\frac{\\partial f}{\\partial x}$ dari $f(x,y) = e^{xy}$.",options:["$ye^{xy}$","$xe^{xy}$","$e^{xy}$","$xye^{xy}$","$e^{x+y}$"],answer:0,hint:"Chain rule: $\\frac{\\partial}{\\partial x}(xy) = y$.",explanation:"$\\frac{\\partial f}{\\partial x} = e^{xy} \\cdot y = ye^{xy}$."},
{question:"Tentukan gradien dari $f(x,y) = x^2 + y^2$ di titik $(1, 2)$.",options:["$\\langle 2, 4 \\rangle$","$\\langle 1, 2 \\rangle$","$\\langle 4, 2 \\rangle$","$\\langle 2, 2 \\rangle$","$\\langle 1, 4 \\rangle$"],answer:0,hint:"$\\nabla f = \\langle 2x, 2y \\rangle$.",explanation:"$\\nabla f = \\langle 2x, 2y \\rangle$.\nDi $(1,2)$: $\\nabla f = \\langle 2, 4 \\rangle$."},
{question:"Hitung integral ganda $\\int_0^1 \\int_0^1 xy \\, dx \\, dy$.",options:["$\\frac{1}{4}$","$\\frac{1}{2}$","$1$","$\\frac{1}{3}$","$0$"],answer:0,hint:"$\\int_0^1 \\left[\\frac{x^2 y}{2}\\right]_0^1 dy = \\int_0^1 \\frac{y}{2}dy$.",explanation:"$\\int_0^1 \\frac{y}{2}dy = \\left[\\frac{y^2}{4}\\right]_0^1 = \\frac{1}{4}$."},

// [Teknik Integrasi Lanjut]
{question:"Tentukan $\\int \\frac{1}{x^2-1} dx$.",options:["$\\frac{1}{2}\\ln\\left|\\frac{x-1}{x+1}\\right| + C$","$\\ln|x^2-1| + C$","$\\arctan(x) + C$","$\\frac{1}{x^2-1} + C$","$\\ln|x-1| + C$"],answer:0,hint:"Pecahan parsial: $\\frac{1}{(x-1)(x+1)} = \\frac{1/2}{x-1} - \\frac{1/2}{x+1}$.",explanation:"$= \\frac{1}{2}\\ln|x-1| - \\frac{1}{2}\\ln|x+1| + C = \\frac{1}{2}\\ln\\left|\\frac{x-1}{x+1}\\right| + C$."},
{question:"Tentukan $\\int \\frac{x}{(x+1)(x+2)} dx$.",options:["$-\\ln|x+1| + 2\\ln|x+2| + C$","$\\ln|x+1| + \\ln|x+2| + C$","$\\frac{x}{x+1} + C$","$\\ln\\frac{x+1}{x+2} + C$","$\\arctan(x) + C$"],answer:0,hint:"Pecahan parsial: $\\frac{x}{(x+1)(x+2)} = \\frac{-1}{x+1} + \\frac{2}{x+2}$.",explanation:"$\\frac{x}{(x+1)(x+2)} = \\frac{A}{x+1} + \\frac{B}{x+2}$.\n$x = A(x+2) + B(x+1)$.\n$x=-1: -1=A \\Rightarrow A=-1$. $x=-2: -2=-B \\Rightarrow B=2$.\n$-\\ln|x+1| + 2\\ln|x+2| + C$."},
{question:"Tentukan $\\int \\frac{dx}{\\sqrt{4-x^2}}$.",options:["$\\arcsin\\left(\\frac{x}{2}\\right) + C$","$\\arccos\\left(\\frac{x}{2}\\right) + C$","$\\arctan\\left(\\frac{x}{2}\\right) + C$","$\\frac{1}{2}\\arcsin(x) + C$","$\\ln\\sqrt{4-x^2} + C$"],answer:0,hint:"Bentuk $\\frac{1}{\\sqrt{a^2-x^2}}$ dengan $a = 2$.",explanation:"$\\int \\frac{dx}{\\sqrt{a^2-x^2}} = \\arcsin(x/a) + C$.\n$= \\arcsin(x/2) + C$."},
{question:"Tentukan $\\int x^3 \\ln x \\, dx$.",options:["$\\frac{x^4}{4}\\ln x - \\frac{x^4}{16} + C$","$\\frac{x^4}{4}\\ln x + C$","$x^3 \\ln x - x^3 + C$","$\\frac{x^4}{16}\\ln x + C$","$\\frac{(\\ln x)^2}{2} + C$"],answer:0,hint:"By parts: $u = \\ln x$, $dv = x^3 dx$.",explanation:"$u=\\ln x, dv=x^3 dx$.\n$du=\\frac{1}{x}dx, v=\\frac{x^4}{4}$.\n$\\frac{x^4}{4}\\ln x - \\int \\frac{x^3}{4}dx = \\frac{x^4}{4}\\ln x - \\frac{x^4}{16} + C$."},

// [Aplikasi Integral — panjang busur, luas permukaan]
{question:"Tentukan panjang kurva $y = \\frac{2}{3}x^{3/2}$ dari $x=0$ ke $x=3$.",options:["$\\frac{14}{3}$","$3\\sqrt{2}$","$2\\sqrt{3}$","$4$","$\\sqrt{10}$"],answer:0,hint:"$y' = x^{1/2}$. $L = \\int_0^3 \\sqrt{1+x}dx$.",explanation:"$y' = x^{1/2}$.\n$L = \\int_0^3 \\sqrt{1+x}dx = \\left[\\frac{2}{3}(1+x)^{3/2}\\right]_0^3 = \\frac{2}{3}(8-1) = \\frac{14}{3}$."},
{question:"Rumus luas permukaan benda putar kurva $y=f(x)$ mengelilingi sumbu-$x$ adalah...",options:["$2\\pi \\int_a^b f(x)\\sqrt{1+[f'(x)]^2}dx$","$\\pi \\int_a^b [f(x)]^2 dx$","$2\\pi \\int_a^b f(x)dx$","$\\pi \\int_a^b \\sqrt{1+[f'(x)]^2}dx$","$2\\pi \\int_a^b x f(x)dx$"],answer:0,hint:"Gabungan keliling lingkaran ($2\\pi f$) dan elemen panjang busur.",explanation:"$S = 2\\pi \\int_a^b f(x)\\sqrt{1 + [f'(x)]^2}\\,dx$."},

// [Metode Numerik]
{question:"Pada metode trapesium, pendekatan integral $\\int_a^b f(x)dx$ dengan satu trapesium adalah...",options:["$\\frac{(b-a)}{2}[f(a)+f(b)]$","$(b-a)f(a)$","$(b-a)f(b)$","$(b-a)f\\left(\\frac{a+b}{2}\\right)$","$\\frac{f(a)+f(b)}{2}$"],answer:0,hint:"Luas trapesium = $\\frac{1}{2}(\\text{jumlah sisi sejajar})(\\text{tinggi})$.",explanation:"$\\int_a^b f(x)dx \\approx \\frac{b-a}{2}[f(a)+f(b)]$."},
{question:"Pada metode Simpson 1/3, pendekatan integral menggunakan...",options:["Parabola","Garis lurus","Kubik","Konstanta","Eksponensial"],answer:0,hint:"Simpson menggunakan polinomial derajat 2.",explanation:"Metode Simpson 1/3 menggunakan parabola (polinomial derajat 2).\n$\\int_a^b f \\approx \\frac{h}{3}[f(a) + 4f(m) + f(b)]$ dengan $m = (a+b)/2$."},

// [Teorema Penting]
{question:"Nyatakan Teorema Dasar Kalkulus bagian 2 (evaluasi).",options:["$\\int_a^b f(x)dx = F(b) - F(a)$ di mana $F' = f$","$\\frac{d}{dx}\\int_a^x f(t)dt = f(x)$","$\\int f' = f$","$f(b)-f(a) = f'(c)(b-a)$","$\\lim \\sum = \\int$"],answer:0,hint:"FTC-2: integral tentu dievaluasi menggunakan antiturunan.",explanation:"FTC bagian 2: $\\int_a^b f(x)dx = F(b) - F(a)$.\nDi mana $F$ adalah antiturunan dari $f$ ($F' = f$)."},
{question:"Tentukan nilai rata-rata fungsi $f(x) = x^2$ pada interval $[0, 3]$.",options:["$3$","$9$","$\\frac{9}{2}$","$\\frac{3}{2}$","$6$"],answer:0,hint:"$\\bar{f} = \\frac{1}{b-a}\\int_a^b f(x)dx = \\frac{1}{3}\\int_0^3 x^2 dx$.",explanation:"$\\frac{1}{3}\\int_0^3 x^2 dx = \\frac{1}{3}\\left[\\frac{x^3}{3}\\right]_0^3 = \\frac{1}{3} \\cdot 9 = 3$."},
{question:"Tentukan nilai rata-rata $f(x) = \\sin x$ pada $[0, \\pi]$.",options:["$\\frac{2}{\\pi}$","$0$","$1$","$\\frac{1}{\\pi}$","$\\frac{\\pi}{2}$"],answer:0,hint:"$\\bar{f} = \\frac{1}{\\pi}\\int_0^\\pi \\sin x\\,dx = \\frac{1}{\\pi}(2)$.",explanation:"$\\frac{1}{\\pi}[-\\cos x]_0^\\pi = \\frac{1}{\\pi}(1+1) = \\frac{2}{\\pi}$."},

// [Soal Cerita Kalkulus]
{question:"Kecepatan partikel $v(t) = 3t^2 - 2t$. Tentukan posisi $s(t)$ jika $s(0) = 0$.",options:["$s(t) = t^3 - t^2$","$s(t) = 6t - 2$","$s(t) = t^3 - t^2 + 1$","$s(t) = 3t^2 - 2t$","$s(t) = \\frac{3t^3}{3} - t^2$"],answer:0,hint:"$s(t) = \\int v(t)dt = \\int (3t^2-2t)dt$.",explanation:"$s(t) = t^3 - t^2 + C$.\n$s(0) = 0 \\Rightarrow C = 0$.\n$s(t) = t^3 - t^2$."},
{question:"Percepatan $a(t) = -10$ m/s² (gravitasi). Jika $v(0) = 20$ m/s, tentukan $v(t)$.",options:["$v(t) = -10t + 20$","$v(t) = -5t^2 + 20$","$v(t) = 10t + 20$","$v(t) = -10t$","$v(t) = 20 - 5t$"],answer:0,hint:"$v(t) = \\int a\\,dt = -10t + C$. $v(0) = C = 20$.",explanation:"$v(t) = \\int -10\\,dt = -10t + C$.\n$v(0) = 20 \\Rightarrow C = 20$.\n$v(t) = -10t + 20$."},
{question:"Kapan partikel di soal sebelumnya mencapai ketinggian maksimum?",options:["$t = 2$ s","$t = 1$ s","$t = 0$ s","$t = 4$ s","$t = 10$ s"],answer:0,hint:"Ketinggian maks saat $v(t) = 0$.",explanation:"$v(t) = -10t + 20 = 0$.\n$t = 2$ detik."},
{question:"Populasi tumbuh menurut $P'(t) = 0.05P$, $P(0) = 1000$. Tentukan $P(t)$.",options:["$P(t) = 1000e^{0.05t}$","$P(t) = 1000 + 0.05t$","$P(t) = 1000(1.05)^t$","$P(t) = 50t + 1000$","$P(t) = e^{1000t}$"],answer:0,hint:"PD pertumbuhan: $P = P_0 e^{kt}$.",explanation:"$P' = 0.05P \\Rightarrow P = Ce^{0.05t}$.\n$P(0) = C = 1000$.\n$P(t) = 1000e^{0.05t}$."},
{question:"Hukum pendinginan Newton: $\\frac{dT}{dt} = -k(T - T_s)$. Jenis PD ini adalah...",options:["PD separabel orde 1","PD orde 2","PD eksak","PD Bernoulli","Bukan PD"],answer:0,hint:"Variabel $T$ dan $t$ dapat dipisahkan.",explanation:"$\\frac{dT}{T-T_s} = -k\\,dt$.\nSeparabel orde 1.\nSolusi: $T(t) = T_s + (T_0 - T_s)e^{-kt}$."},

// [Uji Konvergensi Deret]
{question:"Gunakan uji perbandingan: apakah $\\sum \\frac{1}{n^2+1}$ konvergen?",options:["Konvergen","Divergen","Tidak dapat ditentukan","Osilasi","Konvergen bersyarat"],answer:0,hint:"$\\frac{1}{n^2+1} < \\frac{1}{n^2}$, dan $\\sum 1/n^2$ konvergen.",explanation:"$\\frac{1}{n^2+1} \\le \\frac{1}{n^2}$.\n$\\sum 1/n^2$ konvergen (deret-$p$, $p=2$).\nUji perbandingan → konvergen."},
{question:"Gunakan uji integral: apakah $\\sum_{n=1}^\\infty \\frac{1}{n^3}$ konvergen?",options:["Konvergen","Divergen","Tidak dapat ditentukan","Osilasi","$= \\infty$"],answer:0,hint:"$\\int_1^\\infty x^{-3}dx$ konvergen.",explanation:"$\\int_1^\\infty \\frac{1}{x^3}dx = \\left[-\\frac{1}{2x^2}\\right]_1^\\infty = \\frac{1}{2}$.\nKonvergen → deret juga konvergen."},
{question:"Deret $\\sum_{n=1}^\\infty \\frac{(-1)^{n+1}}{n} = 1 - \\frac{1}{2} + \\frac{1}{3} - \\cdots$ konvergen ke...",options:["$\\ln 2$","$1$","$e$","$\\frac{\\pi}{4}$","$0$"],answer:0,hint:"Ini adalah ekspansi Maclaurin $\\ln(1+x)$ di $x = 1$.",explanation:"$\\ln(1+x) = x - \\frac{x^2}{2} + \\frac{x^3}{3} - \\cdots$\nDi $x=1$: $\\ln 2 = 1 - \\frac{1}{2} + \\frac{1}{3} - \\cdots$"},
{question:"Deret $\\sum_{n=0}^\\infty \\frac{(-1)^n}{(2n+1)} = 1 - \\frac{1}{3} + \\frac{1}{5} - \\cdots$ konvergen ke...",options:["$\\frac{\\pi}{4}$","$\\ln 2$","$1$","$\\frac{\\pi}{2}$","$e$"],answer:0,hint:"Ini adalah ekspansi Maclaurin $\\arctan(x)$ di $x = 1$.",explanation:"$\\arctan x = x - \\frac{x^3}{3} + \\frac{x^5}{5} - \\cdots$\nDi $x=1$: $\\frac{\\pi}{4} = 1 - \\frac{1}{3} + \\frac{1}{5} - \\cdots$ (Leibniz)"},

// [Soal Review Mixed]
{question:"Hitung $\\lim_{x \\to 1} \\frac{x^n - 1}{x - 1}$ untuk $n$ bilangan asli.",options:["$n$","$1$","$0$","$n-1$","$\\infty$"],answer:0,hint:"$x^n - 1 = (x-1)(x^{n-1}+x^{n-2}+\\cdots+1)$.",explanation:"$\\frac{x^n-1}{x-1} = x^{n-1}+x^{n-2}+\\cdots+1$.\nDi $x=1$: $= n$."},
{question:"Tentukan $\\frac{d}{dx}[x^x]$ menggunakan diferensiasi logaritmik.",options:["$x^x(\\ln x + 1)$","$x \\cdot x^{x-1}$","$x^x \\ln x$","$x^{x+1}$","$e^x \\ln x$"],answer:0,hint:"$\\ln y = x\\ln x$. Turunkan kedua ruas.",explanation:"$\\ln y = x\\ln x$.\n$\\frac{y'}{y} = \\ln x + 1$.\n$y' = x^x(\\ln x + 1)$."},
{question:"Hitung $\\int_0^\\infty xe^{-x} dx$.",options:["$1$","$0$","$\\infty$","$e$","$\\frac{1}{2}$"],answer:0,hint:"By parts: $u = x, dv = e^{-x}dx$. Evaluasi di $\\infty$.",explanation:"$u=x, dv=e^{-x}dx$.\n$[-xe^{-x}]_0^\\infty + \\int_0^\\infty e^{-x}dx = 0 + 1 = 1$."},
{question:"Tentukan $\\int_0^{2\\pi} \\sin^2 x \\, dx$.",options:["$\\pi$","$0$","$2\\pi$","$\\frac{\\pi}{2}$","$1$"],answer:0,hint:"$\\sin^2 x = \\frac{1-\\cos 2x}{2}$.",explanation:"$\\int_0^{2\\pi} \\frac{1-\\cos 2x}{2}dx = \\left[\\frac{x}{2} - \\frac{\\sin 2x}{4}\\right]_0^{2\\pi} = \\pi - 0 = \\pi$."},
{question:"Hitung $\\sum_{n=0}^\\infty \\frac{1}{n!}$.",options:["$e$","$1$","$\\infty$","$2$","$\\pi$"],answer:0,hint:"Ini adalah ekspansi Maclaurin $e^x$ di $x = 1$.",explanation:"$e^1 = \\sum_{n=0}^\\infty \\frac{1}{n!} = e \\approx 2.71828$."},
{question:"Tentukan $\\int \\frac{dx}{x \\ln x}$.",options:["$\\ln|\\ln x| + C$","$\\frac{(\\ln x)^2}{2} + C$","$\\frac{1}{\\ln x} + C$","$\\ln(x \\ln x) + C$","$x \\ln x + C$"],answer:0,hint:"Substitusi $u = \\ln x$, $du = dx/x$.",explanation:"$u = \\ln x$.\n$\\int \\frac{du}{u} = \\ln|u| + C = \\ln|\\ln x| + C$."},
{question:"Hitung $\\frac{d}{dx}\\left[\\int_0^{\\sin x} t^2 \\, dt\\right]$.",options:["$\\sin^2 x \\cos x$","$\\sin^2 x$","$\\cos x$","$2\\sin x \\cos x$","$\\frac{\\sin^3 x}{3}$"],answer:0,hint:"FTC + chain rule: $f(\\sin x) \\cdot \\cos x$ di mana $f(t) = t^2$.",explanation:"$\\frac{d}{dx}\\int_0^{\\sin x} t^2 dt = (\\sin x)^2 \\cdot \\cos x = \\sin^2 x \\cos x$."},
{question:"Tentukan $\\lim_{x \\to 0} \\frac{\\arctan x}{x}$.",options:["$1$","$0$","$\\infty$","$\\frac{\\pi}{2}$","$-1$"],answer:0,hint:"L'Hôpital atau deret Taylor: $\\arctan x \\approx x$ untuk $x \\to 0$.",explanation:"$\\lim \\frac{\\arctan x}{x}$. Bentuk $0/0$.\nL'Hôpital: $\\frac{1/(1+x^2)}{1} \\to 1$."},
{question:"Tentukan $\\lim_{n \\to \\infty} \\frac{n}{\\sqrt{n^2+1}}$.",options:["$1$","$0$","$\\infty$","$\\frac{1}{2}$","$\\sqrt{2}$"],answer:0,hint:"Bagi atas-bawah dengan $n$.",explanation:"$\\frac{n}{\\sqrt{n^2+1}} = \\frac{1}{\\sqrt{1+1/n^2}} \\to \\frac{1}{1} = 1$."},
{question:"Evaluasi $\\int_0^1 \\frac{x}{\\sqrt{1+x^2}} dx$.",options:["$\\sqrt{2}-1$","$1$","$\\ln 2$","$\\frac{\\pi}{4}$","$\\frac{1}{2}$"],answer:0,hint:"Substitusi $u = 1+x^2$.",explanation:"$u = 1+x^2, du = 2x\\,dx$.\n$\\frac{1}{2}\\int_1^2 u^{-1/2}du = [\\sqrt{u}]_1^2 / 1 = \\sqrt{2}-1$.\nWait: $\\frac{1}{2}[2\\sqrt{u}]_1^2 = [\\sqrt{u}]_1^2 = \\sqrt{2}-1$."},
]);
