// ============================================
// ADVANCED CHALLENGE — Kalkulus Batch 3
// Filling to 250: More limits, MVT, Rolle, curve sketching,
// arc length, trig integrals, improper integrals, more PDE/ODE,
// Taylor series, parametric, and mixed applications
// ============================================

appendQuestions('adv_calculus', [
// [Mean Value Theorem & Rolle's]
{question:"Nyatakan Teorema Nilai Rata-rata (MVT) untuk $f$ pada $[a,b]$.",options:["Ada $c \\in (a,b)$ sehingga $f'(c) = \\frac{f(b)-f(a)}{b-a}$","$f'(c) = 0$ untuk suatu $c$","$f(a) = f(b)$","$\\int_a^b f = f(c)(b-a)$","$f''(c) = 0$"],answer:0,hint:"MVT menghubungkan gradien sekan dengan gradien singgung.",explanation:"MVT: Jika $f$ kontinu di $[a,b]$ dan terdiferensialkan di $(a,b)$, maka ada $c \\in (a,b)$ sehingga $f'(c) = \\frac{f(b)-f(a)}{b-a}$."},
{question:"Tentukan nilai $c$ yang memenuhi MVT untuk $f(x)=x^2$ pada $[1,3]$.",options:["$c = 2$","$c = 1$","$c = 3$","$c = 1.5$","$c = 2.5$"],answer:0,hint:"$f'(c) = \\frac{f(3)-f(1)}{3-1} = \\frac{9-1}{2} = 4$. $f'(x) = 2x$.",explanation:"$\\frac{f(3)-f(1)}{2} = 4$.\n$f'(c) = 2c = 4 \\Rightarrow c = 2$."},
{question:"Apakah Teorema Rolle berlaku untuk $f(x) = |x|$ pada $[-1, 1]$?",options:["Tidak, $f$ tidak terdiferensialkan di $x=0$","Ya, $f'(0) = 0$","Tidak, $f(-1) \\ne f(1)$","Ya, $c = 0$","Tidak, $f$ tidak kontinu"],answer:0,hint:"Teorema Rolle memerlukan diferensiabilitas di seluruh $(a,b)$.",explanation:"$f(x) = |x|$ tidak terdiferensialkan di $x=0$ (titik lancip).\nSyarat Rolle tidak terpenuhi."},

// [Curve Sketching]
{question:"Tentukan interval kecekungan atas (concave up) dari $f(x) = x^3 - 6x^2$.",options:["$x > 2$","$x < 2$","$x > 0$","$x > 6$","$x < 0$"],answer:0,hint:"$f''(x) = 6x - 12 > 0 \\Rightarrow x > 2$.",explanation:"$f'(x) = 3x^2-12x$.\n$f''(x) = 6x-12 > 0 \\Rightarrow x > 2$.\nCekung atas pada $(2,\\infty)$."},
{question:"Tentukan interval kecekungan bawah (concave down) dari $f(x) = -x^4$.",options:["$\\mathbb{R}$ (seluruh domain)","$(0, \\infty)$","$(-\\infty, 0)$","Tidak ada","$(0, 1)$"],answer:0,hint:"$f''(x) = -12x^2 \\le 0$ untuk semua $x$.",explanation:"$f'(x) = -4x^3$.\n$f''(x) = -12x^2 < 0$ untuk $x \\ne 0$.\nSelalu cekung bawah."},
{question:"Fungsi $f(x) = x^4 - 4x^3$ memiliki titik belok di...",options:["$x = 0$ dan $x = 2$","$x = 0$","$x = 4$","$x = 1$","$x = 3$"],answer:0,hint:"$f''(x) = 12x^2 - 24x = 12x(x-2) = 0$.",explanation:"$f''(x) = 12x(x-2) = 0 \\Rightarrow x = 0, 2$.\nKeduanya mengubah tanda $f''$ → titik belok."},
{question:"Untuk $f(x) = \\frac{x^2}{x-1}$, tentukan asimtot miring (oblique).",options:["$y = x + 1$","$y = x$","$y = x - 1$","Tidak ada","$y = 2x$"],answer:0,hint:"Bagi dengan pembagian panjang: $\\frac{x^2}{x-1} = x + 1 + \\frac{1}{x-1}$.",explanation:"Pembagian: $x^2 ÷ (x-1) = x + 1 + \\frac{1}{x-1}$.\nUntuk $x \\to \\infty$: $\\frac{1}{x-1} \\to 0$.\nAsimtot miring: $y = x + 1$."},

// [More L'Hôpital applications]
{question:"Hitung $\\lim_{x \\to 0} \\frac{\\sin x - x}{x^3}$ menggunakan L'Hôpital.",options:["$-\\frac{1}{6}$","$0$","$\\frac{1}{6}$","$-\\frac{1}{3}$","$1$"],answer:0,hint:"Terapkan L'Hôpital 3 kali.",explanation:"$\\frac{\\cos x - 1}{3x^2} \\to \\frac{-\\sin x}{6x} \\to \\frac{-\\cos x}{6} = -\\frac{1}{6}$."},
{question:"Hitung $\\lim_{x \\to 0^+} x \\ln x$.",options:["$0$","$-\\infty$","$1$","$\\infty$","Tidak ada"],answer:0,hint:"Bentuk $0 \\cdot (-\\infty)$. Tulis ulang: $\\frac{\\ln x}{1/x}$, lalu L'Hôpital.",explanation:"$\\frac{\\ln x}{1/x} \\to \\frac{-\\infty}{\\infty}$.\nL'Hôpital: $\\frac{1/x}{-1/x^2} = -x \\to 0$."},
{question:"Hitung $\\lim_{x \\to \\infty} x e^{-x}$.",options:["$0$","$\\infty$","$1$","$e$","Tidak ada"],answer:0,hint:"Bentuk $\\infty \\cdot 0$. Tulis: $\\frac{x}{e^x}$.",explanation:"$\\frac{x}{e^x} \\to \\frac{\\infty}{\\infty}$.\nL'Hôpital: $\\frac{1}{e^x} \\to 0$."},
{question:"Hitung $\\lim_{x \\to 0} \\frac{e^x - 1 - x}{x^2}$.",options:["$\\frac{1}{2}$","$0$","$1$","$\\frac{1}{3}$","$e$"],answer:0,hint:"L'Hôpital dua kali.",explanation:"$\\frac{e^x - 1}{2x} \\to \\frac{e^x}{2} = \\frac{1}{2}$."},

// [Arc Length]
{question:"Tentukan panjang kurva $y = x$ dari $x = 0$ ke $x = 1$.",options:["$\\sqrt{2}$","$1$","$2$","$\\frac{\\sqrt{2}}{2}$","$\\pi$"],answer:0,hint:"$L = \\int_0^1 \\sqrt{1+(y')^2}dx = \\int_0^1 \\sqrt{2}dx$.",explanation:"$y' = 1$.\n$L = \\int_0^1 \\sqrt{1+1}dx = \\sqrt{2}$."},
{question:"Tentukan rumus panjang busur kurva $y = f(x)$ dari $a$ ke $b$.",options:["$L = \\int_a^b \\sqrt{1 + [f'(x)]^2} \\, dx$","$L = \\int_a^b |f(x)| dx$","$L = \\int_a^b f'(x) dx$","$L = b - a$","$L = \\int_a^b \\sqrt{f(x)} dx$"],answer:0,hint:"Rumus panjang busur menggunakan teorema Pythagoras infinitesimal.",explanation:"$L = \\int_a^b \\sqrt{1 + [f'(x)]^2} dx$.\nDiturunkan dari $ds = \\sqrt{dx^2 + dy^2}$."},

// [Trigonometric Integrals]
{question:"Tentukan $\\int \\sin^2 x \\, dx$.",options:["$\\frac{x}{2} - \\frac{\\sin(2x)}{4} + C$","$-\\sin x \\cos x + C$","$\\frac{\\sin^3 x}{3} + C$","$\\frac{x}{2} + C$","$\\cos^2 x + C$"],answer:0,hint:"Gunakan identitas: $\\sin^2 x = \\frac{1-\\cos 2x}{2}$.",explanation:"$\\int \\frac{1-\\cos 2x}{2}dx = \\frac{x}{2} - \\frac{\\sin 2x}{4} + C$."},
{question:"Tentukan $\\int \\cos^2 x \\, dx$.",options:["$\\frac{x}{2} + \\frac{\\sin(2x)}{4} + C$","$\\sin x \\cos x + C$","$\\frac{\\cos^3 x}{3} + C$","$\\frac{x}{2} + C$","$\\sin^2 x + C$"],answer:0,hint:"Gunakan $\\cos^2 x = \\frac{1+\\cos 2x}{2}$.",explanation:"$\\int \\frac{1+\\cos 2x}{2}dx = \\frac{x}{2} + \\frac{\\sin 2x}{4} + C$."},
{question:"Tentukan $\\int \\sin x \\cos x \\, dx$.",options:["$\\frac{\\sin^2 x}{2} + C$","$-\\frac{\\cos^2 x}{2} + C$","$-\\sin^2 x + C$","$\\frac{\\sin(2x)}{4} + C$","$\\cos^2 x + C$"],answer:0,hint:"$\\sin x \\cos x = \\frac{1}{2}\\sin(2x)$. Atau sub $u = \\sin x$.",explanation:"$u = \\sin x, du = \\cos x\\,dx$.\n$\\int u\\,du = \\frac{u^2}{2} + C = \\frac{\\sin^2 x}{2} + C$."},

// [Improper Integrals]
{question:"Tentukan apakah $\\int_1^\\infty \\frac{1}{x^3} dx$ konvergen dan hitung.",options:["Konvergen, $= \\frac{1}{2}$","Divergen","Konvergen, $= 1$","Konvergen, $= \\frac{1}{3}$","Konvergen, $= 2$"],answer:0,hint:"$\\int x^{-3}dx = -\\frac{1}{2x^2}$.",explanation:"$\\left[-\\frac{1}{2x^2}\\right]_1^\\infty = 0 - (-\\frac{1}{2}) = \\frac{1}{2}$.\nKonvergen."},
{question:"Tentukan apakah $\\int_0^1 \\frac{1}{\\sqrt{x}} dx$ konvergen.",options:["Konvergen, $= 2$","Divergen","Konvergen, $= 1$","Konvergen, $= \\frac{1}{2}$","Konvergen, $= \\sqrt{2}$"],answer:0,hint:"$\\int x^{-1/2}dx = 2\\sqrt{x}$.",explanation:"$[2\\sqrt{x}]_0^1 = 2 - 0 = 2$.\nKonvergen meskipun integran tak terbatas di $x=0$."},
{question:"Tentukan apakah $\\int_1^\\infty \\frac{1}{\\sqrt{x}} dx$ konvergen.",options:["Divergen","Konvergen, $= 2$","Konvergen, $= 1$","Konvergen, $= \\sqrt{2}$","Konvergen, $= \\infty$"],answer:0,hint:"$\\int x^{-1/2}dx = 2\\sqrt{x}$. Evaluasi di $\\infty$.",explanation:"$[2\\sqrt{x}]_1^\\infty = \\infty - 2 = \\infty$.\nDivergen. ($p = 1/2 < 1$."},

// [More ODE]
{question:"Selesaikan $\\frac{dy}{dx} = 3x^2 + 2x$ dengan $y(0) = 1$.",options:["$y = x^3 + x^2 + 1$","$y = x^3 + x^2$","$y = 3x^2 + 2x + 1$","$y = x^3 + x + 1$","$y = x^3 + 2x^2 + 1$"],answer:0,hint:"$y = \\int (3x^2+2x)dx = x^3+x^2+C$. $y(0) = C = 1$.",explanation:"$y = x^3 + x^2 + C$.\n$y(0) = 0 + 0 + C = 1 \\Rightarrow C = 1$.\n$y = x^3 + x^2 + 1$."},
{question:"Selesaikan $\\frac{dy}{dx} = e^{-x}$ dengan $y(0) = 0$.",options:["$y = 1 - e^{-x}$","$y = -e^{-x}$","$y = e^{-x} - 1$","$y = e^{-x}$","$y = -e^{-x} + 1$"],answer:0,hint:"$y = \\int e^{-x}dx = -e^{-x} + C$.",explanation:"$y = -e^{-x} + C$.\n$y(0) = -1 + C = 0 \\Rightarrow C = 1$.\n$y = 1 - e^{-x}$."},
{question:"Selesaikan PD separabel $\\frac{dy}{dx} = xy$.",options:["$y = Ce^{x^2/2}$","$y = Ce^x$","$y = Cx^2$","$y = Ce^{2x}$","$y = Ce^{-x^2/2}$"],answer:0,hint:"$\\frac{dy}{y} = x\\,dx$.",explanation:"$\\ln|y| = \\frac{x^2}{2} + C_1$.\n$y = Ce^{x^2/2}$."},
{question:"Selesaikan PD $y' + y = e^x$.",options:["$y = \\frac{e^x}{2} + Ce^{-x}$","$y = e^x + C$","$y = Ce^x$","$y = e^x(x+C)$","$y = \\frac{e^{2x}}{2} + C$"],answer:0,hint:"PD linear orde 1. Faktor integrating: $e^{\\int 1\\,dx} = e^x$.",explanation:"Kalikan $e^x$: $(ye^x)' = e^{2x}$.\n$ye^x = \\frac{e^{2x}}{2} + C$.\n$y = \\frac{e^x}{2} + Ce^{-x}$."},
{question:"Selesaikan PD $y'' + 4y = 0$.",options:["$y = C_1\\cos(2x) + C_2\\sin(2x)$","$y = C_1 e^{2x} + C_2 e^{-2x}$","$y = C_1\\cos(4x)$","$y = Ce^{4x}$","$y = C_1 x + C_2$"],answer:0,hint:"$r^2 + 4 = 0 \\Rightarrow r = \\pm 2i$.",explanation:"$r = \\pm 2i$.\n$y = C_1\\cos(2x) + C_2\\sin(2x)$."},
{question:"Selesaikan PD $y'' - 4y' + 4y = 0$.",options:["$y = (C_1 + C_2 x)e^{2x}$","$y = C_1 e^{2x} + C_2 e^{-2x}$","$y = Ce^{2x}$","$y = C_1 e^{4x}$","$y = (C_1 + C_2 x)e^{-2x}$"],answer:0,hint:"$r^2 - 4r + 4 = 0 \\Rightarrow (r-2)^2 = 0$. Akar kembar.",explanation:"$(r-2)^2 = 0 \\Rightarrow r = 2$ (kembar).\n$y = (C_1 + C_2 x)e^{2x}$."},

// [Taylor/Maclaurin Series extra]
{question:"Tuliskan deret Maclaurin untuk $\\frac{1}{1+x}$ (4 suku).",options:["$1 - x + x^2 - x^3$","$1 + x + x^2 + x^3$","$1 - x + x^2$","$1 + x - x^2$","$1 - 2x + 3x^2 - 4x^3$"],answer:0,hint:"$\\frac{1}{1+x} = \\frac{1}{1-(-x)}$. Deret geometri dengan $r = -x$.",explanation:"$\\frac{1}{1+x} = 1 - x + x^2 - x^3 + \\cdots$ untuk $|x| < 1$."},
{question:"Hitung deret Taylor $e^x$ di $a = 1$ (3 suku pertama).",options:["$e + e(x-1) + \\frac{e}{2}(x-1)^2$","$1 + x + \\frac{x^2}{2}$","$e + (x-1) + (x-1)^2$","$e(1 + x + x^2)$","$1 + (x-1) + \\frac{(x-1)^2}{2}$"],answer:0,hint:"$f^{(n)}(1) = e$ untuk semua $n$.",explanation:"$f(1)=e, f'(1)=e, f''(1)=e$.\n$e + e(x-1) + \\frac{e}{2}(x-1)^2 + \\cdots$"},
{question:"Tentukan jari-jari konvergensi deret $\\sum_{n=0}^\\infty \\frac{x^n}{n!}$.",options:["$\\infty$","$1$","$0$","$e$","$2$"],answer:0,hint:"Ini adalah deret Maclaurin untuk $e^x$, konvergen untuk semua $x$.",explanation:"$\\frac{a_{n+1}}{a_n} = \\frac{|x|}{n+1} \\to 0$ untuk semua $x$.\nJari-jari konvergensi $= \\infty$."},
{question:"Tentukan jari-jari konvergensi deret $\\sum_{n=0}^\\infty x^n$.",options:["$1$","$\\infty$","$0$","$2$","$1/2$"],answer:0,hint:"Deret geometri konvergen untuk $|x| < 1$.",explanation:"$|r| < 1 \\Rightarrow |x| < 1$.\nJari-jari konvergensi $= 1$."},
{question:"Gunakan uji rasio untuk menentukan konvergensi $\\sum \\frac{n!}{n^n}$.",options:["Konvergen","Divergen","Tidak dapat ditentukan","Osilasi","Konvergen bersyarat"],answer:0,hint:"$\\frac{a_{n+1}}{a_n} = \\frac{(n+1)!}{(n+1)^{n+1}} \\cdot \\frac{n^n}{n!} = \\left(\\frac{n}{n+1}\\right)^n$.",explanation:"$\\lim \\frac{a_{n+1}}{a_n} = \\lim \\left(\\frac{n}{n+1}\\right)^n = \\frac{1}{e} < 1$.\nKonvergen."},
{question:"Apakah deret $\\sum_{n=1}^\\infty \\frac{(-1)^n}{n}$ konvergen?",options:["Konvergen (bersyarat)","Divergen","Konvergen (mutlak)","Osilasi","Tidak dapat ditentukan"],answer:0,hint:"Deret harmonik berganti tanda, Leibniz test.",explanation:"$\\frac{1}{n} \\searrow 0$ → uji Leibniz terpenuhi.\nKonvergen bersyarat.\n(Tidak konvergen mutlak karena $\\sum 1/n$ divergen.)"},

// [Parametric & Polar Calculus]
{question:"Tentukan $\\frac{dy}{dx}$ untuk kurva parametrik $x = t^2$, $y = t^3$.",options:["$\\frac{3t}{2}$","$\\frac{3t^2}{2t}$","$\\frac{2t}{3t^2}$","$\\frac{t}{2}$","$3t^2$"],answer:0,hint:"$\\frac{dy}{dx} = \\frac{dy/dt}{dx/dt} = \\frac{3t^2}{2t}$.",explanation:"$\\frac{dy}{dx} = \\frac{3t^2}{2t} = \\frac{3t}{2}$ (untuk $t \\ne 0$)."},
{question:"Tentukan luas daerah yang dibatasi kurva polar $r = 2$ (lingkaran).",options:["$4\\pi$","$2\\pi$","$\\pi$","$8\\pi$","$16\\pi$"],answer:0,hint:"$A = \\frac{1}{2}\\int_0^{2\\pi} r^2 d\\theta$.",explanation:"$A = \\frac{1}{2}\\int_0^{2\\pi} 4\\,d\\theta = \\frac{1}{2}(4)(2\\pi) = 4\\pi$."},

// [Mixed Conceptual]
{question:"Jika $f'(x) > 0$ dan $f''(x) > 0$ pada interval $I$, bagaimana grafik $f$?",options:["Naik dan cekung atas","Naik dan cekung bawah","Turun dan cekung atas","Turun dan cekung bawah","Datar"],answer:0,hint:"$f' > 0$: naik. $f'' > 0$: cekung atas.",explanation:"$f' > 0$: fungsi naik.\n$f'' > 0$: cekung atas (kurva melengkung ke atas)."},
{question:"Apa interpretasi geometris dari $\\int_a^b f(x)dx$?",options:["Luas bersih antara grafik $f$ dan sumbu-$x$","Panjang kurva $f$","Gradien rata-rata","Volume benda putar","Nilai rata-rata $f$"],answer:0,hint:"Integral tentu dihubungkan dengan luas di bawah kurva.",explanation:"$\\int_a^b f(x)dx$ = luas bersih (signed area) antara grafik $f$ dan sumbu-$x$ pada $[a,b]$."},
{question:"Apa interpretasi geometris dari $f'(a)$?",options:["Gradien garis singgung di $x=a$","Luas di bawah kurva","Nilai rata-rata","Kecepatan rata-rata","Kelengkungan"],answer:0,hint:"Turunan = laju perubahan sesaat = kemiringan singgung.",explanation:"$f'(a)$ = gradien garis singgung grafik $f$ di titik $x = a$."},
{question:"Jika $f(x)$ memiliki maksimum lokal di $x = c$ dan $f'(c)$ ada, maka $f'(c) = ?$",options:["$0$","$1$","$-1$","$\\infty$","Tidak terdefinisi"],answer:0,hint:"Di titik ekstrem, gradien singgung horizontal.",explanation:"Di maksimum lokal: $f'(c) = 0$ (syarat perlu, Fermat's theorem)."},
{question:"Hitung $\\lim_{n \\to \\infty} \\left(1 + \\frac{1}{n}\\right)^n$.",options:["$e$","$1$","$\\infty$","$0$","$2$"],answer:0,hint:"Ini adalah definisi bilangan Euler $e$.",explanation:"$\\lim_{n \\to \\infty} \\left(1 + \\frac{1}{n}\\right)^n = e \\approx 2.71828$.\nDefinisi bilangan Euler."},
{question:"Hitung $\\frac{d}{dx}[\\sin^{-1}(x)]$.",options:["$\\frac{1}{\\sqrt{1-x^2}}$","$\\frac{-1}{\\sqrt{1-x^2}}$","$\\frac{1}{1+x^2}$","$\\cos^{-1}(x)$","$\\sec^2(x)$"],answer:0,hint:"Turunan arcsin.",explanation:"$\\frac{d}{dx}\\arcsin(x) = \\frac{1}{\\sqrt{1-x^2}}$ untuk $|x| < 1$."},
{question:"Tentukan $\\int \\frac{1}{\\sqrt{1-x^2}} dx$.",options:["$\\arcsin(x) + C$","$\\arccos(x) + C$","$\\arctan(x) + C$","$\\ln\\sqrt{1-x^2} + C$","$-\\arcsin(x) + C$"],answer:0,hint:"Antiturunan dari $\\frac{1}{\\sqrt{1-x^2}}$ adalah $\\arcsin x$.",explanation:"$\\int \\frac{1}{\\sqrt{1-x^2}} dx = \\arcsin(x) + C$."},
{question:"Tentukan $\\int \\frac{1}{x^2+4} dx$.",options:["$\\frac{1}{2}\\arctan\\left(\\frac{x}{2}\\right) + C$","$\\arctan(x) + C$","$\\frac{1}{4}\\arctan(x) + C$","$\\ln(x^2+4) + C$","$\\arctan(2x) + C$"],answer:0,hint:"$\\frac{1}{x^2+a^2} \\to \\frac{1}{a}\\arctan(x/a)$ dengan $a = 2$.",explanation:"$\\int \\frac{dx}{x^2+4} = \\frac{1}{2}\\arctan\\left(\\frac{x}{2}\\right) + C$."},

// [Related Rates]
{question:"Lingkaran dengan jari-jari bertambah $3$ cm/s. Hitung laju perubahan luas saat $r=10$ cm.",options:["$60\\pi$ cm²/s","$30\\pi$ cm²/s","$100\\pi$ cm²/s","$6\\pi$ cm²/s","$90\\pi$ cm²/s"],answer:0,hint:"$A = \\pi r^2$. $\\frac{dA}{dt} = 2\\pi r \\frac{dr}{dt}$.",explanation:"$\\frac{dA}{dt} = 2\\pi(10)(3) = 60\\pi$ cm²/s."},
{question:"Bola dengan volume $V = \\frac{4}{3}\\pi r^3$. Jika $\\frac{dr}{dt} = 2$ saat $r=3$, hitung $\\frac{dV}{dt}$.",options:["$72\\pi$","$36\\pi$","$108\\pi$","$24\\pi$","$48\\pi$"],answer:0,hint:"$\\frac{dV}{dt} = 4\\pi r^2 \\frac{dr}{dt}$.",explanation:"$\\frac{dV}{dt} = 4\\pi(9)(2) = 72\\pi$."},

// [Optimization]
{question:"Petani memiliki 100 m pagar untuk membuat kandang persegi panjang. Berapa luas maksimum?",options:["$625$ m²","$500$ m²","$250$ m²","$2500$ m²","$100$ m²"],answer:0,hint:"$P = 2l+2w = 100$. Maks $A = lw$ saat $l = w = 25$.",explanation:"$w = 50-l$.\n$A = l(50-l) = 50l-l^2$.\n$A'=50-2l=0 \\Rightarrow l=25, w=25$.\n$A = 625$ m²."},
{question:"Tentukan dimensi kotak terbuka (tanpa tutup) bervolume $32$ cm³ dengan bahan minimum (dasar persegi).",options:["Dasar $4 \\times 4$, tinggi $2$","Dasar $2 \\times 2$, tinggi $8$","Dasar $8 \\times 8$, tinggi $0.5$","Dasar $32 \\times 32$, tinggi $1/32$","Dasar $1 \\times 1$, tinggi $32$"],answer:0,hint:"$V = x^2 h = 32$. Min $S = x^2 + 4xh$.",explanation:"$h = 32/x^2$. $S = x^2 + 128/x$.\n$S' = 2x - 128/x^2 = 0 \\Rightarrow x^3 = 64 \\Rightarrow x = 4$.\n$h = 32/16 = 2$."},
{question:"Tentukan titik pada grafik $y = \\sqrt{x}$ yang terdekat ke titik $(3, 0)$.",options:["$(\\frac{5}{2}, \\sqrt{\\frac{5}{2}})$","$(3, \\sqrt{3})$","$(1, 1)$","$(4, 2)$","$(2, \\sqrt{2})$"],answer:0,hint:"Min $D^2 = (x-3)^2 + x$. Turunkan dan setarakan nol.",explanation:"$D^2 = (x-3)^2 + x = x^2 - 5x + 9$.\n$\\frac{d(D^2)}{dx} = 2x - 5 = 0 \\Rightarrow x = 5/2$.\n$y = \\sqrt{5/2}$."},

// [Newton's Method]
{question:"Tuliskan rumus iterasi Newton-Raphson untuk mencari akar $f(x) = 0$.",options:["$x_{n+1} = x_n - \\frac{f(x_n)}{f'(x_n)}$","$x_{n+1} = x_n - f(x_n)$","$x_{n+1} = \\frac{f(x_n)}{f'(x_n)}$","$x_{n+1} = x_n + \\frac{f(x_n)}{f'(x_n)}$","$x_{n+1} = x_n - \\frac{f'(x_n)}{f(x_n)}$"],answer:0,hint:"Metode Newton menggunakan garis singgung untuk memperbaiki tebakan.",explanation:"$x_{n+1} = x_n - \\frac{f(x_n)}{f'(x_n)}$."},

// [Riemann Sum]
{question:"Tentukan $\\int_0^1 x^2 dx$ menggunakan definisi Riemann sum.",options:["$\\frac{1}{3}$","$\\frac{1}{2}$","$1$","$\\frac{1}{4}$","$0$"],answer:0,hint:"$\\lim_{n\\to\\infty} \\sum_{i=1}^n \\left(\\frac{i}{n}\\right)^2 \\frac{1}{n} = \\lim \\frac{1}{n^3}\\frac{n(n+1)(2n+1)}{6}$.",explanation:"$\\lim_{n\\to\\infty} \\frac{n(n+1)(2n+1)}{6n^3} = \\frac{2}{6} = \\frac{1}{3}$."},
]);
