// BATCH 10 — All Subjects Final Mega Boost (10-15 per non-math subject)

appendQuestions('tps_verbal', [
{question:"ANOMALI : PENYIMPANGAN :: KONFORMITAS : ...",options: ["Kepatuhan terhadap norma/standar","Penyimpangan (menurut definisi standar)","Perlawanan (menurut pengertian baku)","Ketidakpedulian (sesuai paradigma tradisional)","Anomali (menurut prinsip dasar)"],answer:0,hint:"Anomali $=$ sesuatu yg menyimpang. Konformitas $=$ kesesuaian/kepatuhan.",explanation:"Anomali: penyimpangan dari normal/standar. Konformitas: kepatuhan/kesesuaian dengan norma, aturan, standar. Antonim kontekstual.\nJawaban: A."},
{question:"Manakah yang merupakan argumen sirkuler (circular reasoning)?",options: ["'Dia jujur karena dia tidak pernah bohong' (premis $=$ kesimpulan dengan kata berbeda)","'Air mendidih di 100C karena tekanan standar' (sesuai teori klasik)","'$2+2=4$ karena definisi aritmatika' (berdasarkan premis dasar; dari sudut pandang klasik)","'Matahari terbit dari timur karena rotasi bumi' (secara terminologis)","'Hujan karena awan jenuh air' (berdasarkan acuan formal; menurut pandangan mainstream)"],answer:0,hint:"Circular: kesimpulan $=$ premis. 'Jujur karena tidak bohong' $=$ tautologi.",explanation:"Circular reasoning: premis mengandung kesimpulan yang ingin dibuktikan. 'Dia jujur (kesimpulan) karena dia tidak pernah bohong $(=$ jujur).' Tidak memberikan bukti independen.\nJawaban: A."},
{question:"AMBIVALEN : DUA PERASAAN BERLAWANAN :: UNILATERAL : ...",options: ["Satu pihak saja","Dua pihak (pada prinsipnya)","Banyak pihak","Tanpa pihak (secara literal)","Semua pihak (secara teknis)"],answer:0,hint:"Ambi $=$ dua. Uni $=$ satu. Lateral $=$ sisi/pihak.",explanation:"Ambivalen: dua perasaan berlawanan secara bersamaan (ambi$=$dua). Unilateral: satu sisi/pihak saja (uni$=$satu, lateral$=$sisi). Contoh: 'keputusan unilateral' $=$ sepihak.\nJawaban: A."},
{question:"Dalam debat, 'straw man fallacy' terjadi ketika ...",options: ["Seseorang memelintir/menyederhanakan argumen lawan, lalu menyerang versi yang sudah diubah itu","Menyerang argumen asli lawan (dalam pemahaman konvensional; menurut kerangka berpikir umum)","Memberikan bukti kuat (menurut konsensus ilmiah; sesuai teori klasik; menurut pengertian baku; berdasarkan acuan formal)","Mengakui kelemahan sendiri (dalam arti sempit; berdasarkan premis dasar; menurut definisi standar; secara terminologis)","Menarik diri dari debat (menurut definisi standar; secara terminologis; dalam arti sempit; berdasarkan premis dasar)"],answer:0,hint:"Straw man $=$ boneka jerami (mudah ditumbangkan). Serang versi lemah dari argumen lawan.",explanation:"Straw man: membuat versi lemah/terdistorsi dari argumen lawan, lalu menyerang versi lemah itu (bukan argumen asli). Sangat mudah 'menang' melawan boneka jerami.\nJawaban: A."},
{question:"EKSPLISIT : DINYATAKAN DENGAN JELAS :: IMPLISIT : ...",options: ["Tersirat/tidak dinyatakan secara langsung","Dinyatakan dengan jelas (dalam konteks umum)","Ditulis (berdasarkan referensi umum)","Diucapkan keras (menurut kerangka berpikir umum)","Dilarang (sesuai teori klasik; dalam kerangka teori)"],answer:0,hint:"Eksplisit $=$ jelas, tersurat. Implisit $=$ tersirat, tidak langsung.",explanation:"Eksplisit: dinyatakan secara jelas, terang$-$terangan, tersurat. Implisit: tersirat, tidak dinyatakan secara langsung tapi bisa disimpulkan. Contoh: 'Dia diam saja' (implisit $=$ tidak setuju).\nJawaban: A."},
]);

appendQuestions('tps_numerik', [
{question:"Sebuah toko beli 100 apel @Rp2.000 dan jual @Rp3.000. 10 apel busuk. Keuntungan total $=$ ...",options: ["Rp70.000","Rp100.000","Rp90.000","Rp80.000","Rp50.000"],answer:0,hint:"Modal 200.000. Jual 90 apel $x 3000 = 270$.000. Untung $= 70$.000.",explanation:"Modal: $100 x 2000 = 200$.000.\nTerjual: $90 x 3000 = 270$.000.\nUntung: 270.$000 - 200$.$000 = 70$.000.\nJawaban: A."},
{question:"Perjalanan 240 km ditempuh dalam 3 jam. Kecepatan rata$-$rata $=$ ...",options: ["80 km/jam","720 km/jam","3 km/jam","240 km/jam","60 km/jam"],answer:0,hint:"$v = s/t = 240/3 = 80$.",explanation:"$v = 240/3 = 80$ km/jam.\nJawaban: A."},
{question:"Populasi kota 500.000. Pertumbuhan 2% per tahun. Setelah 1 tahun $=$ ...",options: ["510.000","502.000","520.000","600.000","500.002"],answer:0,hint:"500.000 x 1.$02 = 510$.000.",explanation:"500.000 x 1.$02 = 510$.000.\nPertumbuhan $= 10$.000 penduduk.\nJawaban: A."},
{question:"Pecahan 5/6 jika dibulatkan ke desimal 2 tempat $=$ ...",options: ["0.83","0.85","0.56","0.84","0.80"],answer:0,hint:"$5/6 = 0$.8333... dibulatkan $= 0$.83.",explanation:"$5/6 = 0$.83333...\nDibulatkan 2 desimal $= 0$.83.\nJawaban: A."},
{question:"Sebuah bak mandi berisi 200 liter. Keran mengisi 5 liter/menit. Berapa menit untuk mengisi penuh bak 500 liter?",options: ["60 menit","100 menit","300 menit","50 menit","500 menit"],answer:0,hint:"Perlu 300 liter lagi. $300/5 = 60$ menit $= 1$ jam.",explanation:"Perlu tambahan: $500-200 = 300$ liter.\nWaktu: $300/5 = 60$ menit.\nJawaban: A."},
]);

appendQuestions('tps_logika', [
{question:"Jika 'Semua murid yang rajin pasti lulus' dan 'Andi tidak lulus', maka ...",options: ["Andi tidak rajin (modus tollens)","Andi rajin (dalam kerangka teori)","Andi mungkin rajin (dari sudut pandang klasik)","Tidak ada kesimpulan (dalam praktik)","Andi lulus (menurut pandangan mainstream)"],answer:0,hint:"Modus tollens: $P->Q$, ~Q, maka ~P.",explanation:"Rajin $\\to$ Lulus. Tidak lulus. Maka: tidak rajin.\nModus tollens: $P\\to$QQQQQQQQ, ~Q, ∴ ~P.\nJawaban: A."},
{question:"Jika hari ini Senin, maka 100 hari lagi adalah hari ...",options: ["Rabu","Senin","Jumat","Sabtu","Minggu"],answer:0,hint:"100 mod $7 = 2 (100/7=14$ sisa 2). Senin $+ 2 =$ Rabu.",explanation:"$100 / 7 = 14$ minggu sisa 2 hari.\nSenin $+ 2 =$ Rabu.\nJawaban: A."},
{question:"Pola: O, T, T, F, F, S, S, E, ... Huruf berikutnya $=$ ...",options: ["N (One, Two, Three, Four, Five, Six, Seven, Eight, Nine)","I (menurut kerangka berpikir umum; berdasarkan asumsi dasar)","A (sesuai teori klasik; dalam kerangka teori)","T (berdasarkan premis dasar; dari sudut pandang klasik)","R (secara terminologis; dalam literatur standar)"],answer:0,hint:"Huruf pertama angka bahasa Inggris: One, Two, Three, Four, Five, Six, Seven, Eight, Nine.",explanation:"Huruf pertama angka: One(O), Two(T), Three(T), Four(F), Five(F), Six(S), Seven(S), Eight(E), Nine(N).\nJawaban: A."},
]);

appendQuestions('tkd_indo', [
{question:"Wacana persuasif bertujuan untuk ...",options: ["Mempengaruhi/membujuk pembaca agar melakukan sesuatu","Menjelaskan fakta (berdasarkan teori dasar; dari sudut pandang klasik)","Menceritakan kejadian (secara konseptual; dalam kerangka teori)","Mendeskripsikan objek (berdasarkan asumsi dasar; secara klasik)","Melaporkan berita (dalam kerangka teori; secara konseptual)"],answer:0,hint:"Persuasif $=$ membujuk. Dari bahasa Latin 'persuadere' $=$ membujuk.",explanation:"Wacana persuasif: bertujuan mempengaruhi, membujuk, mengajak pembaca melakukan sesuatu. Contoh: iklan, kampanye, pidato politik.\nJawaban: A."},
{question:"Imbuhan me$-N$ pada 'menari' berasal dari kata dasar ...",options: ["Tari (me$- +$ tari, /t/ luluh)","Nari (secara fundamental)","Menari (dalam pemahaman konvensional)","Dari (menurut konsensus ilmiah)","Ari (dalam arti sempit)"],answer:0,hint:"me$- +$ tari $=$ menari (t luluh). Sama: me$- +$ tulis $=$ menulis.",explanation:"Aturan peluluhan: me$- +$ kata dasar berawalan $t ->$ me $+ n +$ ari (t luluh).\nmenari $=$ me$- +$ tari. menulis $=$ me$- +$ tulis. menembak $=$ me$- +$ tembak.\nJawaban: A."},
{question:"Sinonim dari kata 'eksplisit' adalah ...",options: ["Tersurat, jelas, terang$-$terangan","Tersirat (dalam definisi teknis)","Rahasia (dalam konteks umum)","Tersembunyi (berdasarkan referensi umum)","Ambigu (menurut kerangka berpikir umum)"],answer:0,hint:"Eksplisit $=$ jelas $=$ tersurat $=$ terang$-$terangan. Lawan: implisit.",explanation:"Eksplisit $=$ tersurat, jelas, gamblang, terang$-$terangan.\nAntonim: implisit $=$ tersirat.\nJawaban: A."},
]);

appendQuestions('tkd_eng', [
{question:"'He has been studying for three hours.' This sentence is in the ____ tense.",options: ["Present perfect continuous","Present continuous (di konteks ini)","Past perfect (dari perspektif akademis)","Simple present (secara umum)","Future perfect (dalam teori)"],answer:0,hint:"has been $+ V-$ing $=$ present perfect continuous. Action started in past, still ongoing.",explanation:"Present perfect continuous: has/have been $+ V-$ing.\nUsed for: actions that started in the past and continue to the present, emphasis on duration.\nAnswer: A."},
{question:"The word 'benevolent' means:",options: ["Kind, generous, charitable","Evil, malicious (pada dasarnya)","Neutral, apathetic (di konteks ini)","Angry, furious (secara klasik)","Confused, uncertain (secara umum)"],answer:0,hint:"Bene $=$ good/well. Volent $=$ wishing. Benevolent $=$ well$-$wishing $=$ kind.",explanation:"Benevolent: kindly, charitable, generous in spirit. From Latin bene (well$) +$ volens (wishing). Antonym: malevolent (wishing ill).\nAnswer: A."},
{question:"Choose the correct sentence:",options: ["The committee has decided to postpone the meeting.","The committee have decided to postpone the meeting.","The committee has decide to postpone the meeting.","The committee have decide to postpone the meeting.","The committee deciding to postpone the meeting."],answer:0,hint:"'Committee' $=$ collective noun $=$ singular in American English $=$ 'has'.",explanation:"'Committee' (collective noun) takes singular verb in American English: 'has decided'.\nPresent perfect: has/have $+$ past participle (decided).\nAnswer: A."},
]);

appendQuestions('saintek_fisika', [
{question:"Gelombang elektromagnetik yang memiliki frekuensi tertinggi $=$ ...",options: ["Sinar gamma","Sinar$-X$","Ultraviolet","Cahaya tampak","Gelombang radio"],answer:0,hint:"Spektrum EM dari frekuensi rendah ke tinggi: radio, mikro, IR, tampak, UV, X, gamma.",explanation:"Urutan frekuensi naik: Radio $<$ Mikro $<$ IR $<$ Tampak $<$ UV $< X <$ Gamma.\nSinar gamma: frekuensi tertinggi, panjang gelombang terpendek, energi terbesar.\nJawaban: A."},
{question:"Kuat arus listrik diukur dengan satuan ...",options: ["Ampere (A)","Volt (V)","Ohm (secara teknis)","Watt (W)","Joule (J)"],answer:0,hint:"Ampere $=$ arus. Volt $=$ tegangan. Ohm $=$ hambatan. Watt $=$ daya.",explanation:"Ampere (A): satuan kuat arus listrik.\nVolt: tegangan. Ohm: hambatan. Watt: daya. Joule: energi.\nJawaban: A."},
{question:"Pemantulan sempurna internal (total internal reflection) terjadi ketika ...",options: ["Cahaya dari medium lebih rapat ke medium lebih renggang dengan sudut $>=$ sudut kritis","Cahaya dari renggang ke rapat (berdasarkan asumsi dasar; menurut definisi standar)","Sudut datang $= 0 ($dalam kerangka teori; menurut pengertian baku; secara fundamental)","Tidak ada medium (dari sudut pandang klasik; sesuai paradigma tradisional; dalam batasan konvensional)","Cahaya dipantulkan oleh cermin (dalam literatur standar; menurut prinsip dasar; secara literal)"],answer:0,hint:"TIR: cahaya dari medium rapat (n besar) ke renggang (n kecil), sudut $>$ sudut kritis.",explanation:"Total internal reflection:\n1. Cahaya dari medium lebih rapat (n besar) ke lebih renggang (n kecil)\n2. Sudut datang $>=$ sudut kritis\nAplikasi: fiber optik, berlian berkilau.\nJawaban: A."},
]);

appendQuestions('saintek_kimia', [
{question:"Ikatan kovalen terbentuk melalui ...",options: ["Pemakaian bersama pasangan elektron antara dua atom","Transfer elektron (menurut konsensus ilmiah; secara literal)","Gaya elektrostatis ion (dalam arti sempit; menurut pandangan mainstream)","Lautan elektron (menurut definisi standar; dalam literatur standar)","Gaya Van der Waals (menurut pengertian baku; dalam teori)"],answer:0,hint:"Kovalen $=$ co$-$valence $=$ bersama valensi. Sharing electrons.",explanation:"Ikatan kovalen: pemakaian bersama pasangan elektron antar atom non$-$logam.\nIonik: transfer elektron (logam ke non$-$logam).\nLogam: lautan elektron.\nJawaban: A."},
{question:"pH larutan asam kuat HCl 0.$01 M =$ ...",options: ["2","1","7","14","0.01"],answer:0,hint:"HCl asam kuat, terionisasi sempurna. [$H+$]$=0$.$01=10^{-2}$. pH$=-$log[$H+$]$=2$.",explanation:"[$H+$] $= 0$.$01 M = 10$^$(-2) M$.\npH $= -$log(10^$(-2)) = 2$.\nJawaban: A."},
{question:"Reaksi netralisasi antara asam dan basa menghasilkan ...",options: ["Garam dan air","Hanya garam","Hanya air (dalam teori)","Gas (pada prinsipnya)","Logam (menurut standar)"],answer:0,hint:"Asam $+$ basa $->$ garam $+$ air. HCl $+$ NaOH $->$ NaCl $+ H2O$.",explanation:"Netralisasi: asam $+$ basa $->$ garam $+$ air.\nHCl $+$ NaOH $->$ NaCl $+ H2O$.\nH$+ +$ OH$- -> H2O$.\nJawaban: A."},
]);

appendQuestions('saintek_biologi', [
{question:"Fotosintesis terjadi di organel ...",options: ["Kloroplas","Mitokondria","Ribosom","Nukleus","Retikulum endoplasma"],answer:0,hint:"Kloroplas $=$ pabrik makanan sel tumbuhan. Mengandung klorofil.",explanation:"Fotosintesis: kloroplas (mengandung klorofil).\n6CO$2 + 6H2O +$ cahaya $-> C6H12O6 + 6O2$.\nMitokondria: respirasi seluler (kebalikan).\nJawaban: A."},
{question:"Rantai makanan yang benar: ...",options: ["Rumput $->$ belalang $->$ katak $->$ ular $->$ elang","Elang $->$ ular $->$ rumput (dalam pengertian luas)","Katak $->$ rumput $->$ belalang (dalam definisi teknis)","Ular $->$ elang $->$ rumput (dalam konteks umum)","Belalang $->$ rumput $->$ katak (berdasarkan referensi umum)"],answer:0,hint:"Produsen $->$ konsumen $I ->$ konsumen II $->$ konsumen III $->$ top predator.",explanation:"Rumput (produsen$) ->$ belalang (herbivora$/K1) ->$ katak $(K2) ->$ ular $(K3) ->$ elang (top predator).\nEnergi mengalir satu arah dari produsen ke konsumen.\nJawaban: A."},
{question:"Gen dominan dinyatakan dengan huruf ...",options: ["Kapital/besar (contoh: A)","Kecil (contoh: a) (pada dasarnya)","Angka (secara normatif)","Simbol khusus (secara klasik)","Tidak ada notasi (secara umum)"],answer:0,hint:"Dominan $=$ huruf besar (A). Resesif $=$ huruf kecil (a).",explanation:"Konvensi genetika Mendel:\nDominan: huruf besar (A, B, C).\nResesif: huruf kecil (a, b, c).\nAA $=$ homozigot dominan. aa $=$ homozigot resesif. Aa $=$ heterozigot.\nJawaban: A."},
]);

appendQuestions('soshum_ekonomi', [
{question:"Inflasi diukur menggunakan indeks ...",options: ["Indeks Harga Konsumen (IHK/CPI)","Indeks Saham (berdasarkan acuan formal)","Indeks Pembangunan Manusia","Indeks UV (pada konteks konvensional)","Indeks Demokratisasi (secara klasik)"],answer:0,hint:"CPI $=$ Consumer Price Index $=$ mengukur perubahan harga sekeranjang barang konsumsi.",explanation:"Inflasi diukur oleh IHK (CPI): mengukur perubahan rata$-$rata harga sekeranjang barang dan jasa konsumsi dari waktu ke waktu. Inflasi $=$ kenaikan IHK.\nJawaban: A."},
{question:"Biaya peluang (opportunity cost) adalah ...",options: ["Nilai dari alternatif terbaik yang dikorbankan ketika membuat pilihan","Harga barang (dari sudut pandang klasik; sesuai paradigma tradisional)","Biaya produksi (dalam literatur standar; menurut prinsip dasar)","Biaya transportasi (menurut pandangan mainstream; secara normatif)","Gaji karyawan (dalam pengertian luas; dari perspektif akademis)"],answer:0,hint:"Opportunity cost $=$ apa yang kamu 'korbankan' saat memilih. Trade$-$off.",explanation:"Biaya peluang $=$ nilai dari pilihan terbaik berikutnya yang tidak diambil. Contoh: kuliah 4 tahun $->$ biaya peluang $=$ gaji yang bisa didapat jika bekerja 4 tahun itu.\nJawaban: A."},
{question:"Bank sentral Indonesia adalah ...",options: ["Bank Indonesia (BI)","BRI (menurut definisi standar)","BCA (menurut pengertian baku)","Bank Dunia (dalam praktik)","OJK (menurut prinsip dasar)"],answer:0,hint:"BI $=$ bank sentral $=$ mengatur kebijakan moneter, menjaga stabilitas Rupiah.",explanation:"Bank Indonesia (BI): bank sentral RI. Tugas: menetapkan dan melaksanakan kebijakan moneter, mengatur & menjaga kelancaran sistem pembayaran, stabilitas sistem keuangan.\nJawaban: A."},
]);

appendQuestions('soshum_sosiologi', [
{question:"Mobilitas sosial vertikal naik (social climbing) contohnya ...",options: ["Anak petani menjadi dokter (naik strata sosial)","Pindah dari Jakarta ke Bandung (sesuai teori klasik)","Ganti pekerjaan dengan gaji sama (berdasarkan premis dasar)","Tetap di posisi yang sama selama karir","Turun jabatan (berdasarkan acuan formal)"],answer:0,hint:"Vertikal naik $=$ naik kelas/strata sosial. Horizontal $=$ gerak setara.",explanation:"Mobilitas vertikal naik: perpindahan ke strata sosial lebih tinggi.\nContoh: anak buruh menjadi profesional/pengusaha sukses.\nContoh turun: eksekutif di$-$PHK jadi pengangguran.\nJawaban: A."},
{question:"Lembaga sosial (social institution) yang mengatur hubungan keluarga disebut ...",options: ["Lembaga keluarga (family institution)","Lembaga politik (secara konseptual)","Lembaga ekonomi (berdasarkan asumsi dasar)","Lembaga pendidikan (dalam kerangka teori)","Lembaga agama (dari sudut pandang klasik)"],answer:0,hint:"Setiap jenis hubungan sosial diatur oleh lembaga berbeda. Keluarga $=$ family institution.",explanation:"Lembaga keluarga: mengatur hubungan pernikahan, keturunan, hak waris, pengasuhan, sosialisasi primer.\n5 lembaga sosial utama: keluarga, pendidikan, agama, ekonomi, politik.\nJawaban: A."},
]);

appendQuestions('soshum_sejarah', [
{question:"Proklamasi kemerdekaan Indonesia dibacakan pada ...",options: ["17 Agustus 1945, pukul 10.00 WIB, di Jalan Pegangsaan Timur 56, Jakarta","1 Juni 1945 (dalam pemahaman konvensional; menurut kerangka berpikir umum)","22 Juni 1945 (menurut konsensus ilmiah; sesuai teori klasik)","18 Agustus 1945 (dalam arti sempit; berdasarkan premis dasar)","2 September 1945 (menurut definisi standar; secara terminologis)"],answer:0,hint:"Tujuh$-$belas$-$Agustus$-$empat$-$lima! Di rumah Soekarno, Pegangsaan Timur 56.",explanation:"17 Agustus 1945, pukul 10.00 WIB\nTempat: Jalan Pegangsaan Timur 56, Jakarta\nPembaca: Ir. Soekarno, didampingi Drs. Moh. Hatta\nPengetik naskah: Sayuti Melik\nJawaban: A."},
{question:"Organisasi pergerakan nasional Indonesia yang pertama $(1908) =$ ...",options: ["Budi Utomo","Sarekat Islam","Indische Partij","PNI","Muhammadiyah"],answer:0,hint:"20 Mei $1908 =$ Hari Kebangkitan Nasional. Budi Utomo didirikan.",explanation:"Budi Utomo (20 Mei 1908): organisasi pergerakan nasional pertama. Didirikan oleh Dr. Sutomo dan mahasiswa STOVIA. Diperingati sebagai Hari Kebangkitan Nasional (20 Mei).\nJawaban: A."},
{question:"Sumpah Pemuda dideklarasikan pada ...",options: ["28 Oktober 1928","17 Agustus 1945","20 Mei 1908","1 Juni 1945","10 November 1945"],answer:0,hint:"Satu nusa, satu bangsa, satu bahasa: Indonesia!",explanation:"Sumpah Pemuda (28 Oktober 1928):\n1. Satu tanah air: Indonesia\n2. Satu bangsa: Bangsa Indonesia\n3. Satu bahasa: Bahasa Indonesia\nDiperingati sebagai Hari Sumpah Pemuda.\nJawaban: A."},
]);

appendQuestions('soshum_geografi', [
{question:"Sumber daya alam yang dapat diperbarui (renewable) contohnya ...",options: ["Energi matahari, angin, air, biomassa","Minyak bumi, batu bara, gas alam","Emas, berlian (dalam batasan konvensional)","Uranium (secara fundamental)","Besi, tembaga (dalam pemahaman konvensional)"],answer:0,hint:"Renewable $=$ bisa diperbarui/regenerasi. Matahari, angin, air $=$ tak terbatas.",explanation:"Renewable: matahari, angin, air (hidro), panas bumi (geothermal), biomassa.\nNon$-$renewable: fossil fuels (minyak, gas, batu bara), mineral.\nJawaban: A."},
{question:"Sabuk gunung api (ring of fire) Pasifik melingkari ...",options: ["Samudra Pasifik (dari Selandia Baru ke Asia, ke Amerika)","Samudra Atlantik (menurut pandangan mainstream)","Samudra Hindia (dalam pengertian luas; dari perspektif akademis)","Kutub Utara (dalam definisi teknis; sesuai klasifikasi umum)","Kutub Selatan (dalam konteks umum; berdasarkan teori dasar)"],answer:0,hint:"Ring of Fire $=$ cincin api Pasifik. 75% gunung api dunia ada di sini.",explanation:"Ring of Fire: zona berbentuk tapal kuda di tepi Samudra Pasifik. 452 gunung api aktif (75% total dunia). Membentang dari Selandia Baru $-$ Indonesia $-$ Jepang $-$ Alaska $-$ Amerika.\nJawaban: A."},
{question:"Hujan orografis terjadi karena ...",options: ["Udara lembab dipaksa naik oleh penghalang pegunungan","Pemanasan konvektif (sesuai paradigma tradisional)","Pertemuan dua massa udara (menurut prinsip dasar)","Evaporasi di laut (secara normatif; dalam batasan konvensional)","Angin muson (dari perspektif akademis; secara fundamental)"],answer:0,hint:"Orografis $=$ terkait pegunungan. Udara naik $->$ dingin $->$ kondensasi $->$ hujan.",explanation:"Hujan orografis: udara lembab bertemu pegunungan $->$ dipaksa naik $->$ mendingin adiabatik $->$ kondensasi $->$ hujan di sisi windward. Sisi leeward kering (rain shadow).\nJawaban: A."},
]);

appendQuestions('saintek_matipa', [
{question:"Determinan matriks 3x3 [[1,2,3],[4,5,6],[7,8,9]] $=$ ...",options: ["0","1","$-1$","45","162"],answer:0,hint:"Baris $3 =$ baris $1 +$ baris $2 (7=1+2x3$ bukan, tapi $R3=R1+R2$... cek: $1+4=5$ bukan 7). Hmm. Sarrus: $1(45-48)-2(36-42)+3(32-35) = -3+12-9=0$.",explanation:"Sarrus: $1(5x9-6x8)-2(4x9-6x7)+3(4x8-5x7)$.\n$= 1(45-48)-2(36-42)+3(32-35)$.\n$= -3+12-9 = 0$.\nDet $= 0 ($matriks singular, baris linearly dependent).\nJawaban: A."},
{question:"Persamaan diferensial dy/dx $=$ ky memiliki solusi umum $y =$ ...",options: ["Ce^(kx)","kx$+C$","x^$k+C$","sin(kx$)+C$","1/kx$+C$"],answer:0,hint:"dy$/y = k$ dx. Integral: ln|y| $=$ kx$+C1$. $y =$ Ce^(kx).",explanation:"dy/dx $=$ ky $->$ dy$/y = k$ dx.\nIntegral: ln|y| $=$ kx$+C1$.\ny $= e$^(kx$+C1) =$ Ce^(kx$) (C=e$^C1).\nPertumbuhan/peluruhan eksponensial.\nJawaban: A."},
{question:"Matriks Jacobian dari transformasi polar $(x=r$ cos t, $y=r$ sin t) memiliki determinan $=$ ...",options: ["r","1","r^2","0","2r"],answer:0,hint:"$J =$ [[cos t, $-r$ sin t],[sin t, r cos t]]. det $= r$ cos^$2 t + r$ sin^$2 t = r$.",explanation:"dx/dr$=$cos t, dx/dt$=-r$ sin t.\ndy/dr$=$sin t, dy/dt$=r$ cos t.\ndet$(J) =$ cos t(r cos $t)-(-r$ sin t)(sin $t) = r$ cos^$2 t+r$ sin^$2 t = r$.\nJawaban: A."},
]);
