// BATCH 15 — Matematika Dasar ABSOLUTE LAST + All Subjects CAPSTONE

// === MATDAS: 50 FINAL ===
appendQuestions('tkd_matdas', [
{question:"Jika $f(x) = x^3 - 3x$, titik belok (inflection) f terjadi di $x =$ ...",options: ["0","1","$-1$","3","2"],answer:0,hint:"f''$(x)=6x=0 => x=0$. f'' berubah tanda di $x=0$.",explanation:"f'$(x)=3x^2-3$. f''$(x)=6x$.\nf''$(x)=0 => x=0$. f'' berubah tanda: inflection point.\nJawaban: A."},
{question:"Jika $z = 3+4i$, konjugat $z* =$ ...",options: ["$3-4i$","$3+4i$","$-3-4i$","$-3+4i$","$4+3i$"],answer:0,hint:"Konjugat: ganti tanda bagian imajiner. $a+$bi $-> a-$bi.",explanation:"$z* = 3-4i$.\nKonjugat: bagian real tetap, bagian imajiner dibalik tanda.\nJawaban: A."},
{question:"Nilai $3/7 x 14/9 =$ ...",options: ["$\\frac{2}{3}$","$\\frac{42}{63}$","$\\frac{14}{21}$","$\\frac{6}{7}$","$\\frac{7}{9}$"],answer:0,hint:"$(3x14)/(7x9) = 42/63 = 2/3$.",explanation:"$42/63 = 2/3 ($bagi 21).\nAtau: $(3/7)(14/9) = (3$.14)/(7.$9) = (1$.2)/(1.$3) = 2/3$.\nJawaban: A."},
{question:"Rumus variasi (P) n objek diambil $r =$ ...",options: ["n!$/(n-r)$!","n!/r! (pada prinsipnya)","C(n,r) (menurut standar)","n^r (secara literal)","r! (secara teknis)"],answer:0,hint:"P(n,$r) = n$!$/(n-r)$! Urutan penting.",explanation:"P(n,$r) = n$!$/(n-r)$!.\nBerbeda dari C(n,r): urutan penting di permutasi.\nJawaban: A."},
{question:"Jika tabungan Rp1.000.000 dengan bunga 12% per tahun (bunga sederhana), setelah 6 bulan bunga $=$ ...",options: ["Rp60.000","Rp120.000","Rp12.000","Rp6.000","Rp100.000"],answer:0,hint:"$I =$ PRT $= 1$jt x 0.12 x 0.$5 = 60$.000.",explanation:"$I = 1$.000.000 x 0.$12 x (6/12) = 60$.000.\nJawaban: A."},
{question:"Hitunglah log_10(0.$01) =$ ...",options: ["$-2$","2","0.01","100","$-0$.01"],answer:0,hint:"0.$01 = 10$^$(-2)$. log(10^$(-2)) = -2$.",explanation:"log(0.$01) =$ log(10^$(-2)) = -2$.\nJawaban: A."},
{question:"Jika matriks [[a,b],[c,d]] adalah matriks rotasi 90 derajat, maka $=$ ...",options: ["[[0,$-1$],[1,0]]","[[1,0],[0,1]]","[[0,1],[$-1$,0]]","[[$-1$,0],[0,$-1$]]","[[1,1],[1,1]]"],answer:0,hint:"Rotasi 90: [[cos90,$-$sin90],[sin90,cos90]] $=$ [[0,$-1$],[1,0]].",explanation:"$R(90) =$ [[cos90,$-$sin90],[sin90,cos90]] $=$ [[0,$-1$],[1,0]].\nJawaban: A."},
{question:"Jarak antara titik (1,2,3) dan (4,6,3) di $R^3 =$ ...",options: ["5","7","25","6","10"],answer:0,hint:"$d = \\sqrt{9+16+0} = \\sqrt{25} = 5$.",explanation:"$d = \\sqrt{(4-1}^2+(6-2)^2+(3-3)^2) = \\sqrt{9+16+0} = 5$.\nJawaban: A."},
{question:"Akar kuadrat dari $196 =$ ...",options: ["14","13","15","12","16"],answer:0,hint:"$14 x 14 = 196$.",explanation:"$\\sqrt{196} = 14$.\n$14^2 = 196$.\nJawaban: A."},
{question:"Berapa banyak permutasi huruf kata 'MAMA'?",options: ["6","24","4","12","3"],answer:0,hint:"4 huruf: M(2x), A(2x). 4!/(2!2!$) = 24/4 = 6$.",explanation:"4!/(2!.2!$) = 24/4 = 6$.\nSusunan: MMAA, MAMA, MAAM, AMMA, AMAM, AAMM.\nJawaban: A."},
{question:"Jika $7x-5 > 2x+10$, maka $x >$ ...",options: ["3","5","2","10","$-1$"],answer:0,hint:"$5x > 15 => x > 3$.",explanation:"$7x-5>2x+10 => 5x>15 => x>3$.\nJawaban: A."},
{question:"Berapa 3^4?",options: ["81","64","27","12","243"],answer:0,hint:"$3x3x3x3 = 81$.",explanation:"$3^4 = 3x3x3x3 = 81$.\nJawaban: A."},
{question:"Luas daerah antara $y=x^2$ dan $y=4 ($dari $x=-2$ ke $x=2) =$ ...",options: ["$\\frac{32}{3}$","$\\frac{16}{3}$","8","4","16"],answer:0,hint:"Integral_{$-2$}^{2} $(4-x^2)$ dx $=$ [$4x-x^3/3$]_{$-2$}^{2} $= 2(8-8/3) = 2(16/3) = 32/3$.",explanation:"Integral $(4-x^2)$ dx dari $-2$ ke 2.\n$=$ [$4x-x^3/3$]_{$-2$}^{2} $= (8-8/3)-(-8+8/3) = 16-16/3 = 32/3$.\nJawaban: A."},
{question:"Jika koefisien determinasi $R^2 = 0$.81, artinya ...",options: ["81% variasi Y dijelaskan oleh X","81% data benar (dalam arti sempit)","$R = 81 ($menurut definisi standar)","Tidak ada hubungan (menurut pengertian baku)","$Y = 0$.81X (sesuai paradigma tradisional)"],answer:0,hint:"R^2: proporsi variansi Y yang bisa dijelaskan model.",explanation:"$R^2 = 0$.81: 81% variasi pada Y dapat dijelaskan oleh variabel X.\nSisanya 19% tidak dijelaskan (faktor lain/error).\nR $= \\sqrt{0.81} = 0$.9.\nJawaban: A."},
{question:"Tentukan x: $5(x+2) - 3(x-1) = 17$. $x =$ ...",options: ["2","3","4","1","5"],answer:0,hint:"$5x+10-3x+3=17 => 2x+13=17 => 2x=4 => x=2$.",explanation:"$5x+10-3x+3 = 17$.\n$2x+13 = 17$.\n$2x = 4$. $x = 2$.\nJawaban: A."},
{question:"Berapa banyak cara memilih ketua dan wakil dari 8 orang?",options: ["56","28","64","16","8"],answer:0,hint:"Urutan penting: P(8,$2) = 8x7 = 56$.",explanation:"P(8,$2) = 8$!/6! $= 8x7 = 56$.\nUrutan penting (ketua bukan wakil ketua).\nJawaban: A."},
{question:"Hitunglah: $2^8 =$ ...",options: ["256","128","64","512","1024"],answer:0,hint:"$2^8 = 256$. 2,4,8,16,32,64,128,256.",explanation:"$2^8 = 256$.\nJawaban: A."},
{question:"Jaji beli 2 buku @Rp45.000 dan 3 pensil @Rp5.000. Total $=$ ...",options: ["Rp105.000","Rp90.000","Rp100.000","Rp15.000","Rp150.000"],answer:0,hint:"2x45.$000 + 3x5$.$000 = 90$.$000+15$.$000 = 105$.000.",explanation:"90.$000+15$.$000 = 105$.000.\nJawaban: A."},
{question:"Jika untung 20% dari modal Rp500.000, harga jual $=$ ...",options: ["Rp600.000","Rp520.000","Rp100.000","Rp400.000","Rp700.000"],answer:0,hint:"Untung $= 20$% x 500.$000 = 100$.000. Jual $= 600$.000.",explanation:"Untung $= 100$.000. Jual $= 500$.$000+100$.$000 = 600$.000.\nJawaban: A."},
{question:"Nilai sin(pi$) =$ ...",options: ["0","1","$-1$","pi","0.5"],answer:0,hint:"sin(pi$) =$ sin$(180) = 0$.",explanation:"sin(pi$) =$ sin(180 derajat$) = 0$.\nJawaban: A."},
{question:"Turunan ke$-2$ dari $f(x)=x^4+2x^3 =$ ...",options: ["$12x^2+12x$","$4x^3+6x^2$","$x^5/5+x^4/2$","$4x+6$","0"],answer:0,hint:"f'$=4x^3+6x^2$. f''$=12x^2+12x$.",explanation:"f'$(x)=4x^3+6x^2$. f''$(x)=12x^2+12x$.\nJawaban: A."},
{question:"Jika f:$R->R$, $f(x)=x^2$, apakah f surjektif (onto)?",options: ["Tidak (range $f =$ [0,inf) bukan seluruh R, bilangan negatif tanpa preimage)","Ya (menurut pengertian baku; berdasarkan acuan formal; dalam kerangka teori)","Tidak terdefinisi (sesuai paradigma tradisional; secara konvensional; secara klasik)","Tergantung x (menurut prinsip dasar; pada konteks konvensional; secara konseptual)","Selalu surjektif (secara normatif; dalam batasan konvensional; berdasarkan teori dasar)"],answer:0,hint:"$f(x)=x^2 >= 0$ selalu. $-1$ tidak memiliki preimage. Maka f tidak onto ke R.",explanation:"$f(x)=x^2$: range $=$ [0,inf). Codomain $= R$.\nRange bukan seluruh codomain (bilangan negatif tidak terjangkau).\nMaka TIDAK surjektif.\nJawaban: A."},
{question:"Jika jari$-$jari roda 35 cm, keliling roda (pi$=22/7) =$ ...",options: ["220 cm","110 cm","70 cm","154 cm","44 cm"],answer:0,hint:"$K = 2$ pi $r = 2(22/7)(35) = 220$ cm.",explanation:"$K = 2 x 22/7 x 35 = 2 x 110 = 220$ cm.\nJawaban: A."},
{question:"1 ton $=$ ... kg",options: ["1000","100","10","10000","500"],answer:0,hint:"1 ton $= 1000$ kg.",explanation:"1 ton $= 1000$ kg.\nJawaban: A."},
{question:"Jika log $5 = 0$.699, log $50 =$ ...",options: ["1.699","0.699","2.699","5.699","0.05"],answer:0,hint:"log $50 =$ log$(5x10) =$ log$5+$log$10 = 0$.$699+1 = 1$.699.",explanation:"log $50 =$ log$(5)+$log$(10) = 0$.$699+1 = 1$.699.\nJawaban: A."},
]);

// === ALL-SUBJECTS FINAL CAPSTONE ===
appendQuestions('tps_verbal', [
{question:"HETEROGEN : BERAGAM :: HOMOGEN : ...",options: ["Seragam/sejenis","Beragam (dalam teori)","Acak (pada prinsipnya)","Tidak teratur","Campuran (secara literal)"],answer:0,hint:"Hetero $=$ berbeda. Homo $=$ sama. Homogen $=$ sejenis/seragam.",explanation:"Heterogen: terdiri dari unsur yang berbeda$-$beda. Homogen: terdiri dari unsur yang sama/sejenis. Contoh: susu $=$ campuran homogen. Salad $=$ campuran heterogen.\nJawaban: A."},
{question:"Silogisme: 'Semua mawar adalah bunga. Beberapa mawar merah.' Kesimpulan valid: ...",options: ["Beberapa bunga merah","Semua bunga merah","Semua bunga mawar","Tidak ada bunga merah","Merah bukan bunga"],answer:0,hint:"Beberapa mawar merah. Semua mawar bunga. Maka beberapa bunga $(=$ mawar) merah.",explanation:"Beberapa mawar merah $+$ semua mawar bunga $=$ beberapa bunga merah (yang kebetulan mawar).\nDari particular affirmative $+$ universal affirmative.\nJawaban: A."},
{question:"Kata 'AMBIGUITAS' berarti ...",options: ["Ketidakjelasan makna, bisa ditafsirkan lebih dari satu cara","Kejelasan (dalam batasan konvensional; dalam konteks umum)","Ketepatan (secara fundamental; berdasarkan referensi umum)","Konsistensi (dalam pemahaman konvensional; menurut kerangka berpikir umum)","Transparansi (menurut konsensus ilmiah; sesuai teori klasik)"],answer:0,hint:"Ambi $=$ dua/ganda. Ambiguitas $=$ bermakna ganda $=$ tidak jelas.",explanation:"Ambiguitas: keadaan bermakna ganda, bisa diinterpretasikan lebih dari satu cara. Dari Latin 'ambiguus' $=$ berkeliaran ke dua arah.\nJawaban: A."},
]);

appendQuestions('tps_numerik', [
{question:"Jika harga saham naik 20% lalu turun 20%, apakah kembali ke harga semula?",options: ["Tidak, menjadi 96% dari harga semula (rugi 4%)","Ya, kembali semula (dalam pengertian luas)","Menjadi 100% (dalam definisi teknis)","Naik 40% (dalam konteks umum; berdasarkan teori dasar)","Turun 40% (berdasarkan referensi umum)"],answer:0,hint:"100 x 1.$2 = 120$. 120 x 0.$8 = 96$. Bukan 100! Rugi 4%.",explanation:"$100 -> 120 (+20$%$) -> 96 (-20$% dari 120).\n96% dari awal. RUGI 4%.\nNaik x% lalu turun x% SELALU rugi $(x/100)^2 x 100$%.\nJawaban: A."},
{question:"Rata$-$rata kecepatan perjalanan: pergi 60 km/jam, pulang 40 km/jam (jarak sama). Rata$-$rata $=$ ...",options: ["48 km/jam (rata$-$rata harmonik)","50 km/jam (menurut prinsip dasar)","100 km/jam (secara normatif)","40 km/jam (dari perspektif akademis)","60 km/jam (sesuai klasifikasi umum)"],answer:0,hint:"Rata2 kecepatan jarak sama $=$ harmonik: $2/(1/60+1/40) = 2/(5/120) = 48$.",explanation:"HM $= 2/(1/60+1/40) = 2/((2+3)/120) = 2/(5/120) = 240/5 = 48$.\nBUKAN rata$-$rata aritmatika (50)!\nJawaban: A."},
{question:"Sebuah teko berisi 2 liter air. Digunakan 350 ml, lalu ditambah 1.5 liter. Sisa $=$ ...",options: ["3.15 liter","3.5 liter","2 liter","3 liter","1.15 liter"],answer:0,hint:"$2000-350+1500 = 3150$ ml $= 3$.15 L.",explanation:"$2000-350+1500 = 3150$ ml $= 3$.15 liter.\nJawaban: A."},
]);

appendQuestions('tps_logika', [
{question:"Jika A maka B. Jika B maka C. Jika A maka ...",options: ["C (transitivitas implikasi)","Tidak bisa disimpulkan","A (dalam literatur standar)","Bukan C (menurut pandangan mainstream)","D (dalam pengertian luas)"],answer:0,hint:"$A->B$, $B->C$. Maka $A->C$. Transitivitas (hypothetical syllogism).",explanation:"Hypothetical syllogism: $A->B$, $B->C$, maka $A->C$.\nRantai implikasi: transitivitas.\nJawaban: A."},
{question:"Pernyataan kontradiksi selalu bernilai ...",options: ["Salah (untuk semua kemungkinan)","Benar (menurut definisi standar)","Tergantung (menurut pengertian baku)","Tidak diketahui (sesuai paradigma tradisional)","Benar dan salah (menurut prinsip dasar)"],answer:0,hint:"Kontradiksi: F selalu. Tautologi: T selalu. Kontingensi: kadang T kadang F.",explanation:"Kontradiksi: selalu FALSE (contoh: p AND NOT p).\nTautologi: selalu TRUE (contoh: p OR NOT p).\nKontingensi: terkadang TRUE, terkadang FALSE.\nJawaban: A."},
]);

appendQuestions('tkd_indo', [
{question:"Majas metafora adalah ...",options: ["Perbandingan langsung tanpa kata 'seperti' atau 'bagaikan'","Perbandingan dengan kata 'seperti' (sesuai teori klasik)","Pengulangan kata (berdasarkan premis dasar; dari sudut pandang klasik)","Pertentangan (secara terminologis; dalam literatur standar)","Melebih$-$lebihkan (berdasarkan acuan formal; menurut pandangan mainstream)"],answer:0,hint:"Metafora $=$ langsung. Simile $=$ pakai 'seperti/bagaikan'.",explanation:"Metafora: perbandingan langsung tanpa kata pembanding. Contoh: 'Raja siang' (matahari).\nSimile: perbandingan dengan 'seperti/bagaikan'. Contoh: 'Cantik seperti bulan.'\nJawaban: A."},
{question:"Konjungsi 'meskipun' termasuk konjungsi ...",options: ["Konsesif (menyatakan pertentangan/pengecualian)","Kausal (secara konseptual; dalam arti sempit)","Temporal (berdasarkan asumsi dasar; menurut definisi standar)","Aditif (dalam kerangka teori; menurut pengertian baku)","Konjungtif (dari sudut pandang klasik)"],answer:0,hint:"Meskipun $=$ walaupun $=$ kendati $=$ konsesif (mengakui satu hal tetapi menyatakan hal lain tetap berlaku).",explanation:"Konsesif: meskipun, walaupun, kendatipun, biarpun.\nMenyatakan pertentangan: 'Meskipun hujan, dia tetap pergi.' (Pertentangan antara hujan dan tetap pergi.)\nJawaban: A."},
]);

appendQuestions('tkd_eng', [
{question:"'I wish I ____ taller.' Choose the correct verb form:",options: ["were (subjunctive for unreal present wish)","am (dalam pemahaman konvensional)","is (menurut konsensus ilmiah; sesuai teori klasik)","was (dalam arti sempit; berdasarkan premis dasar)","will be (menurut definisi standar)"],answer:0,hint:"'I wish' $+$ past subjunctive (were) for unreal present wishes.",explanation:"'I wish' $+$ past subjunctive: express unreal present situations. Use 'were' for all persons (formal).\n'I wish I were taller' (but I'm not). 'I wish he were here' (but he's not).\nAnswer: A."},
{question:"An 'oxymoron' is:",options: ["A figure of speech combining contradictory terms (e.g., 'jumbo shrimp', 'deafening silence')","A type of metaphor (dalam konteks umum; berdasarkan teori dasar; sesuai klasifikasi umum; dalam pemahaman konvensional)","A long speech (berdasarkan referensi umum; secara konseptual; dari perspektif akademis; secara fundamental)","A mathematical term (menurut kerangka berpikir umum; berdasarkan asumsi dasar; secara konvensional)","A type of poem (sesuai teori klasik; dalam kerangka teori; menurut prinsip dasar; pada konteks konvensional)"],answer:0,hint:"Oxy $=$ sharp, moron $=$ dull. Oxymoron itself is an oxymoron!",explanation:"Oxymoron: combining contradictory/opposite terms for effect. Examples: 'bittersweet', 'living dead', 'deafening silence', 'clearly confused'. The word 'oxymoron' itself is an oxymoron (oxy$=$sharp $+$ moros$=$dull).\nAnswer: A."},
]);

appendQuestions('saintek_fisika', [
{question:"Suhu 0 Kelvin disebut nol mutlak karena ...",options: ["Merupakan suhu terendah yang secara teoritis mungkin (partikel berhenti bergerak)","Suhu biasa (dari perspektif akademis; secara fundamental; secara konvensional; dalam pengertian luas)","Suhu ruangan (sesuai klasifikasi umum; dalam pemahaman konvensional; dari sudut pandang klasik)","Suhu air mendidih (berdasarkan teori dasar; menurut konsensus ilmiah; dalam kerangka teori)","Suhu matahari (secara konseptual; dalam arti sempit; berdasarkan premis dasar; dari sudut pandang klasik)"],answer:0,hint:"$0K = -273$.15C. Gerakan molekuler minimum. Tidak bisa lebih rendah.",explanation:"$0 K = -273$.15 C: nol mutlak (absolute zero).\nPartikel memiliki energi kinetik minimum (gerakan kuantum nol titik).\nTidak mungkin dicapai (Hukum termodinamika III).\nJawaban: A."},
{question:"Hukum Newton III: aksi $=$ reaksi berarti ...",options: ["Setiap gaya memiliki gaya lawannya yang sama besar dan berlawanan arah","Gaya selalu ke bawah (pada konteks konvensional; dalam definisi teknis)","Tidak ada reaksi (dalam batasan konvensional; dalam konteks umum)","Gaya hanya satu arah (secara fundamental; berdasarkan referensi umum)","Benda selalu diam (dalam pemahaman konvensional; menurut kerangka berpikir umum)"],answer:0,hint:"F_AB $= -F$_BA. Pasangan aksi$-$reaksi pada benda BERBEDA.",explanation:"Hukum III Newton: $F12 = -F21$.\nAksi dan reaksi sama besar, berlawanan arah, bekerja pada benda BERBEDA.\nContoh: Anda dorong dinding, dinding dorong balik Anda.\nJawaban: A."},
]);

appendQuestions('saintek_kimia', [
{question:"Rumus kimia garam dapur (natrium klorida$) =$ ...",options: ["NaCl","NaOH","HCl","KCl","NaCO3"],answer:0,hint:"Na (natrium$) +$ Cl (klorin$) =$ NaCl.",explanation:"Garam dapur $=$ NaCl (natrium klorida).\nIkatan ionik: Na$+$ dan Cl$-$.\nStruktur kristal kubik.\nJawaban: A."},
{question:"Gas mulia (noble gas) bersifat inert karena ...",options: ["Konfigurasi elektron valensi penuh (oktet stabil) sehingga tidak reaktif","Sangat ringan (sesuai paradigma tradisional; secara konvensional; menurut standar)","Berwarna (menurut prinsip dasar; pada konteks konvensional; sesuai paradigma tradisional)","Berbau (secara normatif; dalam batasan konvensional; menurut pengertian baku)","Beracun (dari perspektif akademis; secara fundamental; menurut definisi standar)"],answer:0,hint:"Gas mulia: kulit terluar penuh (He:2, Ne,Ar,Kr,Xe,Rn:8). Sangat stabil.",explanation:"Gas mulia (Gol 18): He, Ne, Ar, Kr, Xe, Rn.\nElektron valensi penuh (oktet/duplet): sangat stabil, tidak perlu membentuk ikatan.\nInert $=$ tidak/sangat sulit bereaksi.\nJawaban: A."},
]);

appendQuestions('saintek_biologi', [
{question:"Mitosis menghasilkan ... sel anak ...",options: ["2 sel anak diploid (identik dengan sel induk)","4 sel anak haploid (secara terminologis)","1 sel anak (berdasarkan acuan formal)","8 sel anak (secara konvensional; dalam pengertian luas)","2 sel anak haploid (pada konteks konvensional)"],answer:0,hint:"Mitosis $=$ pembelahan biasa. $2n -> 2n$. Untuk pertumbuhan dan perbaikan.",explanation:"Mitosis: 1 sel $2n -> 2$ sel 2n (diploid, identik genetis).\nMeiosis: 1 sel $2n -> 4$ sel n (haploid, variasi genetis).\nJawaban: A."},
{question:"Organ yang memproduksi insulin $=$ ...",options: ["Pankreas (sel beta pulau Langerhans)","Hati (dalam kerangka teori)","Ginjal (dari sudut pandang klasik)","Jantung (dalam literatur standar)","Paru$-$paru (menurut pandangan mainstream)"],answer:0,hint:"Insulin: hormon untuk menurunkan kadar gula darah. Diproduksi pankreas.",explanation:"Insulin diproduksi oleh sel beta pulau Langerhans di pankreas.\nFungsi: menurunkan kadar glukosa darah dengan memfasilitasi penyerapan glukosa ke sel.\nDiabetes tipe 1: pankreas tidak memproduksi insulin.\nJawaban: A."},
]);

appendQuestions('soshum_ekonomi', [
{question:"GDP (Gross Domestic Product) mengukur ...",options: ["Total nilai barang dan jasa akhir yang diproduksi dalam suatu negara dalam periode tertentu","Jumlah penduduk (dalam arti sempit; berdasarkan premis dasar; dari perspektif akademis; secara fundamental)","Luas wilayah (menurut definisi standar; secara terminologis; secara normatif; dalam batasan konvensional)","Jumlah uang beredar (menurut pengertian baku; berdasarkan acuan formal; berdasarkan acuan formal)","Hutang negara (sesuai paradigma tradisional; secara konvensional; sesuai paradigma tradisional; secara konvensional)"],answer:0,hint:"GDP $=$ total output ekonomi suatu negara. Indikator utama.",explanation:"GDP: total nilai pasar dari semua barang dan jasa akhir yang diproduksi dalam batas geografis suatu negara dalam satu periode.\nIndikator utama ukuran ekonomi.\nJawaban: A."},
{question:"Elastisitas permintaan $= 1$ disebut ...",options: ["Unit elastic (perubahan harga dan kuantitas proporsional)","Elastis (menurut kerangka berpikir umum; berdasarkan asumsi dasar)","Inelastis (sesuai teori klasik; dalam kerangka teori)","Sempurna elastis (berdasarkan premis dasar)","Sempurna inelastis (secara terminologis; dalam literatur standar)"],answer:0,hint:"$E=1$: unitary. $E>1$: elastic. $E<1$: inelastic.",explanation:"Ed $= 1$: unit elastic (% perubahan Qd $=$ % perubahan harga).\nEd $> 1$: elastis. Ed $< 1$: inelastis.\nEd $= 0$: perfectly inelastic. Ed $=$ inf: perfectly elastic.\nJawaban: A."},
]);

appendQuestions('soshum_sosiologi', [
{question:"Teori konflik Karl Marx berfokus pada ...",options: ["Pertentangan antar kelas sosial (borjuis vs proletar) dalam memperebutkan sumber daya","Harmoni sosial (berdasarkan teori dasar; menurut konsensus ilmiah; menurut konsensus ilmiah)","Fungsionalisme (secara konseptual; dalam arti sempit; secara konseptual; dalam arti sempit)","Interaksi simbolik (berdasarkan asumsi dasar; menurut definisi standar; secara fundamental)","Solidaritas organik (dalam kerangka teori; menurut pengertian baku; dalam batasan konvensional)"],answer:0,hint:"Marx: kelas pemilik modal (borjuis) vs kelas pekerja (proletar$) =$ konflik.",explanation:"Marx: masyarakat terbagi menjadi kelas$-$kelas berdasarkan kepemilikan alat produksi. Borjuis (pemilik modal) vs proletar (pekerja). Konflik kelas $=$ motor penggerak perubahan sosial.\nJawaban: A."},
]);

appendQuestions('soshum_sejarah', [
{question:"Perjanjian Renville (1948) merugikan Indonesia karena ...",options: ["Indonesia harus mengakui wilayah RI hanya Jawa Tengah, Yogyakarta, dan Sumatera (sebagian)","Belanda menyerah (secara fundamental; berdasarkan referensi umum)","Indonesia menjadi merdeka penuh (dalam pemahaman konvensional; menurut kerangka berpikir umum)","Tidak ada dampak (menurut konsensus ilmiah; sesuai teori klasik)","Belanda angkat kaki (dalam arti sempit; berdasarkan premis dasar)"],answer:0,hint:"Renville (di kapal USS Renville): garis demarkasi merugikan RI, wilayah RI mengecil drastis.",explanation:"Perjanjian Renville (17 Jan 1948): garis demarkasi Van Mook merugikan RI. Wilayah RI mengecil drastis. Pasukan TNI harus mundur ke belakang garis. Memicu Agresi Militer Belanda II.\nJawaban: A."},
]);

appendQuestions('soshum_geografi', [
{question:"Tenaga endogen dalam geologi meliputi ...",options: ["Vulkanisme, tektonisme, dan seisme (berasal dari dalam bumi)","Erosi, sedimentasi (dalam definisi teknis; sesuai klasifikasi umum)","Pelapukan (dalam konteks umum; berdasarkan teori dasar)","Angin dan hujan (berdasarkan referensi umum; secara konseptual)","Gelombang laut (menurut kerangka berpikir umum)"],answer:0,hint:"Endogen $=$ dalam. Tenaga dari dalam bumi: vulkanisme, tektonisme, gempa.",explanation:"Tenaga endogen (dalam bumi): vulkanisme (aktivitas gunung api), tektonisme (pergerakan lempeng), seisme (gempa).\nTenaga eksogen (luar bumi): pelapukan, erosi, sedimentasi.\nJawaban: A."},
]);

appendQuestions('saintek_matipa', [
{question:"Integral garis (line integral) dari vektor F sepanjang kurva C ditulis ...",options: ["Integral_C F.dr","Integral_0^1 F dt","F x C","d/dx F","F/C"],answer:0,hint:"Line integral: integral F(r).dr sepanjang kurva C.",explanation:"Line integral: Integral_C F.dr.\nMenghitung kerja (work) yang dilakukan gaya F sepanjang lintasan C.\nJawaban: A."},
{question:"Teorema Green menghubungkan ...",options: ["Integral garis pada kurva tertutup dengan integral ganda pada daerah yang dibatasi kurva tersebut","Dua titik (secara konvensional; dalam pengertian luas; berdasarkan referensi umum; secara konseptual)","Tiga dimensi (pada konteks konvensional; dalam definisi teknis; dalam konteks umum; berdasarkan teori dasar)","Logaritma (dalam batasan konvensional; dalam konteks umum; dalam definisi teknis; sesuai klasifikasi umum)","Turunan (secara fundamental; berdasarkan referensi umum; dalam pengertian luas; dari perspektif akademis)"],answer:0,hint:"Green: integral keliling $=$ integral luas. 2D version of Stokes.",explanation:"Teorema Green: integral garis pada kurva tertutup $C =$ integral ganda pada daerah D yang dibatasi C.\nMenghubungkan sirkulasi pada batas dengan fluks melalui interior.\nJawaban: A."},
]);
