// BATCH 20 — FINAL ALL-SUBJECTS MEGA BOOST (additional ~100 across all non-math)

appendQuestions('tps_verbal', [
{question:"APATIS : KETIDAKPEDULIAN :: EMPATI : ...",options: ["Kemampuan merasakan perasaan orang lain","Ketidakpedulian","Kemarahan","Kesedihan","Kebahagiaan"],answer:0,hint:"Apatis = tidak peduli. Empati = bisa merasakan apa yang orang lain rasakan.",explanation:"Apatis: tidak peduli, acuh tak acuh.\nEmpati: kemampuan memahami dan merasakan perasaan orang lain.\nAntonimikal secara sifat.\nJawaban: A."},
{question:"OBJEKTIF : TIDAK MEMIHAK :: SUBJEKTIF : ...",options: ["Dipengaruhi pandangan/perasaan pribadi","Tidak memihak","Netral","Ilmiah","Faktual"],answer:0,hint:"Objektif = berdasarkan fakta. Subjektif = berdasarkan opini pribadi.",explanation:"Objektif: berdasarkan fakta, tanpa bias personal.\nSubjektif: dipengaruhi perasaan, pendapat, pengalaman pribadi.\nJawaban: A."},
{question:"Kesalahan logika 'false dichotomy' terjadi ketika ...",options: ["Hanya memberikan 2 pilihan padahal ada lebih banyak opsi","Memberikan terlalu banyak pilihan","Tidak memberikan pilihan","Pilihan semuanya benar","Pilihan semuanya salah"],answer:0,hint:"False dichotomy = either/or fallacy. 'Kalau bukan X, pasti Y' (padahal bisa Z,W,dll).",explanation:"False dichotomy: menyajikan hanya 2 opsi seolah-olah itu satu-satunya pilihan, padahal ada alternatif lain. 'Kalau bukan teman saya, berarti musuh saya.' (Bisa juga netral/stranger.)\nJawaban: A."},
{question:"PRAGMATIS : PRAKTIS :: IDEALIS : ...",options: ["Mengutamakan cita-cita/nilai ideal","Praktis","Realistis","Materialistis","Pesimistis"],answer:0,hint:"Pragmatis = fokus realitas/hasil. Idealis = fokus ideal/cita-cita.",explanation:"Pragmatis: berorientasi pada hasil nyata dan praktis.\nIdealis: berorientasi pada cita-cita, standar ideal, nilai-nilai luhur.\nJawaban: A."},
{question:"Silogisme: 'Semua reptil berdarah dingin. Ular adalah reptil.' Kesimpulan: ...",options: ["Ular berdarah dingin","Ular berdarah panas","Semua hewan berdarah dingin","Reptil bukan ular","Tidak ada kesimpulan"],answer:0,hint:"Barbara syllogism: All M are P. S is M. Therefore S is P.",explanation:"Major: Semua reptil berdarah dingin.\nMinor: Ular adalah reptil.\nKonklusi: Ular berdarah dingin (valid, sound).\nJawaban: A."},
]);

appendQuestions('tps_numerik', [
{question:"Harga tiket pesawat naik 15% menjadi Rp1.150.000. Harga sebelum naik = ...",options: ["Rp1.000.000","Rp977.500","Rp1.035.000","Rp997.500","Rp1.150.000"],answer:0,hint:"x(1.15) = 1.150.000 => x = 1.000.000.",explanation:"1.15x = 1.150.000.\nx = 1.000.000.\nJawaban: A."},
{question:"Jika bunga bank 6%/tahun dan menabung Rp5.000.000, bunga setelah 8 bulan = ...",options: ["Rp200.000","Rp300.000","Rp400.000","Rp100.000","Rp250.000"],answer:0,hint:"I = 5jt x 0.06 x 8/12 = 200.000.",explanation:"I = PRT = 5.000.000 x 0.06 x 8/12 = 200.000.\nJawaban: A."},
{question:"Sebuah tangga 10m bersandar di dinding. Kaki tangga 6m dari dinding. Tinggi di dinding = ...",options: ["8 m","4 m","16 m","14 m","12 m"],answer:0,hint:"h = $\\sqrt{100-36}$ = $\\sqrt{64}$ = 8.",explanation:"h = $\\sqrt{10^2-6^2}$ = $\\sqrt{64}$ = 8 m.\nJawaban: A."},
]);

appendQuestions('tps_logika', [
{question:"Jika huruf-huruf ABCDE digeser 2 posisi ke kanan (cipher), A menjadi ...",options: ["C","B","D","E","A"],answer:0,hint:"Caesar cipher shift 2: A->C, B->D, C->E.",explanation:"Shift 2: A(1)->C(3), B->D, C->E, D->F, E->G.\nCaesar cipher dengan kunci 2.\nJawaban: A."},
{question:"Jika 3 kucing menangkap 3 tikus dalam 3 menit, berapa kucing untuk 100 tikus dalam 100 menit?",options: ["3 kucing","100 kucing","9 kucing","300 kucing","33 kucing"],answer:0,hint:"1 kucing = 1 tikus/3menit = 33.3 tikus/100menit. 3 kucing = 100 tikus/100 menit.",explanation:"1 kucing menangkap 1 tikus tiap 3 menit.\nDalam 100 menit, 1 kucing: 100/3 = 33.3 tikus.\n3 kucing: 3 x 33.3 = 100 tikus.\nJawaban: 3 kucing!\nJawaban: A."},
]);

appendQuestions('tkd_indo', [
{question:"Tanda koma (,) digunakan untuk memisahkan ...",options: ["Keterangan tambahan, anak kalimat, dan unsur-unsur dalam perincian","Dua kalimat utuh","Suku kata","Paragraf","Bab"],answer:0,hint:"Koma: rincian, anak kalimat, apositif, keterangan tambahan.",explanation:"Koma digunakan dalam:\n1. Perincian (apel, jeruk, mangga)\n2. Anak kalimat mendahului induk\n3. Keterangan tambahan/apositif\n4. Sebelum konjungsi (tetapi, namun, sedangkan)\nJawaban: A."},
{question:"Bentuk baku dari 'merubah' adalah ...",options: ["Mengubah (me- + ubah, bukan me- + rubah)","Merubah","Berubah","Diubah","Terubah"],answer:0,hint:"Ubah -> mengubah. Rubah = hewan. Mengubah = membuat jadi berbeda.",explanation:"Kata dasar: ubah (bukan rubah).\nme- + ubah = mengubah (benar).\nme- + rubah = merubah (salah, rubah = hewan sejenis serigala).\nJawaban: A."},
{question:"Paragraf deduktif dimulai dengan ...",options: ["Kalimat utama (gagasan umum) di awal, diikuti penjelas","Kalimat penjelas dulu","Tanpa kalimat utama","Kesimpulan saja","Contoh saja"],answer:0,hint:"Deduktif: umum -> khusus. Induktif: khusus -> umum.",explanation:"Deduktif: kalimat utama di awal (umum ke khusus).\nInduktif: kalimat utama di akhir (khusus ke umum).\nCampuran: kalimat utama di awal dan akhir.\nJawaban: A."},
]);

appendQuestions('tkd_eng', [
{question:"'Break a leg!' is an idiom meaning:",options: ["Good luck!","Get injured","Run away","Be careful","Literally break your leg"],answer:0,hint:"Theater idiom: saying 'good luck' is considered bad luck, so they say 'break a leg'.",explanation:"'Break a leg' = good luck (especially in theater/performance). Origin: theatrical superstition that wishing good luck brings bad luck, so the opposite is said.\nAnswer: A."},
{question:"The correct plural of 'phenomenon' is:",options: ["Phenomena","Phenomenons","Phenomenas","Phenomeni","Phenomenon"],answer:0,hint:"Greek origin: -on becomes -a. Criterion/criteria. Phenomenon/phenomena.",explanation:"Phenomenon (singular) -> phenomena (plural). Greek-derived words: criterion/criteria, bacterium/bacteria, datum/data.\nAnswer: A."},
{question:"Which sentence uses the passive voice?",options: ["The cake was eaten by the children.","The children ate the cake.","She runs every morning.","He will finish the project tomorrow.","They are playing soccer."],answer:0,hint:"Passive: subject receives action. 'was eaten' = be + past participle.",explanation:"Passive voice: subject receives the action. Structure: be + past participle (+ by agent).\n'The cake (subject/receiver) was eaten (passive) by the children (agent).'\nAnswer: A."},
]);

appendQuestions('saintek_fisika', [
{question:"Energi kinetik benda bermassa m dan kecepatan v = ...",options: ["1/2 mv^2","mv","mgh","mv^2","1/2 mv"],answer:0,hint:"Ek = 1/2 mv^2. Energi potensial = mgh.",explanation:"Ek = 1/2 mv^2.\nEp = mgh (gravitasi).\nHukum kekekalan energi: Ek + Ep = konstan (tanpa gaya luar).\nJawaban: A."},
{question:"Lensa cembung (konveks) bersifat ...",options: ["Konvergen (mengumpulkan cahaya)","Divergen","Tidak membiaskan","Memantulkan","Menyerap"],answer:0,hint:"Cembung/konveks = mengumpulkan sinar. Cekung/konkaf = menyebarkan.",explanation:"Lensa konveks (cembung): mengumpulkan sinar sejajar ke satu titik fokus (konvergen).\nLensa konkaf (cekung): menyebarkan sinar sejajar (divergen).\nJawaban: A."},
{question:"Gelombang longitudinal: arah getar partikel ...",options: ["Sejajar dengan arah rambat gelombang","Tegak lurus arah rambat","Melingkar","Tidak bergetar","Acak"],answer:0,hint:"Longitudinal: getar sejajar. Transversal: getar tegak lurus.",explanation:"Longitudinal: getar sejajar arah rambat (contoh: gelombang bunyi).\nTransversal: getar tegak lurus arah rambat (contoh: gelombang tali).\nJawaban: A."},
]);

appendQuestions('saintek_kimia', [
{question:"Unsur dengan nomor atom 8 adalah ...",options: ["Oksigen (O)","Nitrogen (N)","Karbon (C)","Fluor (F)","Neon (Ne)"],answer:0,hint:"Z=8: 8 proton = Oksigen. C=6, N=7, O=8, F=9, Ne=10.",explanation:"Z=8: Oksigen (O).\nKonfigurasi elektron: 1s2 2s2 2p4.\nGolongan VIA, Periode 2.\nJawaban: A."},
{question:"Reaksi eksoterm ...",options: ["Melepaskan panas ke lingkungan (delta H negatif)","Menyerap panas","Tidak melibatkan panas","Hanya terjadi di suhu tinggi","Membutuhkan listrik"],answer:0,hint:"Ekso = keluar. Term = panas. Melepas panas. Delta H < 0.",explanation:"Eksoterm: melepaskan panas (dH<0). Contoh: pembakaran, netralisasi.\nEndoterm: menyerap panas (dH>0). Contoh: fotosintesis, penguapan.\nJawaban: A."},
{question:"Senyawa organik yang memiliki gugus fungsi -OH = ...",options: ["Alkohol","Aldehida","Keton","Ester","Eter"],answer:0,hint:"-OH = hidroksil = alkohol. -CHO = aldehida. C=O = keton.",explanation:"Alkohol: R-OH (hidroksil). Contoh: metanol (CH3OH), etanol (C2H5OH).\nAldehida: R-CHO. Keton: R-CO-R'. Ester: R-COO-R'.\nJawaban: A."},
]);

appendQuestions('saintek_biologi', [
{question:"Proses penguraian glukosa tanpa oksigen disebut ...",options: ["Fermentasi (anaerob)","Fotosintesis","Respirasi aerob","Transpirasi","Osmosis"],answer:0,hint:"Tanpa O2 = anaerob = fermentasi. Hasil: alkohol/asam laktat + sedikit ATP.",explanation:"Fermentasi (anaerob): penguraian glukosa tanpa O2.\nHasil: etanol+CO2 (ragi) atau asam laktat (otot).\nATP: hanya 2 (vs 36-38 aerob).\nJawaban: A."},
{question:"Mekanisme pertahanan tubuh non-spesifik (innate) contohnya ...",options: ["Kulit, mukosa, asam lambung, fagositosis (tidak spesifik terhadap patogen tertentu)","Antibodi","Sel T","Vaksinasi","Transplantasi"],answer:0,hint:"Non-spesifik = lini pertama: kulit, mukus, enzim, sel NK. Spesifik = antibodi.",explanation:"Pertahanan non-spesifik (innate):\n- Fisik: kulit, mukosa\n- Kimia: asam lambung, enzim lisosom\n- Seluler: fagosit, sel NK\nTidak spesifik terhadap patogen tertentu.\nJawaban: A."},
]);

appendQuestions('soshum_ekonomi', [
{question:"Kebijakan fiskal adalah kebijakan pemerintah melalui ...",options: ["Pendapatan (pajak) dan pengeluaran pemerintah (APBN)","Suku bunga","Jumlah uang beredar","Giro wajib minimum","Operasi pasar terbuka"],answer:0,hint:"Fiskal = pajak+belanja pemerintah. Moneter = suku bunga+jumlah uang.",explanation:"Fiskal: instrumen pajak dan belanja pemerintah (APBN).\nMoneter: instrumen suku bunga, giro wajib minimum, operasi pasar terbuka (Bank Indonesia).\nJawaban: A."},
{question:"Hukum Engel menyatakan bahwa semakin tinggi pendapatan ...",options: ["Proporsi pengeluaran untuk makanan semakin kecil (% menurun)","Pengeluaran makanan naik proporsinya","Tidak ada perubahan","Pengeluaran hiburan turun","Tabungan menurun"],answer:0,hint:"Engel: orang miskin habiskan % besar untuk makan. Orang kaya % kecil.",explanation:"Hukum Engel: semakin tinggi pendapatan, proporsi (%) pengeluaran untuk makanan semakin kecil. Pendapatan naik -> % makanan turun, % non-makanan (pendidikan, rekreasi) naik.\nJawaban: A."},
]);

appendQuestions('soshum_sosiologi', [
{question:"Kelompok primer (primary group) menurut Charles Cooley dicirikan oleh ...",options: ["Hubungan antarpribadi yang intim, tatap muka, dan kooperatif (contoh: keluarga, sahabat)","Hubungan formal dan kontraktual","Kelompok besar tanpa interaksi","Organisasi birokrasi","Massa anonim"],answer:0,hint:"Primary group: keluarga, sahabat. Secondary: organisasi, perusahaan.",explanation:"Kelompok primer: hubungan dekat, personal, emosional, tatap muka, langgeng. Contoh: keluarga, geng bermain, sahabat.\nKelompok sekunder: formal, impersonal, tujuan tertentu. Contoh: perusahaan, partai.\nJawaban: A."},
{question:"Ethnosentrisme adalah ...",options: ["Menilai budaya lain berdasarkan standar budaya sendiri (menganggap budaya sendiri paling baik)","Menghargai semua budaya","Mempelajari budaya lain","Menerima perbedaan","Relativisme budaya"],answer:0,hint:"Ethno=suku/bangsa. Sentrisme=pusat. Budaya sendiri = pusat/standar.",explanation:"Ethnosentrisme: menganggap budaya sendiri sebagai standar tertinggi dan menilai budaya lain berdasarkan standar itu.\nLawan: relativisme budaya (memahami budaya lain dari perspektifnya sendiri).\nJawaban: A."},
]);

appendQuestions('soshum_sejarah', [
{question:"Serangan Umum 1 Maret 1949 di Yogyakarta dipimpin oleh ...",options: ["Letkol Soeharto","Jenderal Sudirman","Bung Tomo","Soekarno","Sjafruddin"],answer:0,hint:"Serangan 6 jam ke Yogyakarta yang diduduki Belanda. Bukti RI masih eksis.",explanation:"Serangan Umum 1 Maret 1949: serangan 6 jam ke Yogyakarta oleh pasukan TNI di bawah Letkol Soeharto. Tujuan: membuktikan kepada dunia bahwa TNI dan RI masih eksis dan kuat.\nJawaban: A."},
{question:"Konferensi Asia-Afrika (KAA) Bandung diselenggarakan pada ...",options: ["18-24 April 1955","17 Agustus 1945","1 Juni 1945","28 Oktober 1928","10 November 1945"],answer:0,hint:"KAA Bandung 1955: 29 negara Asia-Afrika. Dasasila Bandung.",explanation:"KAA Bandung (18-24 April 1955): 29 negara Asia-Afrika. Menghasilkan Dasasila Bandung (10 prinsip) tentang perdamaian dunia dan kerjasama.\nInisiator: Indonesia, India, Pakistan, Burma, Sri Lanka.\nJawaban: A."},
{question:"Perjanjian Linggarjati (1946) antara Indonesia dan Belanda mengakui ...",options: ["De facto kekuasaan RI atas Jawa, Madura, dan Sumatera","Kemerdekaan penuh Indonesia","Tidak ada kesepakatan","Belanda menguasai semua","Indonesia menguasai seluruh Nusantara"],answer:0,hint:"Linggarjati: Belanda akui RI de facto di Jawa, Madura, Sumatera.",explanation:"Perjanjian Linggarjati (25 Maret 1947):\n1. Belanda mengakui de facto RI atas Jawa, Madura, Sumatera.\n2. Pembentukan RIS (federal) dengan Belanda.\n3. Uni Indonesia-Belanda.\nJawaban: A."},
]);

appendQuestions('soshum_geografi', [
{question:"Garis Wallace membagi ...",options: ["Fauna Asia dan Australia (antara Kalimantan-Sulawesi dan Bali-Lombok)","Flora Asia dan Eropa","Iklim tropis dan subtropis","Samudra Pasifik dan Atlantik","Benua Amerika Utara dan Selatan"],answer:0,hint:"Alfred Russel Wallace: fauna sangat berbeda di kedua sisi garis ini.",explanation:"Garis Wallace: batas biogeografi fauna tipe Asia (barat) dan tipe Australasia (timur).\nBarat: gajah, harimau, orangutan.\nTimur: kuskus, burung cenderawasih.\nJawaban: A."},
{question:"Jenis tanah vulkanik (andosol) subur karena ...",options: ["Kaya mineral dan unsur hara dari abu vulkanik","Banyak air","Berwarna merah","Tidak mengandung mineral","Berbatu"],answer:0,hint:"Abu gunung api mengandung mineral dan nutrisi = tanah vulkanik subur.",explanation:"Tanah vulkanik (andosol): sangat subur karena kaya mineral, unsur hara, dan memiliki kemampuan menahan air yang baik. Berasal dari endapan material vulkanik.\nJawaban: A."},
{question:"El Nino adalah fenomena ...",options: ["Pemanasan abnormal suhu permukaan laut di Pasifik timur (menyebabkan kekeringan di Indonesia)","Pendinginan laut Pasifik","Gempa bawah laut","Tsunami","Badai tropis"],answer:0,hint:"El Nino = 'anak laki-laki' (Natal). Pasifik timur hangat = Indonesia kering.",explanation:"El Nino: pemanasan abnormal permukaan laut Pasifik ekuatorial timur.\nDampak Indonesia: kekeringan, gagal panen, kebakaran hutan.\nLa Nina (sebaliknya): curah hujan berlebihan, banjir.\nJawaban: A."},
]);

appendQuestions('saintek_matipa', [
{question:"Transformasi Laplace dari f(t)=1 = ...",options: ["1/s (untuk s > 0)","s","e^s","0","1"],answer:0,hint:"L{1} = integral_0^inf e^(-st) dt = [-e^(-st)/s]_0^inf = 1/s.",explanation:"L{1} = 1/s.\nL{t^n} = n!/s^(n+1).\nL{e^(at)} = 1/(s-a).\nJawaban: A."},
{question:"Dalam aljabar linear, rank matriks mengukur ...",options: ["Jumlah baris (atau kolom) yang linearly independent","Jumlah elemen","Trace matriks","Determinan","Jumlah nol"],answer:0,hint:"Rank = dimensi ruang kolom (atau baris) = max jumlah kolom LI.",explanation:"Rank(A) = jumlah baris/kolom linearly independent.\n= dimensi column space = dimensi row space.\nrank(A) <= min(m,n) untuk matriks m x n.\nJawaban: A."},
{question:"Jika f(x,y) = x^2y^3, maka d^2f/dxdy = ...",options: ["6xy^2","2xy^3","3x^2y^2","6x^2y","x^2"],answer:0,hint:"df/dx = 2xy^3. d/dy(2xy^3) = 6xy^2.",explanation:"df/dx = 2xy^3.\nd^2f/dxdy = d/dy(2xy^3) = 6xy^2.\n(Clairaut: d^2f/dxdy = d^2f/dydx untuk fungsi kontinu.)\nJawaban: A."},
]);
