// BATCH 2 — Soshum Ekonomi (127 Soal HOTS)
appendQuestions('soshum_ekonomi', [
{question:"Ketika bank sentral menurunkan suku bunga acuan, efek yang diharapkan pada ekonomi adalah …",options:["Investasi dan konsumsi meningkat (stimulus ekonomi)","Investasi menurun","Inflasi turun","Pengangguran naik","Ekspor menurun"],answer:0,hint:"Suku bunga turun → biaya pinjam murah → investasi dan konsumsi naik → AD naik.",explanation:"Suku bunga turun → cost of borrowing turun → perusahaan lebih banyak investasi, konsumen lebih banyak belanja/pinjam → aggregate demand naik → stimulus ekonomi.\nIni adalah kebijakan moneter ekspansif.\nJawaban: A."},
{question:"Dalam kurva Phillips, hubungan antara inflasi dan pengangguran dalam jangka pendek adalah …",options:["Berbanding terbalik (trade-off)","Berbanding lurus","Tidak ada hubungan","Eksponensial","Acak"],answer:0,hint:"Phillips curve: inflasi tinggi ↔ pengangguran rendah (jangka pendek).",explanation:"Kurva Phillips (jangka pendek): trade-off antara inflasi dan pengangguran. Inflasi tinggi → pengangguran rendah (dan sebaliknya). Dalam jangka panjang, hubungan ini bisa melemah (stagflasi).\nJawaban: A."},
{question:"Externality negatif dalam produksi (contoh: polusi pabrik) menyebabkan …",options:["Produksi pasar melebihi tingkat optimal secara sosial (overproduction)","Produksi kurang dari optimal","Harga terlalu tinggi","Tidak ada dampak","Efisiensi sempurna"],answer:0,hint:"Biaya privat < biaya sosial → produsen memproduksi terlalu banyak karena tidak menanggung biaya eksternalitas.",explanation:"Externality negatif: biaya sosial > biaya privat. Produsen tidak menanggung biaya polusi → memproduksi lebih banyak dari optimal sosial (overproduction). Pasar gagal (market failure) → perlu intervensi (pajak Pigouvian).\nJawaban: A."},
{question:"Comparative advantage menurut Ricardo ditentukan oleh …",options:["Biaya peluang relatif (opportunity cost) yang lebih rendah","Biaya absolut produksi","Jumlah tenaga kerja","Kualitas produk","Ukuran negara"],answer:0,hint:"Comparative ≠ absolute. Negara memiliki keunggulan komparatif jika opportunity cost-nya lebih rendah.",explanation:"Keunggulan komparatif: kemampuan memproduksi barang dengan biaya peluang (opportunity cost) yang lebih rendah dibandingkan negara lain, MESKIPUN mungkin tidak memiliki keunggulan absolut.\nJawaban: A."},
{question:"GDP deflator dihitung sebagai …",options:["(GDP Nominal / GDP Riil) × 100","GDP Nominal - GDP Riil","GDP Riil / GDP Nominal","GDP Nominal × GDP Riil","GDP Nominal + Inflasi"],answer:0,hint:"Deflator = rasio nominal terhadap riil, mengukur tingkat harga.",explanation:"GDP Deflator = (Nominal GDP / Real GDP) × 100.\nMenjadi ukuran tingkat harga keseluruhan dalam ekonomi (alternatif CPI).\nJika deflator = 110, harga naik 10% dari baseline.\nJawaban: A."},
{question:"Dalam teori permintaan, barang Giffen memiliki sifat unik yaitu …",options:["Kuantitas yang diminta NAIK ketika harga NAIK (melanggar hukum permintaan)","Kuantitas turun saat harga naik","Permintaan elastis sempurna","Permintaan tidak terpengaruh harga","Barang mewah"],answer:0,hint:"Giffen good: efek pendapatan > efek substitusi → kurva permintaan positif.",explanation:"Barang Giffen (inferior ekstrem): ketika harga naik, efek pendapatan (konsumen jadi lebih miskin → membeli lebih banyak barang inferior) > efek substitusi → kuantitas diminta justru NAIK. Contoh historis: kentang di Irlandia saat kelaparan.\nJawaban: A."},
{question:"Crowding out effect terjadi ketika …",options:["Pengeluaran pemerintah meningkat → suku bunga naik → investasi swasta menurun","Pemerintah mengurangi belanja","Ekspor meningkat","Pengangguran turun","Pajak diturunkan"],answer:0,hint:"Pemerintah meminjam uang → bunga naik → swasta terhambat pinjam.",explanation:"Government spending ↑ → pemerintah meminjam lebih banyak → permintaan loanable funds naik → suku bunga naik → investasi swasta turun ('crowded out'). Efek multiplier fiskal berkurang.\nJawaban: A."},
{question:"Indeks Gini mengukur …",options:["Tingkat ketimpangan distribusi pendapatan (0=sempurna merata, 1=sempurna timpang)","Tingkat inflasi","Pertumbuhan ekonomi","Tingkat pengangguran","Neraca perdagangan"],answer:0,hint:"Gini coefficient: angka antara 0 dan 1 yang mengukur ketidakmerataan.",explanation:"Indeks Gini: 0 = distribusi pendapatan sempurna merata (semua orang pendapatan sama). 1 (atau 100) = ketimpangan sempurna (satu orang memiliki semua pendapatan). Dihitung dari kurva Lorenz.\nJawaban: A."},
{question:"Ketika pemerintah menetapkan harga CEILING (harga maksimum) di BAWAH harga keseimbangan, akibatnya …",options:["Terjadi kekurangan barang (shortage/excess demand)","Terjadi kelebihan barang (surplus)","Harga naik","Permintaan turun","Pasar tidak terpengaruh"],answer:0,hint:"Price ceiling di bawah equilibrium: harga terlalu rendah → Qd > Qs → shortage.",explanation:"Price ceiling < P equilibrium → harga ditekan rendah → produsen kurang berminat menyuplai (Qs turun) + konsumen ingin beli lebih banyak (Qd naik) → excess demand/shortage.\nContoh: kontrol harga sewa.\nJawaban: A."},
{question:"Menurut Keynesian economics, kebijakan yang tepat saat resesi adalah …",options:["Kebijakan fiskal ekspansif (belanja naik/pajak turun) + moneter ekspansif (bunga turun)","Menaikkan pajak dan bunga","Menghentikan semua belanja pemerintah","Mendevaluasi mata uang 100%","Melarang impor sepenuhnya"],answer:0,hint:"Keynes: saat resesi, pemerintah harus MERANGSANG ekonomi melalui stimulus.",explanation:"Keynesian response to recession:\nFiskal ekspansif: G↑ dan/atau T↓ → AD↑.\nMoneter ekspansif: interest rate↓ → I↑, C↑ → AD↑.\nTujuan: meningkatkan aggregate demand untuk mengurangi pengangguran.\nJawaban: A."},
{question:"Elastisitas harga permintaan = -2 berarti …",options:["Kenaikan harga 1% menyebabkan penurunan kuantitas diminta 2% (elastis)","Harga dan kuantitas tidak berhubungan","Permintaan inelastis","Kenaikan harga 2% menyebabkan penurunan 1%","Permintaan unitari"],answer:0,hint:"PED = %ΔQd / %ΔP = -2. |E|>1 = elastis.",explanation:"PED = -2: %ΔQd/%ΔP = -2.\nJika P naik 1%, Qd turun 2% (responsif).\n|E| = 2 > 1 → permintaan elastis.\nElastis sempurna: |E|=∞. Inelastis: |E|<1. Unitari: |E|=1.\nJawaban: A."},
{question:"Perbedaan antara GNP dan GDP adalah …",options:["GNP = output oleh warga negara di mana pun, GDP = output dalam wilayah negara oleh siapa pun","GNP selalu lebih besar","GDP termasuk depresiasi, GNP tidak","Keduanya identik","GNP tidak termasuk jasa"],answer:0,hint:"GDP = domestik (berdasarkan wilayah). GNP = nasional (berdasarkan kewarganegaraan).",explanation:"GDP: total produksi DALAM batas wilayah negara (oleh siapa pun — WNA termasuk).\nGNP: total produksi oleh WARGA NEGARA (di mana pun — termasuk di luar negeri).\nGNP = GDP + pendapatan WNI di LN - pendapatan WNA di dalam negeri.\nJawaban: A."},
{question:"Dalam model circular flow of income, 'injection' (suntikan) ke dalam aliran ekonomi meliputi …",options:["Investasi (I), pengeluaran pemerintah (G), ekspor (X)","Tabungan, pajak, impor","Hanya konsumsi","Hanya upah","Hanya dividen"],answer:0,hint:"Injection = aliran masuk ke circular flow. Leakage = aliran keluar.",explanation:"Injection (masuk): Investasi (I), Pengeluaran Pemerintah (G), Ekspor (X).\nLeakage (keluar): Tabungan (S), Pajak (T), Impor (M).\nKeseimbangan: I+G+X = S+T+M.\nJawaban: A."},
{question:"Moral hazard dalam konteks asuransi terjadi ketika …",options:["Pihak yang diasuransikan mengambil risiko lebih besar karena merasa dilindungi","Perusahaan asuransi bangkrut","Premi terlalu mahal","Klaim ditolak","Tidak ada yang membeli asuransi"],answer:0,hint:"Moral hazard: perilaku berubah SETELAH mendapat perlindungan (risk-taking naik).",explanation:"Moral hazard: setelah diasuransikan, seseorang cenderung lebih ceroboh/berisiko karena merasa kerugian akan ditanggung asuransi. Contoh: pengemudi yang kurang hati-hati setelah punya asuransi kendaraan.\nJawaban: A."},
{question:"Quantity Theory of Money (MV=PY) menyatakan bahwa jika M naik dan V serta Y konstan, maka …",options:["P (tingkat harga) naik proporsional — inflasi","P turun","Y naik","V naik","Tidak ada perubahan"],answer:0,hint:"MV=PY. M↑, V dan Y konstan → P harus naik untuk menjaga kesetaraan.",explanation:"MV = PY. Jika V dan Y konstan:\nM↑ → P↑ (harga naik proporsional).\nIni basis teori monetaris: inflasi 'selalu dan di mana pun merupakan fenomena moneter' (Friedman).\nJawaban: A."},
{question:"Dead weight loss (DWL) dalam monopoli timbul karena …",options:["Monopolis memproduksi kurang dari output efisien dan mengenakan harga lebih tinggi","Monopolis untung terlalu banyak","Biaya produksi terlalu rendah","Permintaan terlalu tinggi","Pemerintah terlalu banyak regulasi"],answer:0,hint:"DWL = hilangnya surplus total karena misalokasi sumber daya.",explanation:"Monopolis memaksimalkan profit di MR=MC, menghasilkan Q < Q_kompetitif dan P > P_kompetitif. Area antara kurva demand dan MC dari Q_monopoli ke Q_kompetitif = DWL (transaksi yang saling menguntungkan tapi tidak terjadi).\nJawaban: A."},
]);
