// BATCH 2 — Saintek Biologi (127 Soal HOTS)
appendQuestions('saintek_biologi', [
{question:"Sebuah organisme memiliki genotipe AaBbCc. Jika ketiga gen terletak pada kromosom yang berbeda (independen), jumlah jenis gamet yang mungkin dihasilkan adalah …",options:["8 (2³)","6","3","12","27"],answer:0,hint:"Setiap gen heterozigot menghasilkan 2 jenis alel dalam gamet. Total = 2ⁿ.",explanation:"3 gen heterozigot pada kromosom berbeda → segregasi independen.\nJenis gamet = 2³ = 8: ABC, ABc, AbC, Abc, aBC, aBc, abC, abc.\nJawaban: A."},
{question:"Proses transkripsi menghasilkan mRNA dari cetakan DNA. Enzim utama yang mengkatalisis transkripsi adalah …",options:["RNA Polimerase","DNA Polimerase","Helikase","Ligase","Reverse Transcriptase"],answer:0,hint:"Trans-KRIP-si: menulis RNA dari DNA. Enzim yang membuat RNA = RNA Polimerase.",explanation:"RNA Polimerase: enzim yang mengkatalisis sintesis mRNA dari template DNA (transkripsi).\nDNA Polimerase: replikasi DNA. Helikase: membuka heliks DNA. Ligase: menyambung fragmen.\nJawaban: A."},
{question:"Dalam rantai transpor elektron mitokondria, akseptor elektron terakhir adalah …",options:["O₂ (oksigen molekuler)","NAD⁺","FAD","Sitokrom c","CO₂"],answer:0,hint:"Oksigen menangkap elektron di akhir rantai, membentuk air.",explanation:"O₂ = akseptor elektron terakhir di ETC. O₂ + 4H⁺ + 4e⁻ → 2H₂O.\nInilah mengapa kita membutuhkan oksigen untuk respirasi aerob.\nJawaban: A."},
{question:"Perbedaan utama antara sel prokariotik dan eukariotik adalah …",options:["Prokariotik tidak memiliki membran inti (nukleus), eukariotik memiliki","Prokariotik lebih besar","Eukariotik tidak memiliki ribosom","Prokariotik memiliki mitokondria","Eukariotik tidak memiliki DNA"],answer:0,hint:"Pro = sebelum, karyon = inti. Prokariotik = sebelum adanya inti (tanpa membran inti).",explanation:"Prokariotik (bakteri, archaea): tidak memiliki membran inti — DNA di nukleoid.\nEukariotik (hewan, tumbuhan, fungi): memiliki membran inti yang membungkus DNA.\nKedua tipe memiliki ribosom dan DNA.\nJawaban: A."},
{question:"Dalam siklus Calvin, enzim RuBisCO mengkatalisis …",options:["Fiksasi CO₂ ke RuBP (ribulosa-1,5-bisfosfat)","Pemecahan air","Fosforilasi oksidatif","Transkripsi RNA","Glikolisis"],answer:0,hint:"RuBisCO = Ribulose-1,5-BisPhosphate Carboxylase/Oxygenase.",explanation:"RuBisCO: enzim paling melimpah di bumi, mengkatalisis fiksasi CO₂ ke RuBP (5C) → 2 molekul 3-PGA (3C). Langkah pertama siklus Calvin (reaksi gelap fotosintesis).\nJawaban: A."},
{question:"Persilangan dihibrid AaBb × AaBb menghasilkan rasio fenotipe …",options:["9:3:3:1 (jika dominansi penuh)","3:1","1:2:1","1:1:1:1","15:1"],answer:0,hint:"Hukum Mendel II: segregasi independen menghasilkan 9:3:3:1 jika dominansi penuh.",explanation:"AaBb × AaBb = 16 kemungkinan.\nDominan-Dominan: 9. Dominan-Resesif: 3. Resesif-Dominan: 3. Resesif-Resesif: 1.\nRasio fenotipe: 9:3:3:1.\nJawaban: A."},
{question:"Hemoglobin dalam sel darah merah berfungsi untuk …",options:["Mengangkut O₂ dari paru-paru ke jaringan dan CO₂ sebaliknya","Melawan infeksi","Pembekuan darah","Menyimpan lemak","Menghancurkan bakteri"],answer:0,hint:"Hemo- = darah, -globin = protein. Protein merah pembawa oksigen.",explanation:"Hemoglobin (Hb): protein tetramerik dalam eritrosit yang mengikat O₂ (oksihemoglobin) di paru-paru dan melepaskannya di jaringan. Juga membawa ~23% CO₂ kembali ke paru-paru (karbaminohemoglobin).\nJawaban: A."},
{question:"Antibodi (imunoglobulin) diproduksi oleh …",options:["Sel plasma (sel B yang teraktivasi)","Sel T sitotoksik","Neutrofil","Sel dendritik","Trombosit"],answer:0,hint:"Sel B matang menjadi sel plasma yang mensekresi antibodi.",explanation:"Sel B → teraktivasi oleh antigen → diferensiasi menjadi sel plasma → mensekresi antibodi (IgG, IgM, IgA, IgE, IgD) secara masif.\nSel T sitotoksik membunuh sel terinfeksi secara langsung (cell-mediated immunity), bukan memproduksi antibodi.\nJawaban: A."},
{question:"Crossing over terjadi pada … fase meiosis.",options:["Profase I (khususnya pakiten/diakinesis)","Metafase I","Anafase I","Profase II","Telofase II"],answer:0,hint:"Crossing over = pertukaran segmen kromosom homolog selama profase I.",explanation:"Crossing over terjadi antara kromatid non-sister dari kromosom homolog selama profase I (tahap pakiten). Menghasilkan rekombinasi genetik yang meningkatkan variasi.\nJawaban: A."},
{question:"PCR (Polymerase Chain Reaction) digunakan untuk …",options:["Mengamplifikasi (memperbanyak) segmen DNA spesifik secara in vitro","Menghancurkan DNA","Menyuntikkan DNA ke sel","Mengubah RNA menjadi protein","Mewarnai kromosom"],answer:0,hint:"PCR = mesin fotokopi untuk DNA, memperbanyak secara eksponensial.",explanation:"PCR mengamplifikasi (memperbanyak) segmen DNA tertentu secara eksponensial in vitro. Menggunakan primer, dNTP, dan Taq polymerase (tahan panas). Siklus: denaturasi → annealing → elongasi.\nJawaban: A."},
{question:"Dalam ekologi, organisme yang memecah bahan organik mati dan mengembalikan nutrisi ke tanah disebut …",options:["Dekomposer/pengurai","Produsen","Konsumen primer","Predator puncak","Parasit"],answer:0,hint:"De-compose = menguraikan. Bakteri dan jamur pengurai.",explanation:"Dekomposer (jamur, bakteri saprofitik): memecah organisme mati dan sisa organik menjadi komponen anorganik yang dikembalikan ke tanah (daur biogeokimia). Peran krusial dalam recycling nutrisi.\nJawaban: A."},
{question:"Organ vestigial pada manusia (contoh: usus buntu/apendiks) menurut teori evolusi menunjukkan …",options:["Bukti evolusi: organ yang dulunya fungsional pada nenek moyang tapi kini tereduksi","Organ tersebut tidak pernah ada","Organ tersebut baru berkembang","Evolusi tidak terjadi","Organ vestigial selalu berbahaya"],answer:0,hint:"Vestigial = sisa dari struktur yang dulu fungsional pada ancestor.",explanation:"Organ vestigial: struktur yang tereduksi dan kehilangan fungsi utama pada organisme modern, tetapi fungsional pada nenek moyang. Bukti evolusi: menunjukkan perubahan fungsi/degenerasi seiring evolusi.\nJawaban: A."},
{question:"Golongan darah ABO ditentukan oleh alel I^A, I^B, dan i. Ini merupakan contoh …",options:["Alel ganda (multiple alleles) dan kodominansi","Epistasis","Poliploid","Monohibrida sederhana","Sex-linked inheritance"],answer:0,hint:"3 alel untuk 1 gen, I^A dan I^B kodominan terhadap satu sama lain, keduanya dominan terhadap i.",explanation:"Golongan darah ABO: 3 alel (multiple alleles) untuk 1 lokus.\nI^A dan I^B kodominan (keduanya diekspresikan di AB).\nI^A dan I^B dominan terhadap i.\nGenotipe: I^AI^A/I^Ai = A, I^BI^B/I^Bi = B, I^AI^B = AB, ii = O.\nJawaban: A."},
{question:"Fase light-dependent reaction fotosintesis yang menghasilkan O₂ disebut …",options:["Fotolisis air (water splitting)","Siklus Calvin","Glikolisis","Fosforilasi oksidatif","Fermentasi"],answer:0,hint:"O₂ berasal dari pemecahan H₂O oleh cahaya di Fotosistem II.",explanation:"Fotolisis air di Fotosistem II: 2H₂O → 4H⁺ + 4e⁻ + O₂.\nO₂ yang kita hirup berasal dari pemecahan air oleh energi cahaya di tilakoid, BUKAN dari CO₂.\nJawaban: A."},
{question:"Mutasi frameshift terjadi ketika … dan mengubah seluruh urutan asam amino setelah titik mutasi.",options:["Insersi atau delesi nukleotida yang bukan kelipatan 3","Substitusi satu basa","Inversi segmen besar","Translokasi kromosom","Duplikasi gen"],answer:0,hint:"Frame = kerangka baca (triplet kodon). Shift = bergeser.",explanation:"Frameshift mutation: insersi/delesi basa yang jumlahnya BUKAN kelipatan 3, menyebabkan pergeseran kerangka baca (reading frame). Semua kodon setelah titik mutasi berubah → urutan asam amino berubah total.\nSubstitusi 1 basa = missense/nonsense (bukan frameshift).\nJawaban: A."},
{question:"Dalam biogeokimia, proses fiksasi nitrogen adalah …",options:["Konversi N₂ atmosfer menjadi NH₃/NH₄⁺ yang dapat digunakan organisme","Konversi NH₃ menjadi N₂","Konversi NO₃⁻ menjadi NH₃","Konversi NH₃ menjadi NO₃⁻","Penyerapan N₂ langsung oleh tumbuhan"],answer:0,hint:"Fiksasi = 'menangkap' N₂ yang inert menjadi bentuk yang bisa dipakai oleh makhluk hidup.",explanation:"Fiksasi nitrogen: N₂ (inert) → NH₃/NH₄⁺ (usable). Dilakukan oleh:\n1. Bakteri pengikat N (Rhizobium, Azotobacter) — enzim nitrogenase\n2. Kilat/petir\n3. Proses industri (Haber-Bosch)\nTumbuhan TIDAK bisa menggunakan N₂ langsung.\nJawaban: A."},
]);
