// BATCH 2 — Saintek Kimia (127 Soal HOTS)
appendQuestions('saintek_kimia', [
{question:"Larutan CH₃COOH 0.1M (Ka=1.8×10⁻⁵) memiliki pH mendekati …",options:["2.87","1","7","5","4.74"],answer:0,hint:"Asam lemah: [H⁺]=√(Ka×C)=√(1.8×10⁻⁶).",explanation:"[H⁺] = √(Ka×C) = √(1.8×10⁻⁵×0.1) = √(1.8×10⁻⁶) = 1.34×10⁻³.\npH = -log(1.34×10⁻³) ≈ 2.87.\nA bukan 4.74 (itu pKa).\nJawaban: A."},
{question:"Pada sel volta Zn|Zn²⁺||Cu²⁺|Cu, E°sel = … (E°Zn=-0.76V, E°Cu=+0.34V)",options:["1.10 V","0.42 V","-1.10 V","0.76 V","0.34 V"],answer:0,hint:"E°sel = E°katoda - E°anoda = E°Cu - E°Zn.",explanation:"E°sel = E°katoda - E°anoda = 0.34-(-0.76) = 0.34+0.76 = 1.10 V.\nZn = anoda (oksidasi), Cu = katoda (reduksi).\nJawaban: A."},
{question:"Pergeseran kesetimbangan menurut Le Chatelier: jika tekanan dinaikkan pada reaksi N₂ + 3H₂ ⇌ 2NH₃, kesetimbangan bergeser ke …",options:["Kanan (produk) — sisi dengan lebih sedikit mol gas","Kiri (reaktan)","Tidak berubah","Bergantung suhu","Bergantung katalis"],answer:0,hint:"Tekanan naik → kesetimbangan bergeser ke sisi dengan jumlah mol gas LEBIH SEDIKIT.",explanation:"Reaktan: 1+3=4 mol gas. Produk: 2 mol gas.\nTekanan naik → geser ke sisi mol lebih sedikit (kanan, produk).\nKatalis TIDAK menggeser kesetimbangan.\nJawaban: A."},
{question:"Geometri molekul SF₆ menurut teori VSEPR adalah …",options:["Oktahedral","Tetrahedral","Trigonal bipiramidal","Planar segitiga","Linear"],answer:0,hint:"SF₆: 6 pasangan ikatan, 0 pasangan bebas → AX₆.",explanation:"S memiliki 6 ikatan S-F, 0 lone pair.\nVSEPR: AX₆ → geometri oktahedral (sudut 90°).\nSF₆ sangat stabil (24 elektron valensi).\nJawaban: A."},
{question:"Laju reaksi menjadi DUA KALI lipat setiap kenaikan suhu 10°C. Jika suhu dinaikkan dari 20°C ke 50°C, laju reaksi menjadi …",options:["8 kali lipat (2³)","3 kali lipat","6 kali lipat","4 kali lipat","16 kali lipat"],answer:0,hint:"Kenaikan 30°C = 3 kali lipat kenaikan 10°C. Faktor = 2³.",explanation:"Kenaikan 30°C/10°C = 3 interval.\nLaju = 2³ = 8 kali lipat.\nJawaban: A."},
{question:"Bilangan oksidasi S dalam Na₂S₂O₃ (natrium tiosulfat) adalah …",options:["+2","+4","+6","+7","-2"],answer:0,hint:"Na₂S₂O₃: 2Na(+1) + 2S(x) + 3O(-2) = 0. 2+2x-6=0.",explanation:"2(+1)+2x+3(-2) = 0 → 2+2x-6 = 0 → 2x = 4 → x = +2.\nBilangan oksidasi S di tiosulfat = +2.\nJawaban: A."},
{question:"Polimer yang terbentuk dari polimerisasi adisi etilena (CH₂=CH₂) adalah …",options:["Polietilena (PE)","Polistirena (PS)","PVC","Nylon","Teflon"],answer:0,hint:"Etilena = monomer polietilena. Ikatan rangkap terbuka → polimer.",explanation:"CH₂=CH₂ → (-CH₂-CH₂-)ₙ = polietilena (PE).\nAdisi: ikatan rangkap C=C terbuka dan monomer berantai.\nPS dari stirena, PVC dari vinil klorida, Nylon dari kondensasi.\nJawaban: A."},
{question:"Berdasarkan teori orbital molekul, orde ikatan O₂ adalah …",options:["2","1","3","1.5","2.5"],answer:0,hint:"O₂ memiliki 16 elektron. Konfigurasi MO: (σ2s)²(σ*2s)²(σ2p)²(π2p)⁴(π*2p)².",explanation:"O₂: 12 elektron valensi.\nBonding electrons: 8 (σ2s² + σ2p² + π2p⁴).\nAntibonding: 4 (σ*2s² + π*2p²).\nBond order = (8-4)/2 = 2.\nO₂ memiliki 2 elektron tak berpasangan (paramagnetik).\nJawaban: A."},
{question:"Reaksi esterifikasi antara asam karboksilat dan alkohol menghasilkan …",options:["Ester + Air","Eter + CO₂","Aldehida + H₂","Keton + Air","Amida + HCl"],answer:0,hint:"R-COOH + R'-OH → R-COOR' + H₂O (kondensasi).",explanation:"Esterifikasi: asam karboksilat + alkohol → ester + air.\nCH₃COOH + C₂H₅OH → CH₃COOC₂H₅ + H₂O (katalis H₂SO₄).\nReaksi reversibel (kesetimbangan).\nJawaban: A."},
{question:"Prinsip Aufbau menyatakan bahwa pengisian orbital elektron dimulai dari …",options:["Orbital dengan energi terendah ke tertinggi","Orbital dengan energi tertinggi ke terendah","Orbital p sebelum s","Orbital secara acak","Semua orbital sekaligus"],answer:0,hint:"Aufbau (Jerman) = membangun dari bawah ke atas. Energi rendah → tinggi.",explanation:"Prinsip Aufbau: elektron mengisi orbital dari energi terendah ke tertinggi.\nUrutan: 1s→2s→2p→3s→3p→4s→3d→4p→5s→4d→...\n(Urutan ditentukan oleh aturan n+l.)\nJawaban: A."},
{question:"pH larutan buffer yang mengandung 0.1M CH₃COOH dan 0.1M CH₃COONa (pKa=4.74) adalah …",options:["4.74","7","1","14","2.87"],answer:0,hint:"Henderson-Hasselbalch: pH = pKa + log([A⁻]/[HA]).",explanation:"pH = pKa + log([A⁻]/[HA]) = 4.74 + log(0.1/0.1) = 4.74 + 0 = 4.74.\nBuffer equimolar: pH = pKa.\nJawaban: A."},
{question:"Energi ionisasi MENURUN dari atas ke bawah dalam satu golongan karena …",options:["Jari-jari atom bertambah → elektron valensi lebih jauh dari inti → lebih mudah dilepas","Jumlah proton berkurang","Jumlah neutron bertambah","Afinias elektron meningkat","Massa atom berkurang"],answer:0,hint:"Turun satu golongan: lebih banyak kulit → jari-jari besar → gaya tarik inti lebih lemah.",explanation:"Turun satu golongan: jumlah kulit elektron bertambah → jari-jari atom besar → elektron valensi lebih jauh dari inti → gaya tarik inti lebih lemah → energi ionisasi menurun (lebih mudah melepas elektron).\nJawaban: A."},
{question:"Kelarutan (Ksp) AgCl = 1.8×10⁻¹⁰. Konsentrasi Ag⁺ dalam larutan jenuh AgCl = …",options:["≈ 1.34×10⁻⁵ M","1.8×10⁻¹⁰ M","≈ 1.34×10⁻³ M","0.1 M","≈ 1.8×10⁻⁵ M"],answer:0,hint:"AgCl → Ag⁺ + Cl⁻. Ksp = [Ag⁺][Cl⁻] = x². x = √Ksp.",explanation:"AgCl(s) ⇌ Ag⁺(aq) + Cl⁻(aq).\nKsp = x² = 1.8×10⁻¹⁰.\nx = √(1.8×10⁻¹⁰) = 1.34×10⁻⁵ M.\n[Ag⁺] = [Cl⁻] = 1.34×10⁻⁵ M.\nJawaban: A."},
{question:"Reaksi redoks: MnO₄⁻ + Fe²⁺ → Mn²⁺ + Fe³⁺ (dalam asam). Koefisien setara MnO₄⁻ dan Fe²⁺ adalah …",options:["1 MnO₄⁻ : 5 Fe²⁺","1:1","2:5","5:1","1:3"],answer:0,hint:"Mn: +7→+2 (gain 5e). Fe: +2→+3 (lose 1e). Untuk balance: 1 Mn × 5e = 5 Fe × 1e.",explanation:"Mn⁷⁺+5e→Mn²⁺ (reduksi, 5 elektron).\nFe²⁺→Fe³⁺+e (oksidasi, 1 elektron).\nKesetaraan elektron: 1×5 = 5×1.\n1 MnO₄⁻ + 5 Fe²⁺ + 8H⁺ → Mn²⁺ + 5Fe³⁺ + 4H₂O.\nJawaban: A."},
{question:"Tipe ikatan dalam NaCl (ionik) vs HCl (kovalen polar) vs Cl₂ (kovalen nonpolar) ditentukan oleh …",options:["Perbedaan keelektronegatifan antar atom","Jumlah elektron total","Massa atom","Warna senyawa","Nomor atom"],answer:0,hint:"ΔEN besar (>1.7): ionik. ΔEN sedang: kovalen polar. ΔEN=0: kovelen nonpolar.",explanation:"Na-Cl: ΔEN = 3.0-0.9 = 2.1 (ionik).\nH-Cl: ΔEN = 3.0-2.1 = 0.9 (kovalen polar).\nCl-Cl: ΔEN = 0 (kovalen nonpolar).\nPerbedaan keelektronegatifan menentukan tipe ikatan.\nJawaban: A."},
]);
