// BATCH 2 — Saintek Kimia (127 Soal HOTS)
appendQuestions('saintek_kimia', [
{question:"Larutan CH_3COOH 0.1M (Ka$=1$.$8\\times10$⁻^5) memiliki pH mendekati $\\ldots$",options: ["2.87","1","7","5","4.74"],answer:0,hint:"Asam lemah: [H⁺]$=\\sqrt{Ka\\timesC}=\\sqrt{1.8\\times10⁻^6}$.",explanation:"[H⁺] $= \\sqrt{Ka\\timesC} = \\sqrt{1.8\\times10⁻^5\\times0.1} = \\sqrt{1.8\\times10⁻^6} = 1$.$34\\times10$⁻^3.\npH $= -$log(1.$34\\times10$⁻^$3) \\approx 2$.87.\nA bukan 4.74 (itu pKa).\nJawaban: A."},
{question:"Pada sel volta Zn|Zn^2⁺||Cu^2⁺|Cu, E^$\\circ$selselselselselselselsel $= \\ldots (E$^$\\circ$ZnZnZnZnZnZnZnZn$=-0$.76V, E^$\\circ$CuCuCuCuCuCuCuCu$=+0$.34V)",options: ["1.10 V","0.42 V","$-1$.10 V","0.76 V","0.34 V"],answer:0,hint:"E^$\\circ$selselselselselselselsel $= E$^$\\circ$katodakatodakatodakatodakatodakatodakatodakatoda $- E$^$\\circ$anodaanodaanodaanodaanodaanodaanodaanoda $= E$^$\\circ$CuCuCuCuCuCuCuCu $- E$^$\\circ$ZnZnZnZnZnZnZnZn.",explanation:"E^$\\circ$selselselselselselselsel $= E$^$\\circ$katodakatodakatodakatodakatodakatodakatodakatoda $- E$^$\\circ$anodaanodaanodaanodaanodaanodaanodaanoda $= 0$.$34-(-0$.$76) = 0$.$34+0$.$76 = 1$.10 V.\nZn $=$ anoda (oksidasi), Cu $=$ katoda (reduksi).\nJawaban: A."},
{question:"Pergeseran kesetimbangan menurut Le Chatelier: jika tekanan dinaikkan pada reaksi N_$2 + 3H$_2 ⇌ 2NH_3, kesetimbangan bergeser ke $\\ldots$",options: ["Kanan (produk) — sisi dengan lebih sedikit mol gas","Kiri (reaktan) (secara konseptual; dalam arti sempit)","Tidak berubah (berdasarkan asumsi dasar)","Bergantung suhu (dalam kerangka teori)","Bergantung katalis (dari sudut pandang klasik)"],answer:0,hint:"Tekanan naik $\\to$ kesetimbangan bergeser ke sisi dengan jumlah mol gas LEBIH SEDIKIT.",explanation:"Reaktan: $1+3=4$ mol gas. Produk: 2 mol gas.\nTekanan naik $\\to$ geser ke sisi mol lebih sedikit (kanan, produk).\nKatalis TIDAK menggeser kesetimbangan.\nJawaban: A."},
{question:"Geometri molekul SF_6 menurut teori VSEPR adalah $\\ldots$",options: ["Oktahedral","Tetrahedral","Trigonal bipiramidal","Planar segitiga","Linear"],answer:0,hint:"SF_6: 6 pasangan ikatan, 0 pasangan bebas $\\to$ AX_6.",explanation:"S memiliki 6 ikatan $S-F$, 0 lone pair.\nVSEPR: AX_$6 \\to$ geometri oktahedral (sudut 90^$\\circ)$.\nSF_6 sangat stabil (24 elektron valensi).\nJawaban: A."},
{question:"Laju reaksi menjadi DUA KALI lipat setiap kenaikan suhu 10^$\\circ$CCCCCCCC. Jika suhu dinaikkan dari 20^$\\circ$CCCCCCCC ke 50^$\\circ$CCCCCCCC, laju reaksi menjadi $\\ldots$",options: ["8 kali lipat (2^3)","3 kali lipat (secara umum)","6 kali lipat (dalam teori)","4 kali lipat (pada prinsipnya)","16 kali lipat (menurut standar)"],answer:0,hint:"Kenaikan 30^$\\circ$CCCCCCCC $= 3$ kali lipat kenaikan 10^$\\circ$CCCCCCCC. Faktor $= 2^3$.",explanation:"Kenaikan 30^$\\circ$CCCCCCCC/10^$\\circ$CCCCCCCC $= 3$ interval.\nLaju $= 2^3 = 8$ kali lipat.\nJawaban: A."},
{question:"Bilangan oksidasi S dalam Na_2S_2O_3 (natrium tiosulfat) adalah $\\ldots$",options: ["$+2$","$+4$","$+6$","$+7$","$-2$"],answer:0,hint:"Na_2S_2O_3: 2Na$(+1) + 2S(x) + 3O(-2) = 0$. $2+2x-6=0$.",explanation:"$2(+1)+2x+3(-2) = 0 \\to 2+2x-6 = 0 \\to 2x = 4 \\to x = +2$.\nBilangan oksidasi S di tiosulfat $= +2$.\nJawaban: A."},
{question:"Polimer yang terbentuk dari polimerisasi adisi etilena (CH_$2=$CH_2) adalah $\\ldots$",options: ["Polietilena (PE)","Polistirena (PS)","PVC","Nylon","Teflon"],answer:0,hint:"Etilena $=$ monomer polietilena. Ikatan rangkap terbuka $\\to$ polimer.",explanation:"CH_$2=$CH_$2 \\to (-$CH_$2-$CH_$2-)$ₙ $=$ polietilena (PE).\nAdisi: ikatan rangkap $C=C$ terbuka dan monomer berantai.\nPS dari stirena, PVC dari vinil klorida, Nylon dari kondensasi.\nJawaban: A."},
{question:"Berdasarkan teori orbital molekul, orde ikatan O_2 adalah $\\ldots$",options: ["2","1","3","1.5","2.5"],answer:0,hint:"O_2 memiliki 16 elektron. Konfigurasi MO: $(\\sigma2s)^2(\\sigma*2s)^2(\\sigma2p)^2(\\pi2p)^4(\\pi*2p)^2$.",explanation:"O_2: 12 elektron valensi.\nBonding electrons: $8 (\\sigma2s^2 + \\sigma2p^2 + \\pi2p^4)$.\nAntibonding: $4 (\\sigma*2s^2 + \\pi*2p^2)$.\nBond order $= (8-4)/2 = 2$.\nO_2 memiliki 2 elektron tak berpasangan (paramagnetik).\nJawaban: A."},
{question:"Reaksi esterifikasi antara asam karboksilat dan alkohol menghasilkan $\\ldots$",options: ["Ester $+$ Air","Eter $+$ CO_2","Aldehida $+ H$_2","Keton $+$ Air","Amida $+$ HCl"],answer:0,hint:"$R-$COOH $+ R$'$-$OH $\\to R-$COOR' $+ H$_2O (kondensasi).",explanation:"Esterifikasi: asam karboksilat $+$ alkohol $\\to$ ester $+$ air.\nCH_3COOH $+ C$_2H_5OH $\\to$ CH_3COOC_2H_$5 + H$_2O (katalis H_2SO_4).\nReaksi reversibel (kesetimbangan).\nJawaban: A."},
{question:"Prinsip Aufbau menyatakan bahwa pengisian orbital elektron dimulai dari $\\ldots$",options: ["Orbital dengan energi terendah ke tertinggi","Orbital dengan energi tertinggi ke terendah","Orbital p sebelum s","Orbital secara acak","Semua orbital sekaligus"],answer:0,hint:"Aufbau (Jerman$) =$ membangun dari bawah ke atas. Energi rendah $\\to$ tinggi.",explanation:"Prinsip Aufbau: elektron mengisi orbital dari energi terendah ke tertinggi.\nUrutan: $1s\\to2s\\to2p\\to3s\\to3p\\to4s\\to3d\\to4p\\to5s\\to4d\\to$...\n(Urutan ditentukan oleh aturan $n+l$.)\nJawaban: A."},
{question:"pH larutan buffer yang mengandung 0.1M CH_3COOH dan 0.1M CH_3COONa (pKa$=4$.74) adalah $\\ldots$",options: ["4.74","7","1","14","2.87"],answer:0,hint:"Henderson$-$Hasselbalch: pH $=$ pKa $+$ log([A⁻]/[HA]).",explanation:"pH $=$ pKa $+$ log([A⁻]/[HA]$) = 4$.$74 +$ log(0.1/0.$1) = 4$.$74 + 0 = 4$.74.\nBuffer equimolar: pH $=$ pKa.\nJawaban: A."},
{question:"Energi ionisasi MENURUN dari atas ke bawah dalam satu golongan karena $\\ldots$",options: ["Jari$-$jari atom bertambah $\\to$ elektron valensi lebih jauh dari inti $\\to$ lebih mudah dilepas","Jumlah proton berkurang (dalam arti sempit; berdasarkan premis dasar; berdasarkan teori dasar)","Jumlah neutron bertambah (menurut definisi standar; secara terminologis; sesuai klasifikasi umum)","Afinias elektron meningkat (menurut pengertian baku; berdasarkan acuan formal; dari perspektif akademis)","Massa atom berkurang (sesuai paradigma tradisional; secara konvensional; secara normatif)"],answer:0,hint:"Turun satu golongan: lebih banyak kulit $\\to$ jari$-$jari besar $\\to$ gaya tarik inti lebih lemah.",explanation:"Turun satu golongan: jumlah kulit elektron bertambah $\\to$ jari$-$jari atom besar $\\to$ elektron valensi lebih jauh dari inti $\\to$ gaya tarik inti lebih lemah $\\to$ energi ionisasi menurun (lebih mudah melepas elektron).\nJawaban: A."},
{question:"Kelarutan (Ksp) AgCl $= 1$.$8\\times10$⁻¹⁰. Konsentrasi Ag⁺ dalam larutan jenuh AgCl $= \\ldots$",options: ["$\\approx 1$.$34\\times10$⁻^5 M","1.$8\\times10$⁻¹⁰ M","$\\approx 1$.$34\\times10$⁻^3 M","0.1 M","$\\approx 1$.$8\\times10$⁻^5 M"],answer:0,hint:"AgCl $\\to$ Ag⁺ $+$ Cl⁻. Ksp $=$ [Ag⁺][Cl⁻] $= x^2$. $x = \\sqrt$KspKspKspKspKspKspKspKsp.",explanation:"AgCl(s) ⇌ Ag⁺(aq$) +$ Cl⁻(aq).\nKsp $= x^2 = 1$.$8\\times10$⁻¹⁰.\nx $= \\sqrt{1.8\\times10⁻¹⁰} = 1$.$34\\times10$⁻^5 M.\n[Ag⁺] $=$ [Cl⁻] $= 1$.$34\\times10$⁻^5 M.\nJawaban: A."},
{question:"Reaksi redoks: MnO_4⁻ $+$ Fe^2⁺ $\\to$ Mn^2⁺ $+$ Fe^3⁺ (dalam asam). Koefisien setara MnO_4⁻ dan Fe^2⁺ adalah $\\ldots$",options: ["1 MnO_4⁻ : 5 Fe^2⁺","1:1","2:5","5:1","1:3"],answer:0,hint:"Mn: $+7\\to+2 ($gain 5e). Fe: $+2\\to+3 ($lose 1e). Untuk balance: 1 Mn $\\times 5e = 5$ Fe $\\times 1e$.",explanation:"Mn^7⁺$+5e\\to$MnMnMnMnMnMnMnMn^2⁺ (reduksi, 5 elektron).\nFe^2⁺$\\to$FeFeFeFeFeFeFeFe^3⁺$+e ($oksidasi, 1 elektron).\nKesetaraan elektron: $1\\times5 = 5\\times1$.\n1 MnO_4⁻ $+ 5$ Fe^2⁺ $+ 8H$⁺ $\\to$ Mn^2⁺ $+ 5$Fe^3⁺ $+ 4H$_2O.\nJawaban: A."},
{question:"Tipe ikatan dalam NaCl (ionik) vs HCl (kovalen polar) vs Cl_2 (kovalen nonpolar) ditentukan oleh $\\ldots$",options: ["Perbedaan keelektronegatifan antar atom","Jumlah elektron total (secara fundamental)","Massa atom (dalam pemahaman konvensional)","Warna senyawa (menurut konsensus ilmiah)","Nomor atom (dalam arti sempit)"],answer:0,hint:"$\\Delta$ENENENENENENENEN besar $(>1$.7): ionik. $\\Delta$ENENENENENENENEN sedang: kovalen polar. $\\Delta$ENENENENENENENEN$=0$: kovelen nonpolar.",explanation:"Na$-$Cl: $\\Delta$ENENENENENENENEN $= 3$.$0-0$.$9 = 2$.1 (ionik).\nH$-$Cl: $\\Delta$ENENENENENENENEN $= 3$.$0-2$.$1 = 0$.9 (kovalen polar).\nCl$-$Cl: $\\Delta$ENENENENENENENEN $= 0 ($kovalen nonpolar).\nPerbedaan keelektronegatifan menentukan tipe ikatan.\nJawaban: A."},
]);
