// BATCH 2 — Saintek Kimia (127 Soal HOTS)
appendQuestions('saintek_kimia', [
{question:"Larutan CH_3COOH 0.1M (Ka=1.8$\\times$10⁻^5) memiliki pH mendekati $\\ldots$",options: ["2.87","1","7","5","4.74"],answer:0,hint:"Asam lemah: [H⁺]=$\\sqrt{Ka\\timesC}$=$\\sqrt{1.8\\times10⁻^6}$.",explanation:"[H⁺] = $\\sqrt{Ka\\timesC}$ = $\\sqrt{1.8\\times10⁻^5\\times0.1}$ = $\\sqrt{1.8\\times10⁻^6}$ = 1.34$\\times$10⁻^3.\npH = -log(1.34$\\times$10⁻^3) $\\approx$ 2.87.\nA bukan 4.74 (itu pKa).\nJawaban: A."},
{question:"Pada sel volta Zn|Z$n^2$⁺||C$u^2$⁺|Cu, E^$\\circ$selsel = $\\ldots$ (E^$\\circ$ZnZn=-0.76V, E^$\\circ$CuCu=+0.34V)",options: ["1.10 V","0.42 V","-1.10 V","0.76 V","0.34 V"],answer:0,hint:"E^$\\circ$selsel = E^$\\circ$katodakatoda - E^$\\circ$anodaanoda = E^$\\circ$CuCu - E^$\\circ$ZnZn.",explanation:"E^$\\circ$selsel = E^$\\circ$katodakatoda - E^$\\circ$anodaanoda = 0.34-(-0.76) = 0.34+0.76 = 1.10 V.\nZn = anoda (oksidasi), Cu = katoda (reduksi).\nJawaban: A."},
{question:"Pergeseran kesetimbangan menurut Le Chatelier: jika tekanan dinaikkan pada reaksi N_2 + 3H_2 ⇌ 2NH_3, kesetimbangan bergeser ke $\\ldots$",options: ["Kanan (produk) — sisi dengan lebih sedikit mol gas","Kiri (reaktan)","Tidak berubah","Bergantung suhu","Bergantung katalis"],answer:0,hint:"Tekanan naik $\\to$ kesetimbangan bergeser ke sisi dengan jumlah mol gas LEBIH SEDIKIT.",explanation:"Reaktan: 1+3=4 mol gas. Produk: 2 mol gas.\nTekanan naik $\\to$ geser ke sisi mol lebih sedikit (kanan, produk).\nKatalis TIDAK menggeser kesetimbangan.\nJawaban: A."},
{question:"Geometri molekul SF_6 menurut teori VSEPR adalah $\\ldots$",options: ["Oktahedral","Tetrahedral","Trigonal bipiramidal","Planar segitiga","Linear"],answer:0,hint:"SF_6: 6 pasangan ikatan, 0 pasangan bebas $\\to$ AX_6.",explanation:"S memiliki 6 ikatan S-F, 0 lone pair.\nVSEPR: AX_6 $\\to$ geometri oktahedral (sudut 90^$\\circ$).\nSF_6 sangat stabil (24 elektron valensi).\nJawaban: A."},
{question:"Laju reaksi menjadi DUA KALI lipat setiap kenaikan suhu 10^$\\circ$CC. Jika suhu dinaikkan dari 20^$\\circ$CC ke 50^$\\circ$CC, laju reaksi menjadi $\\ldots$",options: ["8 kali lipat (2^3)","3 kali lipat","6 kali lipat","4 kali lipat","16 kali lipat"],answer:0,hint:"Kenaikan 30^$\\circ$CC = 3 kali lipat kenaikan 10^$\\circ$CC. Faktor = $2^3$.",explanation:"Kenaikan 30^$\\circ$CC/10^$\\circ$CC = 3 interval.\nLaju = $2^3$ = 8 kali lipat.\nJawaban: A."},
{question:"Bilangan oksidasi S dalam Na_2S_2O_3 (natrium tiosulfat) adalah $\\ldots$",options: ["+2","+4","+6","+7","-2"],answer:0,hint:"Na_2S_2O_3: 2Na(+1) + 2S(x) + 3O(-2) = 0. 2+2x-6=0.",explanation:"2(+1)+2x+3(-2) = 0 $\\to$ 2+2x-6 = 0 $\\to$ 2x = 4 $\\to$ x = +2.\nBilangan oksidasi S di tiosulfat = +2.\nJawaban: A."},
{question:"Polimer yang terbentuk dari polimerisasi adisi etilena (CH_2=CH_2) adalah $\\ldots$",options: ["Polietilena (PE)","Polistirena (PS)","PVC","Nylon","Teflon"],answer:0,hint:"Etilena = monomer polietilena. Ikatan rangkap terbuka $\\to$ polimer.",explanation:"CH_2=CH_2 $\\to$ (-CH_2-CH_2-)ₙ = polietilena (PE).\nAdisi: ikatan rangkap C=C terbuka dan monomer berantai.\nPS dari stirena, PVC dari vinil klorida, Nylon dari kondensasi.\nJawaban: A."},
{question:"Berdasarkan teori orbital molekul, orde ikatan O_2 adalah $\\ldots$",options: ["2","1","3","1.5","2.5"],answer:0,hint:"O_2 memiliki 16 elektron. Konfigurasi MO: ($\\sigma$2s)^2($\\sigma$*2s)^2($\\sigma$2p)^2($\\pi$2p)^4($\\pi$*2p)^2.",explanation:"O_2: 12 elektron valensi.\nBonding electrons: 8 ($\\sigma$2$s^2$ + $\\sigma$2$p^2$ + $\\pi$2$p^4$).\nAntibonding: 4 ($\\sigma$*2$s^2$ + $\\pi$*2$p^2$).\nBond order = (8-4)/2 = 2.\nO_2 memiliki 2 elektron tak berpasangan (paramagnetik).\nJawaban: A."},
{question:"Reaksi esterifikasi antara asam karboksilat dan alkohol menghasilkan $\\ldots$",options: ["Ester + Air","Eter + CO_2","Aldehida + H_2","Keton + Air","Amida + HCl"],answer:0,hint:"R-COOH + R'-OH $\\to$ R-COOR' + H_2O (kondensasi).",explanation:"Esterifikasi: asam karboksilat + alkohol $\\to$ ester + air.\nCH_3COOH + C_2H_5OH $\\to$ CH_3COOC_2H_5 + H_2O (katalis H_2SO_4).\nReaksi reversibel (kesetimbangan).\nJawaban: A."},
{question:"Prinsip Aufbau menyatakan bahwa pengisian orbital elektron dimulai dari $\\ldots$",options: ["Orbital dengan energi terendah ke tertinggi","Orbital dengan energi tertinggi ke terendah","Orbital p sebelum s","Orbital secara acak","Semua orbital sekaligus"],answer:0,hint:"Aufbau (Jerman) = membangun dari bawah ke atas. Energi rendah $\\to$ tinggi.",explanation:"Prinsip Aufbau: elektron mengisi orbital dari energi terendah ke tertinggi.\nUrutan: 1s$\\to$2s$\\to$2p$\\to$3s$\\to$3p$\\to$4s$\\to$3d$\\to$4p$\\to$5s$\\to$4d$\\to$...\n(Urutan ditentukan oleh aturan n+l.)\nJawaban: A."},
{question:"pH larutan buffer yang mengandung 0.1M CH_3COOH dan 0.1M CH_3COONa (pKa=4.74) adalah $\\ldots$",options: ["4.74","7","1","14","2.87"],answer:0,hint:"Henderson-Hasselbalch: pH = pKa + log([A⁻]/[HA]).",explanation:"pH = pKa + log([A⁻]/[HA]) = 4.74 + log(0.1/0.1) = 4.74 + 0 = 4.74.\nBuffer equimolar: pH = pKa.\nJawaban: A."},
{question:"Energi ionisasi MENURUN dari atas ke bawah dalam satu golongan karena $\\ldots$",options: ["Jari-jari atom bertambah $\\to$ elektron valensi lebih jauh dari inti $\\to$ lebih mudah dilepas","Jumlah proton berkurang","Jumlah neutron bertambah","Afinias elektron meningkat","Massa atom berkurang"],answer:0,hint:"Turun satu golongan: lebih banyak kulit $\\to$ jari-jari besar $\\to$ gaya tarik inti lebih lemah.",explanation:"Turun satu golongan: jumlah kulit elektron bertambah $\\to$ jari-jari atom besar $\\to$ elektron valensi lebih jauh dari inti $\\to$ gaya tarik inti lebih lemah $\\to$ energi ionisasi menurun (lebih mudah melepas elektron).\nJawaban: A."},
{question:"Kelarutan (Ksp) AgCl = 1.8$\\times$10⁻¹⁰. Konsentrasi Ag⁺ dalam larutan jenuh AgCl = $\\ldots$",options: ["$\\approx$ 1.34$\\times$10⁻^5 M","1.8$\\times$10⁻¹⁰ M","$\\approx$ 1.34$\\times$10⁻^3 M","0.1 M","$\\approx$ 1.8$\\times$10⁻^5 M"],answer:0,hint:"AgCl $\\to$ Ag⁺ + Cl⁻. Ksp = [Ag⁺][Cl⁻] = $x^2$. x = $\\sqrt$KspKsp.",explanation:"AgCl(s) ⇌ Ag⁺(aq) + Cl⁻(aq).\nKsp = $x^2$ = 1.8$\\times$10⁻¹⁰.\nx = $\\sqrt{1.8\\times10⁻¹⁰}$ = 1.34$\\times$10⁻^5 M.\n[Ag⁺] = [Cl⁻] = 1.34$\\times$10⁻^5 M.\nJawaban: A."},
{question:"Reaksi redoks: MnO_4⁻ + F$e^2$⁺ $\\to$ M$n^2$⁺ + F$e^3$⁺ (dalam asam). Koefisien setara MnO_4⁻ dan F$e^2$⁺ adalah $\\ldots$",options: ["1 MnO_4⁻ : 5 Fe^2⁺","1:1","2:5","5:1","1:3"],answer:0,hint:"Mn: +7$\\to$+2 (gain 5e). Fe: +2$\\to$+3 (lose 1e). Untuk balance: 1 Mn $\\times$ 5e = 5 Fe $\\times$ 1e.",explanation:"M$n^7$⁺+5e$\\to$MnM$n^2$⁺ (reduksi, 5 elektron).\nF$e^2$⁺$\\to$FeF$e^3$⁺+e (oksidasi, 1 elektron).\nKesetaraan elektron: 1$\\times$5 = 5$\\times$1.\n1 MnO_4⁻ + 5 F$e^2$⁺ + 8H⁺ $\\to$ M$n^2$⁺ + 5F$e^3$⁺ + 4H_2O.\nJawaban: A."},
{question:"Tipe ikatan dalam NaCl (ionik) vs HCl (kovalen polar) vs Cl_2 (kovalen nonpolar) ditentukan oleh $\\ldots$",options: ["Perbedaan keelektronegatifan antar atom","Jumlah elektron total","Massa atom","Warna senyawa","Nomor atom"],answer:0,hint:"$\\Delta$ENEN besar (>1.7): ionik. $\\Delta$ENEN sedang: kovalen polar. $\\Delta$ENEN=0: kovelen nonpolar.",explanation:"Na-Cl: $\\Delta$ENEN = 3.0-0.9 = 2.1 (ionik).\nH-Cl: $\\Delta$ENEN = 3.0-2.1 = 0.9 (kovalen polar).\nCl-Cl: $\\Delta$ENEN = 0 (kovalen nonpolar).\nPerbedaan keelektronegatifan menentukan tipe ikatan.\nJawaban: A."},
]);
