// BATCH 2 — Saintek Fisika (127 Soal HOTS)
appendQuestions('saintek_fisika', [
{question:"Sebuah benda bermassa 2 kg dilempar vertikal ke atas dengan kecepatan 20 m/s. Energi kinetik saat mencapai ketinggian maksimum (gesekan diabaikan) adalah $\\ldots$",options: ["0 J (seluruh Ek berubah menjadi Ep)","200 J","400 J","100 J","Tidak bisa ditentukan"],answer:0,hint:"Di puncak, kecepatan = 0 $\\to$ Ek = 0. Semua energi = potensial.",explanation:"Di ketinggian maksimum, v=0 $\\to$ Ek=½m$v^2$=0.\nSeluruh energi kinetik awal (½$\\times$2$\\times$400=400J) telah terkonversi menjadi energi potensial gravitasi. Hukum Kekekalan Energi Mekanik.\nJawaban: A."},
{question:"Dua benda bermassa m_1=3kg dan m_2=1kg terhubung tali melalui katrol. m_1 di atas meja licin, m_2 menggantung. Percepatan sistem = $\\ldots$ (g=10)",options: ["2.5 m/s^2","5 m/s^2","10 m/s^2","7.5 m/s^2","3.33 m/s^2"],answer:0,hint:"Gaya penggerak = m_2g. Massa total = m_1+m_2. a = m_2g/(m_1+m_2).",explanation:"a = m_2g/(m_1+m_2) = 1(10)/(3+1) = 10/4 = 2.5 m/s^2.\nJawaban: A."},
{question:"Sebuah elektron bergerak dalam medan magnetik seragam B = 0.5 T dengan kecepatan 1$0^6$ m/s tegak lurus B. Jari-jari lintasan lingkaran elektron adalah $\\ldots$ (m=9.1$\\times$10⁻^3¹ kg, q=1.6$\\times$10⁻¹^9 C)",options: ["$\\approx$ 1.14 $\\times$ 10⁻^5 m","$\\approx$ 1.14 $\\times$ 10⁻^3 m","$\\approx$ 1.14 $\\times$ 10⁻^2 m","$\\approx$ 1.14 $\\times$ 10⁻^7 m","$\\approx$ 1.14 $\\times$ 10⁻^4 m"],answer:0,hint:"Gaya Lorentz = gaya sentripetal: qvB = m$v^2$/r $\\to$ r = mv/(qB).",explanation:"r = mv/(qB) = (9.1$\\times$10⁻^3¹)(1$0^6$)/((1.6$\\times$10⁻¹^9)(0.5))\n= 9.1$\\times$10⁻^$2^5$ / 8$\\times$10⁻^2⁰ = 1.14$\\times$10⁻^5 m.\nJawaban: A."},
{question:"Efisiensi mesin Carnot yang beroperasi antara suhu 600K dan 300K adalah $\\ldots$",options: ["50%","25%","75%","100%","33%"],answer:0,hint:"η = 1 - Tc/Th = 1 - 300/600.",explanation:"η = 1 - Tc/Th = 1 - 300/600 = 1 - 0.5 = 0.5 = 50%.\nMesin Carnot = efisiensi maksimum teoritis.\nJawaban: A."},
{question:"Sebuah partikel bermassa m berada pada ketinggian h di atas permukaan bumi (R = jari-jari bumi). Jika h << R, percepatan gravitasi di ketinggian h mendekati $\\ldots$",options: ["g(1 - 2h/R)","g(1 + 2h/R)","g","0","g/2"],answer:0,hint:"g(h) = g(R/(R+h))^2 $\\approx$ g(1-2h/R) untuk h<<R (ekspansi binomial).",explanation:"g(h) = GM/(R+h)^2 = g[R/(R+h)]^2 = g[1/(1+h/R)]^2 $\\approx$ g(1-2h/R) untuk h<<R.\nEkspansi binomial: (1+x)⁻^2 $\\approx$ 1-2x untuk x<<1.\nJawaban: A."},
{question:"Panjang gelombang de Broglie proton (m=1.67$\\times$10⁻^$2^7$ kg) yang bergerak dengan energi kinetik 1 eV (1.6$\\times$10⁻¹^9 J) mendekati $\\ldots$",options: ["$\\approx$ 2.86 $\\times$ 10⁻¹¹ m","$\\approx$ 1.23 $\\times$ 10⁻^9 m","$\\approx$ 2.86 $\\times$ 10⁻^8 m","$\\approx$ 1.23 $\\times$ 10⁻¹⁰ m","$\\approx$ 2.86 $\\times$ 10⁻¹^3 m"],answer:0,hint:"$\\lambda$ = h/p = h/$\\sqrt{2mEk}$. h=6.63$\\times$10⁻^$3^4$.",explanation:"p = $\\sqrt{2mEk}$ = $\\sqrt{2 \\times 1.67\\times10⁻^2^7 \\times 1.6\\times10⁻¹^9}$ = $\\sqrt{5.344\\times10⁻^4^6}$ = 2.312$\\times$10⁻^$2^3$.\n$\\lambda$ = h/p = 6.63$\\times$10⁻^$3^4$/2.312$\\times$10⁻^$2^3$ $\\approx$ 2.87$\\times$10⁻¹¹ m.\nJawaban: A."},
{question:"Hukum Stefan-Boltzmann menyatakan daya radiasi benda hitam sebanding dengan $\\ldots$",options: ["T^4 (pangkat empat suhu absolut)","T^2","T","1/T","T^3"],answer:0,hint:"P = $\\sigma$ATA$T^4$ (sigma $\\times$ luas $\\times$ suh$u^4$).",explanation:"P = $\\sigma$ATA$T^4$. Daya radiasi berbanding lurus dengan pangkat empat suhu absolut. Jika suhu digandakan, daya menjadi 16 kali lipat.\nJawaban: A."},
{question:"Sebuah proyek pesawat mengukur kecepatan cahaya menggunakan cermin berputar. Metode ini pertama kali berhasil dilakukan oleh $\\ldots$",options: ["Fizeau (dan kemudian disempurnakan Foucault)","Newton","Einstein","Galileo","Bohr"],answer:0,hint:"Eksperimen roda bergerigi (Fizeau 1849) dan cermin berputar (Foucault 1850).",explanation:"Fizeau (1849) pertama kali berhasil mengukur kecepatan cahaya di Bumi menggunakan roda bergerigi. Foucault (1850) menyempurnakan dengan cermin berputar.\nJawaban: A."},
{question:"Sebuah kapasitor keping sejajar memiliki kapasitansi C. Jika jarak antar keping dijadikan setengah DAN dielektrik (κ=3) dimasukkan, kapasitansi baru = $\\ldots$",options: ["6C","3C","C/2","2C","3C/2"],answer:0,hint:"C = κ$\\epsilon_0$A/d. Jarak setengah: C$\\to$2C. Dielektrik 3: C$\\to$3C. Gabungan: 6C.",explanation:"C_0 = $\\epsilon_0$A/d.\nJarak setengah: C' = $\\epsilon_0$A/(d/2) = 2C_0.\nDielektrik κ=3: C'' = 3 $\\times$ 2C_0 = 6C_0.\nJawaban: A."},
{question:"Gelombang berdiri pada tali tetap di kedua ujung sepanjang L. Frekuensi harmonik ke-3 (overtone ke-2) = $\\ldots$",options: ["3v/(2L)","v/(2L)","3v/L","v/L","2v/L"],answer:0,hint:"Harmonik ke-n: fₙ = nv/(2L) untuk tali tetap-tetap.",explanation:"fₙ = nv/(2L). Harmonik ke-3: f_3 = 3v/(2L).\nHarmonik 1 (fundamental) = v/(2L). Harmonik 2 = 2v/(2L)=v/L.\nJawaban: A."},
{question:"Menurut prinsip ketidakpastian Heisenberg, $\\Delta$xx $\\times$ $\\Delta$pp $\\geq$ $\\ldots$",options: ["ℏ/2 (h-bar/2)","0","h","ℏ","2ℏ"],answer:0,hint:"Prinsip Heisenberg: ketidakpastian posisi $\\times$ momentum $\\geq$ ℏ/2.",explanation:"$\\Delta$xx$\\cdot$$\\Delta$pp $\\geq$ ℏ/2 = h/(4$\\pi$).\nKita tidak bisa mengetahui posisi DAN momentum partikel secara simultan dengan presisi sempurna.\nJawaban: A."},
{question:"Hukum Ohm dalam bentuk mikroskopik dinyatakan sebagai J = $\\sigma$EE, dimana J = rapat arus, $\\sigma$ = konduktivitas, E = $\\ldots$",options: ["Medan listrik","Energi","GGL","Muatan","Arus"],answer:0,hint:"J = $\\sigma$EE menghubungkan rapat arus dengan medan listrik lokal.",explanation:"Hukum Ohm mikroskopik: J = $\\sigma$EE.\nJ = rapat arus (A/$m^2$).\n$\\sigma$ = konduktivitas (S/m) = 1/$\\r$hoho (kebalikan resistivitas).\nE = medan listrik (V/m).\nJawaban: A."},
{question:"Persamaan Bernoulli untuk fluida ideal menyatakan bahwa sepanjang garis arus, P + ½$\\r$hovho$v^2$ + $\\r$hoghhogh = $\\ldots$",options: ["Konstan","Nol","Berubah linear","P_0 saja","$\\r$hoghog"],answer:0,hint:"Bernoulli = konservasi energi per satuan volume untuk fluida.",explanation:"P + ½$\\r$hovho$v^2$ + $\\r$hoghhogh = konstan (sepanjang streamline).\nIni adalah konservasi energi per satuan volume: energi tekanan + energi kinetik + energi potensial gravitasi.\nJawaban: A."},
{question:"Sebuah lensa tipis cembung (f=20cm) dan lensa cekung (f=-30cm) disusun menempel. Daya lensa gabungan = $\\ldots$",options: ["1/60 dioptri BUKAN, let me recalculate","5 dioptri - 3.33 dioptri = 1.67 dioptri","Fokus gabungan = 60 cm","60 cm dan 1.67 dioptri","Semua salah"],answer:2,hint:"1/f = 1/f_1+1/f_2 = 1/20+1/(-30) = 3/60-2/60 = 1/60.",explanation:"1/f = 1/20 + 1/(-30) = 3/60 - 2/60 = 1/60.\nf = 60 cm. Daya = 100/60 $\\approx$ 1.67 dioptri.\nJawaban: C — Fokus gabungan = 60 cm."},
{question:"Elektron pada atom hidrogen jatuh dari n=3 ke n=2 (deret Balmer). Panjang gelombang foton yang dipancarkan termasuk dalam spektrum $\\ldots$",options: ["Cahaya tampak (visible light)","Inframerah","Ultraviolet","Sinar-X","Gelombang mikro"],answer:0,hint:"Deret Balmer (transisi ke n=2) menghasilkan cahaya tampak.",explanation:"Deret Lyman (ke n=1): UV. Deret Balmer (ke n=2): cahaya tampak. Deret Paschen (ke n=3): IR.\nTransisi n=3$\\to$nn=2 = deret Balmer = visible light ($\\lambda$ $\\approx$ 656 nm, merah = H$\\alpha$).\nJawaban: A."},
{question:"Kapasitas kalor pada tekanan konstan (Cₚ) selalu LEBIH BESAR dari kapasitas kalor pada volume konstan (Cᵥ) karena $\\ldots$",options: ["Pada tekanan konstan, sebagian kalor digunakan untuk kerja ekspansi (PdV)","Cₚ diukur dengan termometer yang lebih akurat","Volume selalu konstan","Tekanan tidak mempengaruhi kalor","Tidak ada perbedaan"],answer:0,hint:"Pada P konstan, gas bekerja melawan tekanan saat memuai (W=P$\\Delta$VV). Pada V konstan, tidak ada kerja.",explanation:"Cₚ > Cᵥ karena pada tekanan konstan, kalor yang diberikan digunakan untuk: (1) menaikkan suhu (sama dengan Cᵥ) + (2) melakukan kerja ekspansi P$\\Delta$VV. Untuk gas ideal: Cₚ - Cᵥ = R (relasi Mayer).\nJawaban: A."},
]);
