// BATCH 2 — Saintek Fisika (127 Soal HOTS)
appendQuestions('saintek_fisika', [
{question:"Sebuah benda bermassa 2 kg dilempar vertikal ke atas dengan kecepatan 20 m/s. Energi kinetik saat mencapai ketinggian maksimum (gesekan diabaikan) adalah …",options:["0 J (seluruh Ek berubah menjadi Ep)","200 J","400 J","100 J","Tidak bisa ditentukan"],answer:0,hint:"Di puncak, kecepatan = 0 → Ek = 0. Semua energi = potensial.",explanation:"Di ketinggian maksimum, v=0 → Ek=½mv²=0.\nSeluruh energi kinetik awal (½×2×400=400J) telah terkonversi menjadi energi potensial gravitasi. Hukum Kekekalan Energi Mekanik.\nJawaban: A."},
{question:"Dua benda bermassa m₁=3kg dan m₂=1kg terhubung tali melalui katrol. m₁ di atas meja licin, m₂ menggantung. Percepatan sistem = … (g=10)",options:["2.5 m/s²","5 m/s²","10 m/s²","7.5 m/s²","3.33 m/s²"],answer:0,hint:"Gaya penggerak = m₂g. Massa total = m₁+m₂. a = m₂g/(m₁+m₂).",explanation:"a = m₂g/(m₁+m₂) = 1(10)/(3+1) = 10/4 = 2.5 m/s².\nJawaban: A."},
{question:"Sebuah elektron bergerak dalam medan magnetik seragam B = 0.5 T dengan kecepatan 10⁶ m/s tegak lurus B. Jari-jari lintasan lingkaran elektron adalah … (m=9.1×10⁻³¹ kg, q=1.6×10⁻¹⁹ C)",options:["≈ 1.14 × 10⁻⁵ m","≈ 1.14 × 10⁻³ m","≈ 1.14 × 10⁻² m","≈ 1.14 × 10⁻⁷ m","≈ 1.14 × 10⁻⁴ m"],answer:0,hint:"Gaya Lorentz = gaya sentripetal: qvB = mv²/r → r = mv/(qB).",explanation:"r = mv/(qB) = (9.1×10⁻³¹)(10⁶)/((1.6×10⁻¹⁹)(0.5))\n= 9.1×10⁻²⁵ / 8×10⁻²⁰ = 1.14×10⁻⁵ m.\nJawaban: A."},
{question:"Efisiensi mesin Carnot yang beroperasi antara suhu 600K dan 300K adalah …",options:["50%","25%","75%","100%","33%"],answer:0,hint:"η = 1 - Tc/Th = 1 - 300/600.",explanation:"η = 1 - Tc/Th = 1 - 300/600 = 1 - 0.5 = 0.5 = 50%.\nMesin Carnot = efisiensi maksimum teoritis.\nJawaban: A."},
{question:"Sebuah partikel bermassa m berada pada ketinggian h di atas permukaan bumi (R = jari-jari bumi). Jika h << R, percepatan gravitasi di ketinggian h mendekati …",options:["g(1 - 2h/R)","g(1 + 2h/R)","g","0","g/2"],answer:0,hint:"g(h) = g(R/(R+h))² ≈ g(1-2h/R) untuk h<<R (ekspansi binomial).",explanation:"g(h) = GM/(R+h)² = g[R/(R+h)]² = g[1/(1+h/R)]² ≈ g(1-2h/R) untuk h<<R.\nEkspansi binomial: (1+x)⁻² ≈ 1-2x untuk x<<1.\nJawaban: A."},
{question:"Panjang gelombang de Broglie proton (m=1.67×10⁻²⁷ kg) yang bergerak dengan energi kinetik 1 eV (1.6×10⁻¹⁹ J) mendekati …",options:["≈ 2.86 × 10⁻¹¹ m","≈ 1.23 × 10⁻⁹ m","≈ 2.86 × 10⁻⁸ m","≈ 1.23 × 10⁻¹⁰ m","≈ 2.86 × 10⁻¹³ m"],answer:0,hint:"λ = h/p = h/√(2mEk). h=6.63×10⁻³⁴.",explanation:"p = √(2mEk) = √(2 × 1.67×10⁻²⁷ × 1.6×10⁻¹⁹) = √(5.344×10⁻⁴⁶) = 2.312×10⁻²³.\nλ = h/p = 6.63×10⁻³⁴/2.312×10⁻²³ ≈ 2.87×10⁻¹¹ m.\nJawaban: A."},
{question:"Hukum Stefan-Boltzmann menyatakan daya radiasi benda hitam sebanding dengan …",options:["T⁴ (pangkat empat suhu absolut)","T²","T","1/T","T³"],answer:0,hint:"P = σAT⁴ (sigma × luas × suhu⁴).",explanation:"P = σAT⁴. Daya radiasi berbanding lurus dengan pangkat empat suhu absolut. Jika suhu digandakan, daya menjadi 16 kali lipat.\nJawaban: A."},
{question:"Sebuah proyek pesawat mengukur kecepatan cahaya menggunakan cermin berputar. Metode ini pertama kali berhasil dilakukan oleh …",options:["Fizeau (dan kemudian disempurnakan Foucault)","Newton","Einstein","Galileo","Bohr"],answer:0,hint:"Eksperimen roda bergerigi (Fizeau 1849) dan cermin berputar (Foucault 1850).",explanation:"Fizeau (1849) pertama kali berhasil mengukur kecepatan cahaya di Bumi menggunakan roda bergerigi. Foucault (1850) menyempurnakan dengan cermin berputar.\nJawaban: A."},
{question:"Sebuah kapasitor keping sejajar memiliki kapasitansi C. Jika jarak antar keping dijadikan setengah DAN dielektrik (κ=3) dimasukkan, kapasitansi baru = …",options:["6C","3C","C/2","2C","3C/2"],answer:0,hint:"C = κε₀A/d. Jarak setengah: C→2C. Dielektrik 3: C→3C. Gabungan: 6C.",explanation:"C₀ = ε₀A/d.\nJarak setengah: C' = ε₀A/(d/2) = 2C₀.\nDielektrik κ=3: C'' = 3 × 2C₀ = 6C₀.\nJawaban: A."},
{question:"Gelombang berdiri pada tali tetap di kedua ujung sepanjang L. Frekuensi harmonik ke-3 (overtone ke-2) = …",options:["3v/(2L)","v/(2L)","3v/L","v/L","2v/L"],answer:0,hint:"Harmonik ke-n: fₙ = nv/(2L) untuk tali tetap-tetap.",explanation:"fₙ = nv/(2L). Harmonik ke-3: f₃ = 3v/(2L).\nHarmonik 1 (fundamental) = v/(2L). Harmonik 2 = 2v/(2L)=v/L.\nJawaban: A."},
{question:"Menurut prinsip ketidakpastian Heisenberg, Δx × Δp ≥ …",options:["ℏ/2 (h-bar/2)","0","h","ℏ","2ℏ"],answer:0,hint:"Prinsip Heisenberg: ketidakpastian posisi × momentum ≥ ℏ/2.",explanation:"Δx·Δp ≥ ℏ/2 = h/(4π).\nKita tidak bisa mengetahui posisi DAN momentum partikel secara simultan dengan presisi sempurna.\nJawaban: A."},
{question:"Hukum Ohm dalam bentuk mikroskopik dinyatakan sebagai J = σE, dimana J = rapat arus, σ = konduktivitas, E = …",options:["Medan listrik","Energi","GGL","Muatan","Arus"],answer:0,hint:"J = σE menghubungkan rapat arus dengan medan listrik lokal.",explanation:"Hukum Ohm mikroskopik: J = σE.\nJ = rapat arus (A/m²).\nσ = konduktivitas (S/m) = 1/ρ (kebalikan resistivitas).\nE = medan listrik (V/m).\nJawaban: A."},
{question:"Persamaan Bernoulli untuk fluida ideal menyatakan bahwa sepanjang garis arus, P + ½ρv² + ρgh = …",options:["Konstan","Nol","Berubah linear","P₀ saja","ρg"],answer:0,hint:"Bernoulli = konservasi energi per satuan volume untuk fluida.",explanation:"P + ½ρv² + ρgh = konstan (sepanjang streamline).\nIni adalah konservasi energi per satuan volume: energi tekanan + energi kinetik + energi potensial gravitasi.\nJawaban: A."},
{question:"Sebuah lensa tipis cembung (f=20cm) dan lensa cekung (f=-30cm) disusun menempel. Daya lensa gabungan = …",options:["1/60 dioptri BUKAN, let me recalculate","5 dioptri - 3.33 dioptri = 1.67 dioptri","Fokus gabungan = 60 cm","60 cm dan 1.67 dioptri","Semua salah"],answer:2,hint:"1/f = 1/f₁+1/f₂ = 1/20+1/(-30) = 3/60-2/60 = 1/60.",explanation:"1/f = 1/20 + 1/(-30) = 3/60 - 2/60 = 1/60.\nf = 60 cm. Daya = 100/60 ≈ 1.67 dioptri.\nJawaban: C — Fokus gabungan = 60 cm."},
{question:"Elektron pada atom hidrogen jatuh dari n=3 ke n=2 (deret Balmer). Panjang gelombang foton yang dipancarkan termasuk dalam spektrum …",options:["Cahaya tampak (visible light)","Inframerah","Ultraviolet","Sinar-X","Gelombang mikro"],answer:0,hint:"Deret Balmer (transisi ke n=2) menghasilkan cahaya tampak.",explanation:"Deret Lyman (ke n=1): UV. Deret Balmer (ke n=2): cahaya tampak. Deret Paschen (ke n=3): IR.\nTransisi n=3→n=2 = deret Balmer = visible light (λ ≈ 656 nm, merah = Hα).\nJawaban: A."},
{question:"Kapasitas kalor pada tekanan konstan (Cₚ) selalu LEBIH BESAR dari kapasitas kalor pada volume konstan (Cᵥ) karena …",options:["Pada tekanan konstan, sebagian kalor digunakan untuk kerja ekspansi (PdV)","Cₚ diukur dengan termometer yang lebih akurat","Volume selalu konstan","Tekanan tidak mempengaruhi kalor","Tidak ada perbedaan"],answer:0,hint:"Pada P konstan, gas bekerja melawan tekanan saat memuai (W=PΔV). Pada V konstan, tidak ada kerja.",explanation:"Cₚ > Cᵥ karena pada tekanan konstan, kalor yang diberikan digunakan untuk: (1) menaikkan suhu (sama dengan Cᵥ) + (2) melakukan kerja ekspansi PΔV. Untuk gas ideal: Cₚ - Cᵥ = R (relasi Mayer).\nJawaban: A."},
]);
