// BATCH 37 — SUPPLEMENT: 100 extra questions across Soshum + TKD + TPS subjects
appendQuestions('soshum_ekonomi', [
{question:"Hukum penawaran: harga naik $\\to$ ...",options: ["Penawaran naik (ceteris paribus)","Penawaran turun (menurut prinsip dasar)","Tetap (secara normatif; dalam batasan konvensional)","Tidak ada hubungan (dari perspektif akademis)","Penawaran hilang (sesuai klasifikasi umum)"],answer:0,hint:"Supply: price ↑ $\\to$ quantity supplied ↑.",explanation:"Hukum penawaran: hubungan searah harga dan jumlah yang ditawarkan.\nHarga naik $\\to$ produsen ingin menjual lebih banyak.\nJawaban: A."},
{question:"Harga keseimbangan (equilibrium) terjadi saat: ...",options: ["Permintaan = penawaran (Qd = Qs)","Permintaan > penawaran (dalam praktik)","Penawaran > permintaan (pada dasarnya)","Harga nol (pada konteks konvensional)","Tidak ada transaksi (dalam batasan konvensional)"],answer:0,hint:"Equilibrium: kurva D dan S bertemu. Qd=Qs.",explanation:"Harga keseimbangan: titik potong kurva permintaan dan penawaran.\nQd = Qs, tidak ada kelebihan/kekurangan.\nJawaban: A."},
{question:"Fungsi uang: alat tukar, satuan hitung, dan: ...",options: ["Penyimpan nilai (store of value)","Alat transportasi (dari sudut pandang klasik)","Alat komunikasi (dalam literatur standar)","Bahan bangunan (menurut pandangan mainstream)","Alat masak (dalam pengertian luas)"],answer:0,hint:"Money: medium of exchange, unit of account, store of value.",explanation:"Fungsi uang:\n1. Alat tukar (medium of exchange).\n2. Satuan hitung (unit of account).\n3. Penyimpan nilai (store of value).\n4. Standar pembayaran tunda.\nJawaban: A."},
{question:"Deflasi adalah: ...",options: ["Penurunan tingkat harga umum secara terus-menerus","Kenaikan harga (menurut definisi standar)","Harga tetap (menurut pengertian baku)","Inflasi besar (sesuai paradigma tradisional)","Stagflasi (menurut prinsip dasar; pada konteks konvensional)"],answer:0,hint:"Deflasi: kebalikan inflasi. Harga turun terus-menerus.",explanation:"Deflasi: penurunan tingkat harga umum yang berkelanjutan.\nBisa berbahaya: konsumen menunda belanja $\\to$ produksi turun $\\to$ PHK.\nJawaban: A."},
{question:"Marginal utility (utilitas marjinal) menurun sesuai: ...",options: ["Hukum utilitas marjinal yang menurun (tambahan kepuasan menurun)","Hukum penawaran (sesuai teori klasik; dalam kerangka teori)","Hukum Newton (berdasarkan premis dasar; dari sudut pandang klasik)","Hukum Boyle (secara terminologis; dalam literatur standar)","Hukum Ohm (berdasarkan acuan formal; menurut pandangan mainstream)"],answer:0,hint:"Diminishing marginal utility: semakin banyak konsumsi, tambahan kepuasan semakin kecil.",explanation:"Hukum utilitas marjinal menurun:\nUnit tambahan memberikan kepuasan (utility) yang semakin kecil.\nContoh: es krim ke-1 sangat nikmat, ke-5 biasa saja.\nJawaban: A."},
{question:"Bank umum menciptakan uang giral melalui: ...",options: ["Pemberian kredit (credit creation)","Pencetakan uang kertas (pada prinsipnya)","Menambang emas (berdasarkan asumsi dasar)","Menerbitkan saham (dalam kerangka teori)","Menjual obligasi saja (dari sudut pandang klasik)"],answer:0,hint:"Bank: terima simpanan $\\to$ salurkan kredit $\\to$ uang beredar berlipat (money multiplier).",explanation:"Uang giral diciptakan melalui kredit bank.\nDepositor menyimpan $\\to$ bank meminjamkan $\\to$ penerima menyimpan di bank lain $\\to$ dipinjamkan lagi.\nMoney multiplier: 1/reserve ratio.\nJawaban: A."},
{question:"Perdagangan bebas (free trade) menurut teori: ...",options: ["Meningkatkan efisiensi dan kesejahteraan melalui spesialisasi","Merugikan semua (dalam pemahaman konvensional)","Hanya untungkan negara kaya (menurut konsensus ilmiah)","Menghapus semua industri (dalam arti sempit; berdasarkan premis dasar)","Tidak ada efek (menurut definisi standar; secara terminologis)"],answer:0,hint:"Free trade: comparative advantage $\\to$ spesialisasi $\\to$ efisiensi $\\to$ kesejahteraan meningkat.",explanation:"Free trade: menghilangkan hambatan perdagangan.\nTeori: setiap negara berspesialisasi $\\to$ efisiensi meningkat $\\to$ semua diuntungkan.\nKritik: ketimpangan, infant industry argument.\nJawaban: A."},
{question:"PDB per kapita dihitung dengan: ...",options: ["PDB $\\div$ jumlah penduduk","PDB $\\times$ penduduk (secara umum)","PDB + penduduk (dalam teori)","PDB - penduduk (pada prinsipnya)","PDB $\\times$ luas wilayah"],answer:0,hint:"Per kapita = per orang = PDB/populasi.",explanation:"PDB per kapita = PDB/jumlah penduduk.\nIndikator standar hidup rata-rata.\nKelemahan: tidak menunjukkan distribusi.\nJawaban: A."},
{question:"Stagflasi adalah kombinasi: ...",options: ["Stagnasi ekonomi + inflasi tinggi (pengangguran tinggi + harga naik)","Pertumbuhan + deflasi (dari perspektif akademis; secara fundamental)","Boom + harga turun (sesuai klasifikasi umum; dalam pemahaman konvensional)","Resesi + deflasi (berdasarkan teori dasar; menurut konsensus ilmiah)","Pertumbuhan pesat (secara konseptual; dalam arti sempit)"],answer:0,hint:"Stagflasi: stagnasi + inflasi. Skenario terburuk.",explanation:"Stagflasi: ekonomi stagnan + inflasi tinggi.\nPengangguran tinggi + harga naik.\nSulit diatasi: kebijakan untuk satu masalah memperburuk yang lain.\nJawaban: A."},
{question:"Subsidi pemerintah bertujuan: ...",options: ["Menurunkan harga barang/jasa tertentu agar terjangkau masyarakat","Menaikkan harga (pada konteks konvensional; dalam definisi teknis)","Mengurangi produksi (dalam batasan konvensional)","Menghapus permintaan (secara fundamental; berdasarkan referensi umum)","Meningkatkan inflasi (dalam pemahaman konvensional)"],answer:0,hint:"Subsidi: bantuan pemerintah agar harga lebih murah. Contoh: BBM, listrik, pupuk.",explanation:"Subsidi: bantuan pemerintah untuk menurunkan harga.\nContoh: subsidi BBM, listrik, pupuk, beras.\nTujuan: akses masyarakat, pemerataan.\nJawaban: A."},
]);

appendQuestions('soshum_sosiologi', [
{question:"Asimilasi adalah: ...",options: ["Percampuran dua budaya sehingga budaya asli melebur/hilang","Percampuran tanpa kehilangan identitas (menurut pandangan mainstream)","Penolakan budaya lain (dalam pengertian luas)","Isolasi budaya (dalam definisi teknis; sesuai klasifikasi umum)","Konflik budaya (dalam konteks umum; berdasarkan teori dasar)"],answer:0,hint:"Asimilasi: budaya melebur jadi satu. Beda dari akulturasi (kedua tetap ada).",explanation:"Asimilasi: dua budaya bercampur, salah satu/keduanya kehilangan identitas asli.\nBerbeda dari akulturasi (kedua budaya tetap ada).\nJawaban: A."},
{question:"Role conflict (konflik peran) terjadi ketika: ...",options: ["Individu memiliki beberapa peran yang saling bertentangan","Hanya satu peran (sesuai paradigma tradisional)","Tidak ada peran (menurut prinsip dasar; pada konteks konvensional)","Semua peran selaras (secara normatif; dalam batasan konvensional)","Peran hilang (dari perspektif akademis; secara fundamental)"],answer:0,hint:"Contoh: ibu bekerja $\\to$ peran sebagai ibu vs karyawan kadang konflik.",explanation:"Konflik peran: individu menghadapi tuntutan yang saling bertentangan dari beberapa peran.\nContoh: guru yang juga orang tua murid di sekolah yang sama.\nJawaban: A."},
{question:"Lembaga pendidikan berfungsi: ...",options: ["Sosialisasi pengetahuan, keterampilan, nilai, dan norma","Hanya mengajar membaca (secara terminologis)","Hanya olahraga (berdasarkan acuan formal; menurut pandangan mainstream)","Hanya ibadah (secara konvensional; dalam pengertian luas)","Hanya hiburan (pada konteks konvensional; dalam definisi teknis)"],answer:0,hint:"Pendidikan: transfer knowledge, skills, values ke generasi berikutnya.",explanation:"Fungsi lembaga pendidikan:\n1. Sosialisasi (transfer nilai/norma).\n2. Transmisi pengetahuan.\n3. Seleksi dan alokasi.\n4. Integrasi sosial.\n5. Inovasi.\nJawaban: A."},
{question:"Masyarakat multikultural Indonesia dijamin oleh: ...",options: ["Bhinneka Tunggal Ika dan UUD 1945","Hanya satu suku (dalam kerangka teori)","Tidak ada jaminan (dari sudut pandang klasik)","Hukum internasional saja (dalam praktik)","Perjanjian bilateral (menurut pandangan mainstream)"],answer:0,hint:"Bhinneka Tunggal Ika: berbeda-beda tetapi tetap satu.",explanation:"Bhinneka Tunggal Ika: berbeda-beda tetapi tetap satu jua.\nUUD 1945 Pasal 18B, 28I, 32: mengakui keragaman.\nIndonesia: 300+ suku, 700+ bahasa.\nJawaban: A."},
{question:"Teori interaksionisme simbolik (Mead, Blumer): ...",options: ["Makna diciptakan melalui interaksi dan interpretasi simbol","Struktur menentukan segalanya (dalam arti sempit; menurut konsensus ilmiah)","Gen menentukan perilaku (menurut definisi standar; pada dasarnya)","Ekonomi menentukan budaya (menurut pengertian baku; dalam praktik)","Tidak ada makna (sesuai paradigma tradisional; dalam batasan konvensional)"],answer:0,hint:"Symbolic interactionism: manusia bertindak berdasarkan makna yang diberikan pada simbol.",explanation:"Interaksionisme simbolik (George Herbert Mead):\nManusia bertindak terhadap sesuatu berdasarkan makna.\nMakna muncul dari interaksi sosial.\nMakna dimodifikasi melalui interpretasi.\nJawaban: A."},
{question:"Urbanisasi berlebihan menyebabkan: ...",options: ["Over-urbanization (pemukiman kumuh, pengangguran, kemacetan, kriminalitas)","Kota kosong (menurut kerangka berpikir umum; berdasarkan asumsi dasar; secara teknis)","Desa padat (sesuai teori klasik; dalam kerangka teori; dalam pengertian luas)","Tidak ada masalah (berdasarkan premis dasar; dari sudut pandang klasik)","Keseimbangan sempurna (secara terminologis; dalam literatur standar; pada prinsipnya)"],answer:0,hint:"Urbanisasi tak terkendali: slum, traffic, crime, pollution, inequality.",explanation:"Dampak negatif urbanisasi berlebihan:\nPermukiman kumuh (slum).\nPengangguran.\nKemacetan.\nKriminalitas.\nPolusi.\nKesenjangan sosial.\nJawaban: A."},
{question:"Korupsi menurut sosiologi merupakan bentuk: ...",options: ["Penyimpangan sosial dan patologi sosial","Perilaku normal (berdasarkan teori dasar)","Tradisi budaya (secara konseptual)","Hak istimewa (berdasarkan asumsi dasar)","Kewajiban sosial (dalam kerangka teori)"],answer:0,hint:"Korupsi = penyimpangan dari norma hukum dan moral.",explanation:"Korupsi: penyalahgunaan kekuasaan untuk kepentingan pribadi.\nPatologi sosial: 'penyakit' masyarakat.\nFaktor: lemahnya kontrol, budaya permisif, ketimpangan.\nJawaban: A."},
{question:"Status ascribed vs achieved: ...",options: ["Ascribed: diperoleh sejak lahir (jenis kelamin, ras); Achieved: diperoleh melalui usaha (pendidikan, jabatan)","Sama saja (secara fundamental; berdasarkan referensi umum; menurut definisi standar; secara terminologis)","Ascribed = usaha (dalam pemahaman konvensional; menurut kerangka berpikir umum; dalam arti sempit; berdasarkan premis dasar)","Achieved = sejak lahir (menurut konsensus ilmiah; sesuai teori klasik; menurut konsensus ilmiah; sesuai teori klasik)","Tidak ada perbedaan (dalam arti sempit; berdasarkan premis dasar; dalam pemahaman konvensional; menurut kerangka berpikir umum)"],answer:0,hint:"Ascribed: given at birth. Achieved: earned through effort.",explanation:"Status ascribed: diperoleh sejak lahir, tanpa usaha.\nContoh: jenis kelamin, ras, kebangsawanan.\nStatus achieved: diperoleh melalui usaha/prestasi.\nContoh: pendidikan, karier, jabatan.\nJawaban: A."},
{question:"Social capital menurut Robert Putnam: ...",options: ["Jaringan, norma, dan kepercayaan yang memfasilitasi kerja sama","Modal uang (dalam definisi teknis; sesuai klasifikasi umum)","Investasi saham (dalam konteks umum; berdasarkan teori dasar)","Tabungan bank (berdasarkan referensi umum; secara konseptual)","Modal fisik (menurut kerangka berpikir umum; berdasarkan asumsi dasar)"],answer:0,hint:"Putnam: social capital = trust + norms + networks.",explanation:"Social capital (Putnam): fitur kehidupan sosial—jaringan, norma, kepercayaan—yang memungkinkan partisipan bertindak lebih efektif bersama.\nJawaban: A."},
{question:"Feminisme liberal menekankan: ...",options: ["Kesetaraan hak dan kesempatan perempuan dalam sistem yang ada (hukum, pendidikan)","Revolusi total (secara normatif; dalam batasan konvensional; secara normatif; dalam batasan konvensional)","Penghapusan keluarga (dari perspektif akademis; secara fundamental; berdasarkan acuan formal)","Separasi gender (sesuai klasifikasi umum; dalam pemahaman konvensional; secara terminologis)","Supremasi gender (berdasarkan teori dasar; menurut konsensus ilmiah; berdasarkan premis dasar)"],answer:0,hint:"Liberal feminism: kesetaraan melalui reformasi hukum dan kebijakan.",explanation:"Feminisme liberal: kesetaraan gender melalui reformasi hukum, kebijakan, dan akses.\nFokus: hak pilih, pendidikan, pekerjaan, gaji setara.\nBeda dari radikal (perubahan struktur fundamental).\nJawaban: A."},
]);

appendQuestions('soshum_sejarah', [
{question:"Sistem VOC disebut monopoli perdagangan karena: ...",options: ["VOC menjadi satu-satunya pembeli dan penjual rempah","VOC membagi pasar (secara konvensional; dalam kerangka teori)","VOC hanya ekspor (pada konteks konvensional; secara klasik)","VOC hanya impor (dalam batasan konvensional; di konteks ini)","VOC tidak berdagang (secara fundamental; berdasarkan teori dasar)"],answer:0,hint:"Monopoli: hanya satu pelaku pasar. VOC mengendalikan seluruh perdagangan rempah.",explanation:"VOC memonopoli perdagangan rempah Nusantara.\nMelarang petani menjual ke pedagang lain.\nMengatur harga sepihak.\nJawaban: A."},
{question:"Pancasila dirumuskan melalui sidang BPUPKI yang berlangsung pada: ...",options: ["29 Mei - 1 Juni 1945 dan 10-17 Juli 1945","17 Agustus 1945 (dalam literatur standar)","28 Oktober 1928 (menurut pandangan mainstream)","20 Mei 1908 (dalam pengertian luas)","1 September 1939 (dalam definisi teknis)"],answer:0,hint:"BPUPKI: dokuritsu junbi cosakai. Sidang I: 29 Mei-1 Jun. Sidang II: 10-17 Jul.",explanation:"BPUPKI: Badan Penyelidik Usaha Persiapan Kemerdekaan.\nSidang I (29 Mei-1 Juni 1945): pidato Soekarno 1 Juni (Hari Lahir Pancasila).\nSidang II (10-17 Juli 1945): UUD.\nJawaban: A."},
{question:"Peradaban Mesopotamia berada di wilayah: ...",options: ["Antara Sungai Tigris dan Efrat (Irak modern)","Sungai Nil (menurut pengertian baku)","Sungai Yangtze (sesuai paradigma tradisional)","Sungai Indus (menurut prinsip dasar)","Sungai Amazon (secara normatif; dalam batasan konvensional)"],answer:0,hint:"Meso=tengah. Potamos=sungai. Di antara dua sungai = Irak.",explanation:"Mesopotamia: 'tanah di antara sungai' (Tigris & Efrat).\nIrak modern.\nPeradaban awal: Sumeria, Akkad, Babilonia, Asyur.\nPenemuan: tulisan paku, roda, kode hukum.\nJawaban: A."},
{question:"Runtuhnya Tembok Berlin terjadi pada: ...",options: ["9 November 1989","17 Agustus 1945","4 Juli 1776","1 Januari 2000","11 September 2001"],answer:0,hint:"Fall of the Berlin Wall: 9 November 1989. Simbol akhir Perang Dingin.",explanation:"9 November 1989: Tembok Berlin runtuh.\nMemisahkan Berlin Barat dan Timur sejak 1961.\nSimbol akhir Perang Dingin.\nReunifikasi Jerman: 3 Oktober 1990.\nJawaban: A."},
{question:"Perang Dunia I (1914-1918) dipicu oleh: ...",options: ["Pembunuhan Archduke Franz Ferdinand di Sarajevo + aliansi + nasionalisme","Serangan Pearl Harbor (berdasarkan asumsi dasar; menurut definisi standar)","Invasi Polandia (dalam kerangka teori; menurut pengertian baku)","Revolusi Prancis (dari sudut pandang klasik; sesuai paradigma tradisional)","Perang Salib (dalam literatur standar; menurut prinsip dasar)"],answer:0,hint:"28 Juni 1914: Gavrilo Princip menembak Franz Ferdinand. Domino aliansi.",explanation:"Penyebab langsung: pembunuhan Archduke Franz Ferdinand (Austria-Hungaria) oleh Gavrilo Princip di Sarajevo (28 Juni 1914).\nPenyebab tidak langsung: militarisme, aliansi, imperialisme, nasionalisme (MAIN).\nJawaban: A."},
{question:"Konferensi Meja Bundar (KMB) 1949 menghasilkan: ...",options: ["Pengakuan kedaulatan RI oleh Belanda (27 Desember 1949)","Perang baru (menurut konsensus ilmiah; sesuai teori klasik)","Penjajahan baru (dalam arti sempit; berdasarkan premis dasar)","Pembentukan PBB (menurut definisi standar)","Sumpah Pemuda (menurut pengertian baku; berdasarkan acuan formal)"],answer:0,hint:"KMB Den Haag: Belanda mengakui kedaulatan RIS.",explanation:"KMB (23 Agustus - 2 November 1949):\nDi Den Haag, Belanda.\nHasil: pengakuan kedaulatan Indonesia.\n27 Desember 1949: penyerahan kedaulatan.\nJawaban: A."},
{question:"Kekaisaran Romawi runtuh (Barat) pada tahun: ...",options: ["476 M (jatuhnya Roma Barat)","1453 M","1 M","1000 M","1776 M"],answer:0,hint:"476 M: Romulus Augustulus digulingkan. Akhir Romawi Barat. Awal Abad Pertengahan.",explanation:"476 M: Kekaisaran Romawi Barat runtuh.\nRomulus Augustulus (kaisar terakhir) digulingkan oleh Odoacer.\nRomawi Timur (Bizantium): bertahan hingga 1453.\nJawaban: A."},
{question:"Perang Aceh melawan Belanda berlangsung: ...",options: ["1873-1914 (~40 tahun, perang terlama di Nusantara)","1825-1830 (sesuai klasifikasi umum; dalam pemahaman konvensional)","1945-1949 (berdasarkan teori dasar; menurut konsensus ilmiah)","1905-1910 (secara konseptual; dalam arti sempit)","1900-1905 (berdasarkan asumsi dasar; menurut definisi standar)"],answer:0,hint:"Perang Aceh: salah satu perang kolonialterlama. Pahlawan: Cut Nyak Dien, Teuku Umar.",explanation:"Perang Aceh (1873-1914): ~40 tahun.\nSalah satu perang terlama melawan kolonialisme.\nPahlawan: Cut Nyak Dien, Teuku Umar, Cut Mutia.\nJawaban: A."},
{question:"Pemilu pertama di Indonesia diselenggarakan pada: ...",options: ["1955 (era Soekarno/demokrasi liberal)","1945","1999","1971","1966"],answer:0,hint:"Pemilu I: 1955. Memilih DPR dan Konstituante.",explanation:"Pemilu pertama: 1955.\nMemilih anggota DPR (29 September) dan Konstituante (15 Desember).\n4 partai besar: PNI, Masyumi, NU, PKI.\nJawaban: A."},
{question:"The Age of Exploration (Abad Penjelajahan) dimulai abad ke-: ...",options: ["15 (1400-an, dimulai oleh Portugis dan Spanyol)","10","20","5","3"],answer:0,hint:"1400-an: Henry the Navigator, Bartolomeu Dias, Vasco da Gama, Columbus.",explanation:"Age of Exploration: abad 15-17.\nPortugis dan Spanyol memimpin.\nHenry the Navigator, Dias, da Gama, Columbus, Magellan.\nJawaban: A."},
]);

appendQuestions('soshum_geografi', [
{question:"Siklus batuan (rock cycle) menghubungkan: ...",options: ["Batuan beku, sedimen, dan metamorf melalui proses geologi","Hanya batuan beku (menurut prinsip dasar; pada konteks konvensional)","Hanya sedimen (secara normatif; dalam batasan konvensional)","Hanya metamorf (dari perspektif akademis; secara fundamental)","Tidak ada hubungan (sesuai klasifikasi umum)"],answer:0,hint:"Rock cycle: igneous ↔ sedimentary ↔ metamorphic. Saling bertransformasi.",explanation:"Siklus batuan: transformasi antar jenis batuan.\nBeku (mendingin) $\\to$ sedimen (erosi/deposisi) $\\to$ metamorf (tekanan/panas) $\\to$ beku (meleleh).\nSiklus terus-menerus.\nJawaban: A."},
{question:"Proyeksi peta yang mempertahankan luas (equal-area): ...",options: ["Proyeksi Mollweide / Peters","Proyeksi Mercator (dalam praktik)","Proyeksi gnomonic (pada dasarnya)","Proyeksi azimuthal (di konteks ini)","Proyeksi stereografik (secara klasik)"],answer:0,hint:"Equal-area: luas akurat, bentuk terdistorsi. Beda dari Mercator (conformal).",explanation:"Proyeksi equal-area: mempertahankan luas relatif.\nMollweide, Peters: equal-area.\nMercator: conformal (arah benar, luas distorsi).\nJawaban: A."},
{question:"Batas lempeng divergen ditandai oleh: ...",options: ["Lempeng bergerak menjauh (mid-ocean ridge, rift valley)","Lempeng bertabrakan (dari sudut pandang klasik; secara literal)","Lempeng bergesekan (dalam literatur standar; menurut prinsip dasar)","Lempeng diam (menurut pandangan mainstream; sesuai paradigma tradisional)","Lempeng menghilang (dalam pengertian luas; menurut pengertian baku)"],answer:0,hint:"Divergen: div= apart. Lempeng terpecah, magma naik.",explanation:"Batas divergen: dua lempeng bergerak menjauh.\nContoh: Mid-Atlantic Ridge.\nMagma naik $\\to$ kerak baru terbentuk.\nJawaban: A."},
{question:"Awan cumulonimbus (Cb) sering menyebabkan: ...",options: ["Hujan lebat, petir, dan badai","Cuaca cerah (menurut definisi standar)","Embun (menurut pengertian baku)","Kabut tipis (sesuai paradigma tradisional)","Salju ringan (menurut prinsip dasar)"],answer:0,hint:"Cumulonimbus: awan konvektif vertikal besar. Badai, petir, granit.",explanation:"Cumulonimbus (Cb): awan konvektif raksasa.\nMenyebabkan: hujan lebat, petir, angin kencang, granit/hujan es.\nBisa juga tornado.\nJawaban: A."},
{question:"Skala Beaufort mengukur: ...",options: ["Kekuatan angin (dari 0=calm hingga 12=hurricane)","Kekuatan gempa (sesuai teori klasik)","Suhu (berdasarkan premis dasar; dari sudut pandang klasik)","Curah hujan (secara terminologis; dalam literatur standar)","Tekanan udara (berdasarkan acuan formal)"],answer:0,hint:"Beaufort: skala angin. 0=tenang, 12=badai.",explanation:"Skala Beaufort: mengukur kecepatan angin.\n0: tenang (calm, <1 km/h).\n12: badai topan/hurricane (>118 km/h).\nDiciptakan oleh Sir Francis Beaufort (1805).\nJawaban: A."},
{question:"Indonesia merupakan negara mega-biodiversitas karena: ...",options: ["Letak geografis tropis, kepulauan, pertemuan zona biogeografi","Hanya satu pulau (secara konseptual; dalam arti sempit)","Iklim dingin (berdasarkan asumsi dasar; menurut definisi standar)","Gurun luas (dalam kerangka teori; menurut pengertian baku)","Dataran tinggi saja (dari sudut pandang klasik)"],answer:0,hint:"Indonesia: tropis + kepulauan + Wallacea = biodiversitas tinggi.",explanation:"Indonesia mega-biodiversitas:\n1. Iklim tropis (energi matahari melimpah).\n2. Kepulauan (isolasi $\\to$ spesiasi).\n3. Zona Wallacea (pertemuan fauna Asia-Australia).\n~17% spesies dunia.\nJawaban: A."},
{question:"Degradasi lahan adalah: ...",options: ["Penurunan kualitas lahan akibat aktivitas manusia atau proses alami","Peningkatan kesuburan (dalam pemahaman konvensional; dalam literatur standar)","Penambahan nutrisi (menurut konsensus ilmiah; sesuai teori klasik)","Pertumbuhan hutan (dalam arti sempit; berdasarkan premis dasar; secara umum)","Peningkatan biodiversitas (menurut definisi standar; berdasarkan asumsi dasar)"],answer:0,hint:"Degradasi: de- = penurunan. Lahan menjadi kurang produktif.",explanation:"Degradasi lahan: penurunan kualitas/produktivitas lahan.\nPenyebab: erosi, salinisasi, pencemaran, deforestasi, over-grazing.\nDampak: desertifikasi, ketahanan pangan terancam.\nJawaban: A."},
{question:"Pembangunan berkelanjutan (sustainable development): ...",options: ["Pembangunan yang memenuhi kebutuhan saat ini tanpa mengorbankan kemampuan generasi mendatang","Eksploitasi total (dalam konteks umum; berdasarkan teori dasar; dalam kerangka teori; menurut pengertian baku)","Tanpa pertumbuhan (berdasarkan referensi umum; secara konseptual; berdasarkan asumsi dasar; menurut definisi standar)","Hanya untuk negara maju (menurut kerangka berpikir umum; berdasarkan asumsi dasar; dalam pemahaman konvensional)","Anti-teknologi (sesuai teori klasik; dalam kerangka teori; berdasarkan teori dasar; menurut konsensus ilmiah)"],answer:0,hint:"Brundtland Report 1987: 'development that meets present needs without compromising future.'",explanation:"Pembangunan berkelanjutan (WCED, 1987):\nMemenuhi kebutuhan saat ini tanpa mengorbankan generasi mendatang.\n3 pilar: ekonomi, sosial, lingkungan.\nSDGs: 17 tujuan PBB.\nJawaban: A."},
{question:"Jenis peta berdasarkan isi: peta tematik menampilkan: ...",options: ["Tema/informasi khusus (curah hujan, kepadatan penduduk, geologi)","Semua informasi umum (dari perspektif akademis; secara fundamental)","Hanya batas negara (sesuai klasifikasi umum; dalam pemahaman konvensional)","Hanya jalan (berdasarkan teori dasar; menurut konsensus ilmiah)","Hanya sungai (secara konseptual; dalam arti sempit)"],answer:0,hint:"Tematik: tema khusus. Topografi: bentuk permukaan. Choropleth: tematik dengan warna.",explanation:"Peta tematik: menampilkan tema/fenomena tertentu.\nContoh: peta curah hujan, peta geologi, peta kepadatan penduduk.\nBerbeda dari peta topografi (bentuk muka bumi).\nJawaban: A."},
{question:"Teori Wegener tentang pergeseran benua (continental drift): ...",options: ["Benua-benua dahulu menyatu (Pangaea) lalu terpisah seiring waktu","Benua selalu di posisi sekarang (pada konteks konvensional)","Benua dibuat oleh manusia (dalam batasan konvensional)","Benua semakin besar (secara fundamental; berdasarkan referensi umum)","Benua menghilang (dalam pemahaman konvensional; menurut kerangka berpikir umum)"],answer:0,hint:"Wegener (1912): Pangaea $\\to$ benua-benua terpisah. Bukti: fossil, formasi batuan, iklim.",explanation:"Continental drift (Alfred Wegener, 1912):\nSemua benua pernah menyatu sebagai Pangaea (~200 juta tahun lalu).\nBukti: fosil serupa, formasi batuan cocok, bukti iklim masa lalu.\nDiterima setelah teori lempeng tektonik (1960-an).\nJawaban: A."},
]);

appendQuestions('tps_logika', [
{question:"Jika tidak hujan, maka piknik. Hari ini tidak piknik. Kesimpulan: ...",options: ["Hari ini hujan (modus tollens)","Hari ini tidak hujan (pada dasarnya)","Hari ini piknik (dalam pengertian luas)","Tidak ada kesimpulan (secara klasik)","Mungkin hujan (dalam konteks umum)"],answer:0,hint:"~H$\\to$PP. ~P. ∴ ~~H = H. Hari ini hujan.",explanation:"Premis 1: ~H $\\to$ P.\nPremis 2: ~P.\nModus tollens: ~P $\\to$ ~~H = H.\nKesimpulan: Hari ini hujan.\nJawaban: A."},
{question:"Berapa angka berikutnya: 2, 6, 18, 54, ...?",options: ["162 (deret geometri r=3)","108","72","216","81"],answer:0,hint:"6/2=3. 18/6=3. 54/18=3. Rasio=3. 54$\\times$3=162.",explanation:"Deret geometri dengan rasio r=3.\n2, 6, 18, 54, 162, ...\n54 $\\times$ 3 = 162.\nJawaban: A."},
{question:"Jika A $\\subset$ B dan x $\\in$ A, maka: ...",options: ["x $\\in$ B (karena A subset B)","x $\\notin$ B","x = B (berdasarkan acuan formal)","A = B (secara konvensional)","Tidak bisa disimpulkan"],answer:0,hint:"Subset: semua elemen A ada di B. x di A $\\to$ x pasti di B.",explanation:"A $\\subset$ B: semua elemen A juga elemen B.\nx $\\in$ A $\\to$ x $\\in$ B.\nJawaban: A."},
{question:"Berapa segi empat (termasuk persegi) dalam grid 3$\\times$3?",options: ["36","9","16","25","30"],answer:0,hint:"1$\\times$1: 9, 2$\\times$2: 4, 3$\\times$3: 1. Tapi termasuk persegi panjang: total lebih dari itu.",explanation:"Segiempat dalam grid m$\\times$nn: C(m+1,2)$\\times$CC(n+1,2).\nGrid 3$\\times$3: C(4,2)$\\times$CC(4,2) = 6$\\times$6 = 36.\nJawaban: A."},
{question:"Jika 'Beberapa dokter adalah wanita' dan 'Semua wanita adalah manusia', maka: ...",options: ["Beberapa dokter adalah manusia","Semua dokter adalah wanita (menurut standar)","Semua manusia adalah dokter (pada prinsipnya)","Tidak ada dokter manusia (dalam teori)","Semua wanita adalah dokter (secara umum)"],answer:0,hint:"Beberapa D=W. Semua W=M. Maka beberapa D=M.",explanation:"Beberapa D $\\in$ W.\nSemua W $\\subseteq$ M.\n∴ Beberapa D $\\in$ M.\nBeberapa dokter adalah manusia.\nJawaban: A."},
]);

appendQuestions('tps_spasial', [
{question:"Berapa kubus kecil bercat 1 sisi pada kubus 3$\\times$3$\\times$3 yang dicat?",options: ["6 (1 per face pusat)","8","12","24","1"],answer:0,hint:"Kubus yang hanya bercat 1 sisi = kubus di pusat setiap face. 6 face $\\times$ 1 = 6.",explanation:"Kubus 3$\\times$3$\\times$3 dicat:\n3 sisi (sudut): 8.\n2 sisi (tepi): 12.\n1 sisi (pusat face): 6 (1 per face $\\times$ 6 face).\n0 sisi (pusat): 1.\nJawaban: A."},
{question:"Luas lingkaran r=14 cm ($\\pi$=22/7): ...",options: ["616 cm^2","308 cm^2","154 cm^2","44 cm^2","88 cm^2"],answer:0,hint:"L = $\\pi$r$r^2$ = 22/7 $\\times$ 196 = 616.",explanation:"L = $\\pi$r$r^2$ = 22/7 $\\times$ 1$4^2$ = 22/7 $\\times$ 196 = 616 c$m^2$.\nJawaban: A."},
{question:"Volume kerucut r=6, t=8: ...",options: ["96$\\pi$ c$m^3$","288$\\pi$ c$m^3$","48$\\pi$ c$m^3$","192$\\pi$ c$m^3$","72$\\pi$ c$m^3$"],answer:0,hint:"V = 1/3 $\\pi$r$r^2$t = 1/3 $\\times$ $\\pi$ $\\times$ 36 $\\times$ 8 = 96$\\pi$.",explanation:"V = 1/3 $\\times$ $\\pi$ $\\times$ $r^2$ $\\times$ t = 1/3 $\\times$ $\\pi$ $\\times$ 36 $\\times$ 8 = 96$\\pi$ c$m^3$.\nJawaban: A."},
{question:"Keliling lingkaran r=21 cm ($\\pi$=22/7): ...",options: ["132 cm","66 cm","42 cm","264 cm","44 cm"],answer:0,hint:"K = 2$\\pi$rr = 2 $\\times$ 22/7 $\\times$ 21 = 132.",explanation:"K = 2$\\pi$rr = 2 $\\times$ 22/7 $\\times$ 21 = 132 cm.\nJawaban: A."},
{question:"Diagonal sisi balok 3$\\times$4$\\times$5 (pada sisi 3$\\times$4): ...",options: ["5 ($\\sqrt{9+16}$)","7","$\\sqrt$50","12","3"],answer:0,hint:"Diagonal sisi = $\\sqrt{3^2+4^2}$ = $\\sqrt$25 = 5.",explanation:"Diagonal sisi 3$\\times$4: $\\sqrt{3^2+4^2}$ = $\\sqrt{9+16}$ = $\\sqrt$25 = 5.\nJawaban: A."},
]);

appendQuestions('tkd_indo', [
{question:"Kata 'justru' bermakna: ...",options: ["Malah, sebaliknya (berlawanan dari yang diharapkan)","Karena (secara konvensional; dalam pengertian luas)","Jadi (pada konteks konvensional; dalam definisi teknis)","Oleh sebab itu (dalam batasan konvensional)","Namun (secara fundamental; berdasarkan referensi umum)"],answer:0,hint:"Justru: malah, sebaliknya dari dugaan.",explanation:"Justru: menyatakan kebalikan dari yang diharapkan.\nContoh: 'Justru dia yang membantu paling banyak.'\nJawaban: A."},
{question:"Kalimat baku yang benar: ...",options: ["Mereka bermain di halaman.","Mereka bermain dihalaman.","Mereka bermain kehalaman.","Mereka main di halaman. (secara umum)","Mereka bermain halaman. (secara klasik)"],answer:0,hint:"'Di' preposisi $\\to$ terpisah. + halaman = lokasi.",explanation:"'Di halaman': preposisi + keterangan tempat $\\to$ terpisah.\n'Bermain' lebih baku dari 'main'.\nJawaban: A."},
{question:"Majas ironi dalam kalimat: ...",options: ["'Rajin sekali kamu, sudah jam 12 baru bangun!' (mengejek dengan pujian)","'Dia secepat kilat' (menurut pengertian baku; berdasarkan acuan formal)","'Hatinya batu' (sesuai paradigma tradisional; secara konvensional)","'Jutaan orang hadir' (menurut prinsip dasar; pada konteks konvensional)","'Matahari tersenyum' (secara normatif; dalam batasan konvensional)"],answer:0,hint:"Ironi: mengatakan kebalikan dari maksud sebenarnya.",explanation:"Ironi: menyatakan sesuatu yang berlawanan dengan fakta.\n'Rajin sekali' padahal bangun siang = menyindir.\nJawaban: A."},
{question:"Sinonim 'kronik' dalam konteks penyakit: ...",options: ["Menahun (berlangsung lama)","Mendadak (berdasarkan premis dasar)","Cepat (secara terminologis)","Ringan (berdasarkan acuan formal)","Sembuh (secara konvensional)"],answer:0,hint:"Kronik (chronic) = menahun, berlangsung lama. Bukan akut.",explanation:"Kronik/kronis: berlangsung lama, menahun.\nLawan: akut (mendadak, singkat).\nContoh: diabetes kronis.\nJawaban: A."},
{question:"Bentuk baku 'merubah' yang benar: ...",options: ["Mengubah (dari kata dasar 'ubah', bukan 'rubah')","Merubah (berdasarkan asumsi dasar; menurut definisi standar)","Merobah (dalam kerangka teori; menurut pengertian baku)","Meng-ubah (dari sudut pandang klasik)","Merombak (dalam literatur standar; menurut prinsip dasar)"],answer:0,hint:"Dasar: ubah. meng- + ubah = mengubah. Rubah = hewan!",explanation:"Kata dasar: ubah.\nmeng- + ubah $\\to$ mengubah.\n'Merubah' salah (me- + rubah? rubah = fox!).\nJawaban: A."},
]);

appendQuestions('tkd_eng', [
{question:"The word 'plethora' means: ...",options: ["An excess or overabundance","A shortage (menurut konsensus ilmiah)","A balance (dalam arti sempit)","A deficit (menurut definisi standar)","An absence (menurut pengertian baku)"],answer:0,hint:"Plethora = too much, excess. 'A plethora of options.'",explanation:"Plethora: an excessive amount; overabundance.\n'There was a plethora of food at the party.'\nJawaban: A."},
{question:"Choose correct sentence: 'The number of students ___ increasing.'",options: ["is (the number = singular)","are (berdasarkan referensi umum)","were (menurut kerangka berpikir umum)","have been (sesuai teori klasik)","am (berdasarkan premis dasar)"],answer:0,hint:"'The number of' = singular $\\to$ 'is'. 'A number of' = plural $\\to$ 'are'.",explanation:"'The number of' $\\to$ singular verb (is).\n'A number of' $\\to$ plural verb (are).\n'The number of students is increasing.'\nJawaban: A."},
{question:"'Juxtaposition' in literature is used to: ...",options: ["Place two contrasting elements side by side for comparison","Create alliteration (sesuai klasifikasi umum)","Make rhymes (berdasarkan teori dasar; menurut konsensus ilmiah)","Write dialogue (secara konseptual; dalam arti sempit)","Add footnotes (berdasarkan asumsi dasar; menurut definisi standar)"],answer:0,hint:"Juxtaposition: placing contrasts together to highlight differences.",explanation:"Juxtaposition: placing two contrasting elements side by side.\nPurpose: highlight differences, create irony, or deepen meaning.\nExample: light/dark imagery.\nJawaban: A."},
{question:"The prefix 'anti-' means: ...",options: ["Against / opposed to","Before (dalam batasan konvensional)","After (secara fundamental)","With (dalam pemahaman konvensional)","Under (menurut konsensus ilmiah)"],answer:0,hint:"Anti = against. Antibody, anti-clockwise, antibiotic.",explanation:"Anti-: against, opposed to.\nExamples: antisocial, antibody, antithesis, antidote.\nJawaban: A."},
{question:"'Whom should I contact?' is correct because: ...",options: ["'Whom' is the object of the verb 'contact' (I contact HIM/HER)","'Whom' is the subject (dalam pengertian luas; dari perspektif akademis)","'Whom' is a conjunction (dalam definisi teknis)","It doesn't matter (dalam konteks umum; berdasarkan teori dasar)","'Who' is always wrong (berdasarkan referensi umum)"],answer:0,hint:"I contact [whom?] = I contact HIM. Object $\\to$ whom.",explanation:"Test: substitute he/him.\n'I should contact HIM/HER' $\\to$ object $\\to$ whom.\nIf 'HE/SHE should contact' $\\to$ subject $\\to$ who.\nJawaban: A."},
]);
