// BATCH 37 — SUPPLEMENT: 100 extra questions across Soshum + TKD + TPS subjects
appendQuestions('soshum_ekonomi', [
{question:"Hukum penawaran: harga naik → ...",options:["Penawaran naik (ceteris paribus)","Penawaran turun","Tetap","Tidak ada hubungan","Penawaran hilang"],answer:0,hint:"Supply: price ↑ → quantity supplied ↑.",explanation:"Hukum penawaran: hubungan searah harga dan jumlah yang ditawarkan.\nHarga naik → produsen ingin menjual lebih banyak.\nJawaban: A."},
{question:"Harga keseimbangan (equilibrium) terjadi saat: ...",options:["Permintaan = penawaran (Qd = Qs)","Permintaan > penawaran","Penawaran > permintaan","Harga nol","Tidak ada transaksi"],answer:0,hint:"Equilibrium: kurva D dan S bertemu. Qd=Qs.",explanation:"Harga keseimbangan: titik potong kurva permintaan dan penawaran.\nQd = Qs, tidak ada kelebihan/kekurangan.\nJawaban: A."},
{question:"Fungsi uang: alat tukar, satuan hitung, dan: ...",options:["Penyimpan nilai (store of value)","Alat transportasi","Alat komunikasi","Bahan bangunan","Alat masak"],answer:0,hint:"Money: medium of exchange, unit of account, store of value.",explanation:"Fungsi uang:\n1. Alat tukar (medium of exchange).\n2. Satuan hitung (unit of account).\n3. Penyimpan nilai (store of value).\n4. Standar pembayaran tunda.\nJawaban: A."},
{question:"Deflasi adalah: ...",options:["Penurunan tingkat harga umum secara terus-menerus","Kenaikan harga","Harga tetap","Inflasi besar","Stagflasi"],answer:0,hint:"Deflasi: kebalikan inflasi. Harga turun terus-menerus.",explanation:"Deflasi: penurunan tingkat harga umum yang berkelanjutan.\nBisa berbahaya: konsumen menunda belanja → produksi turun → PHK.\nJawaban: A."},
{question:"Marginal utility (utilitas marjinal) menurun sesuai: ...",options:["Hukum utilitas marjinal yang menurun (tambahan kepuasan menurun)","Hukum penawaran","Hukum Newton","Hukum Boyle","Hukum Ohm"],answer:0,hint:"Diminishing marginal utility: semakin banyak konsumsi, tambahan kepuasan semakin kecil.",explanation:"Hukum utilitas marjinal menurun:\nUnit tambahan memberikan kepuasan (utility) yang semakin kecil.\nContoh: es krim ke-1 sangat nikmat, ke-5 biasa saja.\nJawaban: A."},
{question:"Bank umum menciptakan uang giral melalui: ...",options:["Pemberian kredit (credit creation)","Pencetakan uang kertas","Menambang emas","Menerbitkan saham","Menjual obligasi saja"],answer:0,hint:"Bank: terima simpanan → salurkan kredit → uang beredar berlipat (money multiplier).",explanation:"Uang giral diciptakan melalui kredit bank.\nDepositor menyimpan → bank meminjamkan → penerima menyimpan di bank lain → dipinjamkan lagi.\nMoney multiplier: 1/reserve ratio.\nJawaban: A."},
{question:"Perdagangan bebas (free trade) menurut teori: ...",options:["Meningkatkan efisiensi dan kesejahteraan melalui spesialisasi","Merugikan semua","Hanya untungkan negara kaya","Menghapus semua industri","Tidak ada efek"],answer:0,hint:"Free trade: comparative advantage → spesialisasi → efisiensi → kesejahteraan meningkat.",explanation:"Free trade: menghilangkan hambatan perdagangan.\nTeori: setiap negara berspesialisasi → efisiensi meningkat → semua diuntungkan.\nKritik: ketimpangan, infant industry argument.\nJawaban: A."},
{question:"PDB per kapita dihitung dengan: ...",options:["PDB ÷ jumlah penduduk","PDB × penduduk","PDB + penduduk","PDB - penduduk","PDB × luas wilayah"],answer:0,hint:"Per kapita = per orang = PDB/populasi.",explanation:"PDB per kapita = PDB/jumlah penduduk.\nIndikator standar hidup rata-rata.\nKelemahan: tidak menunjukkan distribusi.\nJawaban: A."},
{question:"Stagflasi adalah kombinasi: ...",options:["Stagnasi ekonomi + inflasi tinggi (pengangguran tinggi + harga naik)","Pertumbuhan + deflasi","Boom + harga turun","Resesi + deflasi","Pertumbuhan pesat"],answer:0,hint:"Stagflasi: stagnasi + inflasi. Skenario terburuk.",explanation:"Stagflasi: ekonomi stagnan + inflasi tinggi.\nPengangguran tinggi + harga naik.\nSulit diatasi: kebijakan untuk satu masalah memperburuk yang lain.\nJawaban: A."},
{question:"Subsidi pemerintah bertujuan: ...",options:["Menurunkan harga barang/jasa tertentu agar terjangkau masyarakat","Menaikkan harga","Mengurangi produksi","Menghapus permintaan","Meningkatkan inflasi"],answer:0,hint:"Subsidi: bantuan pemerintah agar harga lebih murah. Contoh: BBM, listrik, pupuk.",explanation:"Subsidi: bantuan pemerintah untuk menurunkan harga.\nContoh: subsidi BBM, listrik, pupuk, beras.\nTujuan: akses masyarakat, pemerataan.\nJawaban: A."},
]);

appendQuestions('soshum_sosiologi', [
{question:"Asimilasi adalah: ...",options:["Percampuran dua budaya sehingga budaya asli melebur/hilang","Percampuran tanpa kehilangan identitas","Penolakan budaya lain","Isolasi budaya","Konflik budaya"],answer:0,hint:"Asimilasi: budaya melebur jadi satu. Beda dari akulturasi (kedua tetap ada).",explanation:"Asimilasi: dua budaya bercampur, salah satu/keduanya kehilangan identitas asli.\nBerbeda dari akulturasi (kedua budaya tetap ada).\nJawaban: A."},
{question:"Role conflict (konflik peran) terjadi ketika: ...",options:["Individu memiliki beberapa peran yang saling bertentangan","Hanya satu peran","Tidak ada peran","Semua peran selaras","Peran hilang"],answer:0,hint:"Contoh: ibu bekerja → peran sebagai ibu vs karyawan kadang konflik.",explanation:"Konflik peran: individu menghadapi tuntutan yang saling bertentangan dari beberapa peran.\nContoh: guru yang juga orang tua murid di sekolah yang sama.\nJawaban: A."},
{question:"Lembaga pendidikan berfungsi: ...",options:["Sosialisasi pengetahuan, keterampilan, nilai, dan norma","Hanya mengajar membaca","Hanya olahraga","Hanya ibadah","Hanya hiburan"],answer:0,hint:"Pendidikan: transfer knowledge, skills, values ke generasi berikutnya.",explanation:"Fungsi lembaga pendidikan:\n1. Sosialisasi (transfer nilai/norma).\n2. Transmisi pengetahuan.\n3. Seleksi dan alokasi.\n4. Integrasi sosial.\n5. Inovasi.\nJawaban: A."},
{question:"Masyarakat multikultural Indonesia dijamin oleh: ...",options:["Bhinneka Tunggal Ika dan UUD 1945","Hanya satu suku","Tidak ada jaminan","Hukum internasional saja","Perjanjian bilateral"],answer:0,hint:"Bhinneka Tunggal Ika: berbeda-beda tetapi tetap satu.",explanation:"Bhinneka Tunggal Ika: berbeda-beda tetapi tetap satu jua.\nUUD 1945 Pasal 18B, 28I, 32: mengakui keragaman.\nIndonesia: 300+ suku, 700+ bahasa.\nJawaban: A."},
{question:"Teori interaksionisme simbolik (Mead, Blumer): ...",options:["Makna diciptakan melalui interaksi dan interpretasi simbol","Struktur menentukan segalanya","Gen menentukan perilaku","Ekonomi menentukan budaya","Tidak ada makna"],answer:0,hint:"Symbolic interactionism: manusia bertindak berdasarkan makna yang diberikan pada simbol.",explanation:"Interaksionisme simbolik (George Herbert Mead):\nManusia bertindak terhadap sesuatu berdasarkan makna.\nMakna muncul dari interaksi sosial.\nMakna dimodifikasi melalui interpretasi.\nJawaban: A."},
{question:"Urbanisasi berlebihan menyebabkan: ...",options:["Over-urbanization (pemukiman kumuh, pengangguran, kemacetan, kriminalitas)","Kota kosong","Desa padat","Tidak ada masalah","Keseimbangan sempurna"],answer:0,hint:"Urbanisasi tak terkendali: slum, traffic, crime, pollution, inequality.",explanation:"Dampak negatif urbanisasi berlebihan:\nPermukiman kumuh (slum).\nPengangguran.\nKemacetan.\nKriminalitas.\nPolusi.\nKesenjangan sosial.\nJawaban: A."},
{question:"Korupsi menurut sosiologi merupakan bentuk: ...",options:["Penyimpangan sosial dan patologi sosial","Perilaku normal","Tradisi budaya","Hak istimewa","Kewajiban sosial"],answer:0,hint:"Korupsi = penyimpangan dari norma hukum dan moral.",explanation:"Korupsi: penyalahgunaan kekuasaan untuk kepentingan pribadi.\nPatologi sosial: 'penyakit' masyarakat.\nFaktor: lemahnya kontrol, budaya permisif, ketimpangan.\nJawaban: A."},
{question:"Status ascribed vs achieved: ...",options:["Ascribed: diperoleh sejak lahir (jenis kelamin, ras); Achieved: diperoleh melalui usaha (pendidikan, jabatan)","Sama saja","Ascribed = usaha","Achieved = sejak lahir","Tidak ada perbedaan"],answer:0,hint:"Ascribed: given at birth. Achieved: earned through effort.",explanation:"Status ascribed: diperoleh sejak lahir, tanpa usaha.\nContoh: jenis kelamin, ras, kebangsawanan.\nStatus achieved: diperoleh melalui usaha/prestasi.\nContoh: pendidikan, karier, jabatan.\nJawaban: A."},
{question:"Social capital menurut Robert Putnam: ...",options:["Jaringan, norma, dan kepercayaan yang memfasilitasi kerja sama","Modal uang","Investasi saham","Tabungan bank","Modal fisik"],answer:0,hint:"Putnam: social capital = trust + norms + networks.",explanation:"Social capital (Putnam): fitur kehidupan sosial—jaringan, norma, kepercayaan—yang memungkinkan partisipan bertindak lebih efektif bersama.\nJawaban: A."},
{question:"Feminisme liberal menekankan: ...",options:["Kesetaraan hak dan kesempatan perempuan dalam sistem yang ada (hukum, pendidikan)","Revolusi total","Penghapusan keluarga","Separasi gender","Supremasi gender"],answer:0,hint:"Liberal feminism: kesetaraan melalui reformasi hukum dan kebijakan.",explanation:"Feminisme liberal: kesetaraan gender melalui reformasi hukum, kebijakan, dan akses.\nFokus: hak pilih, pendidikan, pekerjaan, gaji setara.\nBeda dari radikal (perubahan struktur fundamental).\nJawaban: A."},
]);

appendQuestions('soshum_sejarah', [
{question:"Sistem VOC disebut monopoli perdagangan karena: ...",options:["VOC menjadi satu-satunya pembeli dan penjual rempah","VOC membagi pasar","VOC hanya ekspor","VOC hanya impor","VOC tidak berdagang"],answer:0,hint:"Monopoli: hanya satu pelaku pasar. VOC mengendalikan seluruh perdagangan rempah.",explanation:"VOC memonopoli perdagangan rempah Nusantara.\nMelarang petani menjual ke pedagang lain.\nMengatur harga sepihak.\nJawaban: A."},
{question:"Pancasila dirumuskan melalui sidang BPUPKI yang berlangsung pada: ...",options:["29 Mei - 1 Juni 1945 dan 10-17 Juli 1945","17 Agustus 1945","28 Oktober 1928","20 Mei 1908","1 September 1939"],answer:0,hint:"BPUPKI: dokuritsu junbi cosakai. Sidang I: 29 Mei-1 Jun. Sidang II: 10-17 Jul.",explanation:"BPUPKI: Badan Penyelidik Usaha Persiapan Kemerdekaan.\nSidang I (29 Mei-1 Juni 1945): pidato Soekarno 1 Juni (Hari Lahir Pancasila).\nSidang II (10-17 Juli 1945): UUD.\nJawaban: A."},
{question:"Peradaban Mesopotamia berada di wilayah: ...",options:["Antara Sungai Tigris dan Efrat (Irak modern)","Sungai Nil","Sungai Yangtze","Sungai Indus","Sungai Amazon"],answer:0,hint:"Meso=tengah. Potamos=sungai. Di antara dua sungai = Irak.",explanation:"Mesopotamia: 'tanah di antara sungai' (Tigris & Efrat).\nIrak modern.\nPeradaban awal: Sumeria, Akkad, Babilonia, Asyur.\nPenemuan: tulisan paku, roda, kode hukum.\nJawaban: A."},
{question:"Runtuhnya Tembok Berlin terjadi pada: ...",options:["9 November 1989","17 Agustus 1945","4 Juli 1776","1 Januari 2000","11 September 2001"],answer:0,hint:"Fall of the Berlin Wall: 9 November 1989. Simbol akhir Perang Dingin.",explanation:"9 November 1989: Tembok Berlin runtuh.\nMemisahkan Berlin Barat dan Timur sejak 1961.\nSimbol akhir Perang Dingin.\nReunifikasi Jerman: 3 Oktober 1990.\nJawaban: A."},
{question:"Perang Dunia I (1914-1918) dipicu oleh: ...",options:["Pembunuhan Archduke Franz Ferdinand di Sarajevo + aliansi + nasionalisme","Serangan Pearl Harbor","Invasi Polandia","Revolusi Prancis","Perang Salib"],answer:0,hint:"28 Juni 1914: Gavrilo Princip menembak Franz Ferdinand. Domino aliansi.",explanation:"Penyebab langsung: pembunuhan Archduke Franz Ferdinand (Austria-Hungaria) oleh Gavrilo Princip di Sarajevo (28 Juni 1914).\nPenyebab tidak langsung: militarisme, aliansi, imperialisme, nasionalisme (MAIN).\nJawaban: A."},
{question:"Konferensi Meja Bundar (KMB) 1949 menghasilkan: ...",options:["Pengakuan kedaulatan RI oleh Belanda (27 Desember 1949)","Perang baru","Penjajahan baru","Pembentukan PBB","Sumpah Pemuda"],answer:0,hint:"KMB Den Haag: Belanda mengakui kedaulatan RIS.",explanation:"KMB (23 Agustus - 2 November 1949):\nDi Den Haag, Belanda.\nHasil: pengakuan kedaulatan Indonesia.\n27 Desember 1949: penyerahan kedaulatan.\nJawaban: A."},
{question:"Kekaisaran Romawi runtuh (Barat) pada tahun: ...",options:["476 M (jatuhnya Roma Barat)","1453 M","1 M","1000 M","1776 M"],answer:0,hint:"476 M: Romulus Augustulus digulingkan. Akhir Romawi Barat. Awal Abad Pertengahan.",explanation:"476 M: Kekaisaran Romawi Barat runtuh.\nRomulus Augustulus (kaisar terakhir) digulingkan oleh Odoacer.\nRomawi Timur (Bizantium): bertahan hingga 1453.\nJawaban: A."},
{question:"Perang Aceh melawan Belanda berlangsung: ...",options:["1873-1914 (~40 tahun, perang terlama di Nusantara)","1825-1830","1945-1949","1905-1910","1900-1905"],answer:0,hint:"Perang Aceh: salah satu perang kolonialterlama. Pahlawan: Cut Nyak Dien, Teuku Umar.",explanation:"Perang Aceh (1873-1914): ~40 tahun.\nSalah satu perang terlama melawan kolonialisme.\nPahlawan: Cut Nyak Dien, Teuku Umar, Cut Mutia.\nJawaban: A."},
{question:"Pemilu pertama di Indonesia diselenggarakan pada: ...",options:["1955 (era Soekarno/demokrasi liberal)","1945","1999","1971","1966"],answer:0,hint:"Pemilu I: 1955. Memilih DPR dan Konstituante.",explanation:"Pemilu pertama: 1955.\nMemilih anggota DPR (29 September) dan Konstituante (15 Desember).\n4 partai besar: PNI, Masyumi, NU, PKI.\nJawaban: A."},
{question:"The Age of Exploration (Abad Penjelajahan) dimulai abad ke-: ...",options:["15 (1400-an, dimulai oleh Portugis dan Spanyol)","10","20","5","3"],answer:0,hint:"1400-an: Henry the Navigator, Bartolomeu Dias, Vasco da Gama, Columbus.",explanation:"Age of Exploration: abad 15-17.\nPortugis dan Spanyol memimpin.\nHenry the Navigator, Dias, da Gama, Columbus, Magellan.\nJawaban: A."},
]);

appendQuestions('soshum_geografi', [
{question:"Siklus batuan (rock cycle) menghubungkan: ...",options:["Batuan beku, sedimen, dan metamorf melalui proses geologi","Hanya batuan beku","Hanya sedimen","Hanya metamorf","Tidak ada hubungan"],answer:0,hint:"Rock cycle: igneous ↔ sedimentary ↔ metamorphic. Saling bertransformasi.",explanation:"Siklus batuan: transformasi antar jenis batuan.\nBeku (mendingin) → sedimen (erosi/deposisi) → metamorf (tekanan/panas) → beku (meleleh).\nSiklus terus-menerus.\nJawaban: A."},
{question:"Proyeksi peta yang mempertahankan luas (equal-area): ...",options:["Proyeksi Mollweide / Peters","Proyeksi Mercator","Proyeksi gnomonic","Proyeksi azimuthal","Proyeksi stereografik"],answer:0,hint:"Equal-area: luas akurat, bentuk terdistorsi. Beda dari Mercator (conformal).",explanation:"Proyeksi equal-area: mempertahankan luas relatif.\nMollweide, Peters: equal-area.\nMercator: conformal (arah benar, luas distorsi).\nJawaban: A."},
{question:"Batas lempeng divergen ditandai oleh: ...",options:["Lempeng bergerak menjauh (mid-ocean ridge, rift valley)","Lempeng bertabrakan","Lempeng bergesekan","Lempeng diam","Lempeng menghilang"],answer:0,hint:"Divergen: div= apart. Lempeng terpecah, magma naik.",explanation:"Batas divergen: dua lempeng bergerak menjauh.\nContoh: Mid-Atlantic Ridge.\nMagma naik → kerak baru terbentuk.\nJawaban: A."},
{question:"Awan cumulonimbus (Cb) sering menyebabkan: ...",options:["Hujan lebat, petir, dan badai","Cuaca cerah","Embun","Kabut tipis","Salju ringan"],answer:0,hint:"Cumulonimbus: awan konvektif vertikal besar. Badai, petir, granit.",explanation:"Cumulonimbus (Cb): awan konvektif raksasa.\nMenyebabkan: hujan lebat, petir, angin kencang, granit/hujan es.\nBisa juga tornado.\nJawaban: A."},
{question:"Skala Beaufort mengukur: ...",options:["Kekuatan angin (dari 0=calm hingga 12=hurricane)","Kekuatan gempa","Suhu","Curah hujan","Tekanan udara"],answer:0,hint:"Beaufort: skala angin. 0=tenang, 12=badai.",explanation:"Skala Beaufort: mengukur kecepatan angin.\n0: tenang (calm, <1 km/h).\n12: badai topan/hurricane (>118 km/h).\nDiciptakan oleh Sir Francis Beaufort (1805).\nJawaban: A."},
{question:"Indonesia merupakan negara mega-biodiversitas karena: ...",options:["Letak geografis tropis, kepulauan, pertemuan zona biogeografi","Hanya satu pulau","Iklim dingin","Gurun luas","Dataran tinggi saja"],answer:0,hint:"Indonesia: tropis + kepulauan + Wallacea = biodiversitas tinggi.",explanation:"Indonesia mega-biodiversitas:\n1. Iklim tropis (energi matahari melimpah).\n2. Kepulauan (isolasi → spesiasi).\n3. Zona Wallacea (pertemuan fauna Asia-Australia).\n~17% spesies dunia.\nJawaban: A."},
{question:"Degradasi lahan adalah: ...",options:["Penurunan kualitas lahan akibat aktivitas manusia atau proses alami","Peningkatan kesuburan","Penambahan nutrisi","Pertumbuhan hutan","Peningkatan biodiversitas"],answer:0,hint:"Degradasi: de- = penurunan. Lahan menjadi kurang produktif.",explanation:"Degradasi lahan: penurunan kualitas/produktivitas lahan.\nPenyebab: erosi, salinisasi, pencemaran, deforestasi, over-grazing.\nDampak: desertifikasi, ketahanan pangan terancam.\nJawaban: A."},
{question:"Pembangunan berkelanjutan (sustainable development): ...",options:["Pembangunan yang memenuhi kebutuhan saat ini tanpa mengorbankan kemampuan generasi mendatang","Eksploitasi total","Tanpa pertumbuhan","Hanya untuk negara maju","Anti-teknologi"],answer:0,hint:"Brundtland Report 1987: 'development that meets present needs without compromising future.'",explanation:"Pembangunan berkelanjutan (WCED, 1987):\nMemenuhi kebutuhan saat ini tanpa mengorbankan generasi mendatang.\n3 pilar: ekonomi, sosial, lingkungan.\nSDGs: 17 tujuan PBB.\nJawaban: A."},
{question:"Jenis peta berdasarkan isi: peta tematik menampilkan: ...",options:["Tema/informasi khusus (curah hujan, kepadatan penduduk, geologi)","Semua informasi umum","Hanya batas negara","Hanya jalan","Hanya sungai"],answer:0,hint:"Tematik: tema khusus. Topografi: bentuk permukaan. Choropleth: tematik dengan warna.",explanation:"Peta tematik: menampilkan tema/fenomena tertentu.\nContoh: peta curah hujan, peta geologi, peta kepadatan penduduk.\nBerbeda dari peta topografi (bentuk muka bumi).\nJawaban: A."},
{question:"Teori Wegener tentang pergeseran benua (continental drift): ...",options:["Benua-benua dahulu menyatu (Pangaea) lalu terpisah seiring waktu","Benua selalu di posisi sekarang","Benua dibuat oleh manusia","Benua semakin besar","Benua menghilang"],answer:0,hint:"Wegener (1912): Pangaea → benua-benua terpisah. Bukti: fossil, formasi batuan, iklim.",explanation:"Continental drift (Alfred Wegener, 1912):\nSemua benua pernah menyatu sebagai Pangaea (~200 juta tahun lalu).\nBukti: fosil serupa, formasi batuan cocok, bukti iklim masa lalu.\nDiterima setelah teori lempeng tektonik (1960-an).\nJawaban: A."},
]);

appendQuestions('tps_logika', [
{question:"Jika tidak hujan, maka piknik. Hari ini tidak piknik. Kesimpulan: ...",options:["Hari ini hujan (modus tollens)","Hari ini tidak hujan","Hari ini piknik","Tidak ada kesimpulan","Mungkin hujan"],answer:0,hint:"~H→P. ~P. ∴ ~~H = H. Hari ini hujan.",explanation:"Premis 1: ~H → P.\nPremis 2: ~P.\nModus tollens: ~P → ~~H = H.\nKesimpulan: Hari ini hujan.\nJawaban: A."},
{question:"Berapa angka berikutnya: 2, 6, 18, 54, ...?",options:["162 (deret geometri r=3)","108","72","216","81"],answer:0,hint:"6/2=3. 18/6=3. 54/18=3. Rasio=3. 54×3=162.",explanation:"Deret geometri dengan rasio r=3.\n2, 6, 18, 54, 162, ...\n54 × 3 = 162.\nJawaban: A."},
{question:"Jika A ⊂ B dan x ∈ A, maka: ...",options:["x ∈ B (karena A subset B)","x ∉ B","x = B","A = B","Tidak bisa disimpulkan"],answer:0,hint:"Subset: semua elemen A ada di B. x di A → x pasti di B.",explanation:"A ⊂ B: semua elemen A juga elemen B.\nx ∈ A → x ∈ B.\nJawaban: A."},
{question:"Berapa segi empat (termasuk persegi) dalam grid 3×3?",options:["36","9","16","25","30"],answer:0,hint:"1×1: 9, 2×2: 4, 3×3: 1. Tapi termasuk persegi panjang: total lebih dari itu.",explanation:"Segiempat dalam grid m×n: C(m+1,2)×C(n+1,2).\nGrid 3×3: C(4,2)×C(4,2) = 6×6 = 36.\nJawaban: A."},
{question:"Jika 'Beberapa dokter adalah wanita' dan 'Semua wanita adalah manusia', maka: ...",options:["Beberapa dokter adalah manusia","Semua dokter adalah wanita","Semua manusia adalah dokter","Tidak ada dokter manusia","Semua wanita adalah dokter"],answer:0,hint:"Beberapa D=W. Semua W=M. Maka beberapa D=M.",explanation:"Beberapa D ∈ W.\nSemua W ⊆ M.\n∴ Beberapa D ∈ M.\nBeberapa dokter adalah manusia.\nJawaban: A."},
]);

appendQuestions('tps_spasial', [
{question:"Berapa kubus kecil bercat 1 sisi pada kubus 3×3×3 yang dicat?",options:["6 (1 per face pusat)","8","12","24","1"],answer:0,hint:"Kubus yang hanya bercat 1 sisi = kubus di pusat setiap face. 6 face × 1 = 6.",explanation:"Kubus 3×3×3 dicat:\n3 sisi (sudut): 8.\n2 sisi (tepi): 12.\n1 sisi (pusat face): 6 (1 per face × 6 face).\n0 sisi (pusat): 1.\nJawaban: A."},
{question:"Luas lingkaran r=14 cm (π=22/7): ...",options:["616 cm²","308 cm²","154 cm²","44 cm²","88 cm²"],answer:0,hint:"L = πr² = 22/7 × 196 = 616.",explanation:"L = πr² = 22/7 × 14² = 22/7 × 196 = 616 cm².\nJawaban: A."},
{question:"Volume kerucut r=6, t=8: ...",options:["96π cm³","288π cm³","48π cm³","192π cm³","72π cm³"],answer:0,hint:"V = 1/3 πr²t = 1/3 × π × 36 × 8 = 96π.",explanation:"V = 1/3 × π × r² × t = 1/3 × π × 36 × 8 = 96π cm³.\nJawaban: A."},
{question:"Keliling lingkaran r=21 cm (π=22/7): ...",options:["132 cm","66 cm","42 cm","264 cm","44 cm"],answer:0,hint:"K = 2πr = 2 × 22/7 × 21 = 132.",explanation:"K = 2πr = 2 × 22/7 × 21 = 132 cm.\nJawaban: A."},
{question:"Diagonal sisi balok 3×4×5 (pada sisi 3×4): ...",options:["5 (√(9+16))","7","√50","12","3"],answer:0,hint:"Diagonal sisi = √(3²+4²) = √25 = 5.",explanation:"Diagonal sisi 3×4: √(3²+4²) = √(9+16) = √25 = 5.\nJawaban: A."},
]);

appendQuestions('tkd_indo', [
{question:"Kata 'justru' bermakna: ...",options:["Malah, sebaliknya (berlawanan dari yang diharapkan)","Karena","Jadi","Oleh sebab itu","Namun"],answer:0,hint:"Justru: malah, sebaliknya dari dugaan.",explanation:"Justru: menyatakan kebalikan dari yang diharapkan.\nContoh: 'Justru dia yang membantu paling banyak.'\nJawaban: A."},
{question:"Kalimat baku yang benar: ...",options:["Mereka bermain di halaman.","Mereka bermain dihalaman.","Mereka bermain kehalaman.","Mereka main di halaman.","Mereka bermain halaman."],answer:0,hint:"'Di' preposisi → terpisah. + halaman = lokasi.",explanation:"'Di halaman': preposisi + keterangan tempat → terpisah.\n'Bermain' lebih baku dari 'main'.\nJawaban: A."},
{question:"Majas ironi dalam kalimat: ...",options:["'Rajin sekali kamu, sudah jam 12 baru bangun!' (mengejek dengan pujian)","'Dia secepat kilat'","'Hatinya batu'","'Jutaan orang hadir'","'Matahari tersenyum'"],answer:0,hint:"Ironi: mengatakan kebalikan dari maksud sebenarnya.",explanation:"Ironi: menyatakan sesuatu yang berlawanan dengan fakta.\n'Rajin sekali' padahal bangun siang = menyindir.\nJawaban: A."},
{question:"Sinonim 'kronik' dalam konteks penyakit: ...",options:["Menahun (berlangsung lama)","Mendadak","Cepat","Ringan","Sembuh"],answer:0,hint:"Kronik (chronic) = menahun, berlangsung lama. Bukan akut.",explanation:"Kronik/kronis: berlangsung lama, menahun.\nLawan: akut (mendadak, singkat).\nContoh: diabetes kronis.\nJawaban: A."},
{question:"Bentuk baku 'merubah' yang benar: ...",options:["Mengubah (dari kata dasar 'ubah', bukan 'rubah')","Merubah","Merobah","Meng-ubah","Merombak"],answer:0,hint:"Dasar: ubah. meng- + ubah = mengubah. Rubah = hewan!",explanation:"Kata dasar: ubah.\nmeng- + ubah → mengubah.\n'Merubah' salah (me- + rubah? rubah = fox!).\nJawaban: A."},
]);

appendQuestions('tkd_eng', [
{question:"The word 'plethora' means: ...",options:["An excess or overabundance","A shortage","A balance","A deficit","An absence"],answer:0,hint:"Plethora = too much, excess. 'A plethora of options.'",explanation:"Plethora: an excessive amount; overabundance.\n'There was a plethora of food at the party.'\nJawaban: A."},
{question:"Choose correct sentence: 'The number of students ___ increasing.'",options:["is (the number = singular)","are","were","have been","am"],answer:0,hint:"'The number of' = singular → 'is'. 'A number of' = plural → 'are'.",explanation:"'The number of' → singular verb (is).\n'A number of' → plural verb (are).\n'The number of students is increasing.'\nJawaban: A."},
{question:"'Juxtaposition' in literature is used to: ...",options:["Place two contrasting elements side by side for comparison","Create alliteration","Make rhymes","Write dialogue","Add footnotes"],answer:0,hint:"Juxtaposition: placing contrasts together to highlight differences.",explanation:"Juxtaposition: placing two contrasting elements side by side.\nPurpose: highlight differences, create irony, or deepen meaning.\nExample: light/dark imagery.\nJawaban: A."},
{question:"The prefix 'anti-' means: ...",options:["Against / opposed to","Before","After","With","Under"],answer:0,hint:"Anti = against. Antibody, anti-clockwise, antibiotic.",explanation:"Anti-: against, opposed to.\nExamples: antisocial, antibody, antithesis, antidote.\nJawaban: A."},
{question:"'Whom should I contact?' is correct because: ...",options:["'Whom' is the object of the verb 'contact' (I contact HIM/HER)","'Whom' is the subject","'Whom' is a conjunction","It doesn't matter","'Who' is always wrong"],answer:0,hint:"I contact [whom?] = I contact HIM. Object → whom.",explanation:"Test: substitute he/him.\n'I should contact HIM/HER' → object → whom.\nIf 'HE/SHE should contact' → subject → who.\nJawaban: A."},
]);
