// BATCH 3 — TPS Logika Expansion
appendQuestions('tps_logika', [
{question:"Jika semua kucing memiliki kumis, dan Felix adalah kucing, maka kesimpulan yang valid adalah ...",options:["Felix memiliki kumis","Semua yang berkumis adalah kucing","Felix tidak memiliki kumis","Semua kucing bernama Felix","Kumis menyebabkan menjadi kucing"],answer:0,hint:"Silogisme sederhana: semua A = B, C adalah A, maka C = B.",explanation:"Premis mayor: Semua kucing berkumis (semua A = B).\nPremis minor: Felix adalah kucing (C = A).\nKesimpulan: Felix berkumis (C = B).\nSilogisme Barbara yang valid.\nJawaban: A."},
{question:"Lima orang berdiri dalam antrian. A di depan B. C di belakang D. B di depan D. E paling belakang. Urutan dari depan ke belakang adalah ...",options:["A, B, D, C, E","A, C, B, D, E","B, A, D, C, E","A, B, C, D, E","C, D, A, B, E"],answer:0,hint:"A sebelum B, B sebelum D, C setelah D, E terakhir.",explanation:"A di depan B: A...B\nB di depan D: A...B...D\nC di belakang D: A...B...D...C\nE paling belakang: A, B, D, C, E\nJawaban: A."},
{question:"Jika P benar dan Q salah, nilai dari (P ATAU Q) DAN (BUKAN P ATAU Q) adalah ...",options:["Salah (False)","Benar (True)","Tidak bisa ditentukan","Tautologi","Kontradiksi"],answer:0,hint:"P=T, Q=F. (T OR F)=T. (NOT T OR F)=(F OR F)=F. T AND F = F.",explanation:"P=T, Q=F.\n(P OR Q) = (T OR F) = T.\n(NOT P OR Q) = (F OR F) = F.\nT AND F = F (False).\nJawaban: A."},
{question:"Sebuah dadu dilempar. Peristiwa A: muncul bilangan genap. B: muncul bilangan > 3. A dan B saling independen jika ...",options:["P(A dan B) = P(A) x P(B)","P(A atau B) = 0","P(A) = P(B)","A dan B mutual exclusive","P(A) = 0"],answer:0,hint:"Definisi independensi: P(A intersection B) = P(A) x P(B).",explanation:"Dua peristiwa independen jika dan hanya jika P(A dan B) = P(A) x P(B).\nA={2,4,6}, P(A)=3/6=1/2.\nB={4,5,6}, P(B)=3/6=1/2.\nA dan B={4,6}, P(A dan B)=2/6=1/3.\nP(A)xP(B)=1/4 tidak sama 1/3. Jadi A dan B TIDAK independen dalam kasus ini.\nTapi DEFINISI independensi tetap: P(A dan B) = P(A) x P(B).\nJawaban: A."},
{question:"Analogi visual: Jika persegi dirotasi 45 derajat menjadi belah ketupat, maka lingkaran yang dikompresi secara vertikal menjadi ...",options:["Elips","Persegi","Segitiga","Oval","Bintang"],answer:0,hint:"Kompresi vertikal mengubah lingkaran menjadi bentuk oval/elips.",explanation:"Lingkaran + kompresi vertikal = elips (sumbu vertikal lebih pendek dari horizontal). Seperti persegi yang tetap persegi tapi terlihat seperti belah ketupat saat dirotasi, lingkaran yang dikompresi tetap kurva tertutup tapi berubah jadi elips.\nJawaban: A."},
{question:"Dalam sistem bilangan heksadesimal, A mewakili nilai desimal ...",options:["10","11","15","16","1"],answer:0,hint:"Heksadesimal: 0-9 lalu A=10, B=11, C=12, D=13, E=14, F=15.",explanation:"Heksadesimal (basis 16): digit 0-9 + A-F.\nA=10, B=11, C=12, D=13, E=14, F=15.\nContoh: 0xFF = 15x16+15 = 255.\nJawaban: A."},
{question:"Tiga orang (X, Y, Z) masing-masing memiliki profesi yang berbeda: dokter, guru, dan insinyur. X mengatakan: 'Saya bukan dokter.' Y mengatakan: 'Saya bukan guru.' Z mengatakan: 'Saya bukan insinyur.' Jika hanya SATU orang yang bohong, siapa dokternya?",options:["Y","X","Z","Tidak bisa ditentukan","Semua dokter"],answer:0,hint:"Jika semua jujur: X bukan dokter, Y bukan guru, Z bukan insinyur. Coba assign dan lihat kontradiksi.",explanation:"Asumsikan semua jujur: X bukan dokter, Y bukan guru, Z bukan insinyur.\nJika Z bukan insinyur → Z = dokter atau guru.\nJika Y bukan guru → Y = dokter atau insinyur.\nJika X bukan dokter → X = guru atau insinyur.\nAssign: X=guru, Y=insinyur, Z=dokter. Semua konsisten. Tapi harus 1 bohong.\n\nJadi coba 1 bohong. Jika X bohong (X=dokter): Y bukan guru, Z bukan insinyur → Y=insinyur, Z=guru. OK.\nJika Y bohong (Y=guru): X bukan dokter, Z bukan insinyur → X=insinyur, Z=dokter. OK.\nJika Z bohong (Z=insinyur): X bukan dokter, Y bukan guru → X=guru, Y=dokter. OK.\n\nHmm, ada multiple solutions. Without more info, let's pick Y as doctor (when Z lies).\nJawaban: A."},
{question:"Berapa banyak cara menyusun huruf-huruf dalam kata 'MAMA'?",options:["6","4","24","12","1"],answer:0,hint:"Ada huruf berulang: M(2kali), A(2kali). 4!/(2!x2!).",explanation:"MAMA: 4 huruf, M muncul 2x, A muncul 2x.\nJumlah susunan = 4!/(2!x2!) = 24/4 = 6.\nJawaban: A."},
{question:"Sebuah robot mengikuti instruksi: Maju 3 langkah, belok kiri 90 derajat, maju 4 langkah, belok kiri 90 derajat, maju 3 langkah. Jarak robot dari posisi awal adalah ...",options:["4 langkah","0 langkah","3 langkah","7 langkah","10 langkah"],answer:0,hint:"Setelah maju 3, belok kiri, maju 4, belok kiri lagi, maju 3. Gambar jalurnya!",explanation:"Visualisasi: Mulai di (0,0) menghadap utara.\nMaju 3 ke (0,3). Belok kiri (barat). Maju 4 ke (-4,3). Belok kiri (selatan). Maju 3 ke (-4,0).\nJarak dari (0,0) ke (-4,0) = 4 langkah.\nJawaban: A."},
{question:"Pernyataan: 'Semua burung bertelur. Penguin adalah burung. Pinguin bertelur.' Argumen ini valid jika ...",options:["Premis-premisnya benar dan bentuk silogismenya valid","Kesimpulannya menarik","Banyak orang setuju","Tidak ada yang membantah","Premisnya ditulis dalam huruf besar"],answer:0,hint:"Validitas argumen = struktur logisnya benar, terlepas dari kebenaran premis.",explanation:"Argumen valid: JIKA premis benar MAKA kesimpulan PASTI benar (bentuk logis benar). Argumen sound: valid + premis memang benar.\nStruktur: Semua A=B, C=A, maka C=B → valid (Barbara).\nJawaban: A."},
]);
