// BATCH 4 — Non-Math Subjects Expansion (Logika, Spasial, Indo, Eng, Saintek, Soshum)
// ~10 per subject = ~140 total

// TPS Logika
appendQuestions('tps_logika', [
{question:"Jika cuaca hujan MAKA jalanan basah. Jalanan tidak basah. Maka ...",options: ["Cuaca tidak hujan (modus tollens)","Cuaca hujan","Jalanan basah","Tidak bisa ditentukan","Cuaca cerah"],answer:0,hint:"Modus tollens: P->Q, bukan Q, maka bukan P.",explanation:"Modus tollens: jika P maka Q. Bukan Q. Maka bukan P.\nJika hujan maka basah. Tidak basah. Maka tidak hujan.\nJawaban: A."},
{question:"Semua bunga mawar adalah bunga. Semua bunga membutuhkan air. Kesimpulan: ...",options: ["Semua bunga mawar membutuhkan air","Semua yang butuh air adalah mawar","Air menyebabkan bunga","Mawar tidak perlu air","Semua bunga adalah mawar"],answer:0,hint:"Silogisme valid: Semua A=B, Semua B=C, maka Semua A=C.",explanation:"Silogisme transitif: Mawar subset Bunga, Bunga subset 'butuh air'. Maka Mawar subset 'butuh air'.\nJawaban: A."},
{question:"Dalam sebuah keluarga: Ali ayah Budi, Budi kakak Citra, Deni paman Citra. Hubungan Deni dan Ali: ...",options: ["Deni saudara Ali (atau saudara ipar)","Deni anak Ali","Deni ayah Ali","Tidak berhubungan","Deni kakek Citra"],answer:0,hint:"Paman Citra = saudara dari orangtua Citra. Ayah Citra = Ali (karena Ali ayah Budi, Budi kakak Citra). Paman = saudara ayah.",explanation:"Ali ayah Budi dan Citra (Budi kakak Citra = satu ayah).\nDeni paman Citra = saudara dari orangtua Citra = saudara Ali.\nJaway: A."},
{question:"A > B, C < A, B > D. Urutan dari terbesar: ...",options: ["A, B/C, D (A pasti terbesar, tapi urutan B dan C tidak pasti)","D, B, C, A","A, C, B, D","B, A, C, D","C, A, D, B"],answer:0,hint:"A>B, A>C, B>D. Tapi hubungan B dan C tidak diketahui!",explanation:"Kita tahu: A>B, A>C, B>D.\nA pasti terbesar. B>D. Tapi B vs C? Tidak ada info.\nUrutan: A di puncak, D di dasar, B dan C di tengah (urutan relatif B,C tidak pasti).\nJawaban: A."},
{question:"Konversi biner 1101 ke desimal = ...",options: ["13","11","15","7","12"],answer:0,hint:"1101 = 1x8 + 1x4 + 0x2 + 1x1.",explanation:"1101(2) = 1(2^3)+1(2^2)+0(2^1)+1(2^0) = 8+4+0+1 = 13.\nJawaban: A."},
]);

// TPS Spasial
appendQuestions('tps_spasial', [
{question:"Sebuah kertas dilipat dua kali sehingga 4 lapis, lalu dilubangi 1 lubang di tengah. Saat dibuka, ada berapa lubang?",options: ["4","1","2","8","16"],answer:0,hint:"Lipatan 2x = 4 lapis. 1 lubang menembus 4 lapis.",explanation:"Dilipat 2x: kertas 4 lapis. 1 lubang menembus semua lapisan -> 4 lubang saat dibuka. Posisi lubang simetris terhadap garis lipatan.\nJawaban: A."},
{question:"Bayangan huruf 'S' jika dicerminkan terhadap sumbu vertikal adalah ...",options: ["Huruf S yang terbalik horizontal (mirror S)","S biasa","Z","N","2"],answer:0,hint:"Cermin vertikal membalik kiri-kanan. S menjadi S terbalik.",explanation:"Huruf S dicerminkan secara horizontal menghasilkan bentuk S yang terbalik (seperti tulisan S di cermin). Berbeda dari Z (yang merupakan rotasi, bukan refleksi).\nJawaban: A."},
{question:"Kubus 4x4x4 dicat merah semua permukaan, lalu dipotong menjadi kubus 1x1x1. Berapa kubus yang memiliki TEPAT 1 sisi tercat?",options: ["24","8","32","48","16"],answer:0,hint:"Kubus 1 sisi tercat = di tengah muka (bukan rusuk, bukan sudut). Tiap muka: (n-2)^2.",explanation:"Kubus 1 sisi: di tengah setiap muka.\nTiap muka: (4-2)^2 = 4 kubus.\n6 muka x 4 = 24 kubus.\nJawaban: A."},
{question:"Rotasi bangun datar persegi panjang 360 derajat terhadap sisi panjangnya menghasilkan bangun ruang ...",options: ["Tabung (silinder)","Kerucut","Bola","Prisma","Kubus"],answer:0,hint:"Persegi panjang dirotasi terhadap satu sisinya menghasilkan bentuk tabung.",explanation:"Rotasi persegi panjang terhadap sisi panjang: sisi pendek menjadi jari-jari, sisi panjang menjadi tinggi -> tabung/silinder.\nJawaban: A."},
{question:"Sebuah kubus memiliki 8 titik sudut, 12 rusuk, dan 6 sisi. Jika 1 sudut dipotong, berapa sisi yang dimiliki bangun baru?",options: ["7","6","8","9","10"],answer:0,hint:"Potong 1 sudut = hilangkan 1 vertex, tambah 1 sisi baru (bidang potong).",explanation:"Memotong 1 sudut kubus menambahkan 1 sisi baru (bidang potong berupa segitiga).\nSisi baru = 6 + 1 = 7. (3 sisi yang berdekatan masing-masing kehilangan sudut tapi tetap 1 sisi.)\nJawaban: A."},
]);

// TKD Bahasa Indonesia
appendQuestions('tkd_indo', [
{question:"Kata baku dari 'telor', 'nasehat', 'praktek', 'apotek' masing-masing adalah ...",options: ["telur, nasihat, praktik, apotek","telor, nasehat, praktek, apotek","telur, nasehat, praktek, apotik","telor, nasihat, praktik, apotik","telur, nasihat, praktek, apotek"],answer:0,hint:"KBBI: telur (bukan telor), nasihat (bukan nasehat), praktik (bukan praktek).",explanation:"Kata baku sesuai KBBI:\ntelor -> telur. nasehat -> nasihat. praktek -> praktik. apotek (sudah benar).\nKesalahan umum yang sering terjadi dalam ejaan bahasa Indonesia.\nJawaban: A."},
{question:"Kalimat yang menggunakan imbuhan me-N dengan benar adalah ...",options: ["Dia memukul bola dengan keras (me+pukul=memukul)","Dia mempukul bola","Dia mengpukul bola","Dia mepukul bola","Dia memepukul bola"],answer:0,hint:"me-N+pukul: huruf p luluh, nasal m muncul -> memukul.",explanation:"Aturan me-N: huruf awal p,t,k,s luluh saat mendapat prefiks meN-.\nme+pukul: p luluh -> memukul (bukan mempukul).\nme+tulis -> menulis, me+kirim -> mengirim, me+sapu -> menyapu.\nJawaban: A."},
{question:"Jenis kalimat 'Betapa indahnya pemandangan ini!' adalah ...",options: ["Kalimat eksklamatif (seru)","Kalimat deklaratif","Kalimat imperatif (perintah)","Kalimat interogatif (tanya)","Kalimat pasif"],answer:0,hint:"Tanda seru + kata seru (betapa) = eksklamatif.",explanation:"Kalimat eksklamatif: mengungkapkan rasa kagum, heran, terkejut. Ditandai dengan tanda seru (!) dan kata seru (betapa, alangkah, sungguh).\nJawaban: A."},
{question:"Dalam paragraf argumentasi, perbedaan antara fakta dan opini adalah ...",options: ["Fakta dapat diverifikasi kebenarannya, opini bersifat subjektif","Fakta selalu menggunakan angka","Opini selalu salah","Keduanya sama","Fakta hanya di berita"],answer:0,hint:"Fakta = bisa dicek benar/salah. Opini = pandangan pribadi, tidak bisa dibuktikan absolut.",explanation:"Fakta: dapat diverifikasi secara objektif (data, peristiwa, angka). Opini: pandangan/penilaian subjektif seseorang (menurut saya, sebaiknya, indah, buruk).\nJawaban: A."},
{question:"Kesalahan dalam kalimat 'Kepada Bapak Presiden dipersilakan memberikan sambutan' adalah ...",options: ["Kata 'kepada' tidak perlu karena subjek langsung (cukup 'Bapak Presiden dipersilakan...')","Tidak ada kesalahan","Kata 'dipersilakan' salah","Tidak ada predikat","Terlalu panjang"],answer:0,hint:"'Kepada' adalah preposisi untuk objek, bukan untuk subjek kalimat.",explanation:"'Kepada' menandai objek/tujuan, bukan subjek. Dalam kalimat ini, 'Bapak Presiden' adalah SUBJEK (yang dipersilakan), jadi tidak perlu preposisi 'kepada'.\nPerbaikan: 'Bapak Presiden dipersilakan memberikan sambutan.'\nJawaban: A."},
]);

// TKD Bahasa Inggris
appendQuestions('tkd_eng', [
{question:"Choose the correct sentence: 'Each of the students ____ a textbook.'",options: ["has","have","are having","were having","having"],answer:0,hint:"'Each' is singular, so the verb must be singular: 'has'.",explanation:"'Each' = singular, regardless of what follows ('of the students'). Therefore: 'Each has' (singular verb).\nAnswer: A."},
{question:"The word 'benevolent' most closely means:",options: ["Kind and generous","Cruel and selfish","Neutral","Lazy","Ambitious"],answer:0,hint:"Bene- = good. -volent = wishing. Benevolent = well-wishing, kind.",explanation:"Benevolent: well-meaning, kind, generous, charitable. Bene (good) + volent (willing/wishing). Opposite: malevolent (ill-wishing).\nAnswer: A."},
{question:"Choose the correct relative pronoun: 'The house ____ roof was damaged has been repaired.'",options: ["whose","which","that","who","whom"],answer:0,hint:"Possession of a thing: 'whose' (possessive relative pronoun).",explanation:"'Whose' indicates possession (the house's roof). 'Whose' can refer to both people and things in modern English. 'Which' and 'that' cannot show possession.\nAnswer: A."},
{question:"Read: 'The government implemented austerity measures despite public opposition.' What does 'austerity' mean here?",options: ["Strict economic policies involving reduced spending","Generous spending increases","Military actions","Environmental regulations","Educational reforms"],answer:0,hint:"Austerity = strictness/severity, especially in economics = cutting spending.",explanation:"Austerity measures: strict economic policies that reduce government spending, increase taxes, and cut public services, typically implemented during financial crises to reduce budget deficits.\nAnswer: A."},
{question:"Identify the correct use of the present perfect: ",options: ["She has lived here since 2010. (started in past, continues to present)","She has lived here yesterday.","She has lived here tomorrow.","She has live here since 2010.","She have lived here since 2010."],answer:0,hint:"Present perfect: has/have + past participle. Used for actions starting in past and continuing to present.",explanation:"Present perfect: has/have + past participle (lived). Used with 'since' (point in time) and 'for' (duration). 'She has lived here since 2010' = correct.\nB: 'yesterday' = past simple. C: 'tomorrow' = future. D: 'live' should be 'lived'. E: 'have' should be 'has' (she).\nAnswer: A."},
]);

// Saintek Matematika IPA
appendQuestions('saintek_matipa', [
{question:"Turunan parsial dari f(x,y) = x^2y + y^3 terhadap x adalah ...",options: ["2xy","x^2 + 3y^2","2xy + 3y^2","x^2y","y"],answer:0,hint:"Turunkan terhadap x, anggap y sebagai konstanta.",explanation:"df/dx = d/dx(x^2 y) + d/dx(y^3) = 2xy + 0 = 2xy.\n(y^3 dianggap konstanta saat diturunkan terhadap x.)\nJawaban: A."},
{question:"Integral ganda: integral dari 0 ke 1, integral dari 0 ke 1, (x+y) dy dx = ...",options: ["1","2","$\\frac{1}{2}$","$\\frac{3}{2}$","0"],answer:0,hint:"Inner integral (dy): integral (x+y) dari 0 ke 1 = x + 1/2. Outer: integral (x+1/2) dx dari 0 ke 1 = 1/2+1/2 = 1.",explanation:"Inner: integral_0^1 (x+y) dy = xy + y^2/2 |_0^1 = x + 1/2.\nOuter: integral_0^1 (x+1/2) dx = x^2/2 + x/2 |_0^1 = 1/2+1/2 = 1.\nJawaban: A."},
{question:"Trace (jumlah elemen diagonal utama) matriks [[1,2],[3,4]] = ...",options: ["5","10","7","4","1"],answer:0,hint:"Trace = a11 + a22 = 1 + 4.",explanation:"Trace(A) = 1 + 4 = 5.\nTrace matriks nxn = jumlah elemen diagonal utama.\nJawaban: A."},
{question:"Deret Taylor sin(x) di x=0 dimulai dengan ...",options: ["x - x^3/6 + x^5/120 - ...","1 - x^2/2 + x^4/24 - ...","x + x^3/6 + x^5/120 + ...","1 + x + x^2/2 + ...","x^2 - x^4/4 + ..."],answer:0,hint:"sin(x) = x - x^3/3! + x^5/5! - ... (suku ganjil, tanda bergantian).",explanation:"sin(x) = x - x^3/6 + x^5/120 - x^7/5040 + ...\n= sum (-1)^n x^(2n+1)/(2n+1)! dari n=0 ke inf.\nOpsi B adalah cos(x).\nJawaban: A."},
{question:"Jika A matriks 3x3 dan det(A) = 4, maka det(2A) = ...",options: ["32","8","16","64","12"],answer:0,hint:"det(kA) = k^n det(A) untuk matriks nxn. Disini n=3, k=2.",explanation:"det(2A) = 2^3 x det(A) = 8 x 4 = 32.\nUntuk matriks nxn: det(kA) = k^n det(A).\nJawaban: A."},
]);

// Saintek Fisika
appendQuestions('saintek_fisika', [
{question:"Sebuah benda bermassa 5 kg bergerak melingkar dengan jari-jari 2 m dan kecepatan 4 m/s. Gaya sentripetal = ...",options: ["40 N","20 N","10 N","80 N","8 N"],answer:0,hint:"F = mv^2/r = 5(16)/2 = 40 N.",explanation:"F = mv^2/r = 5 x 16/2 = 80/2 = 40 N.\nGaya sentripetal mengarah ke pusat lingkaran.\nJawaban: A."},
{question:"Hukum Coulomb: gaya antara dua muatan q1 dan q2 berjarak r sebanding dengan ...",options: ["q1 x q2 / r^2","q1 x q2 x r^2","q1 + q2 / r","(q1 x q2)^2 / r","q1 x q2 / r"],answer:0,hint:"F = k q1 q2 / r^2 (berbanding lurus kuadrat muatan, terbalik kuadrat jarak).",explanation:"Hukum Coulomb: F = k q1 q2 / r^2.\nk = 9 x 10^9 Nm^2/C^2.\nMirip hukum gravitasi Newton tapi untuk muatan listrik.\nJawaban: A."},
{question:"Energi kinetik benda bermassa 2 kg dengan kecepatan 3 m/s = ...",options: ["9 J","6 J","18 J","3 J","12 J"],answer:0,hint:"Ek = 1/2 mv^2 = 1/2 x 2 x 9.",explanation:"Ek = 1/2 x 2 x 3^2 = 1/2 x 2 x 9 = 9 J.\nJawaban: A."},
{question:"Cepat rambat gelombang dengan frekuensi 500 Hz dan panjang gelombang 0.68 m = ...",options: ["340 m/s","250 m/s","500 m/s","170 m/s","680 m/s"],answer:0,hint:"v = f x lambda = 500 x 0.68.",explanation:"v = f x lambda = 500 x 0.68 = 340 m/s.\nIni kecepatan suara di udara pada suhu normal!\nJawaban: A."},
{question:"Hukum Newton III: aksi-reaksi. Jika A mendorong B dengan gaya 10 N, maka B mendorong A dengan gaya ...",options: ["10 N (arah berlawanan)","20 N","5 N","0 N","10 N (arah sama)"],answer:0,hint:"Newton III: setiap aksi memiliki reaksi yang sama besar dan berlawanan arah.",explanation:"Hukum Newton III: gaya aksi = gaya reaksi, sama besar tapi berlawanan arah.\nA dorong B = 10 N ke kanan. B dorong A = 10 N ke kiri.\nJawaban: A."},
]);

// Saintek Kimia
appendQuestions('saintek_kimia', [
{question:"Konfigurasi elektron atom Na (Z=11) adalah ...",options: ["1s2 2s2 2p6 3s1","1s2 2s2 2p6 3s2","1s2 2s2 2p7","1s2 2s2 2p6 3p1","1s2 2s2 2p6"],answer:0,hint:"Na memiliki 11 elektron. Isi orbital secara berurutan.",explanation:"Na (Z=11): 1s2 2s2 2p6 3s1.\nElektron terakhir di 3s1 (golongan IA, periode 3).\nNa cenderung melepas 1 elektron menjadi Na+.\nJawaban: A."},
{question:"pH larutan HCl 0.001 M (asam kuat, terionisasi sempurna) = ...",options: ["3","1","0.001","7","11"],answer:0,hint:"Asam kuat: [H+] = konsentrasi = 0.001 = 10^(-3). pH = -log[H+] = 3.",explanation:"HCl asam kuat -> terionisasi sempurna.\n[H+] = 0.001 M = 10^(-3) M.\npH = -log(10^(-3)) = 3.\nJawaban: A."},
{question:"Reaksi: 2H2 + O2 -> 2H2O. Jika 4 mol H2 bereaksi, mol H2O yang terbentuk = ...",options: ["4 mol","2 mol","8 mol","1 mol","6 mol"],answer:0,hint:"Stoikiometri: 2 mol H2 -> 2 mol H2O. Rasio 1:1.",explanation:"Dari persamaan: 2H2 -> 2H2O (rasio 1:1).\n4 mol H2 -> 4 mol H2O.\n(Asumsi O2 berlebih.)\nJawaban: A."},
{question:"Jenis ikatan dalam molekul NaCl adalah ...",options: ["Ionik (transfer elektron)","Kovalen polar","Kovalen nonpolar","Logam","Van der Waals"],answer:0,hint:"Na (logam) + Cl (nonlogam): perbedaan keelektronegatifan besar -> ionik.",explanation:"Na (keelektronegatifan 0.93) + Cl (3.16).\nDelta EN = 2.23 (> 1.7) -> ikatan ionik.\nNa melepas 1e -> Na+. Cl menerima 1e -> Cl-.\nJawaban: A."},
{question:"Massa molar H2O = ...",options: ["18 g/mol","2 g/mol","16 g/mol","20 g/mol","36 g/mol"],answer:0,hint:"H=1, O=16. H2O = 2(1)+16 = 18.",explanation:"M(H2O) = 2(1) + 16 = 18 g/mol.\n1 mol H2O = 18 gram = 6.022 x 1$0^{23}$ molekul.\nJawaban: A."},
]);

// Saintek Biologi
appendQuestions('saintek_biologi', [
{question:"DNA tersusun dari nukleotida yang terdiri dari tiga komponen: ...",options: ["Gula deoksiribosa, fosfat, dan basa nitrogen","Protein, lemak, dan karbohidrat","Asam amino, gula, dan fosfat","Gula ribosa, fosfat, dan basa nitrogen","Glukosa, fruktosa, dan sukrosa"],answer:0,hint:"Nukleotida DNA: gula deoksiribosa + gugus fosfat + basa nitrogen (ATGC).",explanation:"Nukleotida DNA terdiri dari:\n1. Gula deoksiribosa (pentosa, 5 karbon, tanpa OH di C-2)\n2. Gugus fosfat (PO4)\n3. Basa nitrogen (Adenin, Timin, Guanin, Sitosin)\nRNA: gula ribosa (ada OH di C-2), Urasil mengganti Timin.\nJawaban: A."},
{question:"Organel sel yang berfungsi sebagai 'pembangkit listrik' (produksi ATP) adalah ...",options: ["Mitokondria","Kloroplas","Ribosom","Lisosom","Retikulum endoplasma"],answer:0,hint:"Mitokondria = powerhouse of the cell. Fosforilasi oksidatif -> ATP.",explanation:"Mitokondria: organel bermembran ganda yang melakukan respirasi seluler aerob (siklus Krebs + rantai transpor elektron) -> menghasilkan mayoritas ATP sel.\nKloroplas = fotosintesis (hanya di tumbuhan).\nJawaban: A."},
{question:"Hukum Mendel I (segregasi) menyatakan bahwa ...",options: ["Sepasang alel berpisah saat pembentukan gamet, setiap gamet membawa 1 alel","Semua gen mewarisi bersama","Gen tidak bisa berpisah","Alel dominan selalu muncul","Gen berada di kromosom X"],answer:0,hint:"Segregasi = pemisahan. Pasangan alel terpisah saat meiosis.",explanation:"Hukum I Mendel (Law of Segregation): dua alel untuk setiap sifat berpisah selama pembentukan gamet (meiosis), sehingga setiap gamet hanya membawa satu alel. Pada pembuahan, pasangan alel terbentuk kembali.\nJawaban: A."},
{question:"Proses perubahan glukosa menjadi 2 piruvat di sitoplasma disebut ...",options: ["Glikolisis","Siklus Krebs","Fosforilasi oksidatif","Fermentasi","Fotosintesis"],answer:0,hint:"Glyco = gula, lysis = pemecahan. Di sitoplasma, bukan mitokondria.",explanation:"Glikolisis: pemecahan glukosa (6C) menjadi 2 piruvat (3C) di sitoplasma.\nMenghasilkan 2 ATP (netto) dan 2 NADH.\nTerjadi baik dalam kondisi aerob maupun anaerob.\nJawaban: A."},
{question:"Fotosintesis menghasilkan reaksi keseluruhan ...",options: ["6CO2 + 6H2O -> C6H12O6 + 6O2 (dengan cahaya)","C6H12O6 + 6O2 -> 6CO2 + 6H2O","6O2 + C6H12O6 -> 6CO2 + 6H2O","CO2 -> C + O2","H2O -> H2 + O"],answer:0,hint:"Fotosintesis: CO2 + air + cahaya -> gula + oksigen.",explanation:"Fotosintesis: 6CO2 + 6H2O + energi cahaya -> C6H12O6 + 6O2.\nKebalikan dari respirasi seluler.\nO2 berasal dari pemecahan H2O (bukan CO2).\nJawaban: A."},
]);

// Soshum Ekonomi
appendQuestions('soshum_ekonomi', [
{question:"Hukum permintaan menyatakan bahwa jika harga naik (ceteris paribus), maka ...",options: ["Kuantitas yang diminta turun (hubungan terbalik)","Kuantitas yang diminta naik","Penawaran turun","Tidak ada perubahan","Kuantitas tetap"],answer:0,hint:"Hukum permintaan: harga naik -> quantity demanded turun (inverse relationship).",explanation:"Hukum permintaan: hubungan negatif/terbalik antara harga dan kuantitas yang diminta (ceteris paribus = hal lain tetap). Kurva permintaan miring ke bawah dari kiri ke kanan.\nJawaban: A."},
{question:"Inflasi didefinisikan sebagai ...",options: ["Kenaikan tingkat harga umum secara terus-menerus (sustained)","Kenaikan harga satu barang","Penurunan harga umum","Kenaikan produksi","Kenaikan pengangguran"],answer:0,hint:"In-flasi = pembengkakan harga. Harus umum (bukan satu barang) dan berkelanjutan.",explanation:"Inflasi: kenaikan tingkat harga UMUM (bukan hanya satu barang) secara BERKELANJUTAN (bukan sekali naik). Diukur dengan CPI atau GDP deflator.\nKenaikan 1 barang = bukan inflasi. Kenaikan sekali = bukan inflasi.\nJawaban: A."},
{question:"Fungsi utama bank sentral meliputi ...",options: ["Menetapkan kebijakan moneter, mengatur jumlah uang beredar, menjaga stabilitas harga","Memberikan kredit konsumsi ke masyarakat","Menjual produk asuransi","Mengelola pajak","Mengatur perdagangan internasional"],answer:0,hint:"Bank sentral (BI di Indonesia): kebijakan moneter, SBI, cadangan devisa."  ,explanation:"Fungsi bank sentral:\n1. Menetapkan kebijakan moneter (suku bunga, cadangan wajib)\n2. Mengatur jumlah uang beredar\n3. Menjaga stabilitas harga (target inflasi)\n4. Lender of last resort\n5. Mengelola cadangan devisa\nJawaban: A."},
{question:"Opportunity cost dari pilihan A adalah ...",options: ["Nilai dari alternatif terbaik yang dikorbankan","Harga barang A","Total biaya produksi","Biaya transportasi","Keuntungan dari A"],answer:0,hint:"Opportunity cost = nilai dari next best alternative yang TIDAK dipilih.",explanation:"Opportunity cost (biaya peluang): nilai dari alternatif terbaik berikutnya yang harus dikorbankan saat membuat pilihan. Jika memilih kuliah (opportunity cost = gaji yang hilang jika bekerja).\nJawaban: A."},
{question:"Pada pasar persaingan sempurna (perfect competition), jumlah penjual dan pembeli ...",options: ["Sangat banyak sehingga tidak ada yang bisa mempengaruhi harga (price taker)","Hanya 1 penjual","Hanya 2-3 penjual","1 penjual 1 pembeli","Sangat sedikit"],answer:0,hint:"Perfect competition: banyak penjual & pembeli, produk homogen, free entry/exit.",explanation:"Pasar persaingan sempurna: sangat banyak penjual & pembeli, produk homogen, informasi sempurna, free entry-exit. Setiap pelaku = price taker (tidak bisa mempengaruhi harga pasar).\nJawaban: A."},
]);

// Soshum Sosiologi
appendQuestions('soshum_sosiologi', [
{question:"Interaksi sosial menurut sosiologi memerlukan dua syarat utama: ...",options: ["Kontak sosial dan komunikasi","Hanya kedekatan fisik","Hanya bahasa yang sama","Hanya status yang sama","Tidak ada syarat"],answer:0,hint:"Interaksi sosial = kontak (awareness) + komunikasi (exchange of messages).",explanation:"Interaksi sosial memerlukan:\n1. Kontak sosial: kesadaran akan keberadaan pihak lain (bisa langsung/tidak langsung)\n2. Komunikasi: pertukaran pesan/makna antara pihak-pihak\nTanpa keduanya, interaksi sosial tidak terjadi.\nJawaban: A."},
{question:"Contoh mobilitas sosial horizontal adalah ...",options: ["Guru SD pindah menjadi guru SMP (jabatan setara, beda institusi)","Karyawan dipromosikan menjadi manajer","Anak petani menjadi dokter","Millioner bangkrut","Mahasiswa menjadi professor"],answer:0,hint:"Horizontal = pindah posisi tapi strata sosial TETAP SAMA.",explanation:"Mobilitas horizontal: perpindahan posisi sosial tanpa perubahan strata (naik/turun). Contoh: guru SD -> guru SMP (keduanya = tenaga pendidik, level setara).\nVertikal: naik/turun strata (karyawan -> manajer).\nJawaban: A."},
{question:"Teori fungsionalisme struktural (Parsons, Durkheim) memandang masyarakat sebagai ...",options: ["Sistem yang terintegrasi dimana setiap bagian memiliki fungsi untuk keseluruhan","Arena konflik antar kelompok","Kumpulan individu tanpa struktur","Hasil konstruksi media","Produk ekonomi semata"],answer:0,hint:"Fungsionalisme: masyarakat = organisme, setiap institusi memiliki fungsi untuk kelangsungan sistem.",explanation:"Fungsionalisme struktural: masyarakat = sistem terintegrasi seperti organisme biologis. Setiap bagian (keluarga, agama, pendidikan, ekonomi) memiliki fungsi untuk menjaga keseimbangan dan kelangsungan sistem sosial.\nJawaban: A."},
{question:"Asimilasi dalam sosiologi adalah proses ...",options: ["Peleburan dua kebudayaan menjadi satu kebudayaan baru","Pemisahan kelompok","Konflik antar kelompok","Dominasi satu kelompok tanpa perubahan","Penolakan budaya asing"],answer:0,hint:"A-simil-asi: menjadi similar (mirip). Dua budaya -> satu budaya baru.",explanation:"Asimilasi: proses sosial dimana dua atau lebih kelompok budaya secara bertahap melebur menjadi satu, menghasilkan budaya baru yang merupakan campuran. Berbeda dari akulturasi (kontak budaya tanpa kehilangan identitas asli).\nJawaban: A."},
{question:"Agen sosialisasi yang PERTAMA dan paling fundamental bagi individu adalah ...",options: ["Keluarga","Sekolah","Media massa","Teman sebaya","Pemerintah"],answer:0,hint:"Keluarga = agen sosialisasi primer. Tempat pertama anak belajar nilai dan norma.",explanation:"Keluarga: agen sosialisasi PRIMER (pertama dan paling mendasar). Membentuk identitas dasar, bahasa, nilai moral, dan kebiasaan. Sekolah, teman, media = agen sosialisasi SEKUNDER.\nJawaban: A."},
]);

// Soshum Sejarah
appendQuestions('soshum_sejarah', [
{question:"Proklamasi kemerdekaan Indonesia dibacakan oleh Soekarno-Hatta pada ...",options: ["17 Agustus 1945","1 Juni 1945","28 Oktober 1928","22 Juni 1945","18 Agustus 1945"],answer:0,hint:"Tujuh belas Agustus empat lima. Hari kemerdekaan Indonesia.",explanation:"17 Agustus 1945: Soekarno membacakan teks Proklamasi Kemerdekaan Indonesia di Jalan Pegangsaan Timur No. 56, Jakarta.\n1 Juni 1945: Pancasila. 28 Oktober 1928: Sumpah Pemuda. 18 Agustus 1945: UUD 1945.\nJawaban: A."},
{question:"Perjanjian Linggarjati (1947) antara Indonesia dan Belanda berisi pengakuan de facto atas ...",options: ["Wilayah RI atas Jawa, Madura, dan Sumatera","Seluruh wilayah NKRI","Hanya Jawa","Hanya Jakarta","Kalimantan dan Sulawesi"],answer:0,hint:"Linggarjati: Belanda mengakui RI de facto atas 3 wilayah.",explanation:"Perjanjian Linggarjati (25 Maret 1947): Belanda mengakui kedaulatan de facto RI atas Jawa, Madura, dan Sumatera. Indonesia dan Belanda akan membentuk Negara Indonesia Serikat dan Uni Indonesia-Belanda.\nJawaban: A."},
{question:"Peristiwa Rengasdengklok (16 Agustus 1945) terjadi karena ...",options: ["Golongan muda mendesak Soekarno-Hatta segera memproklamasikan kemerdekaan","Belanda menyerang Indonesia","Jepang menolak menyerah","PBB mengintervensi","Terjadi perang saudara"],answer:0,hint:"Pemuda: Wikana, Chairul Saleh membawa Soekarno-Hatta ke Rengasdengklok agar segera proklamasi.",explanation:"Peristiwa Rengasdengklok: golongan muda (diwakili Wikana, Chairul Saleh) membawa Soekarno-Hatta ke Rengasdengklok, Karawang, untuk mendesak proklamasi kemerdekaan segera tanpa menunggu Jepang.\nJawaban: A."},
{question:"Reformasi 1998 di Indonesia ditandai oleh ...",options: ["Lengsernya Presiden Soeharto (21 Mei 1998) setelah 32 tahun berkuasa","Kemerdekaan dari Belanda","Pembentukan ASEAN","Pemilu pertama","Pendirian PBB"],answer:0,hint:"21 Mei 1998: Soeharto mengundurkan diri. Akhir Orde Baru, awal Reformasi.",explanation:"Reformasi 1998: didorong oleh krisis ekonomi Asia 1997, gerakan mahasiswa, dan kerusuhan Mei 1998. Soeharto mengundurkan diri 21 Mei 1998 setelah berkuasa sejak 1966. BJ Habibie menjadi presiden.\nJawaban: A."},
{question:"Perjanjian Renville (17 Januari 1948) merugikan Indonesia karena ...",options: ["Wilayah RI menyusut hanya di sebagian Jawa dan Sumatera (status quo Garis Van Mook)","Indonesia mendapat Kalimantan","Belanda mundur total","PBB mendukung Indonesia sepenuhnya","Tidak ada dampak"],answer:0,hint:"Renville: garis demarkasi Van Mook mempersempit wilayah RI. Indonesia dirugikan.",explanation:"Perjanjian Renville: garis demarkasi Van Mook mempersempit wilayah de facto RI. TNI harus mundur dari kantong-kantong gerilya di wilayah Belanda. Merugikan RI secara teritorial tetapi diplomasi tetap berlanjut.\nJawaban: A."},
]);

// Soshum Geografi
appendQuestions('soshum_geografi', [
{question:"Garis khatulistiwa (ekuator) terletak pada lintang ...",options: ["0 derajat","90 derajat utara","90 derajat selatan","23.5 derajat utara","66.5 derajat utara"],answer:0,hint:"Ekuator = garis tengah bumi, lintang 0.",explanation:"Ekuator/khatulistiwa: lintang 0 derajat. Membagi bumi menjadi belahan utara dan selatan.\n23.5 derajat = garis balik (Tropic of Cancer/Capricorn).\n66.5 derajat = lingkaran kutub (Arctic/Antarctic Circle).\n90 derajat = kutub.\nJawaban: A."},
{question:"Faktor utama pembentuk tanah (pedogenesis) meliputi ...",options: ["Iklim, organisme, bahan induk, topografi, dan waktu (CLORPT)","Hanya air","Hanya batuan","Hanya suhu","Hanya manusia"],answer:0,hint:"Jenny (1941): S = f(Cl, O, R, P, T) - Climate, Organisms, Relief, Parent material, Time.",explanation:"Faktor pembentuk tanah (Hans Jenny, 1941 - CLORPT):\n1. Climate (iklim)\n2. Organisms (organisme/biota)\n3. Relief (topografi)\n4. Parent material (bahan induk/batuan)\n5. Time (waktu)\nJawaban: A."},
{question:"Perbedaan antara sumber daya alam yang TERBARUKAN dan TIDAK TERBARUKAN adalah ...",options: ["Terbarukan dapat dipulihkan secara alami (hutan, air), tidak terbarukan habis jika digunakan (minyak, batu bara)","Keduanya sama","Terbarukan lebih mahal","Tidak terbarukan selalu cair","Terbarukan hanya di hutan"],answer:0,hint:"Terbarukan = renewable (bisa tumbuh/pulih kembali). Tidak terbarukan = non-renewable (jutaan tahun untuk terbentuk).",explanation:"Terbarukan: dapat dipulihkan secara alami dalam waktu relatif singkat (hutan, air, tenaga surya, angin).\nTidak terbarukan: membutuhkan jutaan tahun untuk terbentuk, habis jika dieksploitasi berlebihan (minyak bumi, batu bara, gas alam, mineral).\nJawaban: A."},
{question:"Skala Richter mengukur ...",options: ["Kekuatan/magnitudo gempa bumi","Kecepatan angin","Suhu udara","Curah hujan","Ketinggian gelombang"],answer:0,hint:"Richter = gempa. Beaufort = angin. Celsius/Fahrenheit = suhu.",explanation:"Skala Richter: mengukur magnitudo (energi yang dilepaskan) gempa bumi. Logaritmik: kenaikan 1 skala = 10x amplitude, 31.6x energi.\nSkala Mercalli: mengukur intensitas (dampak yang dirasakan).\nJawaban: A."},
{question:"Indonesia termasuk negara maritim karena ...",options: ["Wilayah laut lebih luas dari daratan (2/3 wilayah = laut) dan terdiri dari ribuan pulau","Memiliki gunung tertinggi","Populasi terbesar","Ekonomi terkuat ASEAN","Iklim tropis"],answer:0,hint:"Maritim = berhubungan dengan laut. Indonesia = negara kepulauan terbesar dunia.",explanation:"Indonesia: negara kepulauan terbesar (17.000+ pulau). Luas laut sekitar 2/3 dari total wilayah. Garis pantai terpanjang ke-2 di dunia. Identitas maritim = laut sebagai penghubung, bukan pemisah.\nJawaban: A."},
]);
