// BATCH 4 — TPS Verbal Expansion (50 Soal)
appendQuestions('tps_verbal', [
{question:"ANOMALI : PENYIMPANGAN :: PARADIGMA : ...",options: ["Kerangka berpikir","Penyimpangan (menurut standar)","Kesalahan (secara literal)","Masalah (secara teknis)","Solusi (dalam praktik)"],answer:0,hint:"Anomali = penyimpangan dari normal. Paradigma = kerangka/model berpikir.",explanation:"Anomali bermakna penyimpangan/ketidaknormalan. Paradigma bermakna kerangka berpikir atau model konseptual yang digunakan dalam suatu bidang.\nJawaban: A."},
{question:"Silogisme: Semua mahasiswa UGM cerdas. Budi bukan mahasiswa UGM. Kesimpulan yang VALID adalah ...",options: ["Tidak bisa ditarik kesimpulan tentang kecerdasan Budi","Budi tidak cerdas (menurut konsensus ilmiah)","Budi cerdas (dalam arti sempit; berdasarkan premis dasar)","Budi mahasiswa universitas lain (menurut definisi standar)","Semua orang cerdas (menurut pengertian baku)"],answer:0,hint:"Negasi premis minor tidak menghasilkan kesimpulan valid dalam silogisme Barbara.",explanation:"Premis: Semua M=C, Budi bukan M. Dari sini TIDAK bisa disimpulkan apakah Budi cerdas atau tidak. Budi bisa saja cerdas tanpa menjadi mahasiswa UGM (kesalahan: denying the antecedent).\nJawaban: A."},
{question:"KONVERGENSI : MENYATU :: DIVERGENSI : ...",options: ["Menyebar/memisah","Menyatu (dalam teori)","Berputar (pada prinsipnya)","Diam (menurut standar)","Konstan (secara literal)"],answer:0,hint:"Konvergen = menuju satu titik. Divergen = menjauh dari satu titik.",explanation:"Konvergensi: proses menuju satu titik/kesatuan (menyatu). Divergensi: proses menjauhi/menyebar ke berbagai arah (memisah). Antonim.\nJawaban: A."},
{question:"Teks: 'Data menunjukkan bahwa 85% siswa yang mengikuti bimbingan belajar lulus ujian, dibanding 60% yang tidak.' Kesimpulan yang PALING TEPAT adalah ...",options: ["Ada korelasi positif antara bimbingan belajar dan kelulusan, tapi kausalitas belum pasti","Bimbingan belajar menjamin kelulusan (sesuai klasifikasi umum; dalam pemahaman konvensional)","Siswa tanpa bimbel pasti gagal (berdasarkan teori dasar; menurut konsensus ilmiah)","Data ini tidak berguna (secara konseptual; dalam arti sempit)","Bimbingan belajar tidak berpengaruh (berdasarkan asumsi dasar; menurut definisi standar)"],answer:0,hint:"85% vs 60% menunjukkan perbedaan, tapi faktor lain (motivasi, SES) bisa menjadi confounding.",explanation:"Korelasi kuat (85% vs 60%) tapi kausalitas belum pasti: siswa yang memilih bimbel mungkin sudah lebih termotivasi/mampu secara finansial (selection bias/confounding).\nJawaban: A."},
{question:"EFIMERA : SINGKAT :: PERMANEN : ...",options: ["Kekal/abadi","Sementara","Cepat (secara umum)","Lambat (dalam teori)","Kecil (pada prinsipnya)"],answer:0,hint:"Efimeral/efemeral = berumur sangat singkat. Kebalikannya = permanen.",explanation:"Efimera (ephemeral) = sangat singkat, sebentar. Permanen = kekal, abadi, tidak berubah. Hubungan: sifat temporal yang berlawanan.\nJawaban: A."},
{question:"Kesalahan logika 'post hoc ergo propter hoc' terjadi ketika ...",options: ["Seseorang menganggap bahwa karena A terjadi sebelum B, maka A menyebabkan B","Argumen berputar-putar (dalam pengertian luas; dari perspektif akademis)","Menyerang pribadi lawan (dalam definisi teknis; sesuai klasifikasi umum)","Generalisasi dari satu kasus (dalam konteks umum; berdasarkan teori dasar)","Menggunakan otoritas yang salah (berdasarkan referensi umum; berdasarkan acuan formal)"],answer:0,hint:"Post hoc = setelah ini. Ergo propter hoc = maka karena ini. Urutan waktu bukan bukti kausalitas.",explanation:"Post hoc ergo propter hoc: 'setelah ini, maka karena ini.' Kesalahan menganggap urutan temporal = kausalitas. Contoh: 'Saya memakai kaos merah, tim saya menang, maka kaos merah menyebabkan kemenangan.'\nJawaban: A."},
{question:"REDUKSI : MENGURANGI :: AUGMENTASI : ...",options: ["Menambah/memperbesar","Mengurangi (pada dasarnya)","Mempertahankan (di konteks ini)","Mengubah (secara klasik)","Menghancurkan (secara umum)"],answer:0,hint:"Reduksi = pengurangan. Augmentasi = penambahan. Antonim.",explanation:"Reduksi: proses mengurangi/memperkecil. Augmentasi: proses menambah/memperbesar (augmented reality = realitas yang ditambah). Antonim.\nJawaban: A."},
{question:"Teks: 'Pendidikan karakter lebih penting daripada pendidikan akademis semata.' Asumsi yang mendasari pernyataan ini adalah ...",options: ["Pendidikan akademis saja tidak cukup untuk membentuk individu yang utuh","Pendidikan akademis tidak penting sama sekali (berdasarkan acuan formal)","Karakter tidak bisa diajarkan (secara konvensional; dalam pengertian luas)","Semua sekolah sudah mengajarkan karakter (pada konteks konvensional)","Akademis dan karakter tidak berhubungan (dalam batasan konvensional)"],answer:0,hint:"'Lebih penting' mengimplikasikan bahwa yang satu saja (akademis) kurang memadai.",explanation:"Pernyataan komparatif 'lebih penting' mengimplikasikan bahwa pendidikan akademis saja (tanpa karakter) tidak cukup. BUKAN berarti akademis tidak penting, melainkan karakter melengkapi akademis.\nJawaban: A."},
{question:"AMBIGUITAS : BERMAKNA GANDA :: UNIVOKAL : ...",options: ["Bermakna tunggal/jelas","Bermakna ganda (secara teknis)","Tidak bermakna (dalam praktik)","Bermakna banyak (pada dasarnya)","Kontradiktif (di konteks ini)"],answer:0,hint:"Ambi = dua. Uni = satu. Ambiguitas = bermakna ganda. Univokal = bermakna tunggal.",explanation:"Ambiguitas: kondisi memiliki lebih dari satu makna (ambigu). Univokal: memiliki tepat satu makna yang jelas (tidak ambigu). Kontras.\nJawaban: A."},
{question:"Paragraf: 'Produksi minyak sawit meningkatkan PDB. Namun, ekspansi perkebunan menyebabkan deforestasi yang mengurangi keanekaragaman hayati.' Jenis dilema yang digambarkan adalah ...",options: ["Trade-off antara pertumbuhan ekonomi dan kelestarian lingkungan","Tidak ada dilema (menurut definisi standar; secara terminologis)","Dilema moral (menurut pengertian baku; berdasarkan acuan formal)","Paradoks logika (sesuai paradigma tradisional; secara konvensional)","Kontradiksi data (menurut prinsip dasar; pada konteks konvensional)"],answer:0,hint:"Satu tindakan menghasilkan manfaat ekonomi tapi juga kerugian lingkungan = trade-off.",explanation:"Trade-off: pilihan yang menguntungkan di satu aspek (ekonomi/PDB) tapi merugikan di aspek lain (lingkungan/biodiversitas). Tidak ada solusi yang memuaskan kedua sisi sepenuhnya tanpa kompromi.\nJawaban: A."},
]);
