// BATCH 4 — TPS Verbal Expansion (50 Soal)
appendQuestions('tps_verbal', [
{question:"ANOMALI : PENYIMPANGAN :: PARADIGMA : ...",options:["Kerangka berpikir","Penyimpangan","Kesalahan","Masalah","Solusi"],answer:0,hint:"Anomali = penyimpangan dari normal. Paradigma = kerangka/model berpikir.",explanation:"Anomali bermakna penyimpangan/ketidaknormalan. Paradigma bermakna kerangka berpikir atau model konseptual yang digunakan dalam suatu bidang.\nJawaban: A."},
{question:"Silogisme: Semua mahasiswa UGM cerdas. Budi bukan mahasiswa UGM. Kesimpulan yang VALID adalah ...",options:["Tidak bisa ditarik kesimpulan tentang kecerdasan Budi","Budi tidak cerdas","Budi cerdas","Budi mahasiswa universitas lain","Semua orang cerdas"],answer:0,hint:"Negasi premis minor tidak menghasilkan kesimpulan valid dalam silogisme Barbara.",explanation:"Premis: Semua M=C, Budi bukan M. Dari sini TIDAK bisa disimpulkan apakah Budi cerdas atau tidak. Budi bisa saja cerdas tanpa menjadi mahasiswa UGM (kesalahan: denying the antecedent).\nJawaban: A."},
{question:"KONVERGENSI : MENYATU :: DIVERGENSI : ...",options:["Menyebar/memisah","Menyatu","Berputar","Diam","Konstan"],answer:0,hint:"Konvergen = menuju satu titik. Divergen = menjauh dari satu titik.",explanation:"Konvergensi: proses menuju satu titik/kesatuan (menyatu). Divergensi: proses menjauhi/menyebar ke berbagai arah (memisah). Antonim.\nJawaban: A."},
{question:"Teks: 'Data menunjukkan bahwa 85% siswa yang mengikuti bimbingan belajar lulus ujian, dibanding 60% yang tidak.' Kesimpulan yang PALING TEPAT adalah ...",options:["Ada korelasi positif antara bimbingan belajar dan kelulusan, tapi kausalitas belum pasti","Bimbingan belajar menjamin kelulusan","Siswa tanpa bimbel pasti gagal","Data ini tidak berguna","Bimbingan belajar tidak berpengaruh"],answer:0,hint:"85% vs 60% menunjukkan perbedaan, tapi faktor lain (motivasi, SES) bisa menjadi confounding.",explanation:"Korelasi kuat (85% vs 60%) tapi kausalitas belum pasti: siswa yang memilih bimbel mungkin sudah lebih termotivasi/mampu secara finansial (selection bias/confounding).\nJawaban: A."},
{question:"EFIMERA : SINGKAT :: PERMANEN : ...",options:["Kekal/abadi","Sementara","Cepat","Lambat","Kecil"],answer:0,hint:"Efimeral/efemeral = berumur sangat singkat. Kebalikannya = permanen.",explanation:"Efimera (ephemeral) = sangat singkat, sebentar. Permanen = kekal, abadi, tidak berubah. Hubungan: sifat temporal yang berlawanan.\nJawaban: A."},
{question:"Kesalahan logika 'post hoc ergo propter hoc' terjadi ketika ...",options:["Seseorang menganggap bahwa karena A terjadi sebelum B, maka A menyebabkan B","Argumen berputar-putar","Menyerang pribadi lawan","Generalisasi dari satu kasus","Menggunakan otoritas yang salah"],answer:0,hint:"Post hoc = setelah ini. Ergo propter hoc = maka karena ini. Urutan waktu bukan bukti kausalitas.",explanation:"Post hoc ergo propter hoc: 'setelah ini, maka karena ini.' Kesalahan menganggap urutan temporal = kausalitas. Contoh: 'Saya memakai kaos merah, tim saya menang, maka kaos merah menyebabkan kemenangan.'\nJawaban: A."},
{question:"REDUKSI : MENGURANGI :: AUGMENTASI : ...",options:["Menambah/memperbesar","Mengurangi","Mempertahankan","Mengubah","Menghancurkan"],answer:0,hint:"Reduksi = pengurangan. Augmentasi = penambahan. Antonim.",explanation:"Reduksi: proses mengurangi/memperkecil. Augmentasi: proses menambah/memperbesar (augmented reality = realitas yang ditambah). Antonim.\nJawaban: A."},
{question:"Teks: 'Pendidikan karakter lebih penting daripada pendidikan akademis semata.' Asumsi yang mendasari pernyataan ini adalah ...",options:["Pendidikan akademis saja tidak cukup untuk membentuk individu yang utuh","Pendidikan akademis tidak penting sama sekali","Karakter tidak bisa diajarkan","Semua sekolah sudah mengajarkan karakter","Akademis dan karakter tidak berhubungan"],answer:0,hint:"'Lebih penting' mengimplikasikan bahwa yang satu saja (akademis) kurang memadai.",explanation:"Pernyataan komparatif 'lebih penting' mengimplikasikan bahwa pendidikan akademis saja (tanpa karakter) tidak cukup. BUKAN berarti akademis tidak penting, melainkan karakter melengkapi akademis.\nJawaban: A."},
{question:"AMBIGUITAS : BERMAKNA GANDA :: UNIVOKAL : ...",options:["Bermakna tunggal/jelas","Bermakna ganda","Tidak bermakna","Bermakna banyak","Kontradiktif"],answer:0,hint:"Ambi = dua. Uni = satu. Ambiguitas = bermakna ganda. Univokal = bermakna tunggal.",explanation:"Ambiguitas: kondisi memiliki lebih dari satu makna (ambigu). Univokal: memiliki tepat satu makna yang jelas (tidak ambigu). Kontras.\nJawaban: A."},
{question:"Paragraf: 'Produksi minyak sawit meningkatkan PDB. Namun, ekspansi perkebunan menyebabkan deforestasi yang mengurangi keanekaragaman hayati.' Jenis dilema yang digambarkan adalah ...",options:["Trade-off antara pertumbuhan ekonomi dan kelestarian lingkungan","Tidak ada dilema","Dilema moral","Paradoks logika","Kontradiksi data"],answer:0,hint:"Satu tindakan menghasilkan manfaat ekonomi tapi juga kerugian lingkungan = trade-off.",explanation:"Trade-off: pilihan yang menguntungkan di satu aspek (ekonomi/PDB) tapi merugikan di aspek lain (lingkungan/biodiversitas). Tidak ada solusi yang memuaskan kedua sisi sepenuhnya tanpa kompromi.\nJawaban: A."},
]);
