// BATCH 5 — All Other Subjects Expansion (10 per subject = 140 total)

// TPS Verbal Extra
appendQuestions('tps_verbal', [
{question:"SIMBIOSIS : HUBUNGAN SALING MENGUNTUNGKAN :: PARASITISME : ...",options: ["Hubungan satu pihak diuntungkan, pihak lain dirugikan","Hubungan saling menguntungkan","Tidak ada hubungan","Hubungan netral","Hubungan kompetitif"],answer:0,hint:"Parasit = organisme yang hidup dari host, merugikan host.",explanation:"Simbiosis mutualisme: keduanya untung. Parasitisme: satu untung (parasit), satu rugi (inang). Komensalisme: satu untung, satu netral.\nJawaban: A."},
{question:"Kesimpulan induktif: 'Setiap logam yang diuji mengembang saat dipanaskan. Maka, SEMUA logam mengembang saat dipanaskan.' Kelemahan penalaran ini adalah ...",options: ["Generalisasi dari sampel terbatas ke seluruh populasi (bisa ada pengecualian)","Tidak ada kelemahan","Terlalu spesifik","Menggunakan deduksi","Premisnya salah"],answer:0,hint:"Induksi: dari khusus ke umum. Selalu ada kemungkinan contoh yang belum diuji bertentangan.",explanation:"Induksi: kesimpulan melampaui data yang diamati. Kelemahan: tidak pernah 100% pasti — logam yang BELUM diuji mungkin tidak mengembang (black swan). Berbeda dari deduksi yang conclusive.\nJawaban: A."},
{question:"KAUSAL : PENYEBAB :: KORELASIONAL : ...",options: ["Hubungan tanpa penyebab langsung","Tidak ada hubungan","Penyebab pasti","Acak","Eksperimental"],answer:0,hint:"Kausal = ada sebab-akibat. Korelasional = ada hubungan tapi belum tentu sebab-akibat.",explanation:"Kausal: hubungan sebab-akibat langsung (X menyebabkan Y). Korelasional: hubungan statistik tanpa implikasi kausalitas langsung (X berhubungan dengan Y, tapi mungkin bukan penyebab).\nJawaban: A."},
{question:"Kata 'implikasi' dalam konteks logika berarti ...",options: ["Konsekuensi atau akibat yang mengikuti dari suatu premis","Penyebab langsung","Definisi","Contoh","Pengecualian"],answer:0,hint:"Implikasi = jika P maka Q. Q adalah implikasi dari P.",explanation:"Implikasi (logical implication): hubungan 'jika...maka...' (P $\\to$ Q). Q terimplikasi oleh P berarti Q adalah konsekuensi logis dari P.\nJawaban: A."},
{question:"MIKROSKOPIK : SANGAT KECIL :: MAKROSKOPIK : ...",options: ["Sangat besar/terlihat mata telanjang","Agak kecil","Medium","Tidak terlihat","Transparan"],answer:0,hint:"Mikro = kecil. Makro = besar. -skopik = yang bisa dilihat.",explanation:"Mikroskopik: terlalu kecil untuk dilihat mata telanjang (perlu mikroskop). Makroskopik: cukup besar untuk dilihat mata telanjang. Kontras skala.\nJawaban: A."},
]);

// TPS Numerik Extra
appendQuestions('tps_numerik', [
{question:"Sebuah restoran mendapat 120 pelanggan/hari di weekday dan 200 di weekend. Rata-rata pelanggan per hari dalam seminggu = ...",options: ["142.86 (1000/7)","160","140","150","120"],answer:0,hint:"Total seminggu: 5x120 + 2x200 = 600+400 = 1000. Rata-rata: 1000/7.",explanation:"Weekday: 5 x 120 = 600.\nWeekend: 2 x 200 = 400.\nTotal: 1000. Rata-rata: 1000/7 = 142.86.\nJawaban: A."},
{question:"Jika rasio guru:murid = 1:20 dan ada 500 murid, berapa guru yang dibutuhkan?",options: ["25","20","50","10","100"],answer:0,hint:"1 guru per 20 murid. 500/20 = 25 guru.",explanation:"Guru = 500/20 = 25.\nRasio 1:20 berarti setiap 1 guru menangani 20 murid.\nJawaban: A."},
{question:"Sebuah truk mengangkut 5 ton barang. 20% tumpah di perjalanan. Sisa muatan = ...",options: ["4 ton","1 ton","3 ton","4.5 ton","3.5 ton"],answer:0,hint:"Sisa = 80% x 5 ton = 4 ton.",explanation:"Tumpah 20% = 0.2 x 5 = 1 ton.\nSisa = 5 - 1 = 4 ton.\nAtau: 0.8 x 5 = 4 ton.\nJawaban: A."},
{question:"Dua keran mengisi kolam. Keran A mengisi penuh dalam 6 jam, keran B mengisi penuh dalam 3 jam. Dibuka bersama, kolam penuh dalam ...",options: ["2 jam","1.5 jam","4.5 jam","9 jam","3 jam"],answer:0,hint:"Rate A=1/6, Rate B=1/3. Total=1/6+1/3=1/6+2/6=3/6=1/2.",explanation:"Rate gabungan = 1/6 + 1/3 = 1/6 + 2/6 = 3/6 = 1/2.\nWaktu = 1/(1/2) = 2 jam.\nJawaban: A."},
{question:"Sebuah kapal berlayar 60 km ke utara, lalu 80 km ke timur. Jarak terdekat ke titik awal = ...",options: ["100 km","140 km","70 km","200 km","120 km"],answer:0,hint:"Segitiga siku-siku: $\\sqrt{60^2+80^2}$ = $\\sqrt{3600+6400}$.",explanation:"d = $\\sqrt{3600+6400}$ = $\\sqrt{10000}$ = 100 km.\nTriple Pythagoras 60-80-100 (kelipatan 3-4-5).\nJawaban: A."},
]);

// TPS Logika Extra
appendQuestions('tps_logika', [
{question:"Tabel kebenaran: P AND (NOT P) selalu bernilai ...",options: ["FALSE (kontradiksi)","TRUE (tautologi)","Tergantung P","Kadang true kadang false","Tidak bisa ditentukan"],answer:0,hint:"P AND NOT P: jika P=T maka F AND T=F. Jika P=F maka F AND T=F. Selalu FALSE.",explanation:"P AND (NOT P) = kontradiksi = selalu FALSE.\nTidak mungkin sesuatu benar dan salah sekaligus.\nJawaban: A."},
{question:"Jika semua apel adalah buah, dapatkah disimpulkan bahwa beberapa buah adalah apel?",options: ["Ya, benar (konversi parsial valid)","Tidak, tidak bisa disimpulkan","Semua buah adalah apel","Tidak ada apel yang buah","Tergantung musim"],answer:0,hint:"All A are B => Some B are A (konversi valid untuk proposisi universal afirmatif).",explanation:"Jika semua A adalah B, maka pasti ada B yang merupakan A (setidaknya A itu sendiri). Konversi parsial dari universal affirmative valid.\nAll apples are fruits => Some fruits are apples.\nJawaban: A."},
{question:"Dalam teori himpunan, himpunan kosong adalah subset dari ...",options: ["Setiap himpunan (termasuk dirinya sendiri)","Tidak ada himpunan","Hanya dirinya sendiri","Hanya himpunan universal","Hanya himpunan bilangan real"],answer:0,hint:"Himpunan kosong adalah subset dari setiap himpunan. Ini adalah konvensi/aksioma.",explanation:"Himpunan kosong (empty set) subset setiap himpunan (termasuk dirinya sendiri). Ini valid secara logis karena: 'semua elemen himpunan kosong ada di A' vacuously true (tidak ada counterexample).\nJawaban: A."},
{question:"Modus ponens: Jika hujan maka basah. Hari ini hujan. Kesimpulan: ...",options: ["Hari ini basah","Hari ini tidak basah","Tidak tentu","Besok hujan","Hujan menyebabkan panas"],answer:0,hint:"Modus ponens: P->Q, P, maka Q.",explanation:"Modus ponens: Jika P maka Q. P benar. Maka Q benar.\nP: hujan. Q: basah.\nHujan -> basah. Hujan. Maka: basah.\nJawaban: A."},
{question:"Diberikan premis: 'Tidak ada kucing yang bisa terbang.' dan 'Tom adalah kucing.' Kesimpulan valid: ...",options: ["Tom tidak bisa terbang","Tom bisa terbang","Semua yang tidak terbang kucing","Tom bukan kucing","Tidak ada kesimpulan"],answer:0,hint:"Tidak ada kucing terbang + Tom kucing => Tom tidak terbang.",explanation:"No A are B. C is A. Therefore C is not B.\nTidak ada kucing terbang. Tom kucing. Tom tidak terbang.\nJawaban: A."},
]);

// TPS Spasial Extra
appendQuestions('tps_spasial', [
{question:"Berapa banyak segitiga yang terbentuk jika 5 garis ditarik dari semua titik sudut sebuah segi-5 ke setiap titik sudut lainnya?",options: ["10","5","15","20","8"],answer:0,hint:"C(5,3) = 10 segitiga. Setiap 3 titik dari 5 membentuk segitiga.",explanation:"Dari 5 titik sudut, setiap 3 titik membentuk segitiga.\nJumlah = C(5,3) = 10 segitiga.\nJawaban: A."},
{question:"Jaring-jaring kubus memiliki berapa banyak bentuk berbeda (tidak termasuk rotasi dan refleksi)?",options: ["11","6","8","10","12"],answer:0,hint:"Ada tepat 11 jaring-jaring kubus yang berbeda (hexomino yang membentuk kubus).",explanation:"Kubus memiliki 11 jaring-jaring unik (11 distinct hexominos that fold into a cube). Ini telah dibuktikan secara matematis.\nJawaban: A."},
{question:"Banyaknya simetri putar (rotational symmetry) huruf 'S' adalah ...",options: ["1 (rotasi 180 derajat)","0","2","4","tidak ada simetri"],answer:0,hint:"Huruf S tampak sama jika dirotasi 180 derajat (setengah putaran).",explanation:"Huruf S memiliki simetri rotasi orde 2 (180 derajat). Saat diputar 180 derajat, tampilannya sama.\nTidak memiliki simetri cermin (refleksi).\nJawaban: A."},
]);

// TKD Bahasa Indonesia Extra
appendQuestions('tkd_indo', [
{question:"Tipe paragraf yang menyajikan pendapat disertai alasan dan bukti untuk meyakinkan pembaca disebut ...",options: ["Paragraf argumentasi","Paragraf deskripsi","Paragraf narasi","Paragraf eksposisi","Paragraf persuasi"],answer:0,hint:"Argumentasi = pendapat + alasan/bukti logis. Persuasi = membujuk (lebih emosional).",explanation:"Argumentasi: menyajikan pendapat dengan alasan logis, data, dan bukti untuk meyakinkan pembaca. Berbeda dari persuasi (lebih menggunakan daya bujuk emosional) dan eksposisi (menjelaskan tanpa memihak).\nJawaban: A."},
{question:"Penggunaan tanda koma (,) yang BENAR: ...",options: ["Sebelum konjungsi 'tetapi' dalam kalimat majemuk setara","Sebelum setiap kata 'dan'","Setelah tanda titik","Di awal kalimat selalu","Mengganti tanda titik"],answer:0,hint:"Koma digunakan sebelum 'tetapi', 'melainkan', 'sedangkan' dalam kalimat setara.",explanation:"Koma sebelum 'tetapi' dalam kalimat majemuk: 'Dia pintar, tetapi malas.' Penggunaan koma yang tepat sesuai PUEBI.\nJawaban: A."},
{question:"Majas personifikasi terdapat dalam kalimat ...",options: ["Angin berbisik di telingaku (benda mati diberi sifat manusia)","Harga emas naik drastis","Indonesia merdeka tahun 1945","Dia berlari sangat kencang","Buku ini berisi 200 halaman"],answer:0,hint:"Personifikasi = benda mati diberi sifat/perilaku manusia.",explanation:"Personifikasi: 'angin berbisik' — angin (bukan manusia) diberi kemampuan manusia (berbisik). Majas yang menggambarkan benda mati seolah memiliki sifat/perilaku manusia.\nJawaban: A."},
{question:"Kalimat efektif harus memenuhi syarat utama ...",options: ["Kesepadanan subjek-predikat, kehematan, kecermatan, dan kelogisan","Panjang dan rumit","Menggunakan banyak imbuhan","Menggunakan kata asing","Tanpa tanda baca"],answer:0,hint:"Efektif = menyampaikan gagasan dengan tepat dan mudah dipahami pembaca.",explanation:"Kalimat efektif:\n1. Kesepadanan: S-P-O-K lengkap dan sesuai.\n2. Kehematan: tidak bertele-tele (tidak ada redundansi).\n3. Kecermatan: pilihan kata tepat.\n4. Kelogisan: makna logis dan masuk akal.\nJawaban: A."},
{question:"Contoh kata serapan dari bahasa Arab dalam bahasa Indonesia adalah ...",options: ["Kursi, kitab, masjid, ilmu (semuanya dari bahasa Arab)","Televisi, radio, komputer","Sushi, kimono, karate","Pasta, pizza, opera","Angpao, bakso, tahu"],answer:0,hint:"Banyak kata agama, pendidikan, dan kehidupan sehari-hari diserap dari bahasa Arab.",explanation:"Kata serapan Arab: kursi, kitab, masjid, ilmu, doa, akal, alam, wajib, hukum, adil, dll. Masuk melalui penyebaran Islam di Nusantara.\nJawaban: A."},
]);

// TKD Bahasa Inggris Extra
appendQuestions('tkd_eng', [
{question:"The third conditional: 'If I had studied harder, I ____ the exam.'",options: ["would have passed","will pass","would pass","had passed","has passed"],answer:0,hint:"Third conditional: If + past perfect, would/could + have + past participle.",explanation:"Third conditional (unreal past): If + past perfect (had studied), main clause: would have + past participle (would have passed). Expresses regret about the past.\nAnswer: A."},
{question:"Which sentence uses a gerund correctly?",options: ["Swimming is good exercise. (-ing as subject/noun)","He swim every day.","She has swimming.","They will swimming.","I am swim."],answer:0,hint:"Gerund = verb + -ing used as a NOUN. 'Swimming' is the subject here.",explanation:"Gerund: verb+-ing functioning as a noun. 'Swimming' = subject of the sentence. Other gerund uses: object ('I enjoy swimming'), complement ('My hobby is swimming').\nAnswer: A."},
{question:"The word 'ubiquitous' means:",options: ["Present everywhere simultaneously","Rare and hard to find","Extremely large","Very old","Completely silent"],answer:0,hint:"Ubiquitous: existing or being everywhere at the same time. Think: WiFi is ubiquitous.",explanation:"Ubiquitous: found everywhere, omnipresent. Example: 'Smartphones have become ubiquitous in modern society.' From Latin 'ubique' = everywhere.\nAnswer: A."},
{question:"Choose the correct passive voice: 'The book ____ by millions of people.'",options: ["has been read","has been reading","have been read","was reading","is reading"],answer:0,hint:"Passive: has/have + been + past participle. Subject 'book' = singular = 'has'.",explanation:"Passive voice (present perfect): has/have been + past participle.\n'The book' = singular subject = 'has'.\n'has been read' (read=past participle of read).\nAnswer: A."},
{question:"An oxymoron is best defined as:",options: ["A figure of speech combining contradictory terms (e.g., 'deafening silence')","A comparison using 'like' or 'as'","An extreme exaggeration","A rhetorical question","A reference to mythology"],answer:0,hint:"Oxy-moron: sharp-foolish. Two contradictory words together for effect.",explanation:"Oxymoron: combining two seemingly contradictory words for rhetorical effect. Examples: 'deafening silence', 'living dead', 'bittersweet', 'alone together'.\nA simile uses 'like/as'. Hyperbole = exaggeration.\nAnswer: A."},
]);

// Saintek Fisika Extra
appendQuestions('saintek_fisika', [
{question:"Hukum kekekalan energi menyatakan bahwa energi ...",options: ["Tidak dapat diciptakan atau dimusnahkan, hanya berubah bentuk","Selalu bertambah","Selalu berkurang","Bisa diciptakan dari ketiadaan","Hanya ada dalam bentuk panas"],answer:0,hint:"Hukum I Termodinamika: energi total sistem tertutup = konstan.",explanation:"Hukum kekekalan energi: energi total dalam sistem tertutup konstan. Energi bisa berubah bentuk (kinetik ↔ potensial ↔ panas ↔ listrik ↔ kimia) tapi tidak bisa diciptakan/dimusnahkan.\nJawaban: A."},
{question:"Resistor 10 ohm dan 15 ohm dipasang paralel. Resistansi total = ...",options: ["6 ohm","25 ohm","5 ohm","150 ohm","12.5 ohm"],answer:0,hint:"Paralel: 1/Rtot = 1/R1+1/R2 = 1/10+1/15 = 3/30+2/30 = 5/30 = 1/6.",explanation:"1/Rtot = 1/10+1/15 = 3/30+2/30 = 5/30.\nRtot = 30/5 = 6 ohm.\nParalel: selalu lebih kecil dari resistor terkecil.\nJawaban: A."},
{question:"Frekuensi gelombang yang periodenya 0.02 detik = ...",options: ["50 Hz","20 Hz","0.02 Hz","200 Hz","500 Hz"],answer:0,hint:"f = 1/T = 1/0.02.",explanation:"f = 1/T = 1/0.02 = 50 Hz.\nJawaban: A."},
{question:"Tekanan hidrostatis pada kedalaman h dalam fluida = ...",options: ["rho x g x h","m x g","F/A","rho x v","P x V"],answer:0,hint:"Tekanan hidrostatis = densitas x gravitasi x kedalaman.",explanation:"P = rho g h.\nrho = massa jenis fluida (kg/m^3).\ng = percepatan gravitasi (10 m/s^2).\nh = kedalaman (m).\nJawaban: A."},
{question:"Daya listrik rumusnya P = ...",options: ["V x I (tegangan x arus)","V/I","I/V","V^2/I","I^2/V"],answer:0,hint:"P = VI = I^2R = V^2/R. Satuan: Watt.",explanation:"P = V x I.\nAlternatif: P = I^2 R (dari V=IR).\nP = V^2/R.\nSatuan: Watt (W) = Joule/detik.\nJawaban: A."},
]);

// Saintek Kimia Extra
appendQuestions('saintek_kimia', [
{question:"Asam basa Bronsted-Lowry: Asam adalah ...",options: ["Donor proton (H+)","Akseptor proton","Donor elektron","Akseptor elektron","Netral"],answer:0,hint:"Bronsted: asam = pemberi H+. Basa = penerima H+.",explanation:"Bronsted-Lowry:\nAsam = donor/pemberi proton (H+).\nBasa = akseptor/penerima proton (H+).\nContoh: HCl + H2O -> H3O+ + Cl-. HCl = asam (donor H+), H2O = basa (akseptor H+).\nJawaban: A."},
{question:"Nomor atom (Z) menunjukkan jumlah ... dalam inti atom",options: ["Proton","Neutron","Elektron","Proton + neutron","Massa"],answer:0,hint:"Z = jumlah proton = identitas unsur. A = massa atom = proton + neutron.",explanation:"Z (nomor atom) = jumlah proton = jumlah elektron (atom netral). Identitas unsur ditentukan oleh Z.\nA (nomor massa) = proton + neutron.\nN (neutron) = A - Z.\nJawaban: A."},
{question:"Prinsip Le Chatelier menyatakan bahwa jika sistem kesetimbangan diberi gangguan, maka ...",options: ["Sistem akan bergeser untuk mengurangi efek gangguan tersebut","Sistem tidak berubah","Kesetimbangan hilang","Reaksi berhenti","Semua produk terbentuk"],answer:0,hint:"Le Chatelier: kesetimbangan melawan gangguan (compensating shift).",explanation:"Prinsip Le Chatelier: jika kesetimbangan diganggu (konsentrasi, suhu, tekanan), sistem bergeser ke arah yang mengurangi gangguan.\nTambah reaktan: geser ke produk. Naikkan suhu: geser ke endotermik.\nJawaban: A."},
{question:"Senyawa organik yang mengandung gugus fungsi -OH (hidroksi) disebut ...",options: ["Alkohol","Aldehid","Keton","Asam karboksilat","Ester"],answer:0,hint:"-OH = hidroksi = alkohol. -CHO = aldehid. -COOH = asam karboksilat.",explanation:"Alkohol: R-OH (gugus hidroksi).\nAldehid: R-CHO. Keton: R-CO-R. Asam karboksilat: R-COOH. Ester: R-COO-R.\nContoh alkohol: etanol (C2H5OH).\nJawaban: A."},
{question:"Reaksi eksoterm memiliki delta H yang ...",options: ["Negatif (melepaskan energi/panas ke lingkungan)","Positif","Nol","Tidak terdefinisi","Berubah-ubah"],answer:0,hint:"Ekso = keluar. Energi keluar dari sistem = delta H negatif.",explanation:"Eksoterm: energi keluar (dilepaskan) -> delta H < 0 (negatif). Lingkungan menjadi lebih panas.\nEndoterm: energi masuk (diserap) -> delta H > 0 (positif). Lingkungan menjadi lebih dingin.\nJawaban: A."},
]);

// Saintek Biologi Extra
appendQuestions('saintek_biologi', [
{question:"Proses pembelahan sel yang menghasilkan 2 sel anak identik disebut ...",options: ["Mitosis","Meiosis","Amitosis","Binary fission","Budding"],answer:0,hint:"Mitosis: 1 sel -> 2 sel identik (2n -> 2n). Meiosis: 1 sel -> 4 sel haploid.",explanation:"Mitosis: pembelahan sel yang menghasilkan 2 sel anak yang identik secara genetis (diploid). Fungsi: pertumbuhan, perbaikan jaringan.\nMeiosis: menghasilkan 4 sel haploid (gamet). Fungsi: reproduksi seksual.\nJawaban: A."},
{question:"Sistem peredaran darah manusia bersifat ganda karena ...",options: ["Darah melewati jantung DUA kali dalam satu siklus (peredaran kecil dan besar)","Manusia memiliki 2 jantung","Ada 2 jenis darah","Darah mengalir sekali saja","Jantung hanya memompa sekali"],answer:0,hint:"Ganda = double circulation. Peredaran kecil (paru-paru) + besar (seluruh tubuh).",explanation:"Peredaran ganda:\n1. Peredaran kecil: jantung -> paru-paru -> jantung (oksigenasi).\n2. Peredaran besar: jantung -> seluruh tubuh -> jantung (distribusi O2).\nDarah melewati jantung 2x per siklus.\nJawaban: A."},
{question:"Enzim mempercepat reaksi kimia dengan cara ...",options: ["Menurunkan energi aktivasi reaksi","Menambah energi aktivasi","Mengubah produk reaksi","Menaikkan suhu reaksi","Menambah konsentrasi substrat"],answer:0,hint:"Enzim = katalis biologis. Menurunkan barrier energi tanpa dikonsumsi.",explanation:"Enzim menurunkan energi aktivasi (Ea) sehingga reaksi berlangsung lebih cepat pada suhu tubuh normal. Enzim tidak dikonsumsi (bisa digunakan ulang) dan spesifik terhadap substrat (lock and key model).\nJawaban: A."},
{question:"Urutan taksonomi (klasifikasi) dari tingkat tertinggi ke terendah: ...",options: ["Kingdom - Phylum - Class - Order - Family - Genus - Species","Species - Genus - Family - Order - Class","Kingdom - Species - Genus","Genus - Species - Kingdom","Family - Order - Class saja"],answer:0,hint:"King Philip Came Over For Good Spaghetti.",explanation:"Kingdom (Kerajaan) -> Phylum/Divisio (Filum) -> Class (Kelas) -> Order (Ordo) -> Family (Famili) -> Genus (Marga) -> Species (Jenis).\nMnemonik: King Philip Came Over For Good Spaghetti.\nJawaban: A."},
{question:"Seleksi alam (Darwin) menyatakan bahwa ...",options: ["Individu dengan sifat yang paling sesuai lingkungan memiliki peluang bertahan hidup dan reproduksi lebih besar","Semua individu memiliki peluang sama","Individu terkuat selalu menang","Evolusi bersifat acak sepenuhnya","Spesies tidak berubah"],answer:0,hint:"Survival of the fittest = yang PALING COCOK dengan lingkungan, bukan yang terkuat.",explanation:"Natural selection: variasi ada dalam populasi. Individu dengan sifat yang menguntungkan di lingkungan tertentu (fittest = paling fit/cocok, BUKAN terkuat) lebih mungkin bertahan dan bereproduksi, mewariskan sifat tersebut.\nJawaban: A."},
]);

// Soshum Ekonomi Extra
appendQuestions('soshum_ekonomi', [
{question:"GDP (Gross Domestic Product) mengukur ...",options: ["Total nilai barang dan jasa yang diproduksi dalam suatu negara selama periode tertentu","Kekayaan individu","Jumlah uang beredar","Tingkat pengangguran","Jumlah penduduk"],answer:0,hint:"GDP = ukuran output ekonomi suatu negara. Produksi domestik bruto.",explanation:"GDP: total nilai pasar dari semua barang dan jasa final yang diproduksi dalam batas geografis suatu negara dalam periode waktu tertentu (biasanya 1 tahun). Ukuran utama ukuran ekonomi.\nJawaban: A."},
{question:"Pada titik keseimbangan pasar (equilibrium), ...",options: ["Kuantitas yang diminta = kuantitas yang ditawarkan (Qd=Qs)","Supply melebihi demand","Demand melebihi supply","Harga nol","Tidak ada transaksi"],answer:0,hint:"Equilibrium: kurva demand dan supply bertemu. Tidak ada kelebihan/kekurangan.",explanation:"Keseimbangan pasar: Qd = Qs pada harga keseimbangan (Pe). Tidak ada kelebihan penawaran (surplus) atau kelebihan permintaan (shortage). Pasar clear.\nJawaban: A."},
{question:"Kebijakan fiskal ekspansif untuk mengatasi resesi meliputi ...",options: ["Meningkatkan belanja pemerintah dan/atau menurunkan pajak","Menaikkan suku bunga","Menjual obligasi pemerintah","Menghentikan semua pengeluaran","Menaikkan pajak"],answer:0,hint:"Fiskal ekspansif: naikkan spending, turunkan pajak => stimulasi ekonomi.",explanation:"Kebijakan fiskal ekspansif (pemerintah):\n1. Meningkatkan belanja pemerintah (G naik)\n2. Menurunkan pajak (T turun)\n3. Tujuan: meningkatkan aggregate demand, menciptakan lapangan kerja, mendorong pertumbuhan\nJawaban: A."},
{question:"Elastisitas harga permintaan mengukur ...",options: ["Seberapa responsif kuantitas yang diminta terhadap perubahan harga","Seberapa cepat harga berubah","Total pendapatan penjual","Jumlah barang yang diproduksi","Tingkat inflasi"],answer:0,hint:"Elastisitas = %perubahan Qd / %perubahan P. Measure of responsiveness.",explanation:"Price elasticity of demand = %delta Qd / %delta P.\nElastis (>1): Qd sangat responsif terhadap harga (barang mewah).\nInelastis (<1): Qd kurang responsif (kebutuhan pokok).\nJawaban: A."},
{question:"Uang memiliki fungsi utama sebagai ...",options: ["Alat tukar (medium of exchange), satuan hitung (unit of account), penyimpan nilai (store of value)","Hanya alat tukar","Hanya untuk menabung","Hanya untuk pajak","Dekorasi"],answer:0,hint:"3 fungsi uang: medium of exchange, unit of account, store of value.",explanation:"Fungsi uang:\n1. Medium of exchange (alat pembayaran)\n2. Unit of account (satuan hitung/pengukur nilai)\n3. Store of value (penyimpan kekayaan)\n4. (Tambahan) Standard of deferred payment\nJawaban: A."},
]);

// Soshum Sosiologi Extra
appendQuestions('soshum_sosiologi', [
{question:"Konflik sosial menurut Lewis Coser bisa bersifat FUNGSIONAL karena ...",options: ["Dapat memperkuat solidaritas kelompok dan mendorong perubahan sosial positif","Selalu destruktif","Tidak pernah memiliki manfaat","Hanya menimbulkan kekerasan","Menghancurkan masyarakat"],answer:0,hint:"Coser: konflik tidak selalu negatif — bisa meningkatkan kohesi internal kelompok.",explanation:"Lewis Coser: konflik fungsional (positive) dapat:\n1. Memperkuat solidaritas in-group\n2. Mendorong inovasi dan perubahan\n3. Menjadi safety valve (pelepas ketegangan)\n4. Memperjelas norma dan batas kelompok\nJawaban: A."},
{question:"Diferensiasi sosial berbeda dari stratifikasi sosial karena ...",options: ["Diferensiasi = pembedaan horizontal tanpa peringkat. Stratifikasi = pembedaan vertikal dengan peringkat","Keduanya identik","Diferensiasi selalu vertikal","Stratifikasi tidak ada hierarki","Diferensiasi hanya di kota"],answer:0,hint:"Diferensiasi = beda tapi setara (suku, agama). Stratifikasi = beda dan bertingkat (kayan-miskin).",explanation:"Diferensiasi: pembedaan horizontal (suku, agama, gender) tanpa hierarki tinggi-rendah.\nStratifikasi: pembedaan vertikal (kaya-miskin, upper-lower class) dengan hierarki/ranking.\nJawaban: A."},
]);

// Soshum Sejarah Extra
appendQuestions('soshum_sejarah', [
{question:"Perang kemerdekaan Indonesia yang paling heroik '10 November' terjadi di kota ...",options: ["Surabaya (1945)","Jakarta","Bandung","Yogyakarta","Semarang"],answer:0,hint:"Pertempuran Surabaya 10 November 1945 = Hari Pahlawan.",explanation:"Pertempuran Surabaya (10 November 1945): pertempuran terbesar dan paling berdarah melawan Inggris (Brigadir Mallaby terbunuh). Diperingati sebagai Hari Pahlawan. Bung Tomo membakar semangat lewat radio.\nJawaban: A."},
{question:"Kerajaan Majapahit mencapai puncak kejayaan pada masa pemerintahan ...",options: ["Hayam Wuruk dengan Mahapatih Gajah Mada","Ken Arok","Raden Wijaya","Airlangga","Kertanegara"],answer:0,hint:"Majapahit jaya: Hayam Wuruk (raja) + Gajah Mada (mahapatih, Sumpah Palapa).",explanation:"Majapahit puncak: Hayam Wuruk (1350-1389) dengan Mahapatih Gajah Mada (Sumpah Palapa: tidak makan palapa sebelum menyatukan Nusantara). Menguasai hampir seluruh Nusantara.\nJawaban: A."},
]);

// Soshum Geografi Extra
appendQuestions('soshum_geografi', [
{question:"Letak astronomis Indonesia adalah ...",options: ["6 LU - 11 LS dan 95 BT - 141 BT","0-90 LU dan 0-180 BT","23.5 LU - 23.5 LS","60 LU - 60 LS","10-20 LU dan 100-150 BT"],answer:0,hint:"Indonesia membentang dari Sabang (utara) ke Merauke (selatan, timur).",explanation:"Letak astronomis Indonesia:\n- 6 derajat LU (Sabang) sampai 11 derajat LS (Roti)\n- 95 derajat BT (Sabang) sampai 141 derajat BT (Merauke)\nBerpengaruh: iklim tropis, panjang siang-malam relatif sama.\nJawaban: A."},
{question:"Dampak pemanasan global (global warming) terhadap permukaan laut adalah ...",options: ["Kenaikan permukaan laut akibat pencairan es kutub dan ekspansi termal air laut","Penurunan permukaan laut","Tidak ada perubahan","Air laut membeku","Permukaan tetap stabil"],answer:0,hint:"Suhu naik -> es kutub mencair + air laut mengembang -> sea level rise.",explanation:"Pemanasan global -> kenaikan permukaan laut (sea level rise) karena:\n1. Pencairan es kutub dan gletser (tambahan volume air)\n2. Ekspansi termal (air hangat mengembang)\nAncaman: banjir pesisir, tenggelamnya pulau kecil.\nJawaban: A."},
]);

// Saintek Mat IPA Extra
appendQuestions('saintek_matipa', [
{question:"Gradient dari fungsi f(x,y) = x^2 + y^2 di titik (1,2) adalah ...",options: ["(2, 4)","(1, 2)","(4, 2)","(2, 2)","(0, 0)"],answer:0,hint:"Gradient = (df/dx, df/dy). df/dx=2x, df/dy=2y. Di (1,2): (2,4).",explanation:"Gradient f = (df/dx, df/dy) = (2x, 2y).\nDi titik (1,2): (2(1), 2(2)) = (2, 4).\nGradient menunjuk ke arah kenaikan tercepat.\nJawaban: A."},
{question:"Eigenvalue dari matriks [[3,0],[0,5]] adalah ...",options: ["3 dan 5","0 dan 0","15 dan 0","8 dan -2","1 dan 1"],answer:0,hint:"Matriks diagonal: eigenvalue = elemen diagonal.",explanation:"Matriks diagonal: eigenvalue = elemen diagonal utama.\nlambda_1 = 3, lambda_2 = 5.\ndet(A-lambda.I) = (3-lambda)(5-lambda) = 0.\nJawaban: A."},
]);
