// BATCH 6 — Final All Subjects Mega Expansion (10-15 per subject)

appendQuestions('tps_verbal', [
{question:"SKEPTIS : MERAGUKAN :: OPTIMIS : ...",options: ["Yakin dan positif","Meragukan","Pesimis","Netral","Apatis"],answer:0,hint:"Skeptis = meragukan/curiga. Optimis = yakin akan hal baik.",explanation:"Skeptis: sikap meragukan, mempertanyakan. Optimis: sikap yakin dan positif tentang masa depan. Kontras sikap.\nJawaban: A."},
{question:"Kesalahan logika 'appeal to emotion' terjadi ketika ...",options: ["Argumen menggunakan emosi (kasihan, takut, marah) untuk menggantikan bukti logis","Argumen terlalu logis","Emosi tidak digunakan","Argumen berdasarkan data","Menggunakan statistik"],answer:0,hint:"Appeal to emotion: 'kasihan dong...' bukan bukti logis.",explanation:"Appeal to emotion: menggunakan emosi (kasihan, takut, cinta, marah) untuk meyakinkan alih-alih menyajikan bukti dan argumen logis. Emosi bukan pengganti logika.\nJawaban: A."},
{question:"HOMOGEN : SERAGAM :: HETEROGEN : ...",options: ["Beragam/berbeda-beda","Seragam","Sama","Tunggal","Kosong"],answer:0,hint:"Homo = sama. Hetero = berbeda. Homogen = seragam. Heterogen = beragam.",explanation:"Homogen: terdiri dari komponen yang sama (seragam). Heterogen: terdiri dari komponen yang berbeda-beda (beragam). Kontras komposisi.\nJawaban: A."},
{question:"Paragraf: 'Negara X melarang plastik sekali pakai dan sampah plastik turun 40%. Negara Y belum melarang dan sampah naik 20%.' Klaim terkuat dari data ini:",options: ["Larangan plastik sekali pakai berkorelasi dengan penurunan sampah plastik","Larangan terbukti menghilangkan 100% sampah","Negara Y lebih kotor dari X","Plastik tidak berbahaya","Data tidak berguna"],answer:0,hint:"Ada korelasi kuat tapi belum tentu X penyebab tunggal. Klaim terukur dan hati-hati.",explanation:"Data menunjukkan korelasi yang kuat (40% turun vs 20% naik). Klaim terkuat: korelasi, bukan kausalitas absolut (mungkin ada faktor lain). Tapi bukti cukup kuat untuk mendukung efektivitas larangan.\nJawaban: A."},
{question:"DEDUKTIF : UMUM KE KHUSUS :: INDUKTIF : ...",options: ["Khusus ke umum","Umum ke umum","Khusus ke khusus","Tidak ada kesimpulan","Acak"],answer:0,hint:"Deduksi: premis umum -> kesimpulan khusus. Induksi: observasi khusus -> kesimpulan umum.",explanation:"Deduktif: dari premis umum (universal) ke kesimpulan khusus (particular). Induktif: dari observasi khusus ke generalisasi umum.\nJawaban: A."},
]);

appendQuestions('tps_numerik', [
{question:"Seorang agen menjual rumah Rp800 juta dan mendapat komisi 2.5%. Besar komisi = ...",options: ["Rp20.000.000","Rp200.000.000","Rp2.000.000","Rp80.000.000","Rp25.000.000"],answer:0,hint:"2.5% x 800.000.000 = 0.025 x 800.000.000.",explanation:"Komisi = 2.5% x 800.000.000 = 0.025 x 800.000.000 = 20.000.000.\nRp20 juta.\nJawaban: A."},
{question:"Sebuah lapangan berbentuk lingkaran berdiameter 28m. Luas lapangan = ... (pi=22/7)",options: ["616 m^2","88 m","2464 m^2","154 m^2","308 m^2"],answer:0,hint:"r=14. L = pi r^2 = 22/7 x 196 = 616.",explanation:"r = 14 m.\nL = 22/7 x 14^2 = 22/7 x 196 = 22 x 28 = 616 m^2.\nJawaban: A."},
{question:"Suhu turun dari 5 derajat C menjadi -3 derajat C. Penurunan suhu = ...",options: ["8 derajat","2 derajat","-8 derajat","3 derajat","5 derajat"],answer:0,hint:"Dari +5 ke -3: penurunan = 5-(-3) = 5+3 = 8.",explanation:"Penurunan = 5 - (-3) = 5 + 3 = 8 derajat.\nJawaban: A."},
{question:"Jika 40% siswa lulus dan ada 500 peserta, berapa yang TIDAK lulus?",options: ["300","200","100","400","250"],answer:0,hint:"Tidak lulus = 60% x 500 = 300.",explanation:"Lulus = 40% = 200 siswa.\nTidak lulus = 60% = 300 siswa.\nAtau: 500 - 200 = 300.\nJawaban: A."},
{question:"Rata-rata 3 ulangan: 75, 82, dan x. Jika rata-rata keseluruhan harus >= 80, maka x minimal = ...",options: ["83","80","78","85","75"],answer:0,hint:"(75+82+x)/3 >= 80 => 157+x >= 240 => x >= 83.",explanation:"(75+82+x)/3 >= 80.\n157+x >= 240.\nx >= 83.\nMinimal x = 83.\nJawaban: A."},
]);

appendQuestions('tps_logika', [
{question:"Silogisme disjungtif: A atau B. Bukan A. Maka ...",options: ["B","Bukan B","A dan B","Bukan A dan bukan B","Tidak bisa ditentukan"],answer:0,hint:"A or B. Not A. Therefore B. Disjunctive syllogism.",explanation:"Disjunctive syllogism: P or Q. Not P. Therefore Q.\nA atau B. Bukan A. Maka B (karena salah satu harus benar).\nJawaban: A."},
{question:"Pernyataan 'Jika 2+2=5, maka saya presiden' bernilai ...",options: ["TRUE (karena premisnya salah, implikasi vakuously true)","FALSE","Tidak bisa ditentukan","Tergantung","Paradoks"],answer:0,hint:"P->Q: jika P salah, implikasi SELALU benar (vacuous truth).",explanation:"P = '2+2=5' (salah). Q = 'saya presiden'.\nP->Q: jika P salah, implikasi TRUE (vacuously true).\nHanya FALSE jika P benar DAN Q salah.\nJawaban: A."},
{question:"Diberikan: 'Tidak semua burung bisa terbang.' Ekuivalen dengan ...",options: ["Ada (setidaknya satu) burung yang tidak bisa terbang","Semua burung tidak bisa terbang","Semua burung bisa terbang","Tidak ada burung","Ada burung yang bisa terbang"],answer:0,hint:"NOT(All A are B) = Some A are not B. Negasi universal = partikular negatif.",explanation:"Negasi 'semua A adalah B' = 'ada A yang bukan B'.\n'Tidak semua burung bisa terbang' = 'ada burung yang tidak bisa terbang' (contoh: pinguin, kiwi).\nJawaban: A."},
]);

appendQuestions('tps_spasial', [
{question:"Jumlah sisi, rusuk, dan titik sudut kubus masing-masing = ...",options: ["6, 12, 8","4, 6, 4","8, 12, 6","6, 8, 12","12, 6, 8"],answer:0,hint:"Kubus: 6 sisi (persegi), 12 rusuk, 8 titik sudut. V-E+F = 8-12+6 = 2.",explanation:"Kubus: 6 sisi, 12 rusuk, 8 vertex.\nRumus Euler: V-E+F = 8-12+6 = 2. Benar!\nJawaban: A."},
{question:"Sebuah prisma segitiga memiliki 5 sisi, 9 rusuk, dan ... titik sudut",options: ["6","5","8","10","4"],answer:0,hint:"Prisma segitiga: 2 alas segitiga + 3 sisi persegi = 5 sisi. V = 6.",explanation:"Prisma segitiga: 2 alas + 3 sisi lateral = 5 sisi.\nRusuk: 9 (3 atas + 3 bawah + 3 tegak).\nVerteks: 6 (3 atas + 3 bawah).\nEuler: 6-9+5 = 2. Benar!\nJawaban: A."},
]);

appendQuestions('tkd_indo', [
{question:"Perbedaan antara konjungsi koordinatif dan subordinatif: ...",options: ["Koordinatif menghubungkan klausa setara (dan, atau, tetapi). Subordinatif menghubungkan klausa tidak setara (karena, meskipun, ketika)","Keduanya sama","Koordinatif hanya untuk kalimat pendek","Subordinatif hanya di awal kalimat","Tidak ada perbedaan"],answer:0,hint:"Koordinatif = setara (FANBOYS). Subordinatif = induk-anak kalimat.",explanation:"Koordinatif: dan, atau, tetapi, melainkan (klausa setara).\nSubordinatif: karena, meskipun, ketika, jika, agar, supaya (klausa tidak setara: induk + anak).\nJawaban: A."},
{question:"Kalimat aktif 'Ani memakan roti' jika diubah ke kalimat pasif menjadi ...",options: ["Roti dimakan (oleh) Ani","Roti memakan Ani","Ani dimakan roti","Memakan roti Ani","Roti Ani makan"],answer:0,hint:"Aktif: S+me-V+O. Pasif: O+di-V+(oleh)+S.",explanation:"Aktif: Ani (S) memakan (P) roti (O).\nPasif: Roti (S) dimakan (P) (oleh) Ani (keterangan pelaku).\nPrefiks me- diganti di-.\nJawaban: A."},
{question:"Kata majemuk adalah gabungan dua kata dasar yang membentuk makna baru. Contoh: ...",options: ["Rumah sakit (bukan 'rumah yang sakit')","Rumah besar","Makanan enak","Anak kecil","Buku tebal"],answer:0,hint:"Kata majemuk: 2 kata yang maknanya berbeda dari makna kata-kata penyusunnya.",explanation:"Kata majemuk: gabungan kata yang maknanya tidak bisa ditafsirkan dari makna literal masing-masing kata.\n'Rumah sakit' bukan rumah yang sakit, tapi tempat berobat.\n'Matahari' bukan mata hari.\nJawaban: A."},
]);

appendQuestions('tkd_eng', [
{question:"Which word is a synonym for 'ephemeral'?",options: ["Transient (short-lived)","Permanent","Eternal","Infinite","Constant"],answer:0,hint:"Ephemeral = lasting for a very short time. Synonym: transient, fleeting.",explanation:"Ephemeral: lasting for a very short time (Greek: ephemeros = lasting a day). Synonyms: transient, fleeting, brief. Antonyms: permanent, enduring.\nAnswer: A."},
{question:"The subjunctive mood is used in the sentence:",options: ["I suggest that he BE present at the meeting. (subjunctive 'be' instead of 'is')","He is present at the meeting.","He was at the meeting.","He will be present.","He has been present."],answer:0,hint:"Subjunctive: after verbs of suggestion/demand/recommendation. Use base form.",explanation:"Subjunctive mood: used after verbs like suggest, recommend, demand, insist + that + subject + BASE FORM (no -s, no tense marking).\n'I suggest that he BE' (not 'is').\nAnswer: A."},
{question:"Choose the word that best completes: 'Despite her ____ efforts, the project failed.'",options: ["herculean (enormous, requiring great strength)","lazy","minimal","careless","indifferent"],answer:0,hint:"'Despite' = contrast. Project failed DESPITE great effort. Need word = huge effort.",explanation:"'Despite' signals contrast: even though she tried very hard, it failed. 'Herculean' = requiring great strength/effort (from Hercules). The enormous effort still wasn't enough.\nAnswer: A."},
]);

appendQuestions('saintek_fisika', [
{question:"Hukum Ohm menyatakan hubungan V = ...",options: ["I x R (tegangan = arus x hambatan)","I / R","I + R","I - R","R / I"],answer:0,hint:"V = IR. Arus berbanding lurus tegangan, terbalik hambatan.",explanation:"Hukum Ohm: V = I x R.\nV = tegangan (Volt).\nI = arus (Ampere).\nR = hambatan (Ohm).\nJawaban: A."},
{question:"Efek Doppler menyebabkan frekuensi yang diamati ...",options: ["Meningkat saat sumber mendekati pengamat, menurun saat menjauh","Selalu tetap","Selalu meningkat","Selalu menurun","Tidak berpengaruh"],answer:0,hint:"Ambulans mendekat: frekuensi naik (pitch tinggi). Menjauh: turun (pitch rendah).",explanation:"Efek Doppler: Sumber mendekati -> panjang gelombang memendek -> frekuensi naik (blueshift).\nSumber menjauh -> panjang gelombang memanjang -> frekuensi turun (redshift).\nJawaban: A."},
]);

appendQuestions('saintek_kimia', [
{question:"Bilangan oksidasi Mn dalam KMnO4 = ...",options: ["+7","+2","+4","-1","0"],answer:0,hint:"K=+1, O=-2. +1+Mn+4(-2)=0 => Mn=+7.",explanation:"K = +1, O = -2 (masing-masing).\n+1 + Mn + 4(-2) = 0.\nMn - 7 = 0.\nMn = +7.\nJawaban: A."},
{question:"Larutan buffer berfungsi untuk ...",options: ["Mempertahankan pH larutan meskipun ditambah sedikit asam atau basa","Menaikkan pH menjadi 14","Menurunkan pH menjadi 0","Menghilangkan semua ion","Menguapkan air"],answer:0,hint:"Buffer = penahan pH. Terdiri dari asam lemah + garamnya (atau basa lemah + garamnya).",explanation:"Larutan buffer (penyangga): mempertahankan pH relatif konstan meskipun ditambah sedikit asam/basa/pengenceran. Komponen: asam lemah + garam asam lemah ATAU basa lemah + garam basa lemah.\nJawaban: A."},
]);

appendQuestions('saintek_biologi', [
{question:"Perbedaan sel prokariotik dan eukariotik yang paling mendasar: ...",options: ["Prokariotik TIDAK memiliki membran inti (nukleus), eukariotik MEMILIKI","Prokariotik lebih besar","Eukariotik tidak memiliki DNA","Keduanya identik","Prokariotik memiliki mitokondria"],answer:0,hint:"Pro = sebelum, karyo = inti. Prokariotik = sebelum ada inti = tanpa nukleus bermembran.",explanation:"Prokariotik: tidak memiliki membran inti (DNA di nukleoid, tidak dibungkus membran). Contoh: bakteri, archaea.\nEukariotik: memiliki membran inti (DNA dalam nukleus bermembran). Contoh: hewan, tumbuhan, fungi.\nJawaban: A."},
{question:"Hemoglobin dalam sel darah merah berfungsi untuk ...",options: ["Mengikat dan mengangkut oksigen dari paru-paru ke seluruh tubuh","Melawan infeksi","Pembekuan darah","Mengangkut nutrisi","Memproduksi hormon"],answer:0,hint:"Heme = zat besi. Globin = protein. Hemoglobin mengikat O2.",explanation:"Hemoglobin (Hb): protein dalam eritrosit (sel darah merah) yang mengikat O2 di paru-paru dan melepaskannya di jaringan. Mengandung zat besi (Fe) yang memberikan warna merah. Juga mengangkut sebagian CO2.\nJawaban: A."},
]);

appendQuestions('soshum_ekonomi', [
{question:"Kurva Philips menunjukkan hubungan terbalik antara ...",options: ["Inflasi dan pengangguran","GDP dan populasi","Ekspor dan impor","Harga dan kualitas","Produksi dan konsumsi"],answer:0,hint:"Phillips Curve: inflasi tinggi ↔ pengangguran rendah (trade-off jangka pendek).",explanation:"Kurva Phillips: hubungan terbalik (trade-off) antara inflasi dan pengangguran dalam jangka pendek. Inflasi tinggi $\\to$ pengangguran rendah (ekonomi panas). Inflasi rendah $\\to$ pengangguran tinggi.\nJawaban: A."},
{question:"Keunggulan komparatif (David Ricardo) terjadi ketika ...",options: ["Suatu negara memproduksi barang dengan biaya peluang (opportunity cost) lebih rendah dibanding negara lain","Suatu negara memproduksi lebih banyak","Suatu negara memiliki teknologi lebih baik","Suatu negara lebih besar","Tidak ada perdagangan"],answer:0,hint:"Komparatif = relatif. Siapa yang mengorbankan lebih sedikit? Bukan siapa yang lebih cepat.",explanation:"Keunggulan komparatif (David Ricardo): negara harus mengkkhususkan diri di barang yang biaya peluangnya paling rendah SECARA RELATIF, bukan absolut. Basis perdagangan internasional.\nJawaban: A."},
]);

appendQuestions('soshum_sosiologi', [
{question:"Perubahan sosial yang TIDAK direncanakan dan terjadi secara alamiah disebut ...",options: ["Perubahan yang tidak dikehendaki/unplanned change","Modernisasi","Revolusi","Reformasi","Program pemerintah"],answer:0,hint:"Unplanned = terjadi sendiri tanpa perencanaan. Contoh: perubahan bahasa gaul.",explanation:"Perubahan sosial tidak direncanakan: terjadi secara spontan tanpa kehendak masyarakat. Contoh: perubahan demografi, pergeseran bahasa, urbanisasi spontan.\nBerbeda dari: modernisasi/pembangunan yang direncanakan pemerintah.\nJawaban: A."},
]);

appendQuestions('soshum_sejarah', [
{question:"BPUPKI (Badan Penyelidik Usaha-Usaha Persiapan Kemerdekaan Indonesia) dibentuk oleh Jepang pada tanggal ...",options: ["1 Maret 1945","17 Agustus 1945","1 Juni 1945","28 Oktober 1928","22 Juni 1945"],answer:0,hint:"BPUPKI dibentuk 1 Maret 1945, bersidang Mei-Juli 1945.",explanation:"BPUPKI dibentuk 1 Maret 1945 oleh Jepang. Bersidang dua kali:\n1. 29 Mei - 1 Juni 1945 (pidato Pancasila oleh Soekarno)\n2. 10-17 Juli 1945 (rumusan UUD)\nKemudian diganti PPKI.\nJawaban: A."},
{question:"Perang dingin berakhir ditandai dengan ...",options: ["Runtuhnya Tembok Berlin (1989) dan bubarnya Uni Soviet (1991)","Perang Dunia II","Proklamasi Indonesia","Revolusi Perancis","Penemuan nuklir"],answer:0,hint:"1989: Tembok Berlin runtuh. 1991: Uni Soviet bubar. Akhir bipolar.",explanation:"Akhir Perang Dingin:\n1989: Tembok Berlin runtuh (simbol berakhirnya pembagian Eropa).\n1991: Uni Soviet resmi bubar (25 Desember). Era bipolar berakhir, AS menjadi superpower tunggal.\nJawaban: A."},
]);

appendQuestions('soshum_geografi', [
{question:"Angin Foehn (chinook) terjadi ketika ...",options: ["Udara lembab naik di sisi gunung (windward) lalu turun kering dan hangat di sisi leeward","Udara turun di kedua sisi","Tidak ada gunung","Di daerah kutub saja","Di lautan"],answer:0,hint:"Foehn: udara naik -> hujan di windward -> kering turun di leeward -> hangat.",explanation:"Fenomena Foehn: udara lembab dipaksa naik oleh gunung (windward). Naik -> mendingin -> kondensasi -> hujan. Setelah melewati puncak, udara turun (leeward) -> menghangat secara adiabatik (kering) -> angin kering dan hangat.\nJawaban: A."},
{question:"Letak geologis Indonesia berada pada pertemuan tiga lempeng tektonik yang menyebabkan ...",options: ["Banyak gunung api aktif, sering gempa, dan rawan tsunami","Cuaca selalu cerah","Tidak ada gunung","Tanah sangat datar","Tidak pernah gempa"],answer:0,hint:"3 lempeng aktif = ring of fire = seismik + vulkanik sangat aktif.",explanation:"Indonesia di pertemuan Eurasia, Indo-Australia, Pasifik:\n1. 127 gunung api aktif (terbanyak di dunia)\n2. Gempa bumi sangat sering\n3. Tsunami (gempa di bawah laut)\n4. Tanah subur (abu vulkanik)\nJawaban: A."},
]);

appendQuestions('saintek_matipa', [
{question:"Divergensi vektor F = (x^2, y^2, z^2) di titik (1,1,1) = ...",options: ["6","3","2","1","9"],answer:0,hint:"div F = dFx/dx + dFy/dy + dFz/dz = 2x+2y+2z. Di (1,1,1): 2+2+2=6.",explanation:"div F = df1/dx + df2/dy + df3/dz = 2x + 2y + 2z.\nDi (1,1,1): 2(1)+2(1)+2(1) = 6.\nJawaban: A."},
{question:"Rank matriks [[1,2,3],[2,4,6],[3,6,9]] = ...",options: ["1","2","3","0","9"],answer:0,hint:"R2=2R1, R3=3R1. Semua baris kelipatan R1. Rank = 1.",explanation:"R2 = 2 x R1. R3 = 3 x R1. Semua baris linearly dependent.\nHanya 1 baris independen. Rank = 1.\nJawaban: A."},
]);
