// BATCH 7 — All Subjects Final Boost (10-15 per subject)

appendQuestions('tps_verbal', [
{question:"HIPOTESIS : DUGAAN SEMENTARA :: TEORI : ...",options: ["Penjelasan yang sudah diuji dan didukung bukti kuat","Dugaan tanpa bukti","Fakta tunggal","Hukum mutlak","Ramalan"],answer:0,hint:"Hipotesis = dugaan awal. Teori = hipotesis yang sudah lulus pengujian berulang.",explanation:"Hipotesis: dugaan sementara yang belum teruji. Teori: penjelasan komprehensif yang telah diuji secara berulang dan didukung oleh banyak bukti. Teori BUKAN 'hanya teori' — teori ilmiah sangat kuat.\nJawaban: A."},
{question:"Premis: 'Semua mamalia bernafas dengan paru-paru. Paus adalah mamalia.' Kesimpulan deduktif: ...",options: ["Paus bernafas dengan paru-paru","Paus hidup di darat","Semua ikan adalah mamalia","Paus tidak bernafas","Paus bertelur"],answer:0,hint:"Semua M = P. Paus = M. Maka Paus = P. Silogisme Barbara.",explanation:"Silogisme valid: Semua mamalia bernafas paru-paru. Paus mamalia. Maka paus bernafas paru-paru.\nIni benar! Paus dan lumba-lumba = mamalia laut yang bernafas udara.\nJawaban: A."},
{question:"DIKOTOMI : DUA BAGIAN :: TRIKOTOMI : ...",options: ["Tiga bagian","Dua bagian","Empat bagian","Satu bagian","Lima bagian"],answer:0,hint:"Di = dua, Tri = tiga. Dikotomi = pembagian dua. Trikotomi = pembagian tiga.",explanation:"Dikotomi (di=dua): pembagian menjadi 2 bagian/kelompok. Trikotomi (tri=tiga): pembagian menjadi 3 bagian/kelompok. Pola prefiks numerik.\nJawaban: A."},
{question:"Kesalahan 'cherry picking' dalam argumentasi adalah ...",options: ["Hanya memilih data yang mendukung argumen dan mengabaikan data yang bertentangan","Mengumpulkan semua data","Tidak menggunakan data","Menggunakan terlalu banyak data","Analisis yang terlalu mendetail"],answer:0,hint:"Cherry pick = pilih ceri terbaik saja. Dalam debat = pilih bukti yang menguntungkan saja.",explanation:"Cherry picking (confirmation bias): hanya menyajikan data/bukti yang mendukung argumen sendiri, sementara sengaja mengabaikan atau menyembunyikan data yang bertentangan. Bias seleksi.\nJawaban: A."},
]);

appendQuestions('tps_numerik', [
{question:"Jika kurs 1 USD = Rp15.500, berapa rupiah yang didapat dari 750 USD?",options: ["Rp11.625.000","Rp1.162.500","Rp116.250.000","Rp11.250.000","Rp12.000.000"],answer:0,hint:"750 x 15.500 = 11.625.000.",explanation:"750 x 15.500 = 11.625.000.\nJawaban: A."},
{question:"Sebuah mobil mengonsumsi 1 liter bensin per 12 km. Untuk perjalanan 360 km, dibutuhkan ...",options: ["30 liter","36 liter","12 liter","3 liter","360 liter"],answer:0,hint:"360/12 = 30 liter.",explanation:"360 km / 12 km/liter = 30 liter.\nJawaban: A."},
{question:"Perbandingan uang Rio : Tina = 3 : 5. Jika selisih uang mereka Rp40.000, uang Rio = ...",options: ["Rp60.000","Rp100.000","Rp40.000","Rp80.000","Rp50.000"],answer:0,hint:"Selisih = 5-3 = 2 bagian = 40.000. 1 bagian = 20.000. Rio = 3x20.000.",explanation:"Selisih rasio = 5-3 = 2 bagian = Rp40.000.\n1 bagian = Rp20.000.\nRio = 3 x 20.000 = Rp60.000.\nTina = 5 x 20.000 = Rp100.000.\nJawaban: A."},
{question:"Sebuah tangki air berbentuk tabung berdiameter 2m dan tinggi 3m. Volume air yang bisa ditampung (pi=3.14) = ...",options: ["9.42 m^3","6.28 m^3","18.84 m^3","12.56 m^3","3.14 m^3"],answer:0,hint:"V = pi r^2 h = 3.14(1)(3) = 9.42.",explanation:"r = 1 m.\nV = pi r^2 h = 3.14 x 1 x 3 = 9.42 m^3.\n= 9420 liter.\nJawaban: A."},
{question:"Skala peta 1:250.000. Jarak di peta 8 cm = jarak sebenarnya ...",options: ["20 km","2 km","200 km","2000 km","0.2 km"],answer:0,hint:"8 x 250.000 = 2.000.000 cm = 20.000 m = 20 km.",explanation:"8 cm x 250.000 = 2.000.000 cm = 20.000 m = 20 km.\nJawaban: A."},
]);

appendQuestions('tps_logika', [
{question:"Analogi: Buku : Perpustakaan :: Uang : ...",options: ["Bank","Toko","Pasar","Dompet","ATM"],answer:0,hint:"Buku DISIMPAN di perpustakaan. Uang DISIMPAN di bank.",explanation:"Buku disimpan/dikelola di perpustakaan (secara institusional). Uang disimpan/dikelola di bank (secara institusional). Hubungan: benda dan tempat penyimpanan institusional.\nJawaban: A."},
{question:"Jika benar bahwa 'Beberapa kucing hitam', maka apakah 'Semua kucing hitam' PASTI benar?",options: ["Tidak, 'beberapa' tidak mengimplikasikan 'semua'","Ya, pasti benar","Tergantung","Tidak ada kucing hitam","Semua kucing putih"],answer:0,hint:"Some A are B TIDAK mengimplikasikan All A are B. Subkontrer, bukan subaltern.",explanation:"'Beberapa' -> TIDAK bisa disimpulkan 'semua'. Beberapa kucing hitam tidak berarti SEMUA kucing hitam. Bisa ada kucing yang tidak hitam.\nJawaban: A."},
{question:"Pola angka: 2, 6, 12, 20, 30, 42, ... Rumus suku ke-n = ...",options: ["n(n+1)","2n","n^2","n!","3n"],answer:0,hint:"U1=2=1x2, U2=6=2x3, U3=12=3x4, U4=20=4x5. Pola: n(n+1).",explanation:"Un = n(n+1).\nU1=1x2=2, U2=2x3=6, U3=3x4=12, U4=4x5=20, U5=5x6=30, U6=6x7=42. Benar!\nJawaban: A."},
]);

appendQuestions('tps_spasial', [
{question:"Sebuah balok memiliki ukuran 3x4x5. Panjang diagonal ruangnya = ...",options: ["$\\sqrt{50}$ = 5sqrt(2)","12","50","$\\sqrt{25}$","20"],answer:0,hint:"d = $\\sqrt{3^2+4^2+5^2}$ = $\\sqrt{9+16+25}$ = $\\sqrt{50}$.",explanation:"Diagonal ruang balok = $\\sqrt{p^2+l^2+t^2}$ = $\\sqrt{9+16+25}$ = $\\sqrt{50}$ = 5sqrt(2).\nJawaban: A."},
{question:"Berapa banyak sisi pada prisma heksagonal (segi-6)?",options: ["8","6","12","10","7"],answer:0,hint:"Prisma segi-n memiliki n+2 sisi (2 alas + n sisi lateral).",explanation:"Prisma segi-6: 2 alas heksagonal + 6 sisi lateral = 8 sisi.\nRusuk: 3x6 = 18. Vertex: 2x6 = 12.\nJawaban: A."},
]);

appendQuestions('tkd_indo', [
{question:"Makna denotatif kata 'buaya' adalah ...",options: ["Hewan reptil yang hidup di air (makna sebenarnya)","Orang jahat yang suka menipu","Penjahat","Hewan berbulu","Burung"],answer:0,hint:"Denotatif = makna sebenarnya/leksikal. Konotatif = makna kiasan.",explanation:"Denotatif: makna literal/sebenarnya sesuai kamus. Buaya = reptil ordo Crocodilia.\nKonotatif: makna tambahan/kiasan. 'Dasar buaya!' = orang licik/playboy.\nJawaban: A."},
{question:"Kata berimbuhan 'mempermasalahkan' terdiri dari imbuhan ... + kata dasar 'masalah'",options: ["memper-kan","me-kan","per-kan","mem-kan","di-kan"],answer:0,hint:"mempermasalahkan = mem + per + masalah + kan = memper-...-kan.",explanation:"mempermasalahkan: konfiks memper-...-kan + kata dasar 'masalah'.\nPola: meng + per + KD + kan (konfiks gabungan).\nJawaban: A."},
{question:"Kalimat tunggal adalah kalimat yang memiliki ...",options: ["Satu pola subjek-predikat (satu klausa)","Dua klausa","Tiga klausa atau lebih","Tidak ada subjek","Tidak ada predikat"],answer:0,hint:"Tunggal = satu pola S-P. Majemuk = dua pola S-P atau lebih.",explanation:"Kalimat tunggal: memiliki satu pola S-P (satu klausa). Contoh: 'Adik tidur.'\nKalimat majemuk: memiliki dua atau lebih S-P.\nJawaban: A."},
]);

appendQuestions('tkd_eng', [
{question:"The idiom 'to break the ice' means:",options: ["To start a conversation in an awkward social situation","To literally break ice","To be very cold","To end a relationship","To cause damage"],answer:0,hint:"Break the ice = make people feel more comfortable/start talking.",explanation:"'To break the ice': to do or say something to relieve tension or get conversation going in an uncomfortable social situation. Example: 'She told a joke to break the ice.'\nAnswer: A."},
{question:"Fill in the blank: 'Neither the teacher nor the students ____ the answer.'",options: ["know","knows","is knowing","has known","knowing"],answer:0,hint:"Neither...nor: verb agrees with the NEAREST subject. 'students' (plural) -> 'know'.",explanation:"Neither...nor: verb agrees with the nearest subject (proximity rule). 'students' = plural -> 'know'.\nNeither A nor B + verb (agrees with B).\nAnswer: A."},
{question:"A 'paradox' is:",options: ["A statement that seems self-contradictory but may contain a deeper truth","A type of poem","A mathematical equation","A scientific law","A simple statement"],answer:0,hint:"Para-dox: contrary to expectation. Seemingly contradictory but possibly true.",explanation:"Paradox: a statement that appears self-contradictory or absurd but may reveal a deeper truth upon reflection. Example: 'Less is more.' 'The only constant is change.'\nAnswer: A."},
]);

appendQuestions('saintek_fisika', [
{question:"Energi potensial gravitasi benda bermassa m pada ketinggian h = ...",options: ["mgh","mg/h","mv^2/2","mh/g","g/mh"],answer:0,hint:"Ep = mgh. Energi disimpan karena posisi dalam medan gravitasi.",explanation:"Ep = mgh.\nm = massa (kg). g = percepatan gravitasi (m/s^2). h = ketinggian (m).\nEnergi potensial akan berubah menjadi kinetik saat benda jatuh.\nJawaban: A."},
{question:"Hukum Newton II: F = ma. Jika massa 10 kg diberi gaya 50 N, percepatannya = ...",options: ["5 m/s^2","500 m/s^2","0.2 m/s^2","50 m/s^2","10 m/s^2"],answer:0,hint:"a = F/m = 50/10 = 5.",explanation:"a = F/m = 50/10 = 5 m/s^2.\nJawaban: A."},
{question:"Indeks bias snellius: n1.sin(theta1) = n2.sin(theta2). Ini menjelaskan fenomena ...",options: ["Pembiasan cahaya (refraction) saat memasuki medium berbeda","Pemantulan cahaya","Difraksi","Interferensi","Polarisasi"],answer:0,hint:"Snell's law: hukum pembiasan. Cahaya berbelok saat memasuki medium dengan kerapatan berbeda.",explanation:"Hukum Snellius: n1 sin theta1 = n2 sin theta2.\nMenjelaskan pembiasan (refraction): cahaya berbelok saat melewati batas dua medium dengan indeks bias berbeda.\nContoh: sedotan terlihat 'patah' dalam air.\nJawaban: A."},
]);

appendQuestions('saintek_kimia', [
{question:"Isotop adalah atom-atom yang memiliki ...",options: ["Nomor atom sama tapi nomor massa berbeda (jumlah neutron berbeda)","Nomor massa sama","Jumlah elektron berbeda","Semua sama","Nomor atom berbeda"],answer:0,hint:"Iso = sama, topos = tempat (di tabel periodik). Sama Z, beda A (beda neutron).",explanation:"Isotop: unsur sama (Z/proton sama) tapi massa berbeda (neutron berbeda).\nContoh: C-12 dan C-14 (sama-sama karbon, beda 2 neutron).\nIsotop berada di tempat yang sama di tabel periodik.\nJawaban: A."},
{question:"Hukum kekekalan massa Lavoisier menyatakan ...",options: ["Massa total reaktan = massa total produk dalam reaksi kimia (massa tidak hilang/muncul)","Massa bisa diciptakan","Massa selalu bertambah","Hanya berlaku di laboratorium","Massa habis setelah reaksi"],answer:0,hint:"Lavoisier: massa sebelum = massa sesudah reaksi.",explanation:"Hukum kekekalan massa (Lavoisier, 1789): dalam reaksi kimia tertutup, total massa reaktan = total massa produk. Massa tidak diciptakan/dimusnahkan, hanya berubah bentuk.\nJawaban: A."},
]);

appendQuestions('saintek_biologi', [
{question:"Proses sintesis protein dari mRNA di ribosom disebut ...",options: ["Translasi","Transkripsi","Replikasi","Mutasi","Rekombinasi"],answer:0,hint:"Transkripsi: DNA -> mRNA. Translasi: mRNA -> protein. Replikasi: DNA -> DNA.",explanation:"Translasi: mRNA dibaca oleh ribosom untuk menyintesis rantai polipeptida (protein). Kodon mRNA diterjemahkan ke asam amino melalui tRNA.\nTranskripsi: DNA -> mRNA (di nukleus).\nJawaban: A."},
{question:"Ekosistem terdiri dari komponen ...",options: ["Biotik (makhluk hidup) dan abiotik (tak hidup)","Hanya makhluk hidup","Hanya benda mati","Hanya tumbuhan","Hanya hewan"],answer:0,hint:"Ekosistem = bio (hidup) + abiotik (tak hidup) + interaksi mereka.",explanation:"Ekosistem: biotik (produsen, konsumen, dekomposer) + abiotik (cahaya, suhu, air, tanah, mineral) + interaksi antar keduanya.\nJawaban: A."},
]);

appendQuestions('soshum_ekonomi', [
{question:"Pasar monopoli memiliki ciri utama ...",options: ["Hanya ada SATU penjual yang menguasai seluruh pasar (price maker)","Banyak penjual","Produk homogen","Free entry","Informasi sempurna"],answer:0,hint:"Mono = satu, poli = penjual. Monopoli = satu penjual = price maker.",explanation:"Monopoli: satu penjual, produk unik tanpa substitusi dekat, barrier to entry tinggi. Monopolis = price maker (menentukan harga sendiri). Contoh: PLN (listrik di Indonesia).\nJawaban: A."},
{question:"Neraca perdagangan surplus terjadi ketika ...",options: ["Nilai ekspor > nilai impor","Nilai impor > nilai ekspor","Ekspor = impor","Tidak ada perdagangan","GDP turun"],answer:0,hint:"Surplus = lebih. Ekspor > impor = uang masuk > keluar.",explanation:"Neraca perdagangan = ekspor - impor.\nSurplus: ekspor > impor (positif) -> devisa masuk.\nDefisit: impor > ekspor (negatif) -> devisa keluar.\nJawaban: A."},
]);

appendQuestions('soshum_sosiologi', [
{question:"Nilai sosial berbeda dari norma sosial karena ...",options: ["Nilai = konsepsi abstrak tentang baik-buruk. Norma = aturan konkret/perilaku yang diharapkan","Keduanya identik","Nilai lebih konkret dari norma","Norma tidak bisa berubah","Nilai hanya di agama"],answer:0,hint:"Nilai = prinsip abstrak (kejujuran, keadilan). Norma = aturan perilaku spesifik (tidak boleh mencuri).",explanation:"Nilai: konsepsi abstrak tentang apa yang dianggap baik, benar, dan diinginkan (kejujuran, keadilan, kebebasan).\nNorma: aturan perilaku konkret yang mengatur tindakan berdasarkan nilai (tidak boleh mencuri = norma berdasarkan nilai kejujuran).\nJawaban: A."},
{question:"Pengendalian sosial (social control) bertujuan untuk ...",options: ["Menjaga keteraturan sosial dengan memastikan anggota masyarakat mengikuti norma","Menghilangkan semua konflik","Membuat semua orang sama","Menghapus budaya","Mencegah semua perubahan"],answer:0,hint:"Social control = mekanisme agar orang taat norma. Formal (hukum) dan informal (gossip, sanksi sosial).",explanation:"Pengendalian sosial: mekanisme yang digunakan masyarakat untuk memastikan konformitas terhadap norma.\nFormal: hukum, polisi, pengadilan.\nInformal: sanksi sosial, gossip, tekanan teman.\nJawaban: A."},
]);

appendQuestions('soshum_sejarah', [
{question:"Sistem tanam paksa (cultuurstelsel) diterapkan oleh Belanda pada tahun ...",options: ["1830-1870 (era Van den Bosch)","1600-1700","1900-1945","1500-1600","Setelah kemerdekaan"],answer:0,hint:"Van den Bosch menerapkan cultuurstelsel 1830. Dicabut secara bertahap sampai 1870.",explanation:"Cultuurstelsel (1830-1870): kebijakan Gubernur Jenderal Van den Bosch yang mewajibkan rakyat menanam 1/5 tanahnya dengan tanaman ekspor (kopi, tebu, nila) untuk diserahkan ke Belanda. Sangat eksploitatif.\nJawaban: A."},
{question:"Konferensi Asia-Afrika (KAA) diselenggarakan di Bandung pada tahun ...",options: ["1955","1945","1965","1950","1960"],answer:0,hint:"KAA Bandung 1955: pencetus Gerakan Non-Blok. 29 negara Asia-Afrika.",explanation:"KAA Bandung (18-24 April 1955): 29 negara Asia-Afrika. Menghasilkan Dasasila Bandung. Tokoh: Soekarno, Nehru, Nasser, U Nu. Cikal-bakal Gerakan Non-Blok.\nJawaban: A."},
]);

appendQuestions('soshum_geografi', [
{question:"Iklim Indonesia menurut klasifikasi Koppen termasuk tipe ...",options: ["Af/Am (tropis basah/monsun)","Bw (gurun)","Cs (Mediterania)","Df (subarktik)","ET (tundra)"],answer:0,hint:"Indonesia = tropis (suhu tinggi sepanjang tahun, curah hujan tinggi).",explanation:"Klasifikasi Koppen Indonesia:\nAf: tropis basah (hujan sepanjang tahun, contoh: Kalimantan).\nAm: tropis monsun (musim kemarau pendek, contoh: Jawa).\nAw: tropis savana (musim kering jelas, contoh: NTT).\nJawaban: A."},
{question:"Lapisan atmosfer tempat terjadinya cuaca dan awan disebut ...",options: ["Troposfer (0-12 km)","Stratosfer","Mesosfer","Termosfer","Eksosfer"],answer:0,hint:"Tropo- = berubah/berputar. Cuaca, awan, hujan terjadi di troposfer.",explanation:"Troposfer: lapisan terbawah (0-12 km). Tempat terjadinya semua fenomena cuaca (awan, hujan, angin, badai). Suhu turun seiring ketinggian. 75% massa atmosfer ada di sini.\nJawaban: A."},
]);

appendQuestions('saintek_matipa', [
{question:"Transformasi Laplace dari f(t) = 1 (fungsi konstan) = ...",options: ["1/s (s>0)","s","1","e^s","0"],answer:0,hint:"L{1} = integral 0 ke inf dari e^(-st) dt = 1/s.",explanation:"L{1} = integral_0^inf e^(-st) dt = [-e^(-st)/s]_0^inf = 0-(-1/s) = 1/s.\n(untuk s > 0.)\nJawaban: A."},
{question:"Fungsi gamma: Gamma(n) untuk n bilangan asli = ...",options: ["(n-1)!","n!","n","1/n","n^2"],answer:0,hint:"Gamma(n) = (n-1)! untuk n bilangan bulat positif.",explanation:"Fungsi Gamma: Gamma(n) = (n-1)! untuk n bilangan asli.\nGamma(1) = 0! = 1.\nGamma(5) = 4! = 24.\nMerupakan generalisasi faktorial ke bilangan real/kompleks.\nJawaban: A."},
]);
