// BATCH 8 — All Subjects Additional Expansion

appendQuestions('tps_verbal', [
{question:"EMPIRIS : BERDASARKAN PENGALAMAN/OBSERVASI :: APRIORI : ...",options: ["Berdasarkan logika/penalaran tanpa pengalaman","Berdasarkan pengalaman (secara konvensional)","Berdasarkan otoritas (pada konteks konvensional)","Berdasarkan emosi (dalam batasan konvensional)","Berdasarkan tradisi (secara fundamental)"],answer:0,hint:"Empiris = dari data/pengalaman. A priori = dari penalaran murni, sebelum pengalaman.",explanation:"Empiris (a posteriori): pengetahuan dari pengalaman, observasi, eksperimen. A priori: pengetahuan dari penalaran murni, tanpa perlu pengalaman (contoh: 2+2=4, konsep logika).\nJawaban: A."},
{question:"Kesimpulan yang TIDAK valid dari premis 'Semua dokter adalah sarjana' dan 'Beberapa sarjana kaya': ...",options: ["Semua dokter pasti kaya","Beberapa dokter mungkin kaya","Tidak semua sarjana dokter","Ada sarjana yang kaya","Beberapa orang kaya mungkin sarjana"],answer:0,hint:"'Beberapa sarjana kaya' TIDAK berarti dokter (subset sarjana) termasuk yang kaya.",explanation:"Dari 'semua dokter sarjana' dan 'beberapa sarjana kaya', TIDAK bisa disimpulkan 'semua dokter kaya'. Hanya 'beberapa sarjana kaya' — dokter mungkin atau mungkin tidak termasuk dalam kelompok sarjana yang kaya.\nJawaban: A."},
{question:"PRAGMATIS : PRAKTIS :: IDEALIS : ...",options: ["Berpegang pada cita-cita/prinsip ideal","Praktis (menurut pengertian baku)","Materialistis (sesuai paradigma tradisional)","Pesimistis (menurut prinsip dasar)","Realistis (secara normatif; dalam batasan konvensional)"],answer:0,hint:"Pragmatis = mengutamakan kegunaan praktis. Idealis = mengutamakan cita-cita/prinsip.",explanation:"Pragmatis: berorientasi pada hasil praktis dan kegunaan. Idealis: berorientasi pada cita-cita, prinsip, dan standar ideal. Kontras pendekatan.\nJawaban: A."},
]);

appendQuestions('tps_numerik', [
{question:"Sebuah bus berangkat setiap 15 menit dan kereta setiap 20 menit. Jika keduanya berangkat bersamaan pukul 06:00, kapan berangkat bersamaan lagi?",options: ["07:00 (setelah 60 menit)","06:15","06:20","06:35","08:00"],answer:0,hint:"KPK(15,20) = 60 menit = 1 jam.",explanation:"KPK(15,20) = 60 menit.\n06:00 + 60 menit = 07:00.\nJawaban: A."},
{question:"Uang Rp5.000.000 ditabung dengan bunga sederhana 6% per tahun selama 3 tahun. Bunga total = ...",options: ["Rp900.000","Rp300.000","Rp600.000","Rp1.500.000","Rp950.000"],answer:0,hint:"Bunga sederhana: I = P x r x t = 5jt x 0.06 x 3.",explanation:"I = 5.000.000 x 0.06 x 3 = 900.000.\nBunga sederhana (simple interest): tidak ada bunga berbunga.\nJawaban: A."},
]);

appendQuestions('tps_logika', [
{question:"Kesimpulan dari: 'Jika saya belajar, maka saya lulus' dan 'Saya lulus'. Apakah bisa disimpulkan saya belajar?",options: ["Tidak bisa disimpulkan (fallacy of affirming the consequent)","Ya, pasti belajar (menurut konsensus ilmiah; sesuai teori klasik)","Tidak lulus (dalam arti sempit; berdasarkan premis dasar)","Tidak mungkin lulus (menurut definisi standar)","Pasti tidak belajar (menurut pengertian baku)"],answer:0,hint:"P->Q dan Q benar TIDAK berarti P benar. Bisa lulus tanpa belajar (alasan lain).",explanation:"Affirming the consequent: P->Q, Q, ∴ P. Ini TIDAK valid.\nMungkin lulus karena alasan lain (beruntung, soal mudah). Hanya modus ponens (P->Q, P, ∴ Q) yang valid.\nJawaban: A."},
{question:"Jika A = {x | x > 3} dan B = {x | x < 7}, maka A irisan B = ...",options: ["{x | 3 < x < 7}","{x | x > 3 atau x < 7}","Himpunan kosong","{3, 7}","Semua bilangan real"],answer:0,hint:"A: x>3. B: x<7. Irisan: x>3 DAN x<7 = 3<x<7.",explanation:"A $\\cap$ B = {x | x>3 dan x<7} = {x | 3 < x < 7}.\nContoh elemen: 4, 5, 6, 3.5, 6.9, dll.\nJawaban: A."},
]);

appendQuestions('tkd_indo', [
{question:"Jenis puisi lama yang terdiri dari 4 baris, bersajak a-b-a-b, dengan baris 1-2 sampiran dan 3-4 isi disebut ...",options: ["Pantun","Syair","Gurindam","Soneta","Haiku"],answer:0,hint:"Ciri pantun: 4 baris, sampiran+isi, a-b-a-b, 8-12 suku kata/baris.",explanation:"Pantun: 4 baris, sajak a-b-a-b, baris 1-2 sampiran (tidak berhubungan langsung), baris 3-4 isi (pesan utama).\nSyair: 4 baris, a-a-a-a, semua isi. Gurindam: 2 baris sebab-akibat.\nJawaban: A."},
{question:"Kata homonim adalah kata yang ...",options: ["Sama tulisan dan ucapannya tapi berbeda makna (contoh: bisa = racun ular / bisa = mampu)","Mirip maknanya (dalam batasan konvensional; dalam konteks umum; dalam pemahaman konvensional; menurut kerangka berpikir umum)","Berlawanan maknanya (secara fundamental; berdasarkan referensi umum; dalam definisi teknis)","Sama maknanya (dalam pemahaman konvensional; menurut kerangka berpikir umum; dalam pengertian luas)","Tidak bermakna (menurut konsensus ilmiah; sesuai teori klasik; pada konteks konvensional; dalam definisi teknis)"],answer:0,hint:"Homo = sama, onym = nama. Sama nama/bentuk tapi beda makna.",explanation:"Homonim: sama ejaan dan pengucapan, beda makna. Contoh: 'bisa' (racun/mampu), 'buku' (kitab/ruas), 'genting' (atap/kritis).\nHomofon: sama bunyi beda tulisan. Homograf: sama tulisan beda bunyi.\nJawaban: A."},
]);

appendQuestions('tkd_eng', [
{question:"'She speaks English as if she ____ a native speaker.' Choose the correct form:",options: ["were (subjunctive mood for unreal condition)","is (dalam pengertian luas; dari perspektif akademis)","was (dalam definisi teknis; sesuai klasifikasi umum)","has been (dalam konteks umum; berdasarkan teori dasar)","will be (berdasarkan referensi umum)"],answer:0,hint:"'As if' + past subjunctive (were) for unreal present conditions.",explanation:"'As if/as though' + subjunctive for unreal present: use 'were' (for all persons). She speaks as if she were (but she is NOT) a native speaker.\nAnswer: A."},
{question:"The prefix 'anti-' means:",options: ["Against, opposing","For, supporting","Before (di konteks ini)","After (secara klasik)","Self (sesuai klasifikasi umum)"],answer:0,hint:"Anti-biotics = against life/bacteria. Anti-thesis = against thesis.",explanation:"Anti-: against, opposing, contrary to. Examples: antibiotic (against bacteria), antithesis (opposing thesis), antisocial (against social norms).\nAnswer: A."},
]);

appendQuestions('saintek_fisika', [
{question:"Usaha (work) didefinisikan sebagai W = F x d x cos(theta). Jika gaya tegak lurus perpindahan (theta=90), W = ...",options: ["0 (cos90=0, tidak ada usaha)","F x d (berdasarkan acuan formal)","Infinity (secara konvensional)","F/d (pada konteks konvensional)","d/F (dalam batasan konvensional)"],answer:0,hint:"cos(90) = 0. W = Fd(0) = 0. Gaya tegak lurus perpindahan = tidak ada usaha.",explanation:"W = F.d.cos(90) = 0.\nTidak ada usaha jika gaya tegak lurus perpindahan. Contoh: gaya normal pada benda di atas meja horizontal (gaya vertikal, gerak horizontal).\nJawaban: A."},
{question:"Hukum kekekalan momentum: momentum total sebelum tumbukan = momentum total setelah tumbukan jika ...",options: ["Tidak ada gaya eksternal (sistem tertutup)","Selalu berlaku (dari sudut pandang klasik)","Hanya di vakum (dalam literatur standar)","Hanya untuk benda kecil (menurut pandangan mainstream)","Ada gesekan (dalam pengertian luas)"],answer:0,hint:"Kekekalan momentum berlaku jika resultant external force = 0 (sistem tertutup/isolated).",explanation:"Kekekalan momentum: berlaku jika tidak ada gaya luar netto (sistem terisolasi/tertutup). p_sebelum = p_sesudah.\nMomentum = mass x velocity.\nJawaban: A."},
]);

appendQuestions('saintek_kimia', [
{question:"Molaritas larutan yang mengandung 4 gram NaOH (M=40) dalam 500 mL larutan = ...",options: ["0.2 M","0.4 M","0.1 M","2 M","4 M"],answer:0,hint:"mol = gram/M = 4/40 = 0.1 mol. Molaritas = mol/L = 0.1/0.5 = 0.2.",explanation:"mol NaOH = 4/40 = 0.1 mol.\nVolume = 500 mL = 0.5 L.\nMolaritas = 0.1/0.5 = 0.2 M.\nJawaban: A."},
{question:"Golongan alkana memiliki rumus umum ...",options: ["CnH2n+2","CnH2n","CnH2n-2","CnHn","C2nHn"],answer:0,hint:"Alkana = jenuh (semua ikatan tunggal). CnH(2n+2).",explanation:"Alkana (jenuh): CnH(2n+2). Contoh: CH4 (metana), C2H6 (etana).\nAlkena (1 ikatan rangkap): CnH2n.\nAlkuna (1 ikatan rangkap tiga): CnH(2n-2).\nJawaban: A."},
]);

appendQuestions('saintek_biologi', [
{question:"Vaksin bekerja dengan cara ...",options: ["Merangsang sistem imun untuk membentuk antibodi TANPA menyebabkan penyakit","Membunuh semua bakteri dalam tubuh (secara konseptual; dalam arti sempit)","Menggantikan sel yang rusak (berdasarkan asumsi dasar; menurut definisi standar)","Menurunkan suhu tubuh (dalam kerangka teori; menurut pengertian baku)","Memberikan nutrisi tambahan (dari sudut pandang klasik; sesuai paradigma tradisional)"],answer:0,hint:"Vaksin = antigen yang dilemahkan/dimatikan -> memicu imun -> memori imun terbentuk.",explanation:"Vaksin: memasukkan antigen (patogen yang dilemahkan, dimatikan, atau bagiannya) ke tubuh. Sistem imun merespons dengan membentuk antibodi dan sel memori. Saat terpapar patogen asli, respons imun sudah siap.\nJawaban: A."},
{question:"Kromosom manusia berjumlah ...",options: ["46 (23 pasang)","48","44","22","92"],answer:0,hint:"Manusia: 46 kromosom = 22 pasang autosom + 1 pasang kromosom seks (XX/XY).",explanation:"Manusia: 2n = 46 (diploid).\n22 pasang autosom + 1 pasang kromosom seks.\nPerempuan: 44+XX. Laki-laki: 44+XY.\nGamet (haploid): n = 23.\nJawaban: A."},
]);

appendQuestions('soshum_ekonomi', [
{question:"Prinsip ekonomi berarti ...",options: ["Mendapatkan hasil maksimal dengan pengorbanan minimal (efisiensi)","Menghabiskan semua sumber daya (dalam konteks umum)","Tidak mempedulikan biaya (berdasarkan referensi umum)","Memproduksi sebanyak mungkin tanpa batas (menurut kerangka berpikir umum)","Menghabiskan uang secepat mungkin (sesuai teori klasik)"],answer:0,hint:"Prinsip ekonomi: efisiensi = optimalisasi cost vs benefit.",explanation:"Prinsip ekonomi: dengan sumber daya terbatas, mencapai hasil sebesar-besarnya (memaksimalkan utilitas) ATAU mencapai tujuan tertentu dengan pengorbanan sekecil-kecilnya (meminimalkan biaya).\nJawaban: A."},
]);

appendQuestions('soshum_sosiologi', [
{question:"Globalisasi dalam konteks sosiologi menyebabkan ...",options: ["Semakin terintegrasinya masyarakat dunia melalui pertukaran budaya, ekonomi, dan informasi","Isolasi masyarakat (dari perspektif akademis; secara fundamental; berdasarkan referensi umum; secara konseptual)","Hilangnya semua perbedaan (sesuai klasifikasi umum; dalam pemahaman konvensional; dari perspektif akademis)","Tidak ada perubahan (berdasarkan teori dasar; menurut konsensus ilmiah; secara normatif)","Kemunduran teknologi (secara konseptual; dalam arti sempit; dalam pengertian luas; dari perspektif akademis)"],answer:0,hint:"Globalisasi: proses integrasi dunia melalui perdagangan, teknologi, budaya.",explanation:"Globalisasi: proses integrasi dan interaksi antar masyarakat, perusahaan, dan pemerintah di seluruh dunia. Didorong oleh teknologi, transportasi, dan perdagangan internasional. Dampak: pertukaran budaya, interdependensi ekonomi, homogenisasi vs heterogenisasi.\nJawaban: A."},
]);

appendQuestions('soshum_sejarah', [
{question:"Pancasila sebagai dasar negara pertama kali dirumuskan oleh Soekarno dalam sidang BPUPKI pada ...",options: ["1 Juni 1945","17 Agustus 1945","28 Oktober 1928","22 Juni 1945","18 Agustus 1945"],answer:0,hint:"1 Juni = Hari Lahir Pancasila. Soekarno menyampaikan pidato 'Lahirnya Pancasila'.",explanation:"1 Juni 1945: Soekarno menyampaikan konsep Pancasila dalam sidang BPUPKI. Diperingati sebagai Hari Lahir Pancasila. 22 Juni = Piagam Jakarta. 18 Agustus = UUD 1945 disahkan.\nJawaban: A."},
]);

appendQuestions('soshum_geografi', [
{question:"Klasifikasi iklim menurut Junghuhn berdasarkan ...",options: ["Ketinggian tempat (altitude) dan jenis tanaman yang tumbuh","Curah hujan saja (menurut pandangan mainstream)","Garis lintang (dalam pengertian luas; dari perspektif akademis)","Tekanan udara (dalam definisi teknis; sesuai klasifikasi umum)","Jarak dari laut (dalam konteks umum; berdasarkan teori dasar)"],answer:0,hint:"Junghuhn: iklim berdasarkan ketinggian (panas, sedang, sejuk, dingin/alpine).",explanation:"Junghuhn membagi iklim di Indonesia berdasarkan ketinggian:\n1. Panas (0-600m): kelapa, padi\n2. Sedang (600-1500m): kopi, teh\n3. Sejuk (1500-2500m): sayuran, pinus\n4. Dingin (>2500m): lumut, edelweis\nJawaban: A."},
]);

appendQuestions('saintek_matipa', [
{question:"Jika f(x,y) = x^2 y^3, maka d^2f/dxdy = ...",options: ["6xy^2","2xy^3","3x^2y^2","6x^2y","2x"],answer:0,hint:"df/dx = 2xy^3. d(2xy^3)/dy = 6xy^2.",explanation:"df/dx = 2xy^3.\nd^2f/dxdy = d/dy(2xy^3) = 2x(3y^2) = 6xy^2.\nMixed partial derivative (Clairaut's theorem: order doesn't matter).\nJawaban: A."},
]);
