// DEFINITIVE FINAL — Saintek +150 (38 per subject)

appendQuestions('saintek_matipa', [
{question:"$\\int_0^{\\pi} \\sin(x) dx = ...$",options: ["2","0","$\\pi$","1","$-1$"],answer:0,explanation:"$[-\\cos x]_0^\\pi = -\\cos\\pi - (-\\cos 0) = 1 + 1 = 2$."},
{question:"Turunan dari $e^x$ adalah ...",options: ["$e^x$","$xe^{x-1}$","$e$","$x$","$1$"],answer:0,explanation:"$\\frac{d}{dx}e^x = e^x$. Fungsi eksponensial natural = turunan dirinya sendiri."},
{question:"Nilai $\\arctan(1) = ...$",options: ["$\\frac{\\pi}{4}$","$\\frac{\\pi}{2}$","$\\pi$","$\\frac{\\pi}{3}$","$\\frac{\\pi}{6}$"],answer:0,explanation:"$\\tan(\\pi/4) = 1$, jadi $\\arctan(1) = \\pi/4 = 45^\\circ$."},
{question:"Mean dari data 2, 4, 6, 8, 10 adalah ...",options: ["6","5","7","8","4"],answer:0,explanation:"Mean = $(2+4+6+8+10)/5 = 30/5 = 6$."},
{question:"Luas segitiga dengan alas 10 cm dan tinggi 8 cm adalah ...",options: ["40 cm^2","80 cm^2","18 cm^2","56 cm^2","20 cm^2"],answer:0,explanation:"$L = \\frac{1}{2} \\times 10 \\times 8 = 40$ cm^2."},
{question:"Jika $f(x) = 3^x$, maka $f(4) = ...$",options: ["81","27","9","243","12"],answer:0,explanation:"$f(4) = 3^4 = 81$."},
{question:"Keliling lingkaran dengan diameter 14 cm ($\\pi \\approx \\frac{22}{7}$) = ...",options: ["44 cm","28 cm","88 cm","154 cm","22 cm"],answer:0,explanation:"$K = \\pi d = \\frac{22}{7} \\times 14 = 44$ cm."},
{question:"$\\sqrt{144} = ...$",options: ["12","14","11","13","10"],answer:0,explanation:"$12^2 = 144$, jadi $\\sqrt{144} = 12$."},
{question:"Jika $P(A) = 0.3$ dan $P(B) = 0.5$ (independen), $P(A \\cap B) = ...$",options: ["0.15","0.8","0.2","0.35","0.5"],answer:0,explanation:"Independen: $P(A \\cap B) = P(A) \\times P(B) = 0.3 \\times 0.5 = 0.15$."},
{question:"Gradien garis $2x + 3y = 6$ adalah ...",options: ["$-\\frac{2}{3}$","$\\frac{2}{3}$","$2$","$3$","$-\\frac{3}{2}$"],answer:0,explanation:"$3y = -2x + 6 \\Rightarrow y = -\\frac{2}{3}x + 2$. Gradien = $-2/3$."},
{question:"Persamaan kuadrat yang akar-akarnya 1 dan 5 adalah ...",options: ["$x^2 - 6x + 5 = 0$","$x^2 + 6x + 5 = 0$","$x^2 - 5x + 1 = 0$","$x^2 - 5x + 6 = 0$","$x^2 + 5x - 6 = 0$"],answer:0,explanation:"$(x-1)(x-5) = x^2 - 6x + 5 = 0$."},
{question:"Turunan kedua $f(x) = x^4$ adalah ...",options: ["$12x^2$","$4x^3$","$x^3$","$4x^2$","$24x$"],answer:0,explanation:"$f'(x) = 4x^3$, $f''(x) = 12x^2$."},
{question:"Hasil kali silang $\\vec{i} \\times \\vec{j} = ...$",options: ["$\\vec{k}$","$-\\vec{k}$","$\\vec{i}$","$\\vec{j}$","$0$"],answer:0,explanation:"$\\hat{i} \\times \\hat{j} = \\hat{k}$ (aturan tangan kanan)."},
]);

appendQuestions('saintek_fisika', [
{question:"Modulus Young mengukur ...",options: ["Elastisitas/kekakuan suatu bahan","Kecepatan suara","Suhu bahan","Berat bahan","Warna bahan"],answer:0,explanation:"Young's modulus $E = \\frac{\\text{stress}}{\\text{strain}}$: rasio tegangan terhadap regangan."},
{question:"Hukum II termodinamika menyatakan ...",options: ["Entropi sistem terisolasi selalu cenderung meningkat","Energi kekal","F=ma","Tekanan ∝ suhu","Momentum kekal"],answer:0,explanation:"Hukum II termodinamika: entropi alam semesta cenderung meningkat; panas mengalir dari panas ke dingin."},
{question:"Medan listrik di antara dua plat paralel bersifat ...",options: ["Seragam (homogen)","Radial","Melingkar","Tidak ada medan","Bergradien tinggi"],answer:0,explanation:"Medan listrik kapasitor plat sejajar: seragam (E konstan) di antara plat."},
{question:"Induktansi diri (self-inductance) diukur dalam satuan ...",options: ["Henry (H)","Farad (F)","Ohm ($\\Omega$)","Tesla (T)","Weber (Wb)"],answer:0,explanation:"Henry (H): satuan SI induktansi. $\\varepsilon = -L \\frac{dI}{dt}$."},
{question:"Wavelet de Broglie: panjang gelombang partikel $\\lambda = ...$",options: ["$h/p$ (h/momentum)","$h \\cdot p$","$p/h$","$h/E$","$E/h$"],answer:0,explanation:"de Broglie: $\\lambda = h/p = h/(mv)$. Setiap partikel bermassa memiliki sifat gelombang."},
{question:"Prinsip ketidakpastian Heisenberg menyatakan ...",options: ["Tidak mungkin mengetahui posisi dan momentum partikel secara bersamaan dengan presisi sempurna","Semua bisa diukur pasti","Hanya momentum yang tidak pasti","Hanya posisi yang tidak pasti","Cahaya selalu gelombang"],answer:0,explanation:"$\\Delta x \\cdot \\Delta p \\geq \\frac{\\hbar}{2}$: ketidakpastian fundamental dalam pengukuran kuantum."},
{question:"Resonansi terjadi ketika ...",options: ["Frekuensi gaya luar = frekuensi alami sistem","Frekuensi sangat berbeda","Amplitudo nol","Tidak ada getaran","Sistem diam"],answer:0,explanation:"Resonansi: amplitudo getaran maksimum saat frekuensi paksa = frekuensi natural."},
{question:"Benda terapung jika ...",options: ["Massa jenis benda < massa jenis fluida","Massa jenis benda > fluida","Massa benda sangat besar","Volume benda kecil","Tekanan udara tinggi"],answer:0,explanation:"Syarat terapung: $\\rho_{benda} < \\rho_{fluida}$ \\to gaya apung > berat \\to mengapung."},
{question:"Satelit geostationary memiliki periode ...",options: ["24 jam","12 jam","1 jam","90 menit","365 hari"],answer:0,explanation:"Geostationary: orbit sinkron dengan rotasi bumi = 24 jam, tampak diam dari bumi."},
{question:"Efek Hall menghasilkan ...",options: ["Beda potensial tegak lurus arus dan medan magnet","Arus tambahan","Suhu meningkat","Hambatan menurun","Cahaya"],answer:0,explanation:"Efek Hall: perbedaan potensial melintang (tegak lurus arus & B) pada konduktor berarus dalam medan magnet."},
{question:"Intensitas gelombang berbanding terbalik dengan kuadrat jarak dari sumber, dikenal sebagai ...",options: ["Hukum kuadrat terbalik (inverse square law)","Hukum linear","Hukum kubik","Hukum eksponensial","Hukum konstan"],answer:0,explanation:"$I \\propto 1/r^2$: intensitas gelombang dari sumber titik menurun sebagai kuadrat terbalik jarak."},
{question:"Panjang gelombang cahaya tampak berkisar ...",options: ["400-700 nm","1-10 nm","10-100 $\\mu$mm","1-10 mm","1-10 cm"],answer:0,explanation:"Cahaya tampak (visible light): ~400 nm (ungu) sampai ~700 nm (merah)."},
{question:"Superkonduktor memiliki hambatan listrik ...",options: ["Nol (tepat 0 $\\Omega$)","Sangat besar","Sama dengan tembaga","Negatif","Tidak terbatas"],answer:0,explanation:"Superkonduktor: hambatan listrik tepat = 0 di bawah suhu kritis (Tc)."},
]);

appendQuestions('saintek_kimia', [
{question:"Hukum Avogadro menyatakan ...",options: ["Volume gas sebanding dengan jumlah mol pada T dan P tetap","Massa selalu konstan","Tekanan ∝ volume","Suhu berbanding terbalik volume","Mol tidak memengaruhi volume"],answer:0,explanation:"Avogadro: $V \\propto n$ (pada T, P konstan). Gas bermol sama \\to volumenya sama."},
{question:"Bilangan Avogadro bernilai ...",options: ["$6.022 \\times 10^{23}$ partikel/mol","$6.022 \\times 10^{22}$","$3.14 \\times 10^{8}$","$1.6 \\times 10^{-19}$","$9.1 \\times 10^{-31}$"],answer:0,explanation:"$N_A = 6.022 \\times 10^{23}$: jumlah partikel dalam 1 mol zat."},
{question:"Hukum Boyle: pada suhu tetap ...",options: ["$PV = \\text{konstan}$ (tekanan dan volume berbanding terbalik)","$P \\propto V$","$P = V$","${P}/{V} = \\text{konstan}$","$P + V = \\text{konstan}$"],answer:0,explanation:"Boyle: $PV = k$ pada T konstan. P ↑ \\to V ↓ (dan sebaliknya)."},
{question:"Hukum Charles: pada tekanan tetap ...",options: ["$V \\propto T$ (volume sebanding suhu absolut)","$V \\propto 1/T$","$V = \\text{konstan}$","$T = \\text{konstan}$","$V \\propto P$"],answer:0,explanation:"Charles: $V/T = k$ pada P konstan. Suhu naik \\to volume naik."},
{question:"Perbedaan antara senyawa dan campuran ...",options: ["Senyawa: gabungan unsur melalui reaksi kimia, komposisi tetap; campuran: gabungan fisik, komposisi bervariasi","Keduanya sama","Campuran melalui reaksi","Senyawa komposisi bervariasi","Tidak ada perbedaan"],answer:0,explanation:"Senyawa: ikatan kimia, rumus tetap (H_2O). Campuran: fisik, komposisi variabel (udara, larutan gula)."},
{question:"Gaya Van der Waals meliputi ...",options: ["Gaya dispersi London, dipol-dipol, dan ikatan hidrogen","Hanya ikatan ionik","Hanya ikatan kovalen","Hanya ikatan logam","Hanya ikatan koordinasi"],answer:0,explanation:"Van der Waals: gaya antarmolekul lemah — London dispersion, dipol-dipol, dan hydrogen bonding."},
{question:"Elektrolisis larutan NaCl menghasilkan ...",options: ["Gas klorin (Cl_2) di anoda dan gas hidrogen (H_2) di katoda","NaCl padat","Tidak ada reaksi","Natrium logam di anoda","Oksigen di katoda"],answer:0,explanation:"Elektrolisis NaCl(aq): anoda $\\to$ Cl_2 (gas); katoda $\\to$ H_2 (gas); juga NaOH terbentuk."},
{question:"Reaksi reduksi melibatkan ...",options: ["Penerimaan elektron (biloks turun)","Pelepasan elektron","Biloks naik","Tidak ada transfer elektron","Kehilangan proton"],answer:0,explanation:"Reduksi: penerimaan elektron $\\to$ bilangan oksidasi menurun."},
{question:"Reaksi oksidasi melibatkan ...",options: ["Pelepasan elektron (biloks naik)","Penerimaan elektron","Biloks turun","Tidak ada transfer elektron","Penambahan proton saja"],answer:0,explanation:"Oksidasi: pelepasan elektron $\\to$ bilangan oksidasi meningkat. OIL RIG."},
{question:"Geometri molekul H_2O adalah ...",options: ["Bentuk V (bent/angular)","Linear","Tetrahedral","Trigonal planar","Oktahedral"],answer:0,explanation:"H_2O: 2 domain ikatan + 2 lone pair $\\to$ s$p^3$ tapi bentuknya bent (~104.5^$\\circ$)."},
{question:"pH larutan H_2SO_4 0.005 M adalah ...",options: ["2","1","3","4","7"],answer:0,explanation:"H_2SO_4 divalen: $[H^+] = 2 \\times 0.005 = 0.01 = 10^{-2}$. pH = 2."},
{question:"Protein tersusun dari monomer berupa ...",options: ["Asam amino","Glukosa","Nukleotida","Asam lemak","Gliserol"],answer:0,explanation:"Protein = polimer asam amino yang dihubungkan oleh ikatan peptida."},
]);

appendQuestions('saintek_biologi', [
{question:"Retikulum endoplasma kasar berbeda dari RE halus karena memiliki ...",options: ["Ribosom pada permukaannya","Mitokondria","Kloroplas","Vakuola","Lisosom"],answer:0,explanation:"RE kasar: ribosom menempel di permukaan $\\to$ sintesis protein. RE halus: tanpa ribosom $\\to$ lipid/detoksifikasi."},
{question:"Badan Golgi berfungsi untuk ...",options: ["Memodifikasi, mengemas, dan mengirim protein/lipid","Respirasi sel","Fotosintesis","Pencernaan intraseluler","Replikasi DNA"],answer:0,explanation:"Golgi apparatus: processing center — memodifikasi, menyortir, mengemas protein untuk sekresi."},
{question:"Lisosom berfungsi untuk ...",options: ["Pencernaan intraseluler (mengandung enzim hidrolitik)","Fotosintesis","Respirasi aerob","Sintesis protein","Replikasi DNA"],answer:0,explanation:"Lisosom: organel yang mengandung enzim pencernaan — mendaur ulang komponen sel yang rusak."},
{question:"Mitokondria sering disebut 'powerhouse of the cell' karena ...",options: ["Menghasilkan ATP melalui respirasi seluler","Menyimpan DNA","Menghasilkan protein","Menghasilkan lipid","Membelah sel"],answer:0,explanation:"Mitokondria: tempat respirasi aerob yang menghasilkan sebagian besar ATP sel."},
{question:"Difusi adalah perpindahan zat dari konsentrasi ... ke ...",options: ["Tinggi ke rendah (searah gradien)","Rendah ke tinggi","Sama ke sama","Tinggi ke tinggi","Rendah ke rendah"],answer:0,explanation:"Difusi: pergerakan net molekul dari konsentrasi tinggi $\\to$ rendah (down the concentration gradient)."},
{question:"Transpor aktif memerlukan ...",options: ["Energi (ATP) karena melawan gradien konsentrasi","Tidak perlu energi","Difusi pasif","Osmosis saja","Tidak ada membran"],answer:0,explanation:"Transpor aktif: memindahkan zat melawan gradien konsentrasi $\\to$ memerlukan energi ATP."},
{question:"Hukum Hardy-Weinberg berlaku pada populasi yang ...",options: ["Besar, kawin acak, tanpa mutasi/seleksi/migrasi","Kecil dan terisolasi","Mengalami seleksi kuat","Banyak mutasi","Inbreeding tinggi"],answer:0,explanation:"Hardy-Weinberg: frekuensi alel konstan di populasi ideal (besar, random mating, tanpa evolusi)."},
{question:"Spesiasi alopatrik terjadi karena ...",options: ["Isolasi geografis memisahkan populasi","Isolasi reproduksi tanpa pemisahan geografis","Mutasi tunggal","Seleksi buatan","Rekombinasi saja"],answer:0,explanation:"Alopatrik: populasi terpisah secara geografis (pegunungan, sungai) $\\to$ evolusi terpisah $\\to$ spesies baru."},
{question:"Adaptasi morfologis contohnya ...",options: ["Paruh burung pemikat yang berbeda bentuk sesuai makanan","Migrasi","Hibernasi","Kamuflase perilaku","Simbiosis"],answer:0,explanation:"Adaptasi morfologis: perubahan struktur tubuh. Contoh: paruh Galapagos finches (Darwin)."},
{question:"Piramida biomassa di ekosistem darat biasanya berbentuk ...",options: ["Tegak (produsen > konsumen)","Terbalik","Datar","Acak","Bergilir"],answer:0,explanation:"Di darat: biomassa terbesar pada produsen (tumbuhan) $\\to$ berkurang ke konsumen tingkat tinggi."},
{question:"Eukariot berbeda dari prokariot karena memiliki ...",options: ["Membran inti (nukleus sejati)","Ribosom saja","Dinding sel saja","DNA saja","Sitoplasma saja"],answer:0,explanation:"Eukariot: membran inti, organel bermembran (mitokondria, RE, Golgi). Prokariot: tanpa membran inti."},
{question:"Perkembangbiakan vegetatif alami tumbuhan contohnya ...",options: ["Umbi, tunas, stolon, rizom","Penyerbukan","Pembuahan ganda","Biji","Spora saja"],answer:0,explanation:"Vegetatif alami: reproduksi aseksual tumbuhan melalui umbi, tunas, stolon, rizom (tanpa gamet)."},
]);
