// SOSHUM FINAL 30 — +30 (8 per subject) → 1000

appendQuestions('soshum_ekonomi', [
{question:"Inflasi inti (core inflation) mengeluarkan ...",options: ["Harga makanan dan energi yang volatile","Semua komponen (berdasarkan teori dasar)","Hanya makanan (secara konseptual)","Hanya jasa (berdasarkan asumsi dasar)","Hanya barang mewah (dalam kerangka teori)"],answer:0,explanation:"Core inflation: inflasi yang mengeluarkan komponen volatile (bahan makanan, energi) → tren harga fundamental."},
{question:"Rasio utang terhadap PDB (debt-to-GDP ratio) Indonesia saat ini kisaran ...",options: ["~39% (di bawah batas UU 60%)","~100% (secara fundamental)","~200% (dalam pemahaman konvensional)","~5% (menurut konsensus ilmiah)","~80% (dalam arti sempit)"],answer:0,explanation:"Indonesia: rasio utang/PDB ~39% — masih di bawah batas UU Keuangan Negara (60% dari PDB)."},
{question:"Likuiditas bank menunjukkan ...",options: ["Kemampuan bank memenuhi kewajiban jangka pendek","Keuntungan jangka panjang (dalam definisi teknis)","Ukuran bank (dalam konteks umum; berdasarkan teori dasar)","Jumlah karyawan (berdasarkan referensi umum)","Jumlah cabang (menurut kerangka berpikir umum)"],answer:0,explanation:"Likuiditas: kemampuan bank membayar kewajiban segera → loan-to-deposit ratio, reserve requirement."},
{question:"Fintech P2P lending adalah ...",options: ["Platform yang menghubungkan pemberi pinjaman dan peminjam secara langsung","Bank konvensional (secara normatif; dalam batasan konvensional; dalam literatur standar)","Asuransi (dari perspektif akademis; secara fundamental; dari sudut pandang klasik)","Reksadana (sesuai klasifikasi umum; dalam pemahaman konvensional; secara umum)","Deposito (berdasarkan teori dasar; menurut konsensus ilmiah; berdasarkan asumsi dasar)"],answer:0,explanation:"P2P lending: platform digital yang mempertemukan lender dan borrower tanpa perantara bank tradisional."},
{question:"Omnibus Law (UU Cipta Kerja) bertujuan ...",options: ["Menyederhanakan regulasi untuk menarik investasi dan menciptakan lapangan kerja","Mempersulit investasi (secara konvensional; dalam pengertian luas; dalam arti sempit)","Melarang investasi asing (pada konteks konvensional; dalam definisi teknis; di konteks ini)","Menghapus UMKM (dalam batasan konvensional; dalam konteks umum; dalam pemahaman konvensional)","Menutup pabrik (secara fundamental; berdasarkan referensi umum; secara fundamental)"],answer:0,explanation:"UU Cipta Kerja: menyederhanakan perizinan, memperbaiki iklim investasi, mereformasi ketenagakerjaan."},
{question:"Ekonomi kerakyatan tercantum dalam ...",options:["Pasal 33 UUD 1945","Pasal 1 UUD 1945","Pasal 29 UUD 1945","Pasal 31 UUD 1945","Pasal 27 UUD 1945"],answer:0,explanation:"Pasal 33 UUD 1945: perekonomian disusun sebagai usaha bersama atas asas kekeluargaan."},
{question:"Deposito berjangka memberikan bunga yang ...",options: ["Lebih tinggi dari tabungan biasa karena dana terikat jangka waktu tertentu","Lebih rendah dari tabungan (menurut pengertian baku; berdasarkan acuan formal)","Sama dengan tabungan (sesuai paradigma tradisional; secara konvensional)","Nol (menurut prinsip dasar; pada konteks konvensional)","Negatif (secara normatif; dalam batasan konvensional)"],answer:0,explanation:"Deposito: bunga lebih tinggi karena dana dikunci (1-24 bulan) → bank memiliki kepastian funding."},
{question:"Giro (demand deposit) dapat ditarik kapan saja menggunakan ...",options: ["Cek atau bilyet giro","Hanya ATM (secara literal)","Hanya buku tabungan","Hanya transfer saja","Hanya tunai (pada dasarnya)"],answer:0,explanation:"Giro: simpanan yang penarikannya dapat dilakukan setiap saat dengan cek, bilyet giro, atau pemindahbukuan."},
]);

appendQuestions('soshum_sosiologi', [
{question:"Masyarakat informasi (information society) ditandai oleh ...",options: ["Dominasi produksi dan distribusi informasi/pengetahuan","Dominasi pertanian (berdasarkan asumsi dasar)","Dominasi industri (dalam kerangka teori; menurut pengertian baku)","Tanpa teknologi (dari sudut pandang klasik)","Isolasi total (dalam literatur standar; menurut prinsip dasar)"],answer:0,explanation:"Information society: masyarakat yang ekonomi dan sosialnya didominasi oleh informasi dan teknologi digital."},
{question:"Rasionalisasi menurut Weber berarti ...",options: ["Proses penggantian tindakan tradisional/afektif dengan tindakan rasional-kalkulatif","Penolakan logika (menurut konsensus ilmiah; sesuai teori klasik; pada konteks konvensional)","Kembali ke tradisi (dalam arti sempit; berdasarkan premis dasar; secara konvensional)","Emosi dominan (menurut definisi standar; secara terminologis; menurut prinsip dasar; pada konteks konvensional)","Irasionalitas (menurut pengertian baku; berdasarkan acuan formal; secara terminologis)"],answer:0,explanation:"Weber: rasionalisasi = tren sejarah di mana kalkulasi efisiensi menggantikan tradisi dan emosi."},
{question:"Birokrasi ideal menurut Weber bercirikan ...",options: ["Hierarki, aturan formal, spesialisasi, impersonalitas, merit-based","Tanpa aturan (berdasarkan referensi umum; secara konseptual)","Berdasarkan kesukaan (menurut kerangka berpikir umum)","Tidak ada hierarki (sesuai teori klasik; dalam kerangka teori)","Tanpa spesialisasi (berdasarkan premis dasar; dari sudut pandang klasik)"],answer:0,explanation:"Weber: birokrasi ideal — struktur hierarkis, aturan tertulis, rekrutmen berdasarkan kompetensi."},
{question:"Kapital simbolik menurut Bourdieu meliputi ...",options: ["Prestise, kehormatan, dan pengakuan sosial","Hanya uang (sesuai klasifikasi umum)","Hanya tanah (berdasarkan teori dasar)","Hanya pendidikan (secara konseptual)","Hanya teknologi (berdasarkan asumsi dasar)"],answer:0,explanation:"Symbolic capital: sumber daya berupa prestise, reputasi, status yang memberikan legitimasi dan pengaruh."},
{question:"Masyarakat risk society menurut Ulrich Beck ditandai oleh ...",options: ["Risiko global (lingkungan, nuklir, finansial) yang tidak bisa diprediksi sepenuhnya","Tidak ada risiko (dalam batasan konvensional; dalam konteks umum; dalam definisi teknis)","Keamanan total (secara fundamental; berdasarkan referensi umum; dalam pengertian luas)","Stabilitas sempurna (dalam pemahaman konvensional; menurut kerangka berpikir umum)","Tanpa ancaman (menurut konsensus ilmiah; sesuai teori klasik; secara konvensional; dalam pengertian luas)"],answer:0,explanation:"Beck: risk society — masyarakat modern menghadapi risiko buatan manusia (nuklir, kimia, finansial) yang global."},
{question:"Subkultur adalah ...",options: ["Kelompok dalam masyarakat yang memiliki nilai dan norma berbeda dari budaya dominan","Budaya utama (dalam pengertian luas; dari perspektif akademis; menurut pandangan mainstream; secara normatif)","Budaya tunggal (dalam definisi teknis; sesuai klasifikasi umum; menurut pengertian baku)","Tanpa budaya (dalam konteks umum; berdasarkan teori dasar; dari sudut pandang klasik; sesuai paradigma tradisional)","Budaya hilang (berdasarkan referensi umum; secara konseptual; dalam kerangka teori; menurut pengertian baku)"],answer:0,explanation:"Subculture: kelompok dengan budaya khas yang berbeda (tapi tidak selalu bertentangan) dengan mainstream."},
{question:"Kontrakultur berbeda dari subkultur karena ...",options: ["Kontrakultur secara aktif menentang budaya dominan","Keduanya sama (menurut prinsip dasar; pada konteks konvensional)","Kontrakultur mendukung mainstream (secara normatif)","Subkultur menentang (dari perspektif akademis)","Tidak ada perbedaan (sesuai klasifikasi umum)"],answer:0,explanation:"Counterculture: secara eksplisit menolak/melawan nilai-nilai budaya mainstream. Contoh: hippie, punk."},
{question:"Sosiologi pengetahuan mempelajari ...",options: ["Hubungan antara pengetahuan dan konteks sosial yang menghasilkannya","Hanya sains alam (berdasarkan acuan formal; menurut pandangan mainstream)","Hanya matematika (secara konvensional; dalam pengertian luas)","Hanya teknologi (pada konteks konvensional; dalam definisi teknis)","Hanya fisika (dalam batasan konvensional; dalam konteks umum)"],answer:0,explanation:"Sociology of knowledge (Mannheim, Berger): bagaimana pengetahuan dibentuk, dipengaruhi, dan dilegitimasi oleh konteks sosial."},
]);
