// SOSHUM FINAL CLOSE — +62 (16 per subject) → exactly 1000

appendQuestions('soshum_ekonomi', [
{question:"Usaha mikro memiliki omzet tahunan maksimal ...",options: ["Rp300 juta (UU No. 20/2008)","Rp1 miliar (berdasarkan teori dasar)","Rp5 miliar (secara konseptual)","Rp10 miliar (berdasarkan asumsi dasar)","Rp50 miliar (dalam kerangka teori)"],answer:0,explanation:"UU UMKM: usaha mikro = omzet ≤ Rp300 juta/tahun, aset ≤ Rp50 juta (di luar tanah dan bangunan)."},
{question:"Pajak Pertambahan Nilai (PPN) termasuk jenis pajak ...",options: ["Objektif dan tidak langsung","Subjektif dan langsung","Daerah (dalam pemahaman konvensional)","Progresif (menurut konsensus ilmiah)","Personal (dalam arti sempit)"],answer:0,explanation:"PPN: dikenakan pada barang/jasa (objektif), dibayar konsumen melalui penjual (tidak langsung). Tarif 11%."},
{question:"Kartel adalah bentuk kerja sama antar perusahaan yang bertujuan ...",options: ["Mengatur harga dan produksi untuk menghindari persaingan","Memperbanyak pesaing (dalam definisi teknis)","Menurunkan harga (dalam konteks umum; berdasarkan teori dasar)","Meningkatkan persaingan (berdasarkan referensi umum)","Membuka pasar baru (menurut kerangka berpikir umum)"],answer:0,explanation:"Kartel: kesepakatan antar perusahaan sejenis untuk mengontrol harga/output — mengurangi persaingan (ilegal)."},
{question:"Net Present Value (NPV) positif berarti ...",options: ["Investasi menguntungkan (return > biaya modal)","Investasi merugi (secara normatif; dalam batasan konvensional)","Harus ditolak (dari perspektif akademis)","Tidak ada keuntungan (sesuai klasifikasi umum)","Biaya melebihi return (berdasarkan teori dasar)"],answer:0,explanation:"NPV > 0: present value cash inflow > present value cash outflow → investasi layak diterima."},
{question:"Inflation targeting framework (ITF) di Indonesia diterapkan oleh ...",options: ["Bank Indonesia (sejak 2005)","Kementerian Keuangan (pada dasarnya)","OJK (pada konteks konvensional)","BPK (dalam batasan konvensional)","Kemenkeu (secara fundamental)"],answer:0,explanation:"ITF: BI menetapkan target inflasi eksplisit dan menggunakan kebijakan moneter untuk mencapainya."},
{question:"Ekonomi kreatif meliputi industri berbasis ...",options: ["Kreativitas, talenta, dan kekayaan intelektual","Pertambangan (dalam literatur standar; dalam praktik)","Pertanian saja (menurut pandangan mainstream)","Perikanan saja (dalam pengertian luas; secara literal)","Kehutanan saja (dalam definisi teknis; menurut standar)"],answer:0,explanation:"Ekonomi kreatif: 17 subsektor (film, musik, desain, kuliner, gaming, fashion, dll) berbasis ide dan kreativitas."},
{question:"Inklusi keuangan bertujuan ...",options: ["Memperluas akses layanan keuangan bagi seluruh lapisan masyarakat","Membatasi akses keuangan (menurut pengertian baku)","Menghapus bank (sesuai paradigma tradisional; secara konvensional)","Menaikkan bunga (menurut prinsip dasar; pada konteks konvensional)","Mengurangi tabungan (secara normatif; dalam batasan konvensional)"],answer:0,explanation:"Financial inclusion: semua orang, termasuk unbankable, dapat mengakses produk/layanan keuangan."},
{question:"Dampak positif perdagangan internasional bagi Indonesia meliputi ...",options: ["Devisa, transfer teknologi, perluasan pasar, dan peningkatan efisiensi","Hanya impor (berdasarkan premis dasar; dari sudut pandang klasik)","Menghalangi pertumbuhan (secara terminologis; dalam literatur standar)","Mengurangi pendapatan (berdasarkan acuan formal; menurut pandangan mainstream)","Merusak industri lokal (secara konvensional; dalam pengertian luas)"],answer:0,explanation:"Perdagangan internasional: meningkatkan devisa, mendorong spesialisasi, transfer teknologi dan pengetahuan."},
]);

appendQuestions('soshum_sosiologi', [
{question:"Kelompok acuan normatif berfungsi ...",options: ["Memberikan standar norma dan nilai yang dianut individu","Hanya memberikan informasi (berdasarkan asumsi dasar)","Hanya hiburan (dalam kerangka teori; menurut pengertian baku)","Hanya teknologi (dari sudut pandang klasik)","Hanya ekonomi (dalam literatur standar; menurut prinsip dasar)"],answer:0,explanation:"Normative reference group: kelompok yang menjadi sumber norma/nilai yang diadopsi individu."},
{question:"Teori labeling (Howard Becker) menekankan ...",options: ["Penyimpangan ditentukan oleh reaksi/label masyarakat, bukan tindakan itu sendiri","Penyimpangan bersifat bawaan (menurut konsensus ilmiah; sesuai teori klasik)","Tidak ada penyimpangan (dalam arti sempit; berdasarkan premis dasar; secara konvensional)","Semua orang menyimpang (menurut definisi standar; secara terminologis; berdasarkan acuan formal)","Penyimpangan positif saja (menurut pengertian baku; berdasarkan acuan formal)"],answer:0,explanation:"Becker: deviasi bukan kualitas intrinsik tindakan, tapi konsekuensi dari label yang diberikan orang lain."},
{question:"Social capital menurut Putnam mencakup ...",options: ["Jejaring, norma, dan kepercayaan yang memfasilitasi kerjasama","Hanya uang (berdasarkan referensi umum; secara konseptual)","Hanya tanah (menurut kerangka berpikir umum; berdasarkan asumsi dasar)","Hanya pendidikan (sesuai teori klasik; dalam kerangka teori)","Hanya teknologi (berdasarkan premis dasar; dari sudut pandang klasik)"],answer:0,explanation:"Putnam: modal sosial = networks, norms, trust yang memungkinkan tindakan kolektif efektif."},
{question:"Determinisme teknologi menyatakan ...",options: ["Teknologi membentuk dan menentukan perubahan sosial","Masyarakat menentukan teknologi (sesuai klasifikasi umum)","Keduanya tidak terkait (berdasarkan teori dasar)","Hanya budaya yang berpengaruh (secara konseptual)","Hanya ekonomi yang berpengaruh (berdasarkan asumsi dasar)"],answer:0,explanation:"Technological determinism: inovasi teknologi sebagai penggerak utama perubahan sosial dan budaya."},
{question:"Teori spiral of silence (spiral keheningan) menyatakan ...",options: ["Orang cenderung diam jika pendapatnya minoritas karena takut isolasi","Semua orang bicara (dalam batasan konvensional; dalam konteks umum)","Tidak ada tekanan sosial (secara fundamental; berdasarkan referensi umum)","Mayoritas selalu diam (dalam pemahaman konvensional)","Minoritas selalu dominan (menurut konsensus ilmiah)"],answer:0,explanation:"Noelle-Neumann: fear of isolation → orang menyembunyikan pendapat jika merasa berlawanan dengan mayoritas."},
{question:"Habitualisasi menurut Berger & Luckmann adalah ...",options: ["Pengulangan tindakan menjadi pola kebiasaan","Tindakan spontan (dalam pengertian luas)","Perilaku acak (dalam definisi teknis)","Inovasi setiap saat (dalam konteks umum)","Perubahan konstan (berdasarkan referensi umum)"],answer:0,explanation:"Habitualisasi: tindakan yang diulang → menjadi pola → dianggap 'normal' → melembaga (institutionalisasi)."},
{question:"Fungsi manifes pendidikan menurut Merton ...",options: ["Fungsi yang disengaja dan diakui: sosialisasi pengetahuan, keterampilan","Fungsi tersembunyi (menurut prinsip dasar; pada konteks konvensional)","Dampak tidak diinginkan (secara normatif; dalam batasan konvensional)","Disfungsi (dari perspektif akademis; secara fundamental)","Kerusakan sosial (sesuai klasifikasi umum; dalam pemahaman konvensional)"],answer:0,explanation:"Manifest function: tujuan resmi dan diakui dari lembaga pendidikan — transfer pengetahuan, keterampilan."},
{question:"Fungsi laten pendidikan menurut Merton ...",options: ["Fungsi yang tidak disadari: pembentukan jaringan sosial, penundaan masuk pasar kerja","Fungsi utama (berdasarkan acuan formal; menurut pandangan mainstream; sesuai klasifikasi umum)","Tujuan resmi (secara konvensional; dalam pengertian luas; dalam konteks umum; berdasarkan teori dasar)","Kurikulum (pada konteks konvensional; dalam definisi teknis; dalam definisi teknis; sesuai klasifikasi umum)","Ujian (dalam batasan konvensional; dalam konteks umum; dalam pengertian luas; dari perspektif akademis)"],answer:0,explanation:"Latent function: dampak tidak disengaja — sekolah sebagai childcare, pembentukan peer group, sosialisasi."},
]);

appendQuestions('soshum_sejarah', [
{question:"Kerajaan Majapahit mencapai puncak kejayaan pada masa pemerintahan ...",options: ["Hayam Wuruk dan Gajah Mada","Raden Wijaya saja (secara teknis)","Ken Arok (dalam literatur standar)","Airlangga (menurut pandangan mainstream)","Kertajaya (dalam pengertian luas)"],answer:0,explanation:"Majapahit jaya: Hayam Wuruk (raja) + Gajah Mada (mahapatih) abad ke-14 — menguasai hampir seluruh Nusantara."},
{question:"Kerajaan Sriwijaya merupakan kerajaan maritim yang berpusat di ...",options: ["Sumatera Selatan (Palembang)","Jawa Barat (menurut definisi standar)","Kalimantan (menurut pengertian baku)","Sulawesi (sesuai paradigma tradisional)","Papua (menurut prinsip dasar)"],answer:0,explanation:"Sriwijaya: kerajaan maritim-Buddha terbesar (abad ke-7-13), pusat di Palembang, menguasai Selat Malaka."},
{question:"I-Tsing, pendeta Tiongkok, mencatat kehadiran kerajaan ... pada abad ke-7.",options:["Sriwijaya","Kutai","Tarumanegara","Majapahit","Mataram"],answer:0,explanation:"I-Tsing (abad ke-7): mencatat Sriwijaya sebagai pusat pembelajaran agama Buddha yang penting."},
{question:"Perang Dunia I dimulai pada tahun ...",options:["1914","1939","1941","1945","1918"],answer:0,explanation:"PD I: 1914-1918. Dipicu pembunuhan Archduke Franz Ferdinand di Sarajevo (28 Juni 1914)."},
{question:"Perang Dunia II dimulai dengan invasi Jerman ke ... pada ...",options: ["Polandia, 1 September 1939","Prancis, 1940 (dalam pemahaman konvensional)","Rusia, 1941 (menurut konsensus ilmiah)","Inggris, 1940 (dalam arti sempit)","Austria, 1938 (menurut definisi standar)"],answer:0,explanation:"PD II dimulai ketika Jerman Nazi menginvasi Polandia pada 1 September 1939."},
{question:"Gerakan Non-Blok (GNB) didirikan pada tahun ... oleh ...",options: ["1961, Soekarno, Nehru, Nasser, Tito, Nkrumah","1945, AS dan Soviet (dalam konteks umum; di konteks ini)","1949, NATO","1955, ASEAN","1967, ASEAN"],answer:0,explanation:"NAM (Non-Aligned Movement): 1961 di Beograd — tidak berpihak pada Blok Barat atau Timur."},
{question:"Sistem tanam paksa (Cultuurstelsel) diterapkan oleh ... pada tahun ...",options: ["Van den Bosch, 1830-1870","Raffles, 1811-1816 (secara klasik)","Daendels, 1808-1811 (secara umum)","Douwes Dekker, 1912 (dalam teori)","Soekarno, 1945 (pada prinsipnya)"],answer:0,explanation:"Cultuurstelsel (1830-1870): petani dipaksa menanam komoditas ekspor (kopi, gula, nila) — sangat menindas."},
{question:"Max Havelaar ditulis oleh ... sebagai kritik terhadap ...",options: ["Multatuli (Eduard Douwes Dekker), sistem tanam paksa","Balai Pustaka (pada konteks konvensional)","Soekarno (dalam batasan konvensional; dalam konteks umum)","Kartini (secara fundamental; berdasarkan referensi umum)","Agus Salim (dalam pemahaman konvensional)"],answer:0,explanation:"Max Havelaar (1860): novel realis oleh Multatuli yang mengkritik penindasan Cultuurstelsel di Hindia Belanda."},
]);

appendQuestions('soshum_geografi', [
{question:"Garis Wallace memisahkan flora dan fauna zona ...",options: ["Asiatis (barat) dan peralihan (tengah/Wallacea)","Utara dan selatan (menurut pandangan mainstream)","Timur dan barat total (dalam pengertian luas)","Asia dan Australia langsung (dalam definisi teknis)","Arktik dan tropis (dalam konteks umum)"],answer:0,explanation:"Garis Wallace: batas biogeografi antara fauna Asiatis (Jawa, Sumatera, Kalimantan) dan fauna peralihan."},
{question:"Kawasan konservasi perairan laut (KKP) bertujuan ...",options: ["Melindungi ekosistem laut dan sumber daya hayati di dalamnya","Memperbesar tangkapan ikan (sesuai paradigma tradisional)","Mencemari laut (menurut prinsip dasar; pada konteks konvensional)","Menguras sumber daya (secara normatif; dalam batasan konvensional)","Membuat tambak (dari perspektif akademis; secara fundamental)"],answer:0,explanation:"KKP: melindungi biodiversitas laut, habitat karang, mangrove, padang lamun, dan spesies dilindungi."},
{question:"Terumbu karang Indonesia termasuk pusat ...",options: ["Segitiga karang dunia (Coral Triangle)","Kutub utara (secara terminologis)","Gurun (berdasarkan acuan formal)","Tundra (secara konvensional; dalam pengertian luas)","Padang es (pada konteks konvensional)"],answer:0,explanation:"Coral Triangle: Indonesia, Malaysia, Filipina, Papua Nugini, Timor Leste, Solomon — pusat biodiversitas laut."},
{question:"Dampak El Niño terhadap sektor pertanian Indonesia ...",options: ["Kekeringan → gagal panen, kebakaran lahan, krisis air","Panen melimpah (dalam kerangka teori; menurut pengertian baku)","Hujan lebat (dari sudut pandang klasik; sesuai paradigma tradisional)","Banjir besar (dalam literatur standar; menurut prinsip dasar)","Salju (menurut pandangan mainstream; secara normatif)"],answer:0,explanation:"El Niño: curah hujan ↓ di Indonesia → kemarau panjang → gagal panen, kebakaran hutan/lahan."},
{question:"Urbanisasi di Indonesia terjadi karena faktor ...",options: ["Dorong (push) dari desa: kemiskinan; tarik (pull) dari kota: peluang kerja","Hanya keinginan (dalam arti sempit; berdasarkan premis dasar; berdasarkan referensi umum)","Tanpa alasan (menurut definisi standar; secara terminologis; dalam konteks umum)","Hanya kebijakan (menurut pengertian baku; berdasarkan acuan formal; secara teknis)","Hanya tradisi (sesuai paradigma tradisional; secara konvensional; dalam pengertian luas)"],answer:0,explanation:"Push-pull factors: push (kurang lapangan kerja, lahan sempit di desa), pull (peluang kerja, fasilitas di kota)."},
{question:"Pencemaran tanah disebabkan oleh ...",options: ["Limbah industri, pestisida berlebih, sampah non-organik, kebocoran bahan kimia","Hanya hujan (menurut kerangka berpikir umum; berdasarkan asumsi dasar; secara literal)","Hanya angin (sesuai teori klasik; dalam kerangka teori; dalam pengertian luas; dari perspektif akademis)","Hanya sungai (berdasarkan premis dasar; dari sudut pandang klasik; sesuai paradigma tradisional)","Hanya laut (secara terminologis; dalam literatur standar; dalam literatur standar; menurut prinsip dasar)"],answer:0,explanation:"Soil pollution: kontaminasi tanah oleh zat kimia berbahaya — mengurangi kesuburan, mencemari air tanah."},
{question:"Iklim Koppen tipe Aw (savana tropis) ditemukan di ...",options: ["Nusa Tenggara Timur dengan musim kemarau yang panjang","Sumatera Barat (berdasarkan teori dasar)","Kalimantan Barat (secara konseptual; dalam arti sempit)","Papua bagian utara (berdasarkan asumsi dasar)","Jakarta (dalam kerangka teori; menurut pengertian baku)"],answer:0,explanation:"Aw: tropis dengan musim kering yang jelas — NTT, sebagian NTB memiliki savana dan padang rumput."},
{question:"Penataan ruang wilayah Indonesia diatur dalam ...",options: ["UU No. 26 Tahun 2007 tentang Penataan Ruang","UU Pertambangan (secara fundamental)","UU Pendidikan (dalam pemahaman konvensional)","UU Kesehatan (menurut konsensus ilmiah)","UU Perbankan (dalam arti sempit; berdasarkan premis dasar)"],answer:0,explanation:"UUPR: mengatur RTRW (Rencana Tata Ruang Wilayah) nasional, provinsi, dan kabupaten/kota."},
]);
