// SOSHUM FINAL 30 — +30 (8 per subject) → 1000

appendQuestions('soshum_ekonomi', [
{question:"Inflasi inti (core inflation) mengeluarkan ...",options:["Harga makanan dan energi yang volatile","Semua komponen","Hanya makanan","Hanya jasa","Hanya barang mewah"],answer:0,explanation:"Core inflation: inflasi yang mengeluarkan komponen volatile (bahan makanan, energi) → tren harga fundamental."},
{question:"Rasio utang terhadap PDB (debt-to-GDP ratio) Indonesia saat ini kisaran ...",options:["~39% (di bawah batas UU 60%)","~100%","~200%","~5%","~80%"],answer:0,explanation:"Indonesia: rasio utang/PDB ~39% — masih di bawah batas UU Keuangan Negara (60% dari PDB)."},
{question:"Likuiditas bank menunjukkan ...",options:["Kemampuan bank memenuhi kewajiban jangka pendek","Keuntungan jangka panjang","Ukuran bank","Jumlah karyawan","Jumlah cabang"],answer:0,explanation:"Likuiditas: kemampuan bank membayar kewajiban segera → loan-to-deposit ratio, reserve requirement."},
{question:"Fintech P2P lending adalah ...",options:["Platform yang menghubungkan pemberi pinjaman dan peminjam secara langsung","Bank konvensional","Asuransi","Reksadana","Deposito"],answer:0,explanation:"P2P lending: platform digital yang mempertemukan lender dan borrower tanpa perantara bank tradisional."},
{question:"Omnibus Law (UU Cipta Kerja) bertujuan ...",options:["Menyederhanakan regulasi untuk menarik investasi dan menciptakan lapangan kerja","Mempersulit investasi","Melarang investasi asing","Menghapus UMKM","Menutup pabrik"],answer:0,explanation:"UU Cipta Kerja: menyederhanakan perizinan, memperbaiki iklim investasi, mereformasi ketenagakerjaan."},
{question:"Ekonomi kerakyatan tercantum dalam ...",options:["Pasal 33 UUD 1945","Pasal 1 UUD 1945","Pasal 29 UUD 1945","Pasal 31 UUD 1945","Pasal 27 UUD 1945"],answer:0,explanation:"Pasal 33 UUD 1945: perekonomian disusun sebagai usaha bersama atas asas kekeluargaan."},
{question:"Deposito berjangka memberikan bunga yang ...",options:["Lebih tinggi dari tabungan biasa karena dana terikat jangka waktu tertentu","Lebih rendah dari tabungan","Sama dengan tabungan","Nol","Negatif"],answer:0,explanation:"Deposito: bunga lebih tinggi karena dana dikunci (1-24 bulan) → bank memiliki kepastian funding."},
{question:"Giro (demand deposit) dapat ditarik kapan saja menggunakan ...",options:["Cek atau bilyet giro","Hanya ATM","Hanya buku tabungan","Hanya transfer saja","Hanya tunai"],answer:0,explanation:"Giro: simpanan yang penarikannya dapat dilakukan setiap saat dengan cek, bilyet giro, atau pemindahbukuan."},
]);

appendQuestions('soshum_sosiologi', [
{question:"Masyarakat informasi (information society) ditandai oleh ...",options:["Dominasi produksi dan distribusi informasi/pengetahuan","Dominasi pertanian","Dominasi industri","Tanpa teknologi","Isolasi total"],answer:0,explanation:"Information society: masyarakat yang ekonomi dan sosialnya didominasi oleh informasi dan teknologi digital."},
{question:"Rasionalisasi menurut Weber berarti ...",options:["Proses penggantian tindakan tradisional/afektif dengan tindakan rasional-kalkulatif","Penolakan logika","Kembali ke tradisi","Emosi dominan","Irasionalitas"],answer:0,explanation:"Weber: rasionalisasi = tren sejarah di mana kalkulasi efisiensi menggantikan tradisi dan emosi."},
{question:"Birokrasi ideal menurut Weber bercirikan ...",options:["Hierarki, aturan formal, spesialisasi, impersonalitas, merit-based","Tanpa aturan","Berdasarkan kesukaan","Tidak ada hierarki","Tanpa spesialisasi"],answer:0,explanation:"Weber: birokrasi ideal — struktur hierarkis, aturan tertulis, rekrutmen berdasarkan kompetensi."},
{question:"Kapital simbolik menurut Bourdieu meliputi ...",options:["Prestise, kehormatan, dan pengakuan sosial","Hanya uang","Hanya tanah","Hanya pendidikan","Hanya teknologi"],answer:0,explanation:"Symbolic capital: sumber daya berupa prestise, reputasi, status yang memberikan legitimasi dan pengaruh."},
{question:"Masyarakat risk society menurut Ulrich Beck ditandai oleh ...",options:["Risiko global (lingkungan, nuklir, finansial) yang tidak bisa diprediksi sepenuhnya","Tidak ada risiko","Keamanan total","Stabilitas sempurna","Tanpa ancaman"],answer:0,explanation:"Beck: risk society — masyarakat modern menghadapi risiko buatan manusia (nuklir, kimia, finansial) yang global."},
{question:"Subkultur adalah ...",options:["Kelompok dalam masyarakat yang memiliki nilai dan norma berbeda dari budaya dominan","Budaya utama","Budaya tunggal","Tanpa budaya","Budaya hilang"],answer:0,explanation:"Subculture: kelompok dengan budaya khas yang berbeda (tapi tidak selalu bertentangan) dengan mainstream."},
{question:"Kontrakultur berbeda dari subkultur karena ...",options:["Kontrakultur secara aktif menentang budaya dominan","Keduanya sama","Kontrakultur mendukung mainstream","Subkultur menentang","Tidak ada perbedaan"],answer:0,explanation:"Counterculture: secara eksplisit menolak/melawan nilai-nilai budaya mainstream. Contoh: hippie, punk."},
{question:"Sosiologi pengetahuan mempelajari ...",options:["Hubungan antara pengetahuan dan konteks sosial yang menghasilkannya","Hanya sains alam","Hanya matematika","Hanya teknologi","Hanya fisika"],answer:0,explanation:"Sociology of knowledge (Mannheim, Berger): bagaimana pengetahuan dibentuk, dipengaruhi, dan dilegitimasi oleh konteks sosial."},
]);
