// LAST PUSH — Saintek +51 (13 MatIPA + 13 Fisika + 13 Kimia + 12 Bio) \\to 1000

appendQuestions('saintek_matipa', [
{question:"Vektor satuan dari $\\vec{v}=(3$,4) adalah ...",options: ["(0.6, 0.8)","(3,4)","(1,1)","(0.5,0.5)","(4,3)"],answer:0,explanation:"|$\\vec{v}$|$=5$. $\\hat{v}=(3/5$,$4/5)=(0$.6,0.8)."},
{question:"$\\sum_{k=1}^{4} k^2 =$ ...",options: ["30","10","24","20","16"],answer:0,explanation:"$1+4+9+16=30$."},
{question:"Persamaan elips dengan sumbu mayor horizontal: $a=5$, $b=3$ berpusat di O ...",options: ["$\\frac{x^2}{25}+\\frac{y^2}{9}=1$","$\\frac{x^2}{9}+\\frac{y^2}{25}=1$","$x^2+y^2=25$","$x^2+y^2=9$","$\\frac{x^2}{3}+\\frac{y^2}{5}=1$"],answer:0,explanation:"Elips: $\\frac{x^2}{a^2}+\\frac{y^2}{b^2}=1$ dengan $a>b$: $\\frac{x^2}{25}+\\frac{y^2}{9}=1$."},
{question:"Kuartil bawah (Q_1) data 2,3,5,7,8,10,12 adalah ...",options: ["3","5","2","7","8"],answer:0,explanation:"$n=7$. Q_$1 =$ data ke$-\\frac{7+1}{4}=2$. Data ke$-2 = 3$."},
{question:"Luas trapesium dengan sisi sejajar 6 cm, 10 cm dan tinggi 4 cm $=$ ...",options: ["32 cm^2","40 cm^2","24 cm^2","60 cm^2","20 cm^2"],answer:0,explanation:"$L=\\frac{1}{2}(a+b)t=\\frac{1}{2}(6+10)(4)=32$ cm^2."},
{question:"$\\int \\frac{1}{x}$ dx $=$ ...",options: ["$\\ln$|x|$+C$","$\\frac{1}{x^2}+C$","$x+C$","$-\\frac{1}{x^2}+C$","e^$x+C$"],answer:0,explanation:"$\\int x^{-1}$ dx $= \\ln$|x|$+C$."},
{question:"Transformasi refleksi titik (3,$-2)$ terhadap sumbu x menghasilkan ...",options: ["(3,2)","$(-3$,$-2)$","$(-3$,2)","(2,$-3)$","$(-2$,3)"],answer:0,explanation:"Refleksi terhadap sumbu x: (x,$y)\\to(x,-y)$. (3,$-2)\\to(3,2)$."},
{question:"Jika $\\sin\\theta = \\frac{5}{13} ($kuadran I), maka $\\tan\\theta =$ ...",options: ["$\\frac{5}{12}$","$\\frac{12}{5}$","$\\frac{13}{5}$","$\\frac{5}{13}$","$\\frac{12}{13}$"],answer:0,explanation:"$\\cos\\theta=\\frac{12}{13} ($Pythagoras). $\\tan\\theta=\\frac{5/13}{12/13}=\\frac{5}{12}$."},
{question:"$(-2)^4 =$ ...",options: ["16","$-16$","8","$-8$","32"],answer:0,explanation:"$(-2)^4=(-2)(-2)(-2)(-2)=16 ($pangkat genap $\\to$ positif)."},
{question:"Turunan $f(x)=\\frac{1}{x}$ adalah ...",options: ["$-\\frac{1}{x^2}$","$\\frac{1}{x^2}$","$\\ln x$","$-\\ln x$","$\\frac{1}{x}$"],answer:0,explanation:"$f(x)=x^{-1} \\Rightarrow f$'$(x)=-x^{-2}=-\\frac{1}{x^2}$."},
{question:"Persamaan lingkaran $x^2+y^2-6x+4y-12=0$ memiliki pusat ...",options: ["(3,$-2)$","(6,$-4)$","$(-3$,2)","(3,2)","$(-6$,4)"],answer:0,explanation:"$(x^2-6x+9)+(y^2+4y+4)=12+9+4$. Pusat (3,$-2)$, $r=5$."},
{question:"Rata$-$rata harmonik dari 2 dan $8 =$ ...",options: ["$\\frac{16}{5}=3$.2","5","10","4","6"],answer:0,explanation:"Harmonik: $H=\\frac{2}{1/2+1/8}=\\frac{2}{5/8}=\\frac{16}{5}=3$.2."},
{question:"Jika matriks A memiliki determinan |A|$=0$, maka matriks A ...",options: ["Singular (tidak memiliki invers)","Memiliki invers (menurut kerangka berpikir umum)","Identitas (sesuai teori klasik)","Ortogonal (berdasarkan premis dasar)","Diagonal (secara terminologis)"],answer:0,explanation:"|A|$=0$: matriks singular — tidak memiliki invers."},
]);

appendQuestions('saintek_fisika', [
{question:"Tegangan permukaan menyebabkan ...",options: ["Nyamuk bisa berjalan di atas air","Air jatuh ke bawah (berdasarkan teori dasar)","Es mengapung (secara konseptual)","Gas mengembang (berdasarkan asumsi dasar)","Logam berkarat (dalam kerangka teori)"],answer:0,explanation:"Surface tension: gaya kohesi molekul air di permukaan membentuk 'kulit' — mendukung benda ringan."},
{question:"Viskositas fluida mengukur ...",options: ["Kekentalan/hambatan aliran fluida","Kecepatan gelombang (secara fundamental)","Tekanan fluida (dalam pemahaman konvensional)","Suhu fluida (menurut konsensus ilmiah)","Massa jenis fluida (dalam arti sempit)"],answer:0,explanation:"Viskositas: ukuran resistensi fluida terhadap aliran. Madu $>$ air (viskositas lebih tinggi)."},
{question:"Efisiensi mesin $=$ ...",options: ["$\\frac{\\text{output useful}}{\\text{input energy}} \\times 100$\\%","Output saja","Input saja","Selalu 100%","Tidak bisa dihitung"],answer:0,explanation:"Efisiensi $=$ energi berguna yang dihasilkan / total energi yang dimasukkan $\\times 100$%."},
{question:"Benda bermassa 2 kg dijatuhkan dari ketinggian 5 m. Kecepatan saat menyentuh tanah $(g=10) =$ ...",options: ["10 m/s","5 m/s","20 m/s","15 m/s","25 m/s"],answer:0,explanation:"E_$p=E$_$k \\Rightarrow$ mgh$=\\frac{1}{2}$mv^$2 \\Rightarrow v=\\sqrt{2gh}=\\sqrt{100}=10 m/s$."},
{question:"Tumbukan lenting sempurna mempertahankan ...",options: ["Energi kinetik dan momentum","Hanya momentum (secara konvensional)","Hanya energi kinetik (di konteks ini)","Tidak ada yang kekal (secara klasik)","Hanya energi potensial"],answer:0,explanation:"Perfectly elastic: baik momentum maupun energi kinetik kekal (konservasi keduanya)."},
{question:"Gerak parabola merupakan gabungan ...",options: ["GLB horizontal dan GLBB vertikal","Dua GLB (dalam literatur standar)","Dua GLBB (menurut pandangan mainstream)","Gerak melingkar dan linear","Gerak harmonik dan linear (secara klasik)"],answer:0,explanation:"Projectile: komponen horizontal (kecepatan konstan, GLB$) +$ vertikal (percepatan g, GLBB)."},
{question:"Jangkauan maksimum peluru terjadi pada sudut elevasi ...",options: ["45^$\\circ$","30^$\\circ$","60^$\\circ$","90^$\\circ$","0^$\\circ$"],answer:0,explanation:"$R=\\frac{v_0^2\\sin 2\\theta}{g}$. Maksimum saat $\\sin 2\\theta=1$, $2\\theta=90$^$\\circ$, $\\theta=45$^$\\circ$."},
{question:"Gelombang ultrasonik memiliki frekuensi ...",options: ["$> 20$.000 Hz (di atas pendengaran manusia)","$< 20$ Hz (berdasarkan premis dasar)","$20-20$.000 Hz (secara terminologis)","$= 0$ Hz (berdasarkan acuan formal)","$= 1$ Hz (secara konvensional; dalam pengertian luas)"],answer:0,explanation:"Ultrasonik: frekuensi $> 20$ kHz, tidak dapat didengar manusia. Digunakan dalam USG, sonar."},
{question:"Lensa divergen (cekung) selalu menghasilkan bayangan ...",options: ["Maya, tegak, dan diperkecil","Nyata dan terbalik (menurut standar)","Nyata dan diperbesar (secara literal)","Sama besar dengan benda","Tidak ada bayangan (dalam praktik)"],answer:0,explanation:"Lensa divergen: bayangan selalu maya, tegak, diperkecil — di depan lensa (berlawanan benda)."},
{question:"Fluks magnetik $\\P$hihihihi_$B =$ ...",options: ["$B \\cdot A \\cdot \\cos\\theta$","$B + A$","$B \\times A \\times \\sin\\theta$ saja","B / A","A / B"],answer:0,explanation:"$\\P$hihihihi_$B=$BA$\\cos\\theta ($Tesla$\\cdot$mmmm^$2 =$ Weber). $\\theta =$ sudut antara B dan normal bidang."},
{question:"Medan gravitasi di permukaan bumi $(g) \\approx$ ...",options: ["9.8 m/s^2","10 m/s^2 (approx)","1 m/s^2","100 m/s^2","0 m/s^2"],answer:0,explanation:"$g \\approx 9$.$8 m/s^2 ($sering dibulatkan $10 m/s^2$ untuk kemudahan perhitungan)."},
{question:"1 eV (elektron volt$) =$ ...",options: ["1.$6 \\times 10^{-19} J$","1 J","6.$63 \\times 10^{-34} J$","9.$1 \\times 10^{-31} J$","$3 \\times 10^8 J$"],answer:0,explanation:"1 eV $=$ muatan 1 elektron $\\times 1$ volt $= 1$.$6 \\times 10^{-19} J$."},
{question:"Bunyi tidak bisa merambat di ...",options: ["Ruang hampa (vakum)","Air (dalam batasan konvensional)","Udara (secara fundamental)","Baja (dalam pemahaman konvensional)","Kayu (menurut konsensus ilmiah)"],answer:0,explanation:"Bunyi $=$ gelombang mekanik $\\to$ memerlukan medium. Vakum $=$ tidak ada medium $\\to$ tidak ada bunyi."},
]);

appendQuestions('saintek_kimia', [
{question:"Larutan penyangga asam terdiri dari ...",options: ["Asam lemah dan garam dari asam lemah tersebut","Asam kuat dan basa kuat (dalam pengertian luas)","Garam saja (dalam definisi teknis)","Air murni (dalam konteks umum; berdasarkan teori dasar)","Asam kuat saja (berdasarkan referensi umum)"],answer:0,explanation:"Buffer asam: asam lemah $+$ garam konjugatnya. Contoh: CH_3COOH $+$ CH_3COONa."},
{question:"Larutan penyangga basa terdiri dari ...",options: ["Basa lemah dan garam dari basa lemah tersebut","Asam kuat dan basa kuat (menurut prinsip dasar)","Asam saja (secara normatif; dalam batasan konvensional)","Air saja (dari perspektif akademis)","Basa kuat saja (sesuai klasifikasi umum)"],answer:0,explanation:"Buffer basa: basa lemah $+$ garam konjugatnya. Contoh: NH_$3 +$ NH_4Cl."},
{question:"Reaksi hidrolisis garam NaCl menghasilkan larutan ...",options: ["Netral (pH $= 7)$","Asam (dalam praktik)","Basa (pada dasarnya)","Sangat asam (di konteks ini)","Sangat basa (secara klasik)"],answer:0,explanation:"NaCl: garam dari asam kuat (HCl$) +$ basa kuat (NaOH$) \\to$ tidak terhidrolisis $\\to$ netral."},
{question:"Polimer termoplas bersifat ...",options: ["Dapat dilunakkan dan dibentuk ulang dengan pemanasan","Tidak bisa didaur ulang (dari sudut pandang klasik)","Sangat keras dan getas (dalam literatur standar)","Tidak meleleh (menurut pandangan mainstream)","Selalu cair (dalam pengertian luas; dari perspektif akademis)"],answer:0,explanation:"Termoplas: ikatan antar rantai lemah $\\to$ dapat dilunakkan berulang kali. Contoh: PET, PE, PP."},
{question:"Polimer termoset bersifat ...",options: ["Tidak dapat dibentuk ulang setelah dicetak (ikatan silang kuat)","Mudah meleleh (menurut definisi standar; secara terminologis)","Dapat didaur ulang (menurut pengertian baku; berdasarkan acuan formal)","Lunak dan fleksibel (sesuai paradigma tradisional)","Selalu cair (menurut prinsip dasar; pada konteks konvensional)"],answer:0,explanation:"Termoset: cross$-$linked $\\to$ keras, kaku, tidak bisa dilunakkan lagi. Contoh: bakelit, epoksi."},
{question:"Karbohidrat tersusun dari unsur ...",options: ["C, H, dan O","C dan H saja","N dan O saja","C, H, O, dan N","C, H, O, N, dan S"],answer:0,explanation:"Karbohidrat: C_x(H_2O)_y — mengandung karbon, hidrogen, dan oksigen."},
{question:"Lemak (lipid) tersusun dari ...",options: ["Gliserol dan 3 asam lemak (trigliserida)","Asam amino (secara konseptual; dalam batasan konvensional)","Nukleotida (berdasarkan asumsi dasar; secara literal)","Glukosa (dalam kerangka teori; secara konvensional)","Selulosa (dari sudut pandang klasik; pada prinsipnya)"],answer:0,explanation:"Lipid/trigliserida: 1 gliserol $+ 3$ asam lemak melalui ikatan ester."},
{question:"Vitamin yang larut dalam lemak meliputi ...",options: ["A, D, E, K","B, C","B1, B12, C","Hanya C","Hanya B"],answer:0,explanation:"Vitamin larut lemak: A (mata), D (tulang), E (antioksidan), K (pembekuan darah)."},
{question:"Vitamin yang larut dalam air meliputi ...",options: ["B kompleks dan C","A, D, E, K (secara umum)","Hanya A (dalam teori)","Hanya D (pada prinsipnya)","Hanya K (menurut standar)"],answer:0,explanation:"Vitamin larut air: B kompleks (B1, B2, B6, B12, dll) dan C. Tidak disimpan, harus dikonsumsi rutin."},
{question:"Persamaan reaksi yang setara harus memenuhi ...",options: ["Jumlah atom setiap unsur sama di kedua sisi","Hanya massa total (dari perspektif akademis)","Hanya volume (sesuai klasifikasi umum)","Hanya suhu (berdasarkan teori dasar)","Hanya tekanan (secara konseptual)"],answer:0,explanation:"Hukum kekekalan massa: atom tidak diciptakan/dimusnahkan $\\to$ jumlah atom tiap unsur harus seimbang."},
{question:"Nomor massa $(A) =$ ...",options: ["Jumlah proton $+$ neutron","Jumlah elektron (di konteks ini)","Jumlah proton saja (secara klasik)","Jumlah neutron saja","Jumlah orbital (dalam teori)"],answer:0,explanation:"$A = p + n ($massa atom $\\approx$ proton $+$ neutron, karena massa elektron diabaikan)."},
{question:"Sifat periodik: jari$-$jari atom dalam satu periode dari kiri ke kanan ...",options: ["Mengecil (muatan inti efektif meningkat)","Membesar (menurut pandangan mainstream)","Tetap (dalam pengertian luas; dari perspektif akademis)","Acak (dalam definisi teknis; sesuai klasifikasi umum)","Tidak beraturan (dalam konteks umum)"],answer:0,explanation:"Satu periode: proton ↑ $\\to$ tarikan inti ke elektron ↑ $\\to$ jari$-$jari atom ↓."},
{question:"Sifat periodik: energi ionisasi dalam satu periode dari kiri ke kanan ...",options: ["Meningkat","Menurun","Tetap","Acak","Tidak beraturan"],answer:0,explanation:"Satu periode: atom semakin kecil, elektron semakin terikat $\\to$ IE ↑ (lebih sulit melepas elektron)."},
]);

appendQuestions('saintek_biologi', [
{question:"Pankreas memiliki fungsi ganda yaitu ...",options: ["Eksokrin (enzim pencernaan) dan endokrin (hormon insulin/glukagon)","Hanya eksokrin (secara terminologis; dalam literatur standar)","Hanya endokrin (berdasarkan acuan formal; menurut pandangan mainstream)","Hanya pencernaan lemak (secara konvensional; dalam pengertian luas)","Hanya respirasi (pada konteks konvensional; dalam definisi teknis)"],answer:0,explanation:"Pankreas: kelenjar ganda — eksokrin $\\to$ enzim pencernaan; endokrin $\\to$ insulin, glukagon."},
{question:"Saraf simpatis berfungsi ...",options: ["Memacu aktivitas tubuh (fight$-$or$-$flight)","Menenangkan tubuh (dalam kerangka teori)","Hanya pencernaan (dari sudut pandang klasik)","Hanya tidur (dalam literatur standar)","Hanya relaksasi (menurut pandangan mainstream)"],answer:0,explanation:"Simpatis: meningkatkan detak jantung, melebarkan pupil, menghambat pencernaan — respons darurat."},
{question:"Saraf parasimpatis berfungsi ...",options: ["Menenangkan tubuh (rest$-$and$-$digest)","Memacu aktivitas (dalam arti sempit)","Hanya olahraga (menurut definisi standar)","Hanya gerakan cepat (menurut pengertian baku)","Hanya respon bahaya (sesuai paradigma tradisional)"],answer:0,explanation:"Parasimpatis: memperlambat detak jantung, merangsang pencernaan — keadaan istirahat."},
{question:"Hormon estrogen diproduksi oleh ...",options: ["Ovarium (indung telur)","Testis (menurut kerangka berpikir umum)","Pankreas (sesuai teori klasik)","Tiroid (berdasarkan premis dasar)","Hipofisis (secara terminologis)"],answer:0,explanation:"Estrogen: hormon reproduksi wanita dari ovarium — menentukan karakter seks sekunder wanita."},
{question:"Hormon testosteron diproduksi oleh ...",options: ["Testis","Ovarium","Pankreas","Tiroid","Adrenal saja"],answer:0,explanation:"Testosteron: hormon reproduksi pria dari testis — menentukan karakter seks sekunder pria."},
{question:"Fertilisasi pada manusia biasanya terjadi di ...",options: ["Tuba falopi (oviduk)","Rahim (secara fundamental)","Ovarium (dalam pemahaman konvensional)","Vagina (menurut konsensus ilmiah)","Serviks (dalam arti sempit)"],answer:0,explanation:"Fertilisasi: pertemuan sperma dan ovum biasanya terjadi di sepertiga luar tuba falopi."},
{question:"Plasenta berfungsi untuk ...",options: ["Pertukaran nutrisi, gas, dan limbah antara ibu dan janin","Menyimpan makanan (dalam definisi teknis; sesuai klasifikasi umum)","Menghasilkan susu (dalam konteks umum; berdasarkan teori dasar)","Melindungi dari benturan saja (berdasarkan referensi umum)","Mengatur suhu saja (menurut kerangka berpikir umum)"],answer:0,explanation:"Plasenta: organ penghubung ibu$-$janin — pertukaran O_2/CO_2, nutrisi, limbah, hormon."},
{question:"Kloning adalah proses ...",options: ["Membuat salinan genetik identik dari organisme","Seleksi alam (secara normatif; dalam batasan konvensional)","Mutasi acak (dari perspektif akademis)","Persilangan (sesuai klasifikasi umum)","Migrasi (berdasarkan teori dasar; menurut konsensus ilmiah)"],answer:0,explanation:"Cloning: menghasilkan organisme dengan DNA identik dengan induknya (tanpa reproduksi seksual)."},
{question:"Organisme transgenik adalah organisme yang ...",options: ["Memiliki gen asing yang dimasukkan dari spesies lain","Bermutasi alami (secara konvensional; dalam pengertian luas)","Hasil persilangan biasa (pada konteks konvensional)","Hasil evolusi (dalam batasan konvensional)","Hasil seleksi alam (secara fundamental)"],answer:0,explanation:"Transgenic: organisme yang genomnya telah disisipi gen dari spesies lain (rekayasa genetika)."},
{question:"Biodiversitas (keanekaragaman hayati) meliputi tingkatan ...",options: ["Gen, spesies, dan ekosistem","Hanya spesies (dalam literatur standar)","Hanya gen (menurut pandangan mainstream)","Hanya ekosistem (di konteks ini)","Hanya komunitas (secara klasik)"],answer:0,explanation:"3 tingkat biodiversitas: keanekaragaman gen, keanekaragaman spesies, keanekaragaman ekosistem."},
{question:"Konservasi in situ adalah pelestarian ...",options: ["Di habitat asli (taman nasional, cagar alam)","Di luar habitat (kebun binatang) (secara teknis)","Di laboratorium (sesuai paradigma tradisional)","Di museum (menurut prinsip dasar)","Di akuarium (secara normatif; dalam batasan konvensional)"],answer:0,explanation:"In situ: melestarikan organisme dalam habitat alaminya. Contoh: taman nasional, suaka margasatwa."},
{question:"Konservasi ex situ adalah pelestarian ...",options: ["Di luar habitat asli (kebun raya, kebun binatang, bank gen)","Di habitat asli (berdasarkan premis dasar; dari sudut pandang klasik)","Di hutan belantara (secara terminologis; dalam literatur standar)","Di laut lepas (berdasarkan acuan formal; menurut pandangan mainstream)","Di gunung (secara konvensional; dalam pengertian luas)"],answer:0,explanation:"Ex situ: melestarikan organisme di luar habitat alaminya. Contoh: kebun raya, penangkaran."},
]);
