// SOSHUM FINAL CLOSE — +62 (16 per subject) → exactly 1000

appendQuestions('soshum_ekonomi', [
{question:"Usaha mikro memiliki omzet tahunan maksimal ...",options:["Rp300 juta (UU No. 20/2008)","Rp1 miliar","Rp5 miliar","Rp10 miliar","Rp50 miliar"],answer:0,explanation:"UU UMKM: usaha mikro = omzet ≤ Rp300 juta/tahun, aset ≤ Rp50 juta (di luar tanah dan bangunan)."},
{question:"Pajak Pertambahan Nilai (PPN) termasuk jenis pajak ...",options:["Objektif dan tidak langsung","Subjektif dan langsung","Daerah","Progresif","Personal"],answer:0,explanation:"PPN: dikenakan pada barang/jasa (objektif), dibayar konsumen melalui penjual (tidak langsung). Tarif 11%."},
{question:"Kartel adalah bentuk kerja sama antar perusahaan yang bertujuan ...",options:["Mengatur harga dan produksi untuk menghindari persaingan","Memperbanyak pesaing","Menurunkan harga","Meningkatkan persaingan","Membuka pasar baru"],answer:0,explanation:"Kartel: kesepakatan antar perusahaan sejenis untuk mengontrol harga/output — mengurangi persaingan (ilegal)."},
{question:"Net Present Value (NPV) positif berarti ...",options:["Investasi menguntungkan (return > biaya modal)","Investasi merugi","Harus ditolak","Tidak ada keuntungan","Biaya melebihi return"],answer:0,explanation:"NPV > 0: present value cash inflow > present value cash outflow → investasi layak diterima."},
{question:"Inflation targeting framework (ITF) di Indonesia diterapkan oleh ...",options:["Bank Indonesia (sejak 2005)","Kementerian Keuangan","OJK","BPK","Kemenkeu"],answer:0,explanation:"ITF: BI menetapkan target inflasi eksplisit dan menggunakan kebijakan moneter untuk mencapainya."},
{question:"Ekonomi kreatif meliputi industri berbasis ...",options:["Kreativitas, talenta, dan kekayaan intelektual","Pertambangan","Pertanian saja","Perikanan saja","Kehutanan saja"],answer:0,explanation:"Ekonomi kreatif: 17 subsektor (film, musik, desain, kuliner, gaming, fashion, dll) berbasis ide dan kreativitas."},
{question:"Inklusi keuangan bertujuan ...",options:["Memperluas akses layanan keuangan bagi seluruh lapisan masyarakat","Membatasi akses keuangan","Menghapus bank","Menaikkan bunga","Mengurangi tabungan"],answer:0,explanation:"Financial inclusion: semua orang, termasuk unbankable, dapat mengakses produk/layanan keuangan."},
{question:"Dampak positif perdagangan internasional bagi Indonesia meliputi ...",options:["Devisa, transfer teknologi, perluasan pasar, dan peningkatan efisiensi","Hanya impor","Menghalangi pertumbuhan","Mengurangi pendapatan","Merusak industri lokal"],answer:0,explanation:"Perdagangan internasional: meningkatkan devisa, mendorong spesialisasi, transfer teknologi dan pengetahuan."},
]);

appendQuestions('soshum_sosiologi', [
{question:"Kelompok acuan normatif berfungsi ...",options:["Memberikan standar norma dan nilai yang dianut individu","Hanya memberikan informasi","Hanya hiburan","Hanya teknologi","Hanya ekonomi"],answer:0,explanation:"Normative reference group: kelompok yang menjadi sumber norma/nilai yang diadopsi individu."},
{question:"Teori labeling (Howard Becker) menekankan ...",options:["Penyimpangan ditentukan oleh reaksi/label masyarakat, bukan tindakan itu sendiri","Penyimpangan bersifat bawaan","Tidak ada penyimpangan","Semua orang menyimpang","Penyimpangan positif saja"],answer:0,explanation:"Becker: deviasi bukan kualitas intrinsik tindakan, tapi konsekuensi dari label yang diberikan orang lain."},
{question:"Social capital menurut Putnam mencakup ...",options:["Jejaring, norma, dan kepercayaan yang memfasilitasi kerjasama","Hanya uang","Hanya tanah","Hanya pendidikan","Hanya teknologi"],answer:0,explanation:"Putnam: modal sosial = networks, norms, trust yang memungkinkan tindakan kolektif efektif."},
{question:"Determinisme teknologi menyatakan ...",options:["Teknologi membentuk dan menentukan perubahan sosial","Masyarakat menentukan teknologi","Keduanya tidak terkait","Hanya budaya yang berpengaruh","Hanya ekonomi yang berpengaruh"],answer:0,explanation:"Technological determinism: inovasi teknologi sebagai penggerak utama perubahan sosial dan budaya."},
{question:"Teori spiral of silence (spiral keheningan) menyatakan ...",options:["Orang cenderung diam jika pendapatnya minoritas karena takut isolasi","Semua orang bicara","Tidak ada tekanan sosial","Mayoritas selalu diam","Minoritas selalu dominan"],answer:0,explanation:"Noelle-Neumann: fear of isolation → orang menyembunyikan pendapat jika merasa berlawanan dengan mayoritas."},
{question:"Habitualisasi menurut Berger & Luckmann adalah ...",options:["Pengulangan tindakan menjadi pola kebiasaan","Tindakan spontan","Perilaku acak","Inovasi setiap saat","Perubahan konstan"],answer:0,explanation:"Habitualisasi: tindakan yang diulang → menjadi pola → dianggap 'normal' → melembaga (institutionalisasi)."},
{question:"Fungsi manifes pendidikan menurut Merton ...",options:["Fungsi yang disengaja dan diakui: sosialisasi pengetahuan, keterampilan","Fungsi tersembunyi","Dampak tidak diinginkan","Disfungsi","Kerusakan sosial"],answer:0,explanation:"Manifest function: tujuan resmi dan diakui dari lembaga pendidikan — transfer pengetahuan, keterampilan."},
{question:"Fungsi laten pendidikan menurut Merton ...",options:["Fungsi yang tidak disadari: pembentukan jaringan sosial, penundaan masuk pasar kerja","Fungsi utama","Tujuan resmi","Kurikulum","Ujian"],answer:0,explanation:"Latent function: dampak tidak disengaja — sekolah sebagai childcare, pembentukan peer group, sosialisasi."},
]);

appendQuestions('soshum_sejarah', [
{question:"Kerajaan Majapahit mencapai puncak kejayaan pada masa pemerintahan ...",options:["Hayam Wuruk dan Gajah Mada","Raden Wijaya saja","Ken Arok","Airlangga","Kertajaya"],answer:0,explanation:"Majapahit jaya: Hayam Wuruk (raja) + Gajah Mada (mahapatih) abad ke-14 — menguasai hampir seluruh Nusantara."},
{question:"Kerajaan Sriwijaya merupakan kerajaan maritim yang berpusat di ...",options:["Sumatera Selatan (Palembang)","Jawa Barat","Kalimantan","Sulawesi","Papua"],answer:0,explanation:"Sriwijaya: kerajaan maritim-Buddha terbesar (abad ke-7-13), pusat di Palembang, menguasai Selat Malaka."},
{question:"I-Tsing, pendeta Tiongkok, mencatat kehadiran kerajaan ... pada abad ke-7.",options:["Sriwijaya","Kutai","Tarumanegara","Majapahit","Mataram"],answer:0,explanation:"I-Tsing (abad ke-7): mencatat Sriwijaya sebagai pusat pembelajaran agama Buddha yang penting."},
{question:"Perang Dunia I dimulai pada tahun ...",options:["1914","1939","1941","1945","1918"],answer:0,explanation:"PD I: 1914-1918. Dipicu pembunuhan Archduke Franz Ferdinand di Sarajevo (28 Juni 1914)."},
{question:"Perang Dunia II dimulai dengan invasi Jerman ke ... pada ...",options:["Polandia, 1 September 1939","Prancis, 1940","Rusia, 1941","Inggris, 1940","Austria, 1938"],answer:0,explanation:"PD II dimulai ketika Jerman Nazi menginvasi Polandia pada 1 September 1939."},
{question:"Gerakan Non-Blok (GNB) didirikan pada tahun ... oleh ...",options:["1961, Soekarno, Nehru, Nasser, Tito, Nkrumah","1945, AS dan Soviet","1949, NATO","1955, ASEAN","1967, ASEAN"],answer:0,explanation:"NAM (Non-Aligned Movement): 1961 di Beograd — tidak berpihak pada Blok Barat atau Timur."},
{question:"Sistem tanam paksa (Cultuurstelsel) diterapkan oleh ... pada tahun ...",options:["Van den Bosch, 1830-1870","Raffles, 1811-1816","Daendels, 1808-1811","Douwes Dekker, 1912","Soekarno, 1945"],answer:0,explanation:"Cultuurstelsel (1830-1870): petani dipaksa menanam komoditas ekspor (kopi, gula, nila) — sangat menindas."},
{question:"Max Havelaar ditulis oleh ... sebagai kritik terhadap ...",options:["Multatuli (Eduard Douwes Dekker), sistem tanam paksa","Balai Pustaka","Soekarno","Kartini","Agus Salim"],answer:0,explanation:"Max Havelaar (1860): novel realis oleh Multatuli yang mengkritik penindasan Cultuurstelsel di Hindia Belanda."},
]);

appendQuestions('soshum_geografi', [
{question:"Garis Wallace memisahkan flora dan fauna zona ...",options:["Asiatis (barat) dan peralihan (tengah/Wallacea)","Utara dan selatan","Timur dan barat total","Asia dan Australia langsung","Arktik dan tropis"],answer:0,explanation:"Garis Wallace: batas biogeografi antara fauna Asiatis (Jawa, Sumatera, Kalimantan) dan fauna peralihan."},
{question:"Kawasan konservasi perairan laut (KKP) bertujuan ...",options:["Melindungi ekosistem laut dan sumber daya hayati di dalamnya","Memperbesar tangkapan ikan","Mencemari laut","Menguras sumber daya","Membuat tambak"],answer:0,explanation:"KKP: melindungi biodiversitas laut, habitat karang, mangrove, padang lamun, dan spesies dilindungi."},
{question:"Terumbu karang Indonesia termasuk pusat ...",options:["Segitiga karang dunia (Coral Triangle)","Kutub utara","Gurun","Tundra","Padang es"],answer:0,explanation:"Coral Triangle: Indonesia, Malaysia, Filipina, Papua Nugini, Timor Leste, Solomon — pusat biodiversitas laut."},
{question:"Dampak El Niño terhadap sektor pertanian Indonesia ...",options:["Kekeringan → gagal panen, kebakaran lahan, krisis air","Panen melimpah","Hujan lebat","Banjir besar","Salju"],answer:0,explanation:"El Niño: curah hujan ↓ di Indonesia → kemarau panjang → gagal panen, kebakaran hutan/lahan."},
{question:"Urbanisasi di Indonesia terjadi karena faktor ...",options:["Dorong (push) dari desa: kemiskinan; tarik (pull) dari kota: peluang kerja","Hanya keinginan","Tanpa alasan","Hanya kebijakan","Hanya tradisi"],answer:0,explanation:"Push-pull factors: push (kurang lapangan kerja, lahan sempit di desa), pull (peluang kerja, fasilitas di kota)."},
{question:"Pencemaran tanah disebabkan oleh ...",options:["Limbah industri, pestisida berlebih, sampah non-organik, kebocoran bahan kimia","Hanya hujan","Hanya angin","Hanya sungai","Hanya laut"],answer:0,explanation:"Soil pollution: kontaminasi tanah oleh zat kimia berbahaya — mengurangi kesuburan, mencemari air tanah."},
{question:"Iklim Koppen tipe Aw (savana tropis) ditemukan di ...",options:["Nusa Tenggara Timur dengan musim kemarau yang panjang","Sumatera Barat","Kalimantan Barat","Papua bagian utara","Jakarta"],answer:0,explanation:"Aw: tropis dengan musim kering yang jelas — NTT, sebagian NTB memiliki savana dan padang rumput."},
{question:"Penataan ruang wilayah Indonesia diatur dalam ...",options:["UU No. 26 Tahun 2007 tentang Penataan Ruang","UU Pertambangan","UU Pendidikan","UU Kesehatan","UU Perbankan"],answer:0,explanation:"UUPR: mengatur RTRW (Rencana Tata Ruang Wilayah) nasional, provinsi, dan kabupaten/kota."},
]);
