// TKD Expansion — Bahasa Indonesia Part 2 (+80 soal)

appendQuestions('tkd_indo', [
// [Wacana Kompleks]
{question:"Kalimat yang mengandung hubungan sebab-akibat adalah ...",options:["Tanaman mati karena kekeringan","Tanaman sangat indah","Tanaman tumbuh di kebun","Saya melihat tanaman","Tanaman itu hijau"],answer:0,explanation:"'Karena' menandakan hubungan sebab-akibat."},
{question:"Konjungsi 'sebelum' menunjukkan hubungan ...",options:["Waktu","Syarat","Tujuan","Pertentangan","Sebab-akibat"],answer:0,explanation:"'Sebelum' menunjukkan hubungan waktu (temporal)."},
{question:"Konjungsi 'agar' menunjukkan hubungan ...",options:["Tujuan","Waktu","Syarat","Pertentangan","Penjumlahan"],answer:0,explanation:"'Agar' dan 'supaya' menunjukkan hubungan tujuan (final)."},
{question:"Kata tanya yang tepat untuk menanyakan cara adalah ...",options:["Bagaimana","Mengapa","Kapan","Siapa","Berapa"],answer:0,explanation:"'Bagaimana' (how) digunakan untuk menanyakan cara/proses."},
{question:"Teks editorial berfungsi untuk ...",options:["Menyampaikan pandangan redaksi terhadap suatu isu","Memberikan berita straight news","Menghibur pembaca","Mengiklankan produk","Menceritakan kisah fiksi"],answer:0,explanation:"Editorial/tajuk rencana = opini redaksi media terhadap isu aktual."},
{question:"Resensi buku harus memuat ...",options:["Identitas buku, ringkasan isi, kelebihan, kekurangan","Hanya ringkasan cerita","Hanya kritik negatif","Biografi penulis saja","Daftar pustaka saja"],answer:0,explanation:"Resensi: identitas buku, sinopsis, penilaian kelebihan/kekurangan, dan rekomendasi."},
{question:"Kalimat yang menggunakan gaya bahasa sinestesia adalah ...",options:["Suaranya sangat pedas","Dia berlari cepat","Bunga itu merah","Langit cerah hari ini","Dia pandai memasak"],answer:0,explanation:"Sinestesia: pencampuran panca indra. 'Suara' (pendengaran) + 'pedas' (perasa)."},
{question:"Kalimat yang menggunakan majas metonimia adalah ...",options:["Dia minum Aqua setiap pagi","Dia minum air setiap pagi","Dia suka minum teh","Dia tidak suka air putih","Dia minum susu"],answer:0,explanation:"Metonimia: penggunaan merek/nama lain. 'Aqua' menggantikan 'air mineral'."},
{question:"Paragraf campuran memiliki kalimat utama di ...",options:["Awal dan akhir paragraf","Tengah saja","Awal saja","Akhir saja","Tidak ada kalimat utama"],answer:0,explanation:"Paragraf campuran (deduktif-induktif): kalimat utama di awal dan dipertegas di akhir."},
{question:"Kata serapan 'apotek' berasal dari bahasa ...",options:["Belanda (apotheek)","Arab","Sanskerta","Cina","Jepang"],answer:0,explanation:"'Apotek' diserap dari bahasa Belanda 'apotheek'."},
// [Penalaran Berbahasa]
{question:"Analogi adalah ...",options:["Perbandingan dua hal yang memiliki kesamaan sifat","Pertentangan dua hal","Pengulangan kata","Penyingkatan kalimat","Penghapusan kata"],answer:0,explanation:"Analogi = penalaran berdasarkan perbandingan dua hal yang memiliki kesamaan."},
{question:"'Guru : Murid = Dokter : ...' Jawaban yang tepat ...",options:["Pasien","Obat","Rumah sakit","Perawat","Penyakit"],answer:0,explanation:"Guru mengajar murid, dokter merawat pasien. Hubungan: profesi - yang dilayani."},
{question:"Simpulan yang tepat dari 'Semua mamalia berdarah panas. Paus adalah mamalia' adalah ...",options:["Paus berdarah panas","Paus berdarah dingin","Paus bukan mamalia","Semua ikan berdarah panas","Paus tidak ada"],answer:0,explanation:"Silogisme: Semua mamalia berdarah panas + Paus mamalia → Paus berdarah panas."},
{question:"Kesalahan logika 'straw man' adalah ...",options:["Menyerang argumen yang disederhanakan/diubah","Menyerang pribadi","Menggunakan data palsu","Berargumen melingkar","Banding pada otoritas"],answer:0,explanation:"Straw man: mengubah/menyederhanakan argumen lawan agar mudah diserang."},
{question:"'Post hoc ergo propter hoc' adalah kekeliruan logika yang ...",options:["Menganggap sesuatu yang terjadi setelah peristiwa lain pasti disebabkan peristiwa itu","Menyerang pribadi","Generalisasi berlebih","Analogi keliru","Banding popular"],answer:0,explanation:"Post hoc = setelah ini maka karena ini. Kronologi ≠ kausalitas."},
// [Teks Akademis]
{question:"Ciri karya tulis ilmiah adalah ...",options:["Objektif, sistematis, dan dapat dipertanggungjawabkan","Subjektif dan emosional","Menggunakan bahasa sehari-hari","Tidak perlu sumber referensi","Berisi cerita fiksi"],answer:0,explanation:"KTI harus objektif, sistematis, logis, dan berdasarkan data/fakta yang dapat diverifikasi."},
{question:"Footnote (catatan kaki) berfungsi untuk ...",options:["Memberikan keterangan tambahan atau sumber kutipan","Menghias halaman","Mengisi ruang kosong","Menulis kesimpulan","Menulis abstrak"],answer:0,explanation:"Catatan kaki = keterangan tambahan atau referensi sumber di bagian bawah halaman."},
{question:"Abstrak dalam karya ilmiah berisi ...",options:["Ringkasan singkat isi keseluruhan karya","Detail metodologi","Daftar pustaka","Biografi penulis","Lampiran data"],answer:0,explanation:"Abstrak = ringkasan padat yang mencakup latar belakang, tujuan, metode, hasil, dan kesimpulan."},
{question:"Bibliografi/daftar pustaka disusun berdasarkan ...",options:["Urutan alfabet nama belakang pengarang","Urutan waktu terbit","Urutan jumlah halaman","Urutan harga buku","Urutan ukuran buku"],answer:0,explanation:"Daftar pustaka disusun alfabetis berdasarkan nama belakang pengarang."},
{question:"Kutipan langsung lebih dari 4 baris ditulis dengan cara ...",options:["Menjorok ke dalam tanpa tanda kutip, dengan spasi rapat","Menggunakan tanda kutip biasa","Dicetak miring saja","Digarisbawahi","Dicetak tebal"],answer:0,explanation:"Kutipan langsung panjang (>4 baris): menjorok 1-1.5 cm, spasi tunggal, tanpa tanda kutip."},
// [Ragam Bahasa]
{question:"Ragam bahasa baku digunakan dalam situasi ...",options:["Resmi/formal","Sehari-hari","Pergaulan remaja","Media sosial","Pesan singkat"],answer:0,explanation:"Ragam baku digunakan dalam situasi formal/resmi: surat dinas, karya ilmiah, pidato."},
{question:"Register bahasa adalah ...",options:["Variasi bahasa berdasarkan bidang penggunaan","Aksen daerah","Dialek sosial","Bahasa gaul","Bahasa tubuh"],answer:0,explanation:"Register = variasi bahasa berdasarkan bidang pemakaian (hukum, kedokteran, teknologi, dll)."},
{question:"Dialek adalah variasi bahasa berdasarkan ...",options:["Wilayah geografis","Usia penutur","Jenis kelamin","Pendidikan","Agama"],answer:0,explanation:"Dialek = variasi bahasa berdasarkan daerah/wilayah geografis."},
{question:"Sosiolek adalah variasi bahasa berdasarkan ...",options:["Kelompok sosial","Wilayah","Waktu","Fungsi","Topik"],answer:0,explanation:"Sosiolek = variasi bahasa berdasarkan status sosial, pendidikan, atau profesi penuturnya."},
// [Cerpen & Novel]
{question:"Tokoh protagonis adalah ...",options:["Tokoh utama yang diutamakan dalam cerita","Tokoh jahat","Tokoh pembantu","Tokoh bayangan","Tokoh figuran"],answer:0,explanation:"Protagonis = tokoh utama, pusat cerita, biasanya yang mendapat simpati pembaca."},
{question:"Tokoh antagonis berfungsi sebagai ...",options:["Penentang/lawan protagonis","Pendukung protagonis","Narator","Tokoh netral","Tokoh figuran"],answer:0,explanation:"Antagonis = tokoh yang menentang atau berlawanan dengan protagonis, menciptakan konflik."},
{question:"Latar dalam cerita meliputi ...",options:["Tempat, waktu, dan suasana","Hanya tempat","Hanya waktu","Hanya tokoh","Hanya alur"],answer:0,explanation:"Latar (setting): tempat, waktu, dan suasana (atmosfer) kejadian dalam cerita."},
{question:"Amanat cerita adalah ...",options:["Pesan moral yang ingin disampaikan pengarang","Judul cerita","Konflik utama","Nama tokoh","Latar tempat"],answer:0,explanation:"Amanat = pesan moral/hikmah yang ingin disampaikan pengarang kepada pembaca."},
{question:"Gaya bahasa penulis yang menggunakan banyak kata arkais menunjukkan ...",options:["Latar waktu lampau atau nuansa klasik","Ketidakmampuan menulis","Kesalahan ejaan","Pengaruh bahasa gaul","Gaya modern"],answer:0,explanation:"Kata arkais (kuno) digunakan untuk menciptakan nuansa klasik atau menunjukkan latar waktu lampau."},
// [Semantik & Pragmatik]
{question:"Deiksis adalah ...",options:["Kata yang maknanya bergantung konteks ujaran","Kata bermakna tetap","Kata serapan","Kata berimbuhan","Kata majemuk"],answer:0,explanation:"Deiksis: kata yang maknanya bergantung pada konteks (waktu, tempat, persona). Contoh: 'sini', 'tadi', 'saya'."},
{question:"Implikatur percakapan adalah ...",options:["Makna tersirat di balik ujaran","Makna kamus","Makna gramatikal","Makna denotatif","Makna leksikal"],answer:0,explanation:"Implikatur = makna tambahan yang tersirat di balik apa yang diucapkan, dipahami dari konteks."},
{question:"Tindak tutur ilokusi 'Ruangannya panas sekali' secara tidak langsung bermakna ...",options:["Permintaan untuk menyalakan AC atau membuka jendela","Pujian terhadap ruangan","Deskripsi suhu udara","Pernyataan suka ruangan","Ajakan keluar ruangan"],answer:0,explanation:"Tindak tutur tidak langsung: pernyataan tentang suhu sebenarnya adalah permintaan tindakan."},
{question:"Prinsip kerja sama Grice meliputi maksim ...",options:["Kuantitas, kualitas, relasi, dan cara","Hanya kuantitas","Hanya kualitas","Hanya kesopanan","Hanya relevansi"],answer:0,explanation:"Prinsip Grice: kuantitas (cukup info), kualitas (benar), relasi (relevan), cara (jelas)."},
// [Ejaan Lanjutan]
{question:"Penggunaan tanda pisah (—) yang benar adalah ...",options:["Jakarta—Bandung ditempuh 3 jam","Jakarta - Bandung ditempuh 3 jam","Jakarta-Bandung ditempuh 3 jam","Jakarta– –Bandung ditempuh 3 jam","Jakarta_Bandung ditempuh 3 jam"],answer:0,explanation:"Tanda pisah (—) tanpa spasi digunakan untuk menyatakan 'sampai dengan'."},
{question:"Penulisan singkatan yang benar untuk 'dan sebagainya' adalah ...",options:["dsb.","d.s.b.","d.s.b","DSB","Dsb"],answer:0,explanation:"Singkatan 'dan sebagainya' = dsb. (huruf kecil, diikuti titik)."},
{question:"Fungsi tanda elipsis (...) dalam kalimat adalah ...",options:["Menandakan bagian yang dihilangkan atau kalimat yang terputus","Mengakhiri kalimat","Menandai judul","Menandai kutipan","Menandai angka"],answer:0,explanation:"Elipsis (...) menunjukkan penghilangan bagian teks atau ujaran yang terputus."},
{question:"Penulisan unsur serapan 'ph' dari bahasa asing menjadi ... dalam bahasa Indonesia",options:["f","ph","p","v","b"],answer:0,explanation:"Unsur serapan 'ph' menjadi 'f': philosophy → filosofi, pharmacy → farmasi."},
{question:"Penulisan kata turunan berimbuhan dari 'kerja sama' yang benar ...",options:["bekerja sama","bekerja-sama","bekerjasama","berkerja sama","ber-kerjasama"],answer:0,explanation:"Karena 'kerja sama' ditulis terpisah, bentuk berimbuhan: bekerja sama, memperkerjasamakan."},
// [Membaca Kritis]
{question:"Membaca kritis bertujuan untuk ...",options:["Mengevaluasi dan menilai isi bacaan","Sekadar mengetahui isi","Mencari hiburan","Menghafal seluruh isi","Menyalin teks"],answer:0,explanation:"Membaca kritis = membaca dengan mengevaluasi kebenaran, logika, dan kualitas isi bacaan."},
{question:"Bias dalam penulisan teks berita dapat diidentifikasi melalui ...",options:["Pemilihan kata, penekanan fakta tertentu, dan penyembunyian fakta lain","Jumlah halaman","Ukuran huruf","Warna teks","Jenis kertas"],answer:0,explanation:"Bias media: memilih kata bermakna tertentu, menekankan/menyembunyikan fakta secara selektif."},
{question:"Teknik membaca cepat SQ3R meliputi ...",options:["Survey, Question, Read, Recite, Review","Scan, Query, Read, Rest, Repeat","See, Question, Redo, Recite, Rewrite","Search, Quiz, Read, Recite, Repeat","Study, Question, Read, Recall, Revise"],answer:0,explanation:"SQ3R: Survey (tinjau), Question (tanya), Read (baca), Recite (ceritakan), Review (tinjau ulang)."},
{question:"Scanning adalah teknik membaca untuk ...",options:["Mencari informasi spesifik dengan cepat","Memahami keseluruhan teks","Menghafal teks","Menerjemahkan teks","Menulis ulang teks"],answer:0,explanation:"Scanning = membaca cepat untuk menemukan informasi khusus (tanggal, nama, angka)."},
{question:"Skimming adalah teknik membaca untuk ...",options:["Mendapatkan gambaran umum isi teks dengan cepat","Memahami detail teks","Menghafal teks","Mencari kata tertentu","Menyalin teks"],answer:0,explanation:"Skimming = membaca sekilas untuk menangkap gagasan umum/inti teks secara cepat."},
// [Lanjutan Morfologi & Sintaksis]
{question:"Reduplikasi semantis terdapat pada ...",options:["mondar-mandir","rumah-rumah","sayur-mayur","lauk-pauk","bolak-balik"],answer:0,explanation:"'Mondar-mandir' = reduplikasi semantis (makna berulang/terus-menerus)."},
{question:"Kalimat transitif adalah kalimat yang ...",options:["Predikatnya memerlukan objek","Predikatnya tidak memerlukan objek","Tidak memiliki predikat","Tidak memiliki subjek","Berstruktur SP saja"],answer:0,explanation:"Kalimat transitif: S-P-O (predikat membutuhkan objek). Contoh: 'Dia membaca buku.'"},
{question:"Kalimat intransitif adalah kalimat yang ...",options:["Predikatnya tidak memerlukan objek","Predikatnya memerlukan objek","Memiliki dua objek","Tidak memiliki subjek","Berstruktur SPO"],answer:0,explanation:"Kalimat intransitif: S-P (predikat tidak membutuhkan objek). Contoh: 'Dia berlari.'"},
{question:"Kata 'memperhatikan' memiliki struktur morfem ...",options:["me- + per- + hati + -kan","mem- + perhatikan","memperhatikan (tidak bisa diurai)","mem + per + hati + kan","me + per + hati + an"],answer:0,explanation:"Proses: hati → perhatikan (per-...-kan) → memperhatikan (me(N)-)."},
{question:"Kalimat inversi adalah kalimat yang ...",options:["Predikat mendahului subjek","Subjek mendahului predikat","Tidak memiliki predikat","Tidak memiliki subjek","Memiliki dua predikat"],answer:0,explanation:"Inversi = urutan P-S (predikat di depan subjek). Contoh: 'Pergilah kamu dari sini!'"},
// [Lanjutan Sastra Indonesia]
{question:"Angkatan Balai Pustaka dalam sastra Indonesia ditandai oleh ...",options:["Tema adat vs kaum muda, bahasa Melayu tinggi","Tema kebebasan berekspresi","Tema perlawanan Jepang","Tema modernisasi","Tema globalisasi"],answer:0,explanation:"Angkatan Balai Pustaka (1920-an): konflik adat vs individu, bahasa Melayu halus. Contoh: Siti Nurbaya."},
{question:"Angkatan Pujangga Baru dicirikan oleh ...",options:["Semangat kebangsaan dan romantisme","Tema adat","Gaya realisme sosial","Tema absurdisme","Tema dekonstruksi"],answer:0,explanation:"Pujangga Baru (1930-an): semangat nasionalisme, individualisme, romantisme. Contoh: Layar Terkembang."},
{question:"Puisi lama pantun memiliki ciri ...",options:["4 baris, bersajak a-b-a-b, baris 1-2 sampiran, 3-4 isi","Bebas tanpa aturan","Hanya 2 baris","Bersajak a-a-a-a","Tidak ada sampiran"],answer:0,explanation:"Pantun: 4 baris/larik, bersajak a-b-a-b, baris 1-2 sampiran, 3-4 isi, 8-12 suku kata."},
{question:"Gurindam adalah puisi lama yang ...",options:["Terdiri dari 2 baris, berisi nasihat, bersajak a-a","Terdiri dari 4 baris bersajak a-b-a-b","Bebas tanpa aturan","Berisi cerita panjang","Tanpa rima"],answer:0,explanation:"Gurindam: 2 baris, bersajak a-a, berisi nasihat. Baris 1 syarat, baris 2 jawaban/akibat."},
{question:"Soneta adalah bentuk puisi yang berasal dari ...  dan memiliki ... baris",options:["Italia, 14 baris","Indonesia, 8 baris","Cina, 12 baris","Arab, 20 baris","India, 10 baris"],answer:0,explanation:"Soneta: puisi dari Italia, 14 baris, terdiri dari 2 kuatren (4 baris) + 2 tersina (3 baris)."},
]);
