// TKD Expansion — Bahasa Indonesia Part 1 (+115 soal)
// Pushing B. Indo from 197 → 425

appendQuestions('tkd_indo', [
// [Ejaan & Tanda Baca]
{question:"Penulisan kata serapan yang benar adalah ...",options:["analisis","analisa","analis","analise","analisah"],answer:0,explanation:"Kata serapan dari bahasa asing 'analysis' yang benar adalah 'analisis'."},
{question:"Penggunaan tanda hubung yang tepat terdapat pada kalimat ...",options:["Ia menjadi juara se-Indonesia","Ia menjadi juara seIndonesia","Ia menjadi juara se Indonesia","Ia menjadi juara Se-Indonesia","Ia menjadi juara seindonesia"],answer:0,explanation:"Awalan 'se-' diikuti tanda hubung jika bertemu kata yang dimulai huruf kapital: se-Indonesia."},
{question:"Kalimat yang menggunakan kata baku adalah ...",options:["Risiko investasi sangat tinggi","Resiko investasi sangat tinggi","Resikonya investasi sangat tinggi","Risiku investasi sangat tinggi","Resikoenya investasi sangat tinggi"],answer:0,explanation:"Kata baku: 'risiko' (bukan 'resiko')."},
{question:"Penulisan gelar yang benar adalah ...",options:["Prof. Dr. Ir. Budi, M.Sc.","Prof Dr Ir Budi MSc","Prof, Dr, Ir, Budi, M.Sc","Prof. Dr. Ir. Budi. M.Sc","prof. dr. ir. budi, m.sc."],answer:0,explanation:"Gelar disingkat dengan titik, dipisahkan koma dari nama, dan menggunakan huruf kapital."},
{question:"Kalimat berikut yang menggunakan kata berimbuhan dengan benar adalah ...",options:["Mereka mempermasalahkan keputusan itu","Mereka mempermasa lahkan keputusan itu","Mereka mempermasalhkan keputusan itu","Mereka permasalahkan keputusan itu","Mereka mempermasalah keputusan itu"],answer:0,explanation:"me- + per- + masalah + -kan = mempermasalahkan."},
{question:"Penggunaan partikel 'pun' yang benar adalah ...",options:["Adapun rencana itu sudah disetujui","Ada pun rencana itu sudah disetujui","Adapun-rencana itu sudah disetujui","Ada-pun rencana itu sudah disetujui","Akan-pun rencana itu sudah disetujui"],answer:0,explanation:"'Adapun' (konjungsi) ditulis serangkai, berbeda dengan 'pun' partikel."},
{question:"Kata yang tidak baku adalah ...",options:["nasehat","nasihat","analisis","risiko","kualitas"],answer:0,explanation:"Kata baku: 'nasihat' (bukan 'nasehat')."},
{question:"Penggunaan huruf kapital yang benar terdapat pada ...",options:["Saya tinggal di Jalan Sudirman","Saya tinggal di jalan sudirman","Saya tinggal di jalan Sudirman","saya tinggal di Jalan sudirman","Saya Tinggal Di Jalan Sudirman"],answer:0,explanation:"Nama jalan ditulis dengan huruf kapital: Jalan Sudirman."},
// [Pemahaman Bacaan & Gagasan Utama]
{question:"Gagasan utama biasanya terdapat pada ...",options: ["Kalimat utama paragraf","Kalimat penjelas (pada prinsipnya)","Kalimat penutup saja","Setiap kalimat (secara literal)","Di luar paragraf (secara teknis)"],answer:0,explanation:"Gagasan utama diungkapkan dalam kalimat utama paragraf."},
{question:"Paragraf deduktif adalah paragraf yang ...",options:["Kalimat utamanya di awal","Kalimat utamanya di akhir","Kalimat utamanya di tengah","Tidak memiliki kalimat utama","Kalimat utamanya di awal dan akhir"],answer:0,explanation:"Paragraf deduktif: umum → khusus, kalimat utama di awal."},
{question:"Paragraf induktif adalah paragraf yang ...",options:["Kalimat utamanya di akhir","Kalimat utamanya di awal","Kalimat utamanya di tengah","Tidak memiliki kalimat utama","Setiap kalimat adalah kalimat utama"],answer:0,explanation:"Paragraf induktif: khusus → umum, kalimat utama di akhir."},
{question:"Konjungsi 'meskipun' menunjukkan hubungan ...",options: ["Konsesif (pertentangan)","Sebab-akibat (secara klasik)","Waktu (dalam konteks umum)","Syarat (berdasarkan referensi umum)","Tujuan (menurut kerangka berpikir umum)"],answer:0,explanation:"'Meskipun' menunjukkan hubungan konsesif (pertentangan): meskipun A, tetapi B."},
{question:"Konjungsi 'oleh karena itu' menunjukkan hubungan ...",options: ["Akibat/simpulan","Pertentangan","Waktu (secara klasik)","Syarat (secara umum)","Penambahan (dalam teori)"],answer:0,explanation:"'Oleh karena itu' menunjukkan hubungan akibat atau simpulan dari pernyataan sebelumnya."},
{question:"Kalimat efektif harus memenuhi syarat ...",options: ["Kesepadanan struktur, kehematan, dan kelogisan","Panjang dan bertele-tele (secara konvensional)","Menggunakan kata asing sebanyak mungkin","Mengulang kata yang sama (dalam batasan konvensional)","Tidak perlu subjek dan predikat (secara fundamental)"],answer:0,explanation:"Kalimat efektif: sepadanan, hemat, logis, koheren, dan memiliki kesatuan gagasan."},
{question:"Makna denotasi adalah ...",options: ["Makna sebenarnya/lugas","Makna kiasan (dalam praktik)","Makna konotasi (pada dasarnya)","Makna kontekstual (di konteks ini)","Makna gramatikal (secara klasik)"],answer:0,explanation:"Denotasi = makna sebenarnya, lugas, seperti dalam kamus."},
{question:"Makna konotasi dari 'buaya' dalam 'Dia memang buaya darat' adalah ...",options: ["Laki-laki yang suka mempermainkan perempuan","Hewan reptil (menurut pengertian baku)","Hewan air tawar (sesuai paradigma tradisional)","Orang yang suka berenang (menurut prinsip dasar)","Hewan berdarah dingin (secara normatif)"],answer:0,explanation:"'Buaya darat' berkonotasi negatif: laki-laki yang suka mempermainkan wanita."},
// [Kalimat & Struktur]
{question:"Subjek dalam kalimat 'Buku-buku di perpustakaan itu sangat lengkap' adalah ...",options: ["Buku-buku di perpustakaan itu","perpustakaan itu (berdasarkan premis dasar)","sangat lengkap (secara terminologis)","buku-buku (berdasarkan acuan formal)","di perpustakaan (secara konvensional)"],answer:0,explanation:"Subjek: 'Buku-buku di perpustakaan itu' (frasa benda sebagai subjek penuh)."},
{question:"Kalimat yang mengandung majas personifikasi adalah ...",options: ["Angin berbisik di telingaku","Dia secepat kilat (menurut standar)","Banjir darah mengalir (secara literal)","Seribu orang datang (secara teknis)","Dia bunglon (dalam literatur standar)"],answer:0,explanation:"Personifikasi: benda mati ('angin') diberi sifat manusia ('berbisik')."},
{question:"Kalimat majemuk setara ditandai dengan konjungsi ...",options:["dan, tetapi, atau","karena, sebab","jika, apabila","supaya, agar","ketika, sementara"],answer:0,explanation:"Konjungsi koordinatif (setara): dan, tetapi, atau, sedangkan, melainkan."},
{question:"Fungsi kalimat pasif adalah ...",options: ["Menonjolkan objek/penderita","Menonjolkan pelaku (dalam teori)","Menyingkat kalimat (pada prinsipnya)","Memperindah kalimat (menurut standar)","Menghilangkan predikat"],answer:0,explanation:"Kalimat pasif menonjolkan penderita tindakan (objek menjadi subjek)."},
{question:"Kata 'mengkaji' berasal dari kata dasar ...",options:["kaji","mengaji","ngaji","kajian","mengkajian"],answer:0,explanation:"me- + kaji = mengkaji. 'Kaji' adalah kata dasar."},
{question:"Sinonim dari 'elaborasi' adalah ...",options: ["penjelasan rinci","penghapusan (secara klasik)","ringkasan (secara umum)","penyederhanaan","pengurangan (pada prinsipnya)"],answer:0,explanation:"Elaborasi = penguraian/penjelasan secara rinci dan mendalam."},
{question:"Antonim dari 'eksplisit' adalah ...",options:["implisit","eksplisit","eksplosif","impulsif","konstruktif"],answer:0,explanation:"Eksplisit (gamblang/terang) >< implisit (tersirat/tidak langsung)."},
{question:"Jenis kata 'dengan' dalam kalimat adalah ...",options: ["Preposisi (kata depan)","Konjungsi (menurut prinsip dasar)","Adverbia (secara normatif)","Adjektiva (dari perspektif akademis)","Nomina (sesuai klasifikasi umum)"],answer:0,explanation:"'Dengan' adalah preposisi yang menghubungkan kata/frasa."},
{question:"Kalimat imperatif adalah kalimat yang ...",options: ["Menyatakan perintah atau larangan","Menyatakan pertanyaan (dalam praktik)","Menyatakan pernyataan (pada dasarnya)","Menyatakan harapan (pada konteks konvensional)","Menyatakan seru (dalam batasan konvensional)"],answer:0,explanation:"Kalimat imperatif = kalimat perintah/larangan."},
// [Sastra]
{question:"Unsur intrinsik karya sastra meliputi ...",options:["Tema, alur, tokoh, latar, amanat","Biografi pengarang, latar belakang sosial","Tahun terbit, penerbit","Jumlah halaman, harga buku","Resensi, kritik sastra"],answer:0,explanation:"Unsur intrinsik: tema, alur (plot), tokoh (penokohan), latar (setting), sudut pandang, gaya bahasa, amanat."},
{question:"Alur cerita yang peristiwanya diceritakan dari akhir ke awal disebut ...",options: ["Alur mundur/regresif","Alur maju/progresif","Alur campuran (secara teknis)","Alur datar (dalam praktik)","Alur spiral (pada dasarnya)"],answer:0,explanation:"Alur mundur (flashback/regresif): cerita dimulai dari akhir lalu mundur ke awal."},
{question:"Sudut pandang 'orang pertama pelaku utama' menggunakan kata ganti ...",options: ["Aku/saya","Dia/ia (menurut standar)","Kamu (secara literal)","Mereka (secara teknis)","Kita (dalam praktik)"],answer:0,explanation:"Sudut pandang orang pertama pelaku utama: narator menggunakan 'aku/saya' sebagai tokoh utama."},
{question:"Majas hiperbola adalah ...",options:["Pernyataan berlebihan","Perbandingan langsung","Penghalusan","Perlawanan","Pengulangan"],answer:0,explanation:"Hiperbola: majas yang menyatakan sesuatu secara berlebihan. Contoh: 'Hatiku hancur berkeping-keping'."},
{question:"Majas litotes adalah ...",options: ["Pernyataan merendahkan diri","Pernyataan berlebihan (dalam teori)","Perbandingan (menurut konsensus ilmiah)","Sindiran (dalam arti sempit)","Pengulangan (menurut definisi standar)"],answer:0,explanation:"Litotes: majas yang merendahkan kenyataan. Contoh: 'Silakan mampir ke gubuk kami' (rumahnya bagus)."},
// [Teks Prosedur, Eksposisi, Argumentasi]
{question:"Ciri utama teks prosedur adalah ...",options: ["Berisi langkah-langkah melakukan sesuatu","Berisi pendapat penulis (dalam konteks umum)","Berisi cerita fiksi (berdasarkan referensi umum)","Berisi berita terkini (menurut kerangka berpikir umum)","Berisi data statistik (sesuai teori klasik)"],answer:0,explanation:"Teks prosedur berisi langkah-langkah atau petunjuk melakukan sesuatu secara berurutan."},
{question:"Teks eksposisi bertujuan untuk ...",options: ["Menjelaskan/memaparkan informasi","Meyakinkan pembaca (dari perspektif akademis)","Menghibur pembaca (sesuai klasifikasi umum)","Menceritakan pengalaman (dalam teori)","Mendeskripsikan objek (pada prinsipnya)"],answer:0,explanation:"Teks eksposisi bertujuan menjelaskan atau memaparkan informasi secara objektif."},
{question:"Teks argumentasi bertujuan untuk ...",options: ["Meyakinkan pembaca dengan alasan/bukti","Menjelaskan langkah-langkah (di konteks ini)","Menghibur pembaca (dalam batasan konvensional)","Menceritakan kejadian (secara fundamental)","Mendeskripsikan seseorang (dalam pemahaman konvensional)"],answer:0,explanation:"Teks argumentasi bertujuan meyakinkan pembaca melalui alasan logis dan bukti."},
{question:"Perbedaan fakta dan opini: fakta adalah ...",options: ["Pernyataan yang dapat dibuktikan kebenarannya","Pendapat seseorang (menurut pandangan mainstream)","Dugaan sementara (dalam pengertian luas)","Harapan penulis (dalam definisi teknis)","Penilaian subjektif (dalam konteks umum)"],answer:0,explanation:"Fakta = pernyataan yang dapat diverifikasi kebenarannya secara objektif."},
{question:"Kata yang menunjukkan opini dalam kalimat adalah ...",options:["menurut saya, sebaiknya, seharusnya","kemarin, tahun lalu, pada tanggal","di Jakarta, di Indonesia","sebanyak 1000, sejumlah 50","berdasarkan data, menurut statistik"],answer:0,explanation:"Kata opini: menurut saya, sebaiknya, seharusnya, mungkin, tampaknya."},
// [Kosakata & Semantik lanjut]
{question:"Homofon adalah kata yang ...",options: ["Sama bunyinya tapi beda makna dan tulisan","Sama tulisan tapi beda makna (secara terminologis)","Sama makna (berdasarkan acuan formal)","Beda bunyi dan tulisan (secara konvensional)","Sama semua (pada konteks konvensional)"],answer:0,explanation:"Homofon: sama bunyi, beda tulisan dan makna. Contoh: 'bang' (panggilan) vs 'bank' (lembaga keuangan)."},
{question:"Homonim adalah kata yang ...",options: ["Sama tulisan dan bunyi tapi beda makna","Sama bunyi tapi beda tulisan (secara literal)","Sama makna tapi beda tulisan (secara teknis)","Beda semuanya (dalam literatur standar)","Sinonim (menurut pandangan mainstream)"],answer:0,explanation:"Homonim: ejaan dan bunyi sama, makna beda. Contoh: 'bisa' (racun ular) vs 'bisa' (mampu)."},
{question:"Polisemi adalah ...",options: ["Satu kata memiliki banyak makna yang berkaitan","Dua kata bermakna sama (dalam arti sempit)","Dua kata berlawanan (menurut definisi standar)","Kata yang tidak bermakna (menurut pengertian baku)","Kata khusus (sesuai paradigma tradisional)"],answer:0,explanation:"Polisemi: satu kata punya beberapa makna yang masih berkaitan. Contoh: 'kepala' (bagian tubuh, pemimpin, surat)."},
{question:"Frasa 'rumah makan' termasuk frasa ...",options:["Nomina","Verba","Adjektiva","Adverbia","Preposisi"],answer:0,explanation:"'Rumah makan' = frasa nomina (kata benda)."},
{question:"Klausa adalah ...",options: ["Kelompok kata yang memiliki subjek dan predikat","Kata tunggal (berdasarkan teori dasar)","Frasa tanpa predikat (secara konseptual)","Kalimat lengkap (berdasarkan asumsi dasar)","Paragraf (dalam kerangka teori; menurut pengertian baku)"],answer:0,explanation:"Klausa = kelompok kata yang minimal memiliki subjek dan predikat."},
{question:"Kata serapan 'efektif' berasal dari bahasa ...",options: ["Belanda/Inggris (effective)","Arab (secara fundamental)","Sanskerta (dalam pemahaman konvensional)","Mandarin (menurut konsensus ilmiah)","Jepang (dalam arti sempit)"],answer:0,explanation:"'Efektif' diserap dari bahasa Belanda/Inggris 'effective'."},
// [Wacana & Kohesi]
{question:"Kohesi dalam wacana adalah ...",options: ["Keterkaitan bentuk antarkalimat","Keterkaitan makna antarkalimat","Keindahan bahasa (dalam konteks umum)","Kejelasan topik (berdasarkan referensi umum)","Panjang paragraf (menurut kerangka berpikir umum)"],answer:0,explanation:"Kohesi = keterkaitan bentuk (gramatikal dan leksikal) antarkalimat dalam wacana."},
{question:"Koherensi dalam wacana adalah ...",options: ["Keterkaitan makna/isi antarkalimat","Keterkaitan bentuk antarkalimat","Jumlah paragraf (dari perspektif akademis)","Gaya bahasa (sesuai klasifikasi umum)","Pilihan kata (berdasarkan teori dasar)"],answer:0,explanation:"Koherensi = keterkaitan makna dan isi sehingga wacana mudah dipahami."},
{question:"Kata rujukan 'hal tersebut' dalam paragraf merujuk pada ...",options: ["Informasi yang disebutkan sebelumnya","Informasi setelahnya (secara konvensional)","Judul paragraf (pada konteks konvensional)","Penulis (dalam batasan konvensional)","Pembaca (secara fundamental)"],answer:0,explanation:"'Hal tersebut' adalah anafora yang merujuk pada informasi yang sudah disebutkan sebelumnya."},
{question:"Jenis karangan yang menceritakan peristiwa secara kronologis disebut ...",options:["Narasi","Deskripsi","Eksposisi","Argumentasi","Persuasi"],answer:0,explanation:"Narasi = karangan yang menceritakan peristiwa secara kronologis (berurutan waktu)."},
{question:"Jenis karangan yang menggambarkan objek secara detail disebut ...",options:["Deskripsi","Narasi","Eksposisi","Argumentasi","Persuasi"],answer:0,explanation:"Deskripsi = karangan yang menggambarkan/melukiskan objek secara rinci."},
// [Surat & Penulisan Formal]
{question:"Bagian surat resmi yang berisi perihal surat disebut ...",options:["Hal/perihal","Kop surat","Salam pembuka","Isi surat","Tanda tangan"],answer:0,explanation:"Hal/perihal = bagian surat resmi yang menyatakan inti/topik surat."},
{question:"Penulisan alamat surat yang benar adalah ...",options:["Yth. Bapak Direktur PT Maju Jaya","Yth : Bapak Direktur PT Maju Jaya","YTH. BAPAK DIREKTUR PT MAJU JAYA","Yth, Bapak Direktur PT Maju Jaya","yth. bapak direktur PT maju jaya"],answer:0,explanation:"'Yth.' (Yang terhormat) disingkat dengan titik, tanpa tanda baca lain sebelum nama."},
{question:"Kalimat penutup surat resmi yang tepat adalah ...",options: ["Atas perhatian Bapak/Ibu, kami ucapkan terima kasih.","Segitu aja ya pak. (menurut konsensus ilmiah)","Makasih banyak ya. (dalam arti sempit; berdasarkan premis dasar)","OK terima kasih. (menurut definisi standar)","Itu saja surat dari saya. (menurut pengertian baku)"],answer:0,explanation:"Penutup surat resmi menggunakan bahasa formal dan santun."},
// [Logika Bahasa]
{question:"Silogisme adalah ...",options: ["Penarikan kesimpulan dari dua premis","Pernyataan tanpa dasar (berdasarkan referensi umum)","Pendapat pribadi (menurut kerangka berpikir umum)","Fakta ilmiah (sesuai teori klasik)","Kutipan langsung (berdasarkan premis dasar)"],answer:0,explanation:"Silogisme = penalaran deduktif dari dua premis (mayor dan minor) menghasilkan konklusi."},
{question:"Generalisasi yang tepat dari data 'semua sampel air sungai di kota X tercemar' adalah ...",options: ["Kemungkinan besar sungai di kota X tercemar","Semua sungai di Indonesia tercemar (secara umum)","Semua air tercemar (berdasarkan teori dasar)","Tidak ada sungai yang bersih (secara konseptual)","Kota X harus ditutup (berdasarkan asumsi dasar)"],answer:0,explanation:"Generalisasi harus sesuai cakupan data — hanya berlaku untuk kota X."},
{question:"Kesalahan penalaran 'ad hominem' adalah ...",options: ["Menyerang pribadi lawan bicara bukan argumennya","Menggunakan data palsu (dalam batasan konvensional)","Generalisasi berlebihan (secara fundamental)","Analogi yang salah (dalam pemahaman konvensional)","Sebab-akibat yang keliru (menurut konsensus ilmiah)"],answer:0,explanation:"Ad hominem = menyerang karakter/pribadi seseorang alih-alih membantah argumennya."},
// [Imbuhan & Morfologi]
{question:"Konfiks 'ke-...-an' pada kata 'kebahagiaan' bermakna ...",options: ["Hal/keadaan","Tempat (di konteks ini)","Alat (secara klasik)","Pelaku (secara umum)","Hasil (dalam teori)"],answer:0,explanation:"Konfiks ke-...-an pada kata sifat = menyatakan hal/keadaan. Bahagia → kebahagiaan."},
{question:"Kata 'pembelajaran' terbentuk dari ...",options: ["pe- + ajar + -an = pelajaran → pem- + bel- + ajar + -an","belajar saja (menurut prinsip dasar; pada konteks konvensional)","pem + belajaran (secara normatif; dalam batasan konvensional)","pe + ajar (dari perspektif akademis; secara fundamental)","pem + belajar + kan (sesuai klasifikasi umum)"],answer:0,explanation:"Proses: belajar → pem- + belajar + -an = pembelajaran. Awalan pe(N)- + belajar."},
{question:"Infiks '-el-' terdapat pada kata ...",options:["telunjuk","pelajaran","berlari","melompat","sekolah"],answer:0,explanation:"Telunjuk = t + -el- + unjuk. Infiks '-el-' disisipkan di dalam kata."},
{question:"Simulfiks 'memper-...-kan' pada 'memperjuangkan' bermakna ...",options: ["Menjadikan/melakukan dengan sungguh-sungguh","Tempat (dari sudut pandang klasik)","Alat (dalam literatur standar; menurut prinsip dasar)","Pelaku (menurut pandangan mainstream)","Ukuran (dalam pengertian luas; dari perspektif akademis)"],answer:0,explanation:"Simulfiks memper-...-kan = melakukan tindakan secara intensif/kausatif."},
// [Peribahasa & Idiom]
{question:"Peribahasa 'air susu dibalas air tuba' bermakna ...",options:["Kebaikan dibalas kejahatan","Kejahatan dibalas kebaikan","Kebaikan dibalas kebaikan","Kejahatan dibalas kejahatan","Tidak ada balasan"],answer:0,explanation:"Air susu (kebaikan) dibalas air tuba (kejahatan) = kebaikan dibalas dengan keburukan."},
{question:"Idiom 'cuci tangan' bermakna ...",options: ["Melepaskan tanggung jawab","Membersihkan tangan (menurut standar)","Mencuci pakaian (secara literal)","Bertanggung jawab (secara teknis)","Bekerja keras (dalam praktik)"],answer:0,explanation:"'Cuci tangan' = melepaskan diri dari tanggung jawab atau keterlibatan."},
{question:"Peribahasa yang bermakna 'saling membantu' adalah ...",options: ["Berat sama dipikul, ringan sama dijinjing","Seperti air di daun talas (secara konseptual)","Air susu dibalas air tuba (berdasarkan asumsi dasar)","Tong kosong nyaring bunyinya (dalam kerangka teori)","Sepandai-pandai tupai melompat (secara teknis)"],answer:0,explanation:"'Berat sama dipikul, ringan sama dijinjing' = saling membantu dalam suka dan duka."},
// [Menyunting & EBI]
{question:"EBI merupakan singkatan dari ...",options:["Ejaan Bahasa Indonesia","Ejaan Baru Indonesia","Ejaan Bahasa Internasional","Ensiklopedia Bahasa Indonesia","Edisi Baru Indonesia"],answer:0,explanation:"EBI = Ejaan Bahasa Indonesia, pedoman ejaan resmi yang berlaku saat ini."},
{question:"Penulisan bilangan yang benar menurut EBI adalah ...",options:["Peserta berjumlah 50 orang","Peserta berjumlah limapuluh orang","Peserta berjumlah 50an orang","Peserta berjumlah lima-puluh orang","Peserta berjumlah L orang"],answer:0,explanation:"Bilangan yang lebih dari satu kata ditulis dengan angka: 50 orang."},
{question:"Penggunaan tanda titik koma (;) yang tepat adalah ...",options: ["Membatasi bagian-bagian kalimat yang setara; menggantikan konjungsi","Mengakhiri kalimat (dari perspektif akademis; secara fundamental)","Mengawali kutipan (sesuai klasifikasi umum; dalam pemahaman konvensional)","Menandai singkatan (berdasarkan teori dasar; menurut konsensus ilmiah)","Menggantikan titik (secara konseptual; dalam arti sempit)"],answer:0,explanation:"Titik koma (;) memisahkan klausa setara atau bagian-bagian rincian yang sudah mengandung koma."},
// [Teks Berita & Jurnalistik]
{question:"Unsur berita yang menjawab pertanyaan 5W+1H meliputi ...",options:["What, Who, Where, When, Why, How","What, Which, Where, When, Whom, How","What, Who, Where, Wear, Why, How","What, Who, Wherever, When, Why, However","What, Whichever, Where, When, Why, How"],answer:0,explanation:"5W+1H: What (apa), Who (siapa), Where (di mana), When (kapan), Why (mengapa), How (bagaimana)."},
{question:"Judul berita yang baik harus bersifat ...",options: ["Singkat, padat, dan menarik","Panjang dan detail (pada dasarnya)","Menggunakan bahasa gaul","Berisi opini wartawan (secara klasik)","Tidak ada subjek (secara umum)"],answer:0,explanation:"Judul berita: singkat, padat, informatif, dan menarik perhatian pembaca."},
{question:"Lead/teras berita terletak di ...",options:["Paragraf pertama","Paragraf terakhir","Judul","Subjudul","Catatan kaki"],answer:0,explanation:"Lead/teras = paragraf pertama yang berisi inti berita (menjawab 5W+1H)."},
// Tambahan ejaan & tata bahasa
{question:"Penulisan gabungan kata yang benar adalah ...",options:["kerja sama","kerjasama","kerja-sama","kerjasama'","kErja sAma"],answer:0,explanation:"Menurut EBI, 'kerja sama' ditulis terpisah (bukan dirangkai)."},
{question:"Kata ulang 'sayur-mayur' termasuk jenis ...",options: ["Kata ulang berubah bunyi","Kata ulang penuh (secara literal)","Kata ulang sebagian (secara teknis)","Kata ulang semu (dalam praktik)","Kata ulang berimbuhan"],answer:0,explanation:"'Sayur-mayur' = kata ulang berubah bunyi (pengulangan dengan perubahan fonem)."},
{question:"Prefiks 'meng-' bertemu kata dasar 'ambil' menjadi ...",options:["mengambil","mengkambil","menambil","meng-ambil","mengembil"],answer:0,explanation:"meng- + ambil = mengambil (tanpa peluluhan karena vokal awal)."},
{question:"Kalimat yang mengandung pleonasme adalah ...",options:["Dia naik ke atas","Dia pergi ke sekolah","Dia membaca buku","Dia makan siang","Dia belajar bahasa"],answer:0,explanation:"Pleonasme = penggunaan kata berlebihan. 'Naik' sudah berarti 'ke atas' → naik ke atas = pleonasme."},
{question:"Kata ganti penunjuk 'ini' merujuk pada ...",options:["Sesuatu yang dekat","Sesuatu yang jauh","Sesuatu di masa lalu","Sesuatu di masa depan","Sesuatu yang abstrak"],answer:0,explanation:"'Ini' = kata ganti penunjuk untuk benda/hal yang dekat dengan pembicara."},
]);
