// TPS Expansion — Spasial +15, Logika +14 = 29 soal
// Pushing TPS total from 971 → 1000

appendQuestions('tps_spasial', [
{question:"Jika sebuah kubus dipotong diagonal ruangnya, penampang yang terbentuk adalah ...",options:["Persegi panjang","Segitiga","Lingkaran","Segi enam","Trapesium"],answer:0,explanation:"Diagonal ruang kubus memotong menjadi penampang berbentuk persegi panjang."},
{question:"Berapa banyak simetri putar yang dimiliki oleh segitiga sama sisi?",options:["3","2","6","1","4"],answer:0,explanation:"Segitiga sama sisi memiliki 3 simetri putar (120°, 240°, 360°)."},
{question:"Jika bangun datar diputar 360° terhadap salah satu sisinya, bangun ruang apa yang terbentuk dari persegi panjang?",options:["Tabung","Kerucut","Bola","Prisma","Balok"],answer:0,explanation:"Persegi panjang diputar 360° menghasilkan tabung."},
{question:"Sebuah limas segi empat memiliki berapa rusuk?",options:["8","10","6","12","5"],answer:0,explanation:"Limas segi empat: 4 rusuk alas + 4 rusuk tegak = 8 rusuk."},
{question:"Jaring-jaring yang TIDAK bisa dilipat menjadi kubus adalah yang memiliki ...",options:["4 persegi berjajar lurus","Bentuk T","Bentuk L","Bentuk salib","Bentuk tangga"],answer:0,explanation:"4 persegi berjajar lurus tidak bisa dilipat menjadi kubus karena saling tumpang tindih."},
{question:"Bayangan cermin dari huruf 'R' yang menghadap kanan adalah ...",options:["Я","R","Ʀ","ꓤ","P"],answer:0,explanation:"Bayangan cermin huruf R menghasilkan bentuk terbalik horizontal seperti Я."},
{question:"Sebuah prisma segitiga memiliki berapa sisi?",options:["5","6","4","3","8"],answer:0,explanation:"Prisma segitiga: 2 sisi segitiga + 3 sisi persegi panjang = 5 sisi."},
{question:"Jika sebuah kubus dilihat dari sudut atas depan kanan, berapa sisi yang terlihat?",options:["3","2","1","4","6"],answer:0,explanation:"Dari sudut kubus, kita bisa melihat 3 sisi sekaligus."},
{question:"Pola: segitiga, lingkaran, persegi, segitiga, lingkaran, ... Bangun selanjutnya?",options:["Persegi","Segitiga","Lingkaran","Pentagon","Segi enam"],answer:0,explanation:"Pola berulang setiap 3: segitiga-lingkaran-persegi. Setelah lingkaran adalah persegi."},
{question:"Sebuah kerucut dipotong sejajar alasnya, penampangnya berbentuk ...",options:["Lingkaran","Elips","Segitiga","Parabola","Persegi"],answer:0,explanation:"Potongan sejajar alas kerucut selalu menghasilkan lingkaran."},
{question:"Berapa jumlah diagonal ruang sebuah balok?",options:["4","6","8","12","2"],answer:0,explanation:"Balok memiliki 4 diagonal ruang."},
{question:"Jika kubus diputar 90° searah jarum jam pada sumbu vertikal, sisi mana yang menghadap depan?",options:["Sisi kanan menjadi depan","Sisi kiri menjadi depan","Sisi atas menjadi depan","Sisi belakang menjadi depan","Tetap sama"],answer:0,explanation:"Rotasi 90° searah jarum jam membuat sisi kanan menjadi menghadap depan."},
{question:"Berapa banyak titik sudut pada icosahedron (ikosahedron)?",options:["12","20","30","10","60"],answer:0,explanation:"Icosahedron memiliki 12 titik sudut, 30 rusuk, dan 20 sisi segitiga."},
{question:"Sebuah segitiga sama kaki dipantulkan terhadap garis alasnya. Bangun gabungan yang terbentuk adalah ...",options:["Belah ketupat","Persegi panjang","Layang-layang","Jajaran genjang","Trapesium"],answer:0,explanation:"Segitiga sama kaki dipantulkan terhadap alasnya membentuk belah ketupat."},
{question:"Berapa jumlah sisi pada dodecahedron (dodekahedron)?",options:["12","20","10","6","30"],answer:0,explanation:"Dodecahedron memiliki 12 sisi pentagonal."},
]);

appendQuestions('tps_logika', [
{question:"Semua dokter memakai jas putih. Budi memakai jas putih. Kesimpulan yang tepat?",options:["Tidak dapat dipastikan Budi dokter","Budi pasti dokter","Budi bukan dokter","Semua yang memakai jas putih dokter","Budi mungkin tidak memakai jas putih"],answer:0,explanation:"Ini fallacy afirmasi konsekuen. Memakai jas putih bukan berarti dokter."},
{question:"Jika hujan, maka jalanan basah. Jalanan tidak basah. Maka ...",options:["Tidak hujan","Hujan tapi jalanan kering","Mungkin hujan","Jalanan selalu basah","Tidak bisa disimpulkan"],answer:0,explanation:"Modus tollens: jika P→Q dan ¬Q, maka ¬P. Jalanan tidak basah → tidak hujan."},
{question:"Premis 1: Semua kucing adalah hewan. Premis 2: Semua hewan bernapas. Kesimpulan?",options:["Semua kucing bernapas","Semua yang bernapas adalah kucing","Beberapa hewan adalah kucing","Tidak semua kucing bernapas","Kucing tidak bernapas"],answer:0,explanation:"Silogisme transitif: kucing ⊂ hewan ⊂ yang bernapas → kucing ⊂ yang bernapas."},
{question:"Diketahui: Tidak ada siswa malas yang lulus. Ani lulus. Maka ...",options:["Ani bukan siswa malas","Ani malas","Ani tidak lulus","Tidak bisa disimpulkan","Semua siswa rajin lulus"],answer:0,explanation:"Kontraposisi: malas → tidak lulus. Lulus (¬ tidak lulus) → tidak malas."},
{question:"5 orang duduk melingkar. Ada berapa susunan berbeda yang mungkin?",options:["24","120","60","12","5"],answer:0,explanation:"Permutasi siklis: (n-1)! = 4! = 24."},
{question:"Jika A lebih tinggi dari B, dan C lebih pendek dari B, maka ...",options:["A paling tinggi di antara ketiganya","C paling tinggi","B paling tinggi","A dan C sama tinggi","Tidak bisa ditentukan"],answer:0,explanation:"A > B > C, maka A paling tinggi."},
{question:"Deret: 2, 6, 18, 54, ... Suku ke-6 adalah?",options:["486","162","324","648","243"],answer:0,explanation:"Deret geometri r=3. a₆ = 2 × 3⁵ = 2 × 243 = 486."},
{question:"Semua A adalah B. Tidak ada B yang C. Maka ...",options:["Tidak ada A yang C","Semua A adalah C","Beberapa A adalah C","A dan C sama","Tidak bisa disimpulkan"],answer:0,explanation:"A⊂B dan B∩C=∅, maka A∩C=∅. Tidak ada A yang C."},
{question:"Hari ini Selasa. 100 hari lagi adalah hari ...",options:["Kamis","Rabu","Jumat","Senin","Sabtu"],answer:0,explanation:"100 mod 7 = 2. Selasa + 2 = Kamis."},
{question:"Jika p→q benar dan q→r benar, manakah yang PASTI benar?",options:["p→r","r→p","¬p→¬r","q→p","¬r→q"],answer:0,explanation:"Transitivitas implikasi: p→q dan q→r menghasilkan p→r."},
{question:"Ada 3 kotak: merah, biru, hijau. Bola emas ada di kotak yang labelnya SALAH. Kotak merah berlabel 'Bola di sini', kotak biru berlabel 'Bola tidak di kotak merah', kotak hijau berlabel 'Bola tidak di sini'. Jika semua label salah, bola ada di ...",options:["Kotak hijau","Kotak merah","Kotak biru","Bisa di mana saja","Tidak ada yang benar"],answer:0,explanation:"Label hijau 'Bola tidak di sini' salah → bola di hijau. Cek: label merah 'di sini' salah ✓, label biru 'tidak di merah' salah ✓."},
{question:"Negasi dari 'Semua siswa rajin belajar' adalah ...",options:["Ada siswa yang tidak rajin belajar","Tidak ada siswa yang rajin belajar","Semua siswa tidak rajin belajar","Beberapa siswa rajin belajar","Siswa malas belajar"],answer:0,explanation:"Negasi ∀x P(x) = ∃x ¬P(x). Ada (setidaknya satu) siswa yang tidak rajin."},
{question:"Jika 'Beberapa politisi jujur' salah, maka yang benar adalah ...",options:["Semua politisi tidak jujur","Beberapa politisi tidak jujur","Semua politisi jujur","Tidak ada yang benar","Ada politisi jujur"],answer:0,explanation:"Negasi 'Beberapa A adalah B' = 'Semua A bukan B'. Tidak ada politisi yang jujur."},
{question:"A berbicara: 'Saya selalu berbohong.' Pernyataan ini adalah ...",options:["Paradoks","Benar","Salah","Tidak bisa dinilai","Tautologi"],answer:0,explanation:"Jika benar → dia selalu bohong → pernyataan ini bohong (kontradiksi). Jika bohong → dia tidak selalu bohong → bisa jadi benar. Paradoks liar."},
]);
