// ============================================
// TKA Soshum — Sejarah (50 Soal HOTS)
// UM UGM CBT 2026
// ============================================
registerQuestions('soshum_sejarah', [
{question:"Proklamasi kemerdekaan Indonesia dibacakan oleh Soekarno-Hatta pada tanggal …",options:["17 Agustus 1945","1 Juni 1945","28 Oktober 1928","20 Mei 1908","10 November 1945"],answer:0,hint:"Tanggal bersejarah yang menjadi hari kemerdekaan Indonesia.",explanation:"Proklamasi kemerdekaan dibacakan Soekarno didampingi Hatta pada 17 Agustus 1945 di Jalan Pegangsaan Timur 56, Jakarta.\nJawaban: A."},
{question:"Peristiwa Rengasdengklok terjadi pada …",options:["16 Agustus 1945","17 Agustus 1945","14 Agustus 1945","15 Agustus 1945","18 Agustus 1945"],answer:0,hint:"Peristiwa penculikan Soekarno-Hatta oleh golongan muda sebelum proklamasi.",explanation:"16 Agustus 1945: golongan muda (Sukarni, Wikana, dll) membawa Soekarno-Hatta ke Rengasdengklok untuk mendesak segera memproklamasikan kemerdekaan.\nJawaban: A."},
{question:"Organisasi pergerakan nasional pertama yang bersifat modern di Indonesia adalah …",options:["Budi Utomo (1908)","Sarekat Islam (1911)","Indische Partij (1912)","PNI (1927)","Muhammadiyah (1912)"],answer:0,hint:"Didirikan 20 Mei 1908 oleh dr. Soetomo dan mahasiswa STOVIA.",explanation:"Budi Utomo (20 Mei 1908): organisasi modern pertama di Indonesia, didirikan oleh dr. Soetomo. Awalnya berfokus pada pendidikan dan kebudayaan Jawa.\n20 Mei kemudian diperingati sebagai Hari Kebangkitan Nasional.\nJawaban: A."},
{question:"Sumpah Pemuda dikumandangkan pada …",options:["28 Oktober 1928","20 Mei 1908","17 Agustus 1945","1 Juni 1945","10 November 1945"],answer:0,hint:"Ikrar persatuan pemuda-pemuda Indonesia: satu nusa, satu bangsa, satu bahasa.",explanation:"Sumpah Pemuda: 28 Oktober 1928, mengikrarkan satu nusa, satu bangsa, satu bahasa — Indonesia. Momentum penting dalam pergerakan nasional.\nJawaban: A."},
{question:"Perang Diponegoro (1825-1830) disebabkan oleh …",options:["Campur tangan Belanda dalam urusan Keraton Yogyakarta dan pembangunan jalan melalui tanah milik Diponegoro","Konflik antar kerajaan Jawa","Kedatangan Jepang","Revolusi industri di Eropa","Serangan Portugal"],answer:0,hint:"Pangeran Diponegoro memimpin perlawanan terhadap VOC/Belanda selama 5 tahun.",explanation:"Penyebab Perang Diponegoro:\n1. Campur tangan Belanda di Keraton Yogyakarta\n2. Pembangunan jalan yang melewati tanah dan makam leluhur Diponegoro\n3. Ketidakpuasan terhadap pemerintahan kolonial\nPerang berlangsung 1825-1830, berakhir dengan penangkapan Diponegoro melalui tipu muslihat.\nJawaban: A."},
{question:"Sistem tanam paksa (Cultuurstelsel) diterapkan oleh gubernur jenderal …",options:["Johannes van den Bosch (1830)","Daendels","Raffles","De Graeff","Van Heutsz"],answer:0,hint:"Diterapkan tahun 1830 untuk mengatasi kebangkrutan keuangan Belanda.",explanation:"Cultuurstelsel (1830) diterapkan oleh Gubernur Jenderal Johannes van den Bosch. Petani diwajibkan menanam tanaman ekspor (kopi, tebu, nila) di 1/5 lahannya. Menghasilkan keuntungan besar bagi Belanda tapi menyengsarakan rakyat.\nJawaban: A."},
{question:"Konferensi Asia-Afrika (KAA) pertama diadakan di …",options:["Bandung, 1955","Jakarta, 1945","Manila, 1954","Colombo, 1954","New Delhi, 1947"],answer:0,hint:"Konferensi yang menghasilkan Dasasila Bandung.",explanation:"KAA pertama: 18-24 April 1955 di Gedung Merdeka, Bandung. Diikuti 29 negara Asia-Afrika. Menghasilkan Dasasila Bandung yang menjadi fondasi Gerakan Non-Blok.\nJawaban: A."},
{question:"Politik Etis (Ethische Politiek) yang diterapkan Belanda tahun 1901 meliputi tiga program utama, yaitu …",options:["Edukasi (pendidikan), Irigasi (pengairan), Emigrasi (perpindahan penduduk)","Militer, ekonomi, budaya","Industri, perdagangan, transportasi","Pajak, subsidi, bantuan","Hukum, keamanan, pertahanan"],answer:0,hint:"Trias: Edukasi, Irigasi, Emigrasi — diusulkan Van Deventer.",explanation:"Politik Etis (1901): kebijakan balas budi Belanda kepada Indonesia.\nTiga pilar (Van Deventer):\n1. Edukasi: pendidikan untuk pribumi\n2. Irigasi: pembangunan saluran pengairan\n3. Emigrasi: perpindahan penduduk (transmigrasi)\nJawaban: A."},
{question:"Perang Dunia I (1914-1918) dipicu langsung oleh …",options:["Pembunuhan Archduke Franz Ferdinand dari Austria-Hungaria","Invasi Jerman ke Polandia","Serangan Pearl Harbor","Revolusi Rusia","Runtuhnya Ottoman"],answer:0,hint:"Pembunuhan putra mahkota Austria di Sarajevo oleh seorang nasionalis Serbia.",explanation:"28 Juni 1914: Archduke Franz Ferdinand dan istrinya dibunuh di Sarajevo oleh Gavrilo Princip (nasionalis Serbia). Ini memicu serangkaian deklarasi perang akibat sistem aliansi yang kompleks di Eropa.\nJawaban: A."},
{question:"Peristiwa Supersemar (11 Maret 1966) adalah …",options:["Surat perintah dari Presiden Soekarno kepada Soeharto untuk mengambil tindakan mengamankan keadaan","Deklarasi kemerdekaan","Pembubaran parlemen","Penandatanganan perjanjian perdamaian","Pembentukan konstitusi baru"],answer:0,hint:"Super = Surat Perintah. Semar = Sebelas Maret.",explanation:"Supersemar (11 Maret 1966): Surat Perintah Sebelas Maret dari Presiden Soekarno kepada Mayor Jenderal Soeharto untuk mengambil segala tindakan yang dianggap perlu guna menjaga keamanan dan ketertiban. Menjadi dasar peralihan kekuasaan.\nJawaban: A."},
{question:"Revolusi Prancis (1789) menghasilkan semboyan …",options:["Liberté, Égalité, Fraternité (Kebebasan, Kesetaraan, Persaudaraan)","In God We Trust","E Pluribus Unum","Bhinneka Tunggal Ika","Workers of the world, unite"],answer:0,hint:"Semboyan Revolusi Prancis yang menjadi fondasi nilai-nilai demokrasi modern.",explanation:"Revolusi Prancis (1789): menggulingkan monarki absolut. Semboyan: Liberté (kebebasan), Égalité (kesetaraan), Fraternité (persaudaraan). Mempengaruhi gerakan demokrasi di seluruh dunia.\nJawaban: A."},
{question:"Kerajaan Majapahit mencapai puncak kejayaannya pada masa pemerintahan … dengan mahapatih Gajah Mada.",options:["Hayam Wuruk","Raden Wijaya","Jayanegara","Tribhuwana Tunggadewi","Kertawijaya"],answer:0,hint:"Raja Majapahit yang memerintah 1350-1389, masa keemasan Majapahit.",explanation:"Hayam Wuruk (Rajasanagara, 1350-1389): masa puncak Majapahit. Wilayah kekuasaan meliputi hampir seluruh Nusantara. Dibantu Mahapatih Gajah Mada (Sumpah Palapa) dan pujangga Mpu Prapanca (Nagarakretagama).\nJawaban: A."},
{question:"Perjanjian Linggarjati (1947) mengakui kedaulatan RI atas …",options:["Jawa, Sumatra, dan Madura","Seluruh Indonesia","Hanya Jakarta","Kalimantan dan Sulawesi","Papua"],answer:0,hint:"Perjanjian pertama antara RI dan Belanda setelah kemerdekaan.",explanation:"Perjanjian Linggarjati (25 Maret 1947):\n- Belanda mengakui kedaulatan RI de facto atas Jawa, Sumatra, dan Madura\n- Pembentukan Republik Indonesia Serikat (RIS)\n- Uni Indonesia-Belanda\nJawaban: A."},
{question:"Gerakan Reformasi 1998 di Indonesia dipicu oleh …",options:["Krisis ekonomi, otoritarianisme Orde Baru, dan penembakan mahasiswa Trisakti","Invasi asing","Bencana alam","Konflik antar suku","Perubahan iklim"],answer:0,hint:"Mei 1998: mahasiswa menuntut reformasi di tengah krisis moneter.",explanation:"Reformasi 1998 dipicu:\n1. Krisis moneter Asia 1997 (rupiah anjlok)\n2. KKN (Korupsi, Kolusi, Nepotisme) Orde Baru\n3. Penembakan 4 mahasiswa Trisakti (12 Mei 1998)\n4. Kerusuhan Mei 1998\n→ Soeharto mundur 21 Mei 1998.\nJawaban: A."},
{question:"Perang Dunia II berakhir di Asia setelah …",options:["Bom atom dijatuhkan di Hiroshima dan Nagasaki (Agustus 1945)","Pertempuran Stalingrad","D-Day di Normandia","Perjanjian Versailles","Konferensi Yalta"],answer:0,hint:"Dua bom atom AS menyebabkan Jepang menyerah tanpa syarat.",explanation:"6 Agustus 1945: bom Little Boy di Hiroshima.\n9 Agustus 1945: bom Fat Man di Nagasaki.\n15 Agustus 1945: Kaisar Hirohito mengumumkan penyerahan Jepang (V-J Day).\nJawaban: A."},
{question:"VOC (Vereenigde Oost-Indische Compagnie) didirikan tahun …",options:["1602","1511","1799","1830","1945"],answer:0,hint:"Kongsi dagang Belanda yang memonopoli perdagangan rempah di Nusantara.",explanation:"VOC didirikan 20 Maret 1602, merupakan perusahaan dagang Belanda pertama yang bersifat multinasional. Dibubarkan tahun 1799 karena korupsi dan utang.\nJawaban: A."},
{question:"Renaisans di Eropa (abad 14-17) ditandai oleh …",options:["Kebangkitan seni, ilmu pengetahuan, dan humanisme dari zaman klasik Yunani-Romawi","Perang agama","Runtuhnya imperium Romawi","Penemuan benua Amerika","Revolusi industri"],answer:0,hint:"Renaissance = 'kelahiran kembali' budaya klasik. Berawal dari Italia.",explanation:"Renaisans (abad 14-17): kebangkitan kembali minat pada seni, sastra, dan filsafat Yunani-Romawi kuno. Berpusat di Italia (Florence). Ditandai humanisme, seni (Leonardo da Vinci, Michelangelo), dan revolusi ilmiah.\nJawaban: A."},
{question:"Perang Dingin (Cold War) adalah …",options:["Persaingan ideologi dan pengaruh geopolitik antara AS (kapitalisme) dan Uni Soviet (komunisme) tanpa konflik militer langsung","Perang di Kutub Utara","Pertempuran di musim dingin","Konflik internal AS","Perang antara Eropa dan Asia"],answer:0,hint:"Cold = tidak ada pertempuran langsung (hot war). Perang ideologi dan proxy.",explanation:"Perang Dingin (1947-1991): persaingan AS (blok Barat, kapitalisme/demokrasi liberal) vs Uni Soviet (blok Timur, komunisme). Tidak ada konflik militer langsung tapi melalui perlombaan senjata, perang proxy (Korea, Vietnam), dan Space Race.\nJawaban: A."},
{question:"Runtuhnya Tembok Berlin terjadi pada tahun …",options:["1989","1945","1991","2001","1975"],answer:0,hint:"Simbol berakhirnya Perang Dingin. Jerman bersatu kembali tahun 1990.",explanation:"9 November 1989: Tembok Berlin diruntuhkan, menandai berakhirnya pembagian Jerman dan simbolis akhir Perang Dingin. Jerman resmi bersatu 3 Oktober 1990.\nJawaban: A."},
{question:"Kerajaan Sriwijaya (abad 7-13) berpusat di …",options:["Palembang, Sumatra Selatan","Yogyakarta","Bali","Kalimantan","Papua"],answer:0,hint:"Kerajaan maritim Buddhist terbesar di Asia Tenggara.",explanation:"Sriwijaya: kerajaan maritim Buddhis (abad 7-13) berpusat di Palembang (Sumatra Selatan). Menguasai perdagangan Selat Malaka. Pusat pendidikan Buddhisme (I-Tsing dari Tiongkok belajar di sini).\nJawaban: A."},
{question:"Perjuangan kemerdekaan India dari Inggris dipimpin oleh …",options:["Mahatma Gandhi dengan gerakan non-kekerasan (ahimsa/satyagraha)","Napoleon Bonaparte","Mao Zedong","Ho Chi Minh","Nelson Mandela"],answer:0,hint:"Pemimpin yang menggunakan prinsip non-kekerasan (non-violence) dan pembangkangan sipil.",explanation:"Mahatma Gandhi memimpin perjuangan kemerdekaan India melalui gerakan non-kekerasan (ahimsa) dan satyagraha (keteguhan kebenaran). India merdeka 15 Agustus 1947.\nJawaban: A."},
{question:"Dampak Revolusi Industri (abad 18-19) terhadap masyarakat meliputi …",options:["Urbanisasi, perubahan struktur sosial, dan pertumbuhan kelas pekerja","Kembali ke sistem pertanian subsisten","Hilangnya semua teknologi","Populasi menurun drastis","Tidak ada perubahan signifikan"],answer:0,hint:"Mekanisasi produksi mengubah secara fundamental cara manusia bekerja dan hidup.",explanation:"Dampak Revolusi Industri:\n1. Urbanisasi masif (desa → kota)\n2. Munculnya kelas pekerja/buruh industri\n3. Perubahan struktur keluarga\n4. Pertumbuhan ekonomi pesat\n5. Masalah sosial (kemiskinan urban, polusi)\nJawaban: A."},
{question:"Sidang BPUPKI I (29 Mei–1 Juni 1945) membahas …",options:["Dasar negara Indonesia (Pancasila)","Teks proklamasi","UU Agraria","Perjanjian internasional","Anggaran negara"],answer:0,hint:"Soekarno menyampaikan konsep Pancasila pada 1 Juni 1945.",explanation:"Sidang BPUPKI I (29 Mei–1 Juni 1945): membahas dasar negara. Soekarno menyampaikan gagasan Pancasila pada 1 Juni 1945 (Hari Lahir Pancasila).\nJawaban: A."},
{question:"Perjanjian Westphalia (1648) penting dalam sejarah dunia karena …",options:["Meletakkan dasar sistem negara-bangsa (nation-state) modern dan kedaulatan nasional","Mengakhiri Perang Dunia I","Membentuk PBB","Memulai Perang Dingin","Menghapus perbudakan"],answer:0,hint:"Perjanjian yang mengakhiri Perang 30 Tahun di Eropa dan menetapkan prinsip kedaulatan negara.",explanation:"Perjanjian Westphalia (1648): mengakhiri Perang 30 Tahun dan Perang 80 Tahun di Eropa. Menetapkan prinsip kedaulatan negara (setiap negara berdaulat di wilayahnya sendiri), menjadi fondasi sistem hubungan internasional modern.\nJawaban: A."},
]);
