// ============================================
// TKA Soshum — Ekonomi (50 Soal HOTS)
// UM UGM CBT 2026
// ============================================
registerQuestions('soshum_ekonomi', [
{question:"Hukum permintaan menyatakan bahwa jika harga suatu barang naik, ceteris paribus, maka …",options:["Jumlah barang yang diminta turun","Jumlah barang yang diminta naik","Jumlah barang yang ditawarkan turun","Permintaan dan penawaran seimbang","Harga akan turun kembali"],answer:0,hint:"Ceteris paribus = faktor lain tetap. Hukum permintaan menunjukkan hubungan terbalik harga-kuantitas.",explanation:"Hukum permintaan: hubungan terbalik antara harga dan kuantitas yang diminta (ceteris paribus). Harga naik → kuantitas diminta turun.\nJawaban: A."},
{question:"GDP (Gross Domestic Product) mengukur …",options:["Total nilai barang dan jasa yang diproduksi dalam suatu negara selama satu periode","Total ekspor suatu negara","Jumlah uang beredar","Tingkat pengangguran","Neraca perdagangan"],answer:0,hint:"GDP = total produksi domestik dalam periode tertentu (biasanya 1 tahun).",explanation:"GDP = total nilai pasar semua barang dan jasa final yang diproduksi di dalam batas wilayah suatu negara dalam periode tertentu.\nJawaban: A."},
{question:"Inflasi adalah …",options:["Kenaikan tingkat harga umum secara terus-menerus","Penurunan tingkat harga umum","Kenaikan harga satu barang tertentu","Peningkatan jumlah uang beredar","Penurunan nilai tukar mata uang"],answer:0,hint:"Inflasi = kenaikan harga umum (bukan satu barang) yang bersifat kontinu.",explanation:"Inflasi: kenaikan tingkat harga umum (general price level) secara terus-menerus dan berkepanjangan. Bukan kenaikan harga satu barang, dan bukan sementara.\nJawaban: A."},
{question:"Kebijakan fiskal ekspansif yang dilakukan pemerintah untuk mengatasi resesi meliputi …",options:["Meningkatkan belanja pemerintah dan/atau menurunkan pajak","Menaikkan suku bunga","Mengurangi jumlah uang beredar","Meningkatkan cadangan wajib bank","Menjual surat berharga pemerintah"],answer:0,hint:"Fiskal ekspansif = merangsang ekonomi. Belanja naik atau pajak turun → aggregate demand naik.",explanation:"Kebijakan fiskal ekspansif:\n1. Meningkatkan belanja pemerintah (G↑)\n2. Menurunkan pajak (T↓)\nKeduanya meningkatkan aggregate demand untuk mendorong pertumbuhan ekonomi saat resesi.\nJawaban: A."},
{question:"Biaya peluang (opportunity cost) dari suatu keputusan adalah …",options:["Nilai alternatif terbaik yang dikorbankan","Biaya produksi total","Harga jual barang","Keuntungan yang diperoleh","Biaya tetap ditambah biaya variabel"],answer:0,hint:"Opportunity cost = apa yang Anda 'lewatkan' ketika memilih satu opsi di atas yang lain.",explanation:"Biaya peluang = nilai dari alternatif terbaik berikutnya yang tidak dipilih. Ini adalah konsep fundamental dalam pengambilan keputusan ekonomi.\nJawaban: A."},
{question:"Pasar persaingan sempurna dicirikan oleh …",options:["Banyak penjual dan pembeli, produk homogen, informasi sempurna","Satu penjual dominan","Beberapa penjual besar dengan produk terdiferensiasi","Hambatan masuk tinggi","Harga ditentukan oleh produsen tunggal"],answer:0,hint:"Persaingan sempurna = kondisi ideal pasar: banyak pelaku, produk identik, tidak ada yang bisa mempengaruhi harga.",explanation:"Ciri pasar persaingan sempurna: banyak penjual dan pembeli, produk homogen, informasi sempurna, tidak ada hambatan masuk/keluar, price taker.\nJawaban: A."},
{question:"Instrumen kebijakan moneter Bank Indonesia (BI) meliputi …",options:["BI Rate, operasi pasar terbuka, giro wajib minimum","Pajak, subsidi, belanja pemerintah","Tarif impor, kuota ekspor","Upah minimum regional","Privatisasi BUMN"],answer:0,hint:"Monetar = uang. BI mengatur jumlah uang beredar melalui suku bunga dan instrumen pasar.",explanation:"Instrumen kebijakan moneter BI:\n1. BI Rate (suku bunga acuan)\n2. Operasi Pasar Terbuka (jual-beli SBI)\n3. Giro Wajib Minimum (cadangan wajib)\n4. Kebijakan diskonto\nJawaban: A."},
{question:"Dalam kurva kemungkinan produksi (Production Possibility Curve), titik di DALAM kurva menunjukkan …",options:["Sumber daya tidak digunakan secara efisien","Produksi maksimal tercapai","Sumber daya berlebihan","Inflasi tinggi","Pertumbuhan ekonomi"],answer:0,hint:"Titik pada kurva = efisien. Titik di luar = tidak mungkin. Titik di dalam = belum efisien.",explanation:"Titik di dalam PPC: produksi di bawah kapasitas penuh → sumber daya tidak digunakan secara efisien (pengangguran, kapasitas menganggur).\nJawaban: A."},
{question:"Hukum Engel menyatakan bahwa semakin tinggi pendapatan keluarga, maka …",options:["Proporsi pengeluaran untuk makanan menurun","Proporsi pengeluaran untuk makanan meningkat","Total pengeluaran menurun","Tabungan akan menurun","Konsumsi barang mewah menurun"],answer:0,hint:"Hukum Engel berkaitan dengan proporsi (persentase) pengeluaran pangan terhadap pendapatan.",explanation:"Hukum Engel: seiring meningkatnya pendapatan, PROPORSI (persentase) pengeluaran untuk makanan menurun, meskipun pengeluaran absolut untuk makanan mungkin meningkat.\nJawaban: A."},
{question:"Neraca pembayaran (Balance of Payments) suatu negara terdiri dari …",options:["Neraca berjalan, neraca modal, dan neraca finansial","Hanya neraca perdagangan","GDP dan GNP","Pajak dan subsidi","Ekspor dikurangi impor saja"],answer:0,hint:"BoP mencatat semua transaksi ekonomi antara penduduk suatu negara dengan negara lain.",explanation:"Neraca Pembayaran:\n1. Neraca Berjalan (current account): perdagangan barang/jasa, pendapatan, transfer\n2. Neraca Modal (capital account)\n3. Neraca Finansial (financial account): investasi langsung, portofolio\nJawaban: A."},
{question:"Pajak progresif adalah pajak yang …",options:["Tarif pajaknya meningkat seiring meningkatnya penghasilan","Tarif pajaknya tetap untuk semua penghasilan","Tarif pajaknya menurun seiring meningkatnya penghasilan","Hanya dikenakan pada perusahaan","Hanya dikenakan pada barang mewah"],answer:0,hint:"Progresif = makin banyak penghasilan, makin tinggi persentase pajaknya.",explanation:"Pajak progresif: tarif pajak meningkat seiring meningkatnya dasar pengenaan pajak (penghasilan). Contoh: PPh di Indonesia dengan tarif 5%, 15%, 25%, 30%, 35%.\nJawaban: A."},
{question:"Elastisitas harga permintaan mengukur …",options:["Responsivitas kuantitas yang diminta terhadap perubahan harga","Perubahan harga terhadap waktu","Jumlah total permintaan dalam ekonomi","Hubungan antara pendapatan dan konsumsi","Perubahan penawaran terhadap harga"],answer:0,hint:"Elastisitas = seberapa sensitif kuantitas terhadap perubahan harga (% perubahan Qd / % perubahan P).",explanation:"Elastisitas harga permintaan (PED) = %ΔQd / %ΔP.\nMengukur seberapa responsif kuantitas yang diminta terhadap perubahan harga.\nElastis (|E|>1), inelastis (|E|<1), unitary (|E|=1).\nJawaban: A."},
{question:"Keuntungan perdagangan internasional menurut teori keunggulan komparatif David Ricardo adalah …",options:["Setiap negara mengkhususkan produksi pada barang dengan biaya peluang relatif terendah","Negara besar selalu diuntungkan","Hanya negara maju yang bisa berdagang","Proteksionisme meningkatkan kesejahteraan","Perdagangan hanya menguntungkan satu pihak"],answer:0,hint:"Komparatif = membandingkan biaya peluang relatif, bukan absolut.",explanation:"Teori keunggulan komparatif Ricardo: negara harus mengkhususkan produksi pada barang yang memiliki biaya peluang relatif terendah. Perdagangan saling menguntungkan meskipun satu negara lebih efisien dalam semua barang.\nJawaban: A."},
{question:"Pendapatan nasional dengan pendekatan produksi dihitung dari …",options:["Jumlah nilai tambah (value added) dari seluruh sektor ekonomi","Jumlah seluruh pengeluaran masyarakat","Jumlah seluruh pendapatan faktor produksi","Jumlah pajak yang diterima pemerintah","Jumlah ekspor dikurangi impor"],answer:0,hint:"Pendekatan produksi menghitung nilai tambah di setiap tahap produksi untuk menghindari penghitungan ganda.",explanation:"Pendekatan produksi: Y = Σ Nilai Tambah setiap sektor.\nNilai tambah = Output − Input antara (intermediate input).\nMenghindari penghitungan ganda (double counting).\nJawaban: A."},
{question:"Indeks Harga Konsumen (IHK/CPI) digunakan untuk mengukur …",options:["Perubahan rata-rata harga sekeranjang barang/jasa yang dikonsumsi rumah tangga","Total produksi nasional","Tingkat pengangguran","Neraca perdagangan","Jumlah uang beredar"],answer:0,hint:"IHK membandingkan biaya 'keranjang belanja' tetap dari waktu ke waktu.",explanation:"IHK (CPI): mengukur perubahan rata-rata harga sekelompok barang/jasa konsumsi tertentu (basket) dari waktu ke waktu. Digunakan sebagai indikator inflasi.\nJawaban: A."},
{question:"Pasar oligopoli dicirikan oleh …",options:["Beberapa perusahaan besar yang mendominasi pasar","Satu perusahaan tunggal","Banyak perusahaan dengan produk identik","Tidak ada hambatan masuk","Harga ditentukan pasar"],answer:0,hint:"Oligo = sedikit. Beberapa perusahaan besar yang saling bergantung dalam penetapan harga.",explanation:"Oligopoli: beberapa perusahaan besar mendominasi pasar. Keputusan satu perusahaan mempengaruhi yang lain (saling bergantung/interdependent). Contoh: industri telekomunikasi, penerbangan.\nJawaban: A."},
{question:"Fungsi uang sebagai satuan hitung (unit of account) berarti …",options:["Uang digunakan sebagai standar untuk mengukur dan membandingkan nilai barang/jasa","Uang digunakan untuk menabung","Uang digunakan sebagai alat tukar","Uang digunakan untuk membayar hutang di masa depan","Uang digunakan sebagai komoditas"],answer:0,hint:"Unit of account = memberikan harga/nilai pada barang sehingga bisa dibandingkan.",explanation:"Fungsi uang sebagai satuan hitung: memberikan nilai numerik pada barang/jasa sehingga dapat dibandingkan. Contoh: harga roti Rp10.000 vs harga susu Rp15.000.\nJawaban: A."},
{question:"Dampak pengangguran terhadap perekonomian meliputi …",options:["Penurunan output nasional, peningkatan kemiskinan, beban anggaran negara bertambah","Peningkatan GDP","Inflasi menurun drastis","Nilai tukar menguat","Investasi asing meningkat"],answer:0,hint:"Pengangguran = sumber daya manusia tidak terpakai → output di bawah potensi.",explanation:"Dampak pengangguran:\n1. Output nasional di bawah potensial (GDP gap)\n2. Kemiskinan dan ketimpangan meningkat\n3. Beban fiskal naik (subsidi, tunjangan)\n4. Masalah sosial (kriminalitas, kesehatan mental)\nJawaban: A."},
{question:"Multiplier effect dalam ekonomi Keynesian menunjukkan bahwa …",options:["Perubahan pengeluaran awal menghasilkan perubahan output yang lebih besar","Pajak selalu menurunkan output","Investasi tidak mempengaruhi GDP","Impor meningkatkan pendapatan nasional","Tabungan selalu sama dengan investasi"],answer:0,hint:"Efek pengganda: $1 belanja pemerintah → menghasilkan lebih dari $1 pertumbuhan GDP.",explanation:"Multiplier effect: injeksi pengeluaran (G, I) menghasilkan perubahan output berlipat ganda.\nMultiplier = 1/(1-MPC) di mana MPC = marginal propensity to consume.\nContoh: jika MPC = 0.8, multiplier = 5 → $1 belanja → $5 tambahan GDP.\nJawaban: A."},
{question:"Bank sentral menjalankan fungsi sebagai …",options:["Lender of last resort, pengatur jumlah uang beredar, bank pemerintah","Hanya bank komersial biasa","Perusahaan swasta","Kementerian keuangan","Badan usaha milik negara"],answer:0,hint:"Bank sentral memiliki peran unik yang tidak dimiliki bank komersial.",explanation:"Fungsi bank sentral (BI):\n1. Lender of last resort (pemberi pinjaman terakhir)\n2. Mengatur jumlah uang beredar (kebijakan moneter)\n3. Bank bagi pemerintah\n4. Pengawas sistem keuangan\n5. Penerbit mata uang\nJawaban: A."},
{question:"APBN (Anggaran Pendapatan dan Belanja Negara) disusun berdasarkan prinsip …",options:["Anggaran berimbang dan dinamis","Anggaran selalu surplus","Belanja tanpa batas","Pajak sebagai satu-satunya pendapatan","Utang tidak diperbolehkan"],answer:0,hint:"APBN disusun agar pendapatan dan belanja seimbang (balanced budget) dengan fleksibilitas.",explanation:"APBN disusun berdasarkan prinsip anggaran berimbang dan dinamis: pendapatan diupayakan seimbang dengan belanja, dengan fleksibilitas menyesuaikan kondisi ekonomi.\nJawaban: A."},
{question:"Kegiatan ekonomi yang termasuk dalam sektor tersier adalah …",options:["Jasa perbankan, pendidikan, transportasi","Pertanian dan perikanan","Pertambangan","Manufaktur","Konstruksi"],answer:0,hint:"Primer = bahan mentah. Sekunder = pengolahan/manufaktur. Tersier = jasa.",explanation:"Sektor tersier = sektor jasa: perbankan, pendidikan, kesehatan, transportasi, perdagangan, pariwisata, telekomunikasi.\nJawaban: A."},
{question:"Teori pertumbuhan ekonomi Solow menekankan peran penting dari …",options:["Akumulasi modal, pertumbuhan tenaga kerja, dan kemajuan teknologi","Hanya investasi asing","Hanya sumber daya alam","Kebijakan proteksionisme","Devaluasi mata uang"],answer:0,hint:"Model Solow: output = f(K, L, A) di mana K=kapital, L=tenaga kerja, A=teknologi.",explanation:"Model pertumbuhan Solow: pertumbuhan ekonomi jangka panjang ditentukan oleh:\n1. Akumulasi modal (K)\n2. Pertumbuhan tenaga kerja (L)\n3. Kemajuan teknologi (A) — satu-satunya sumber pertumbuhan berkelanjutan\nJawaban: A."},
{question:"Koperasi di Indonesia berdasarkan UUD 1945 Pasal 33 merupakan …",options:["Soko guru perekonomian nasional","Badan usaha swasta murni","Bank sentral kedua","Perusahaan multinasional","Lembaga pemerintah"],answer:0,hint:"Pasal 33 UUD 1945: perekonomian disusun sebagai usaha bersama berdasar asas kekeluargaan.",explanation:"Koperasi sebagai 'soko guru perekonomian' Indonesia berdasarkan Pasal 33 UUD 1945: bangun perusahaan yang sesuai adalah koperasi (asas kekeluargaan).\nJawaban: A."},
{question:"Devaluasi mata uang adalah …",options:["Penurunan nilai tukar mata uang domestik secara resmi oleh otoritas moneter","Kenaikan nilai mata uang","Penciptaan uang baru","Penghapusan hutang negara","Privatisasi bank"],answer:0,hint:"De- = menurunkan. Valuasi = nilai. Devaluasi = penurunan resmi nilai mata uang domestik terhadap mata uang asing.",explanation:"Devaluasi: penurunan resmi (deliberate) nilai tukar mata uang domestik terhadap mata uang asing oleh otoritas moneter. Berbeda dengan depresiasi (penurunan karena mekanisme pasar).\nJawaban: A."},
]);
