// ============================================
// TKA Soshum — Geografi (50 Soal HOTS)
// UM UGM CBT 2026
// ============================================
registerQuestions('soshum_geografi', [
{question:"Bumi terbagi menjadi lapisan-lapisan. Urutan dari luar ke dalam yang benar adalah …",options:["Kerak → Mantel → Inti Luar → Inti Dalam","Mantel → Kerak → Inti","Inti → Mantel → Kerak","Kerak → Inti → Mantel","Mantel → Inti → Kerak"],answer:0,hint:"Kerak bumi (crust) paling luar, diikuti mantel (mantle), inti luar (outer core), dan inti dalam (inner core).",explanation:"Lapisan bumi (luar→dalam):\n1. Kerak (crust): 5-70 km\n2. Mantel (mantle): 2.900 km\n3. Inti luar (outer core): cair, 2.200 km\n4. Inti dalam (inner core): padat, 1.200 km\nJawaban: A."},
{question:"Indonesia terletak di pertemuan tiga lempeng tektonik, yaitu …",options:["Lempeng Indo-Australia, Eurasia, dan Pasifik","Lempeng Afrika, Antarktika, dan Amerika","Lempeng Arab, Filipina, dan Karibia","Lempeng Amerika Utara, Scotia, dan Nazca","Lempeng Cocos, Juan de Fuca, dan Karibia"],answer:0,hint:"Indonesia = Ring of Fire, di pertemuan lempeng besar.",explanation:"Indonesia terletak di pertemuan 3 lempeng tektonik besar: Indo-Australia (selatan), Eurasia (utara), dan Pasifik (timur). Menyebabkan aktivitas seismik dan vulkanik tinggi (Cincin Api Pasifik).\nJawaban: A."},
{question:"Efek rumah kaca (greenhouse effect) disebabkan oleh …",options:["Gas-gas seperti CO₂, CH₄, dan N₂O yang menahan radiasi inframerah di atmosfer","Polusi air","Deforestasi saja","Limbah plastik","Radiasi ultraviolet"],answer:0,hint:"Gas rumah kaca menyerap dan memancarkan kembali radiasi inframerah ke permukaan bumi.",explanation:"Efek rumah kaca: gas-gas (CO₂, CH₄, N₂O, CFC) menyerap radiasi inframerah yang dipancarkan bumi dan memancarkannya kembali ke permukaan, menyebabkan pemanasan. Tanpa efek ini, suhu bumi akan −18°C (terlalu dingin).\nJawaban: A."},
{question:"Garis khatulistiwa (ekuator) terletak pada lintang …",options:["0°","23.5° LU","66.5° LU","90° LU","45° LS"],answer:0,hint:"Ekuator = garis lintang yang membagi bumi menjadi belahan utara dan selatan.",explanation:"Ekuator/khatulistiwa = garis lintang 0°, membagi bumi menjadi Belahan Bumi Utara (BBU) dan Belahan Bumi Selatan (BBS). Indonesia dilintasi garis khatulistiwa.\nJawaban: A."},
{question:"Siklus hidrologi meliputi proses …",options:["Evaporasi → Kondensasi → Presipitasi → Infiltrasi → Run off","Hanya penguapan dan hujan","Hanya pencairan es","Fotosintesis → Respirasi","Erosi → Sedimentasi"],answer:0,hint:"Siklus air: dari permukaan ke atmosfer (evaporasi/transpirasi), kembali ke permukaan (presipitasi).",explanation:"Siklus hidrologi:\n1. Evaporasi/Transpirasi: air menguap ke atmosfer\n2. Kondensasi: uap air menjadi awan\n3. Presipitasi: turun sebagai hujan/salju\n4. Infiltrasi: meresap ke tanah\n5. Run off: mengalir di permukaan\nJawaban: A."},
{question:"Angin muson barat di Indonesia terjadi pada bulan …",options:["Oktober – April (musim hujan)","Mei – September","Hanya Januari","Hanya Juli","Sepanjang tahun"],answer:0,hint:"Muson barat membawa uap air dari Samudera Hindia → Indonesia → musim hujan.",explanation:"Angin muson barat: Oktober–April (musim hujan di Indonesia). Angin bertiup dari Samudera Hindia/Pasifik (bertekanan tinggi) menuju Australia (bertekanan rendah), melewati Indonesia dan membawa banyak uap air.\nJawaban: A."},
{question:"Daerah Aliran Sungai (DAS) adalah …",options:["Wilayah daratan yang secara topografis dibatasi punggung bukit dan berfungsi menampung, menyimpan, dan mengalirkan air ke sungai utama","Danau besar","Laut dalam","Saluran irigasi buatan","Bendungan"],answer:0,hint:"DAS = watershed/catchment area yang mengumpulkan air hujan ke satu sungai utama.",explanation:"DAS (watershed): wilayah daratan yang merupakan kesatuan ekosistem, dibatasi oleh igir (punggung bukit/gunung), yang menampung dan mengalirkan seluruh air hujan ke sungai utama menuju muara.\nJawaban: A."},
{question:"Perbedaan antara cuaca dan iklim adalah …",options:["Cuaca = kondisi atmosfer jangka pendek, iklim = rata-rata kondisi atmosfer jangka panjang (30 tahun)","Cuaca = global, iklim = lokal","Tidak ada perbedaan","Cuaca hanya tentang suhu, iklim tentang hujan","Iklim berubah setiap hari"],answer:0,hint:"Weather vs climate: skala waktu yang berbeda.",explanation:"Cuaca: kondisi atmosfer di suatu tempat pada waktu tertentu (menit-hari). Contoh: hari ini hujan.\nIklim: rata-rata kondisi atmosfer di suatu wilayah selama minimal 30 tahun. Contoh: iklim tropis.\nJawaban: A."},
{question:"Skala Richter mengukur …",options:["Magnitudo gempa bumi (kekuatan energi yang dilepaskan)","Kecepatan angin","Suhu udara","Curah hujan","Tekanan atmosfer"],answer:0,hint:"Charles Richter mengembangkan skala logaritmik untuk mengukur kekuatan gempa.",explanation:"Skala Richter: mengukur magnitudo gempa (energi yang dilepaskan). Skala logaritmik: setiap kenaikan 1 poin = 10× amplitudo gelombang dan ~31.6× energi.\nJawaban: A."},
{question:"Biosfer adalah lapisan bumi yang …",options:["Dihuni oleh makhluk hidup, mencakup bagian litosfer, hidrosfer, dan atmosfer","Hanya terdiri dari lautan","Hanya terdiri dari daratan","Hanya lapisan atmosfer atas","Inti bumi"],answer:0,hint:"Bio = hidup. Sfer = lapisan. Lapisan kehidupan.",explanation:"Biosfer: zona kehidupan di bumi, mencakup bagian dari litosfer (tanah/batuan), hidrosfer (air), dan atmosfer (udara) yang dihuni organisme hidup.\nJawaban: A."},
{question:"Jenis tanah vulkanik yang sangat subur disebut …",options:["Andosol (tanah vulkanik)","Latosol","Podsolik","Gambut","Aluvial"],answer:0,hint:"Tanah yang terbentuk dari abu vulkanik, kaya mineral, sangat subur.",explanation:"Andosol: tanah yang terbentuk dari material vulkanik (abu, lava). Sangat subur karena kaya mineral. Banyak ditemukan di sekitar gunung berapi aktif di Indonesia.\nJawaban: A."},
{question:"Garis Wallace memisahkan …",options:["Fauna tipe Asia (Barat) dan fauna tipe peralihan (Tengah) di Indonesia","Flora Jawa dan Sumatra","Iklim tropis dan subtropis","Lautan Pasifik dan Hindia","Pulau Jawa dan Bali"],answer:0,hint:"Alfred Russel Wallace mengidentifikasi batas biogeografi antara fauna Oriental dan Australasia.",explanation:"Garis Wallace: batas biogeografi antara fauna tipe Asia (Oriental) di barat dan fauna peralihan/Wallacea di tengah. Membentang antara Kalimantan-Sulawesi dan Bali-Lombok. Garis Weber memisahkan peralihan dan Australasia.\nJawaban: A."},
{question:"Penginderaan jauh (remote sensing) menggunakan …",options:["Citra satelit atau pesawat untuk mengumpulkan data permukaan bumi tanpa kontak langsung","Survei lapangan langsung","Wawancara penduduk","Peta kertas saja","Kompas magnetik"],answer:0,hint:"Remote = jarak jauh. Sensing = penginderaan. Tanpa menyentuh objek.",explanation:"Penginderaan jauh: ilmu dan teknik memperoleh informasi tentang objek/area dari jarak jauh, biasanya menggunakan sensor pada satelit atau pesawat yang mendeteksi radiasi elektromagnetik yang dipantulkan/dipancarkan objek.\nJawaban: A."},
{question:"El Niño adalah fenomena …",options:["Pemanasan suhu permukaan laut di Pasifik Tengah-Timur yang menyebabkan kekeringan di Indonesia","Pendinginan laut Pasifik","Gempa bumi di dasar laut","Angin topan di Atlantik","Erupsi gunung berapi bawah laut"],answer:0,hint:"El Niño = 'anak laki-laki' (merujuk Natal). Pemanasan anomali di Pasifik ekuatorial.",explanation:"El Niño (ENSO warm phase): pemanasan anomali suhu permukaan laut di Pasifik Tengah dan Timur. Dampak di Indonesia: kekeringan, gagal panen, kebakaran hutan. La Niña = kebalikannya (pendinginan).\nJawaban: A."},
{question:"Piramida penduduk tipe ekspansif menunjukkan …",options:["Angka kelahiran tinggi, proporsi penduduk muda besar, pertumbuhan cepat","Populasi menurun","Angka kematian sangat tinggi","Populasi stabil","Penduduk tua dominan"],answer:0,hint:"Ekspansif = berkembang. Bentuk piramida lebar di dasar (banyak anak-anak).",explanation:"Piramida ekspansif: dasar lebar (angka kelahiran tinggi), mengecil ke atas. Menunjukkan populasi muda dominan dan pertumbuhan penduduk cepat. Khas negara berkembang.\nJawaban: A."},
{question:"Sistem Informasi Geografis (SIG/GIS) adalah …",options:["Sistem komputer untuk mengelola, menganalisis, dan memvisualisasikan data geospasial","Alat ukur jarak","Kompas digital","Peta kertas elektronik","Kamera satelit"],answer:0,hint:"GIS = Geographic Information System. Mengintegrasikan peta, database, dan analisis spasial.",explanation:"GIS: sistem berbasis komputer untuk mengumpulkan, menyimpan, mengelola, menganalisis, dan memvisualisasikan data geospasial. Menggabungkan peta (data spasial) dengan database (data atribut) untuk analisis kompleks.\nJawaban: A."},
{question:"Erosi tanah yang disebabkan oleh air hujan yang mengalir di permukaan tanah membentuk alur-alur kecil disebut …",options:["Erosi alur (rill erosion)","Erosi lembar (sheet erosion)","Erosi parit (gully erosion)","Longsor","Abrasi"],answer:0,hint:"Rill = alur kecil. Intensitas antara sheet erosion dan gully erosion.",explanation:"Jenis erosi air:\n1. Sheet erosion: pengikisan lapisan tipis tanah (merata)\n2. Rill erosion: membentuk alur-alur kecil (dangkal)\n3. Gully erosion: membentuk parit-parit dalam\nJawaban: A."},
{question:"Letak astronomis Indonesia adalah …",options:["6°LU – 11°LS dan 95°BT – 141°BT","23.5°LU – 23.5°LS","0° – 90°LU","50°BT – 100°BT","10°LU – 10°LS"],answer:0,hint:"Indonesia membentang dari Sabang (utara) sampai Merauke (selatan dan timur).",explanation:"Letak astronomis Indonesia:\n- Lintang: 6°LU (Sabang) – 11°LS (Rote)\n- Bujur: 95°BT (Sabang) – 141°BT (Merauke)\nMenyebabkan Indonesia beriklim tropis.\nJawaban: A."},
{question:"Konservasi sumber daya alam bertujuan untuk …",options:["Menjaga kelestarian dan pemanfaatan sumber daya alam secara berkelanjutan","Mengeksploitasi sumber daya sebesar-besarnya","Menghentikan semua aktivitas manusia di alam","Menambang tanpa batas","Menghilangkan hutan untuk pertanian"],answer:0,hint:"Konservasi = pelestarian + pemanfaatan bijaksana untuk generasi sekarang dan mendatang.",explanation:"Konservasi: upaya menjaga kelestarian sumber daya alam sekaligus memanfaatkannya secara bijaksana dan berkelanjutan (sustainable). Prinsip: untuk generasi sekarang tanpa mengorbankan kebutuhan generasi mendatang.\nJawaban: A."},
{question:"Zona waktu di Indonesia terbagi menjadi …",options:["3 zona: WIB (UTC+7), WITA (UTC+8), WIT (UTC+9)","2 zona","1 zona","4 zona","5 zona"],answer:0,hint:"Indonesia membentang 46° bujur, dibagi menjadi tiga zona waktu.",explanation:"Indonesia memiliki 3 zona waktu:\n1. WIB (Waktu Indonesia Barat): UTC+7 — Sumatra, Jawa, Kalimantan Barat/Tengah\n2. WITA (Waktu Indonesia Tengah): UTC+8 — Kalimantan Timur/Selatan, Sulawesi, Bali, NTB, NTT\n3. WIT (Waktu Indonesia Timur): UTC+9 — Maluku, Papua\nJawaban: A."},
{question:"Urbanisasi adalah proses …",options:["Perpindahan penduduk dari desa ke kota","Perpindahan dari kota ke desa","Migrasi antar negara","Pertumbuhan penduduk alami","Penurunan jumlah penduduk kota"],answer:0,hint:"Urban = kota. Urbanisasi = pergerakan menuju kota.",explanation:"Urbanisasi: perpindahan penduduk dari daerah pedesaan (rural) ke perkotaan (urban). Didorong oleh faktor pendorong (push: kemiskinan, tidak ada pekerjaan) dan faktor penarik (pull: lapangan kerja, pendidikan, fasilitas).\nJawaban: A."},
{question:"Gempa tektonik disebabkan oleh …",options:["Pergerakan lempeng tektonik (patahan/sesar)","Letusan gunung berapi","Tanah longsor","Aktivitas manusia","Pasang surut laut"],answer:0,hint:"Tektonik = lempeng. Gempa akibat tumbukan, subduksi, atau geseran lempeng.",explanation:"Gempa tektonik: disebabkan oleh pergerakan lempeng tektonik — tumbukan (convergent), menjauh (divergent), atau geseran (transform). Melepaskan energi elastis yang terakumulasi di zona patahan.\nJawaban: A."},
{question:"Hutan mangrove tumbuh di …",options:["Daerah pesisir pantai berlumpur dengan pengaruh pasang surut","Pegunungan tinggi","Gurun pasir","Kutub utara","Hutan hujan pedalaman"],answer:0,hint:"Mangrove = bakau. Tumbuh di zona intertidal (pasang surut) dengan substrat lumpur.",explanation:"Hutan mangrove: ekosistem pesisir yang tumbuh di daerah pasang surut (intertidal) dengan substrat lumpur. Fungsi: pelindung pantai dari abrasi, habitat biota laut, filter polutan, penyerap karbon.\nJawaban: A."},
{question:"Proyeksi peta Mercator paling tepat digunakan untuk …",options:["Navigasi laut karena mempertahankan garis kompas (loxodrome) sebagai garis lurus","Menghitung luas wilayah kutub","Peta iklim global","Peta geologi dalam","Peta batimetri"],answer:0,hint:"Mercator: proyeksi silinder yang menjaga sudut (conformal), baik untuk navigasi.",explanation:"Proyeksi Mercator: proyeksi silinder conformal. Mempertahankan sudut dan bentuk lokal. Garis kompas (rhumb line/loxodrome) digambarkan sebagai garis lurus, sehingga ideal untuk navigasi laut. Kelemahannya: mendistorsi area di kawasan kutub.\nJawaban: A."},
]);
